apache/mynewt-core

libs/util/src/datetime.c

explictely cast to an integer since some compilers don't like to implicitelty
cast a char to an int

MYNEWT-230

---

libs/os/src/arch/sim/os_arch_sim.c

The assertion is correct and does not fire when the program is running
normally however it triggers a false positive when a breakpoint is set
in 'os_arch_idle()' by lldb.

Remove sanity assertion from os_arch_idle().

---

hw/bsp/native/include/bsp/bsp.h
hw/bsp/native/include/bsp/bsp_sysid.h
hw/bsp/native/src/hal_bsp.c
hw/hal/include/hal/hal_pwm.h
hw/hal/include/hal/hal_pwm_int.h
hw/hal/src/hal_pwm.c
hw/mcu/native/include/mcu/hal_pwm.h
hw/mcu/native/pkg.yml
hw/mcu/native/src/hal_pwm.c

A second version of the PWM API (First pull request was closed).
This is a second version of the hal_pwm API.
Its based on a discussion from the devlist.
It contains two different ways to "set" the PWM waveform, a
simple way with duty cycle and a more advanced way with clock ticks.
It also adds methods to query the resolution(bits) and clock
frequency of the underlying device when use the more advanced
waveform control.

Hal pwm final

---

hw/bsp/native/src/hal_bsp.c
hw/hal/include/hal/hal_dac.h
hw/hal/include/hal/hal_dac_int.h
hw/hal/src/hal_dac.c
hw/mcu/native/include/mcu/hal_dac.h
hw/mcu/native/src/hal_dac.c

This looks similar to the hal ADC API except allows you to write a value
(intead of read).  It also allows you to read the current value from the DAC

a hal_dac (Digital To Analog Conversion) API for HAL.

---

apps/slinky/src/main.c
hw/hal/include/hal/hal_gpio.h
hw/mcu/native/src/hal_gpio.c
hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/stm/stm32f4xx/src/hal_gpio.c
libs/json/include/json/json.h
libs/json/src/json_encode.c
libs/newtmgr/src/newtmgr.c
sys/log/src/log_nmgr.c

For json a comma should be present at the end of every object if there
are multiple objects. Also, there shouldn't be trailing commas.
Problem: The je_has_objects flag would track commas as there wasn't a specific
way to do that with the json lib. It wasn't adding commas at the right
places.
Solution: A comma gets added at the right places now. Particularly, at
the end of each object and the flag gets reset each time a comma gets
added.
This should fix the problem we see with nested json encoding.
Also changing the name to be more specific.

Changing has_objects to wr_commas and fixing it

---

apps/slinky/src/main.c

NOTE: This may be a bug, because we probably should not crash when calling logs before they are fully initialized

these were probably accidentally added and seem to cause a crash on

---

libs/util/include/util/cbmem.h

change to a packed structure to allow unaligned access for M0

MYNEWT-282

---

libs/os/src/arch/sim/os_arch_sim.c

When the OS is idling it may disable the periodic timer and enter the tickless mode. The OS exits the tickless mode on arrival of an interrupt/signal (note that OS time is incorrect when this happens). Thus it is important to call 'timer_handler()' to correct the OS time before executing anything else.

Don't do anything in signal handlers when process is blocked in 'sigsuspend()'.

---

apps/blehci/pkg.yml
apps/blehci/src/main.c
hw/bsp/nrf51-arduino_101/boot-nrf51-arduino_101.ld
hw/bsp/nrf51-arduino_101/include/bsp/bsp.h
hw/bsp/nrf51-arduino_101/include/bsp/bsp_sysid.h
hw/bsp/nrf51-arduino_101/include/bsp/cmsis_nvic.h
hw/bsp/nrf51-arduino_101/nrf51-arduino_101.ld
hw/bsp/nrf51-arduino_101/nrf51dk-16kbram_debug.sh
hw/bsp/nrf51-arduino_101/nrf51dk-16kbram_download.sh
hw/bsp/nrf51-arduino_101/nrf51dk-16kbram_no_boot.ld
hw/bsp/nrf51-arduino_101/pkg.yml
hw/bsp/nrf51-arduino_101/src/arch/cortex_m0/gcc_startup_nrf51.s
hw/bsp/nrf51-arduino_101/src/hal_bsp.c
hw/bsp/nrf51-arduino_101/src/libc_stubs.c
hw/bsp/nrf51-arduino_101/src/os_bsp.c
hw/bsp/nrf51-arduino_101/src/sbrk.c
hw/bsp/nrf51-arduino_101/src/system_nrf51.c

These patches add an Arduino 101 BSP as well as a simple app to expose HCI over UART. With the app one can use the native Bluetooth LE host stack in Zephyr on the Arduino 101, with MyNewt running on the nRF51 and Zephyr on the Quark SE.

Patches for exposing HCI over UART

---

apps/ffs2native/src/main.c
fs/nffs/src/nffs.c
fs/nffs/src/nffs_area.c
fs/nffs/src/nffs_block.c
fs/nffs/src/nffs_dir.c
fs/nffs/src/nffs_file.c
fs/nffs/src/nffs_format.c
fs/nffs/src/nffs_gc.c
fs/nffs/src/nffs_hash.c
fs/nffs/src/nffs_inode.c
fs/nffs/src/nffs_misc.c
fs/nffs/src/nffs_path.c
fs/nffs/src/nffs_priv.h
fs/nffs/src/nffs_restore.c
fs/nffs/src/nffs_write.c
fs/nffs/src/test/arch/sim/nffs_test.c

Change on-flash data structures including the addition of ndi_lastblock_id
in the nffs_disk_inode struct.  This field will store the last block of each
file for fast restores. That change is not enabled in this set of changes,
it will come in a subsequent commit.
Other changes include:
* Deleting the per inode/block magic number (ndi_magic, ndb_magic)
* Modifying the code to read in disk objects during restore and in ffs2native.
* Incrementing the filesystem version number stored in struct nffs_disk-area
* Add "-s" flag to ffs2native to parse NFFS flash area images (V1 format for now)

Cache lastblock ID for each file in on-flash data structure

---

apps/ffs2native/src/main.c
fs/fs/src/fsutil.c
fs/nffs/src/nffs.c
fs/nffs/src/nffs_block.c
fs/nffs/src/nffs_cache.c
fs/nffs/src/nffs_hash.c
fs/nffs/src/nffs_inode.c
fs/nffs/src/nffs_priv.h
fs/nffs/src/nffs_restore.c

These changes were made to address jira issue mynewt-343. A couple of bugs were
fixed include the removal of an incorrect assert in nffs_restore_inode(), and
resetting the sweep when a block is removed in nffs_restore_sweep(). Also:
* bug fix in how V1 filesystems are parsed in ffs2native app. CRC check added for each record.
* fsutil_write_file() was update to not automatically cause files to truncate to zero bytes on write
* nffs_stats() routine was added to track how many objects were parsed and are in the hash table.

nffs bug fixes and enhancements

---

apps/ffs2native/src/main.c

Data at the end of a flash area could be incorrectly parsed as valid structures.
Code was added to check for runoff past end of area.

Don't read on-flash structures that extend beyond flash area

---

sys/config/src/config_nmgr.c

Values which require transformation (for example, bytes to str) and are longer than `CONF_MAX_NAME_LEN` would fail in `conf_get_value(..)` because the buffer isn't big enough to hold the result.

sys/config: Fix returning long config values to newtmgr

---

libs/newtmgr/src/newtmgr.c

Fixes The newtmgr response notification's ID field always being 0. The ID field is only 1 byte so there is no reason to reverse the endianness.

Fixed bug where ID was always wrong in response

---

libs/console/full/include/console/console.h
libs/console/full/include/console/prompt.h
libs/console/full/src/cons_tty.c
libs/console/full/src/prompt.c
libs/console/stub/include/console/console_prompt.h
libs/shell/include/shell/shell.h
libs/shell/include/shell/shell_prompt.h
libs/shell/src/shell.c
libs/shell/src/shell_prompt.c

I moved all the prompt-printing stuff to their own files. Timestamps are printed before each prompt, and timestamps before output is working as expected. 
newtmgr tests run on nrf52dk board and they work as expected.

Console shell

---

fs/nffs/pkg.yml
fs/nffs/src/nffs.c
fs/nffs/src/nffs_block.c
fs/nffs/src/nffs_crc.c
fs/nffs/src/nffs_flash.c
fs/nffs/src/nffs_format.c
fs/nffs/src/nffs_gc.c
fs/nffs/src/nffs_hash.c
fs/nffs/src/nffs_inode.c
fs/nffs/src/nffs_misc.c
fs/nffs/src/nffs_priv.h
fs/nffs/src/nffs_restore.c
sys/stats/src/stats.c

This addresses a bug where file hash entries allocated during nffs restore were not removed from the hash table if the entry was freed. Also, statistics are maintained for different types of flash reads.

Bugfix to remove nffs hash entries on error conditions

---

compiler/gdbmacros/nffs.gdb

Add new directory for gdb macros under compiler ("compiler/gdbmacros").
Add gdb macros to display hash table, print stats.
Add gdb arduino_zero platform specific macros to dump and clear nffs flash areas

Add gdb macros for nffs

---

libs/mbedtls/src/x509_crl.c

Fixed compiler warning with added parens.
Compiling x509_crl.c
x509_crl.c: In function 'mbedtls_x509_crl_parse':
x509_crl.c:508:5: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
else
^~~~
x509_crl.c:514:9: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
if( ret == 0 )
^~
Testing package @apache-mynewt-core/sys/log

Fix compiler warning in x509_crl.c

---

hw/bsp/nucleo-f401re/boot-nucleo-f401re.ld
hw/bsp/nucleo-f401re/include/bsp/bsp.h
hw/bsp/nucleo-f401re/include/bsp/bsp_sysid.h
hw/bsp/nucleo-f401re/include/bsp/cmsis_nvic.h
hw/bsp/nucleo-f401re/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/nucleo-f401re/nucleo-f401re.ld
hw/bsp/nucleo-f401re/nucleo-f401re_debug.sh
hw/bsp/nucleo-f401re/nucleo-f401re_download.sh
hw/bsp/nucleo-f401re/pkg.yml
hw/bsp/nucleo-f401re/src/arch/cortex_m4/startup_STM32F40x.s
hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f401re/src/libc_stubs.c
hw/bsp/nucleo-f401re/src/os_bsp.c
hw/bsp/nucleo-f401re/src/sbrk.c
hw/bsp/nucleo-f401re/src/system_stm32f4xx.c
hw/mcu/stm/stm32f4xx/include/mcu/stm32f401xe.h
hw/mcu/stm/stm32f4xx/src/hal_uart.c

Add support for http://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-eval-tools/stm32-mcu-eval-tools/stm32-mcu-nucleo/nucleo-f401re.html.
Tested with the boot and blinky example.
Signed-off-by: Ricardo Salveti ricardo.salveti@linaro.org

bsp: add support for Nucleo-F401RE

---

apps/bletiny/src/parse.c

parse_arg_uint16 extracted UUID argument and if it failed to parse it
parse_arg_byte_stream_exact_length was called, but coudldn't find uuid
argument. Additionally the part that parsed UUID in
"e7add801-b042-4876-aae1112855353cc1" format was ineffective, because
parse_arg_byte_stream_exact_length expects arg name as a first
parameter. Finally parsed stream needed to be reversed.
With this patch it is possible to pass Read Using Characteristic UUID
tests (TC_GAR_CL_BV_03_C, etc.)

bletiny: Fix parse uuid cmd argument

---

net/nimble/host/src/ble_gattc.c

This status change is not needed. With this patch it is possible to pass TC_GAR_CL_BI_07_C.

gattc: Fix unnecessary status overwrite in read by type err

---

net/nimble/host/src/ble_att_svr.c
net/nimble/host/test/src/ble_att_svr_test.c

This fixes Find By Type Value Request handling which is required to allow discover service by UUID from peer. With current implementation, which is invalid, we can expect a lot of interoperability issues when Nimble is used as GATT Server.

nimble: Fix ATT Find By Type Value Request

---

hw/drivers/sensors/lsm303dlhc/include/lsm303dlhc/lsm303dlhc.h
hw/drivers/sensors/lsm303dlhc/pkg.yml
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc_priv.h
hw/drivers/sensors/lsm303dlhc/syscfg.yml

This adds a first pass at an [LSM303DLHC](https://www.adafruit.com/product/1120) ([datasheet](http://www.st.com/content/ccc/resource/technical/document/datasheet/56/ec/ac/de/28/21/4d/48/DM00027543.pdf/files/DM00027543.pdf/jcr:content/translations/en.DM00027543.pdf)) driver using the new sensor API.
The current driver only includes support for reading from the accelerometer. The magnetometer and temperature sensor will be added in the future once the sensor API has stabilized a bit more.
You can initialize the driver with the following code in main (or elsewhere):
```
os_dev_create((struct os_dev *) &lsm303dlhc_sensor, "lsm303dlhc",
OS_DEV_INIT_KERNEL, OS_DEV_INIT_PRIMARY, lsm303dlhc_drvr_init, NULL);
```
...
```
static int
lsm303dlhc_drvr_init(struct os_dev *dev, void *arg)
{
struct …
```

First pass at LSM303DLHC sensor driver

---

hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc_priv.h

This pull request solves an issue that will be encountered when magnetometer support is added. The magnetometer data is 16-bit and requires a different shifting strategy than the 12-bit accelerometer data. To keep the `lsm303dlhc_read48` function generic, a raw buffer is now returned and the 16-bit value formation happens in the calling function.
The return code is also checked when `lsm303dlhc_read48` is called in case the I2C transaction fails.

Updated lsm303dlhc_read48 to allow for differences with mag output

---

hw/bsp/arduino_primo_nrf52/primo_debug.sh
hw/bsp/nrf51-blenano/nrf51dk_debug.sh
hw/bsp/nucleo-f401re/nucleo-f401re_debug.sh
hw/bsp/olimex_stm32-e407_devboard/olimex_stm32-e407_devboard_debug.sh
hw/bsp/rb-nano2/rb-nano2_debug.sh
hw/bsp/stm32f4discovery/stm32f4discovery_debug.sh

If `gdb` is detached while cpu is running (e.g. by sending SIGINT to `gdb`), the openocd detach handler hits an error when trying to execute `resume` command since cpu is not in a resumable state. This aborts the handler and doesn't run the shutdown command, resulting in an orphaned `openocd` process hanging around (and dumping errors to console when device is unplugged, etc.)
This checks that cpu is halted before trying to `resume`. If cpu is already running, it just shuts down `openocd` without touching cpu state.

Fix orphaned openocd when gdb is detached while running

---

hw/scripts/jlink.sh

Since `gdb` executes shell commands using system interpreter, it can't run the shell command to launch `JLinkGDBServer` as currently written. 
Changes:
* Reference `sh` without explicit path, so any `sh` or `sh.exe` in user's environment path will work
* Replace quotes; since `gdb` uses system interpreter to execute shell commands, the entire command has to be passed to `sh`, including job control
* Replace `JLinkGDBServer` with `JLinkGDBServerCL` command-line version

Fix gdb shell command on Windows

---

hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c

The `sensor_set_driver` call should have had both the accelerometer and magnetometer bits set at the same time (`SENSOR_TYPE_ACCELEROMETER | SENSOR_TYPE_MAGNETIC_FIELD`). This PR fixes this bug, where only the magnetometer will show up at present, overriding the accelerometer settings.

Fixed accel/mag driver registration

---

apps/bletiny/src/gatt_svr.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_gatt.h
net/nimble/host/include/host/ble_store.h
net/nimble/host/pts/pts-gap.txt
net/nimble/host/pts/pts-gatt.txt
net/nimble/host/src/ble_att_priv.h
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_gatts.c
net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/test/src/ble_att_svr_test.c
net/nimble/host/test/src/ble_gatt_conn_test.c

This adds proper support for encryption state in ATT code, i.e.
- attribute can have minimum encryption key size requirement
- "Insufficient Encryption" error code returned when LTK is present but encryption is not enabled
- "Insufficient Encryption Key Size" error code returned when encryption key size does not minimum requirement for given attribute
...and other changes which were required to run and test this code.

Nimble: proper encryption state handling in ATT

---

net/nimble/host/src/ble_hs_conn.c
net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/src/ble_sm_sc.c

support for rejecting SM commands when pairing is disabled (this is mandated by spec)  + some minor cleanup

support for rejecting SM commands when pairing is disabled

---

compiler/sim/compiler.yml

Hard-coding the absolute path for cc & as is not only non-consistent
with the other definitions (none use absolute paths), but it is also
wrong, gcc-5 can be installed in any location (via homebrew or
otherwise).

Avoid hard-coding absolute compiler path

---

apps/bletiny/src/bletiny.h
apps/bletiny/src/main.c
net/nimble/host/include/host/ble_gatt.h
net/nimble/host/pts/pts-gatt.txt
net/nimble/host/src/ble_gattc.c

This patch unifies api to make it consistent across all discovery
methods. Always pass true range of attributes to search (start-handle,
end-handle).

nimble/gatt: unify discovery api

---

apps/bletiny/src/main.c
test/runtest/pkg.yml

1) Added #ifndef around #define STR(x) to avoid duplicate define when
including <mgmt/mgmt.h> to enable Newt Manager
2) Added test/testutil package to test/runtest pkg.deps to fix not
able to find include "testutil/testutil.h" in runtest_nmgr.c compile error when
RUNTEST_NEWTMGR is enabled

Fixes MYNEWT-563

---

hw/bsp/bmd200/boot-nrf51xxac.ld
hw/bsp/bmd200/bsp.yml
hw/bsp/bmd200/include/bsp/boards.h
hw/bsp/bmd200/include/bsp/bsp.h
hw/bsp/bmd200/include/bsp/cmsis_nvic.h
hw/bsp/bmd200/nrf51dk_debug.sh
hw/bsp/bmd200/nrf51dk_download.sh
hw/bsp/bmd200/nrf51dk_no_boot.ld
hw/bsp/bmd200/nrf51xxac.ld
hw/bsp/bmd200/pkg.yml
hw/bsp/bmd200/split-nrf51dk.ld
hw/bsp/bmd200/src/arch/cortex_m0/gcc_startup_nrf51.s
hw/bsp/bmd200/src/arch/cortex_m0/gcc_startup_nrf51_split.s
hw/bsp/bmd200/src/hal_bsp.c
hw/bsp/bmd200/src/sbrk.c
hw/bsp/bmd200/syscfg.yml

Based on nrf51dk bsp, with the following changes:
- Program as J-Link device nRF51822
- Default to internally synthesized LF clock
- Default to UART pins used by the factory firmware
See: http://go.rigado.com/BMD-200-Data-Sheet
```diff
diff -ur hw/bsp/nrf51dk/bsp.yml hw/bsp/bmd200/bsp.yml
--- hw/bsp/nrf51dk/bsp.yml      2017-01-27 01:42:42.863797000 -0800
+++ hw/bsp/bmd200/bsp.yml       2017-01-27 01:52:59.069718800 -0800
@@ -20,14 +20,14 @@
bsp.arch: cortex_m0
bsp.compiler: compiler/arm-none-eabi-m0
bsp.linkerscript:
-    - "hw/bsp/nrf51dk/nrf51xxac.ld"
+    - "hw/bsp/bmd200/nrf51xxac.ld"
- "hw/mcu/nordic/nrf51xxx/nrf51.ld"
bsp.linkerscript.BOOT_LOADER.OVERWRITE:
-    - "hw/bsp/nrf51dk/boot-nrf51xxac.ld"
+    - "hw/bsp/bmd200/boot-nrf51xxac.ld"
- "hw/mcu/nordic/nrf51xxx/nrf51.ld" …
```

Add bsp for Rigado BMD-200 module

---

apps/blecent/src/main.c
apps/blecent/src/misc.c
apps/bleprph/src/main.c
apps/bleprph_oic/src/main.c
apps/bletiny/src/cmd.c
apps/bletiny/src/main.c
apps/bleuart/src/main.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_hs_adv.h
net/nimble/host/src/ble_eddystone.c
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_hs_adv.c
net/nimble/host/src/ble_hs_adv_priv.h
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/test/src/ble_gap_test.c
net/nimble/host/test/src/ble_hs_adv_test.c

This does some more fixing for advertising API:
- remove unused/invalid data types from adv data
- use raw data for reports from host to app (so the same as from app to host)
- use ble_uuid types in ble_hs_adv_fields struct (remaining item after ble_uuid refactor)

Nimble: update advertising API

---

apps/bletiny/src/bletiny.h
apps/bletiny/src/cmd.c
apps/bletiny/src/main.c
kernel/os/include/os/queue.h
net/nimble/host/include/host/ble_hs.h
net/nimble/host/include/host/ble_l2cap.h
net/nimble/host/src/ble_att.c
net/nimble/host/src/ble_att_clt.c
net/nimble/host/src/ble_att_priv.h
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_gattc.c
net/nimble/host/src/ble_hs_conn.c
net/nimble/host/src/ble_hs_conn_priv.h
net/nimble/host/src/ble_hs_priv.h
net/nimble/host/src/ble_l2cap.c
net/nimble/host/src/ble_l2cap_coc.c
net/nimble/host/src/ble_l2cap_coc_priv.h
net/nimble/host/src/ble_l2cap_priv.h
net/nimble/host/src/ble_l2cap_sig.c
net/nimble/host/src/ble_l2cap_sig_cmd.c
net/nimble/host/src/ble_l2cap_sig_priv.h
net/nimble/host/src/ble_sm.c
net/nimble/host/syscfg.yml
net/nimble/host/test/src/ble_att_svr_test.c
net/nimble/host/test/src/ble_hs_conn_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_l2cap_test.c

In this pull LE COC signaling part has been implemented together with extensions to Bletiny app needed to test it. It is tested against BlueZ and PTS and works fine.
Note: This pull will not enable LE COC,  BLE_L2CAP_COC_MAX_NUM is 0
As you will notice I change a way of creating and sending signal commands. It is now done similar to what BLE_SM does. I plan to do same for l2cap update command.
Please have a look on API as I change it a bit comparing to what we discussed on mailing list. I found it more useful when writing Bletiny extensions.
In addition in this pull you can find some fixes and cleaning.

L2CAP LE COC signaling part plus some additional fixes

---

fs/fcb/include/fcb/fcb.h
fs/fcb/src/fcb.c
fs/fcb/test/src/fcb_test.c
fs/fcb/test/src/testcases/fcb_test_last_of_n.c
sys/log/full/src/log_fcb.c

- fcb_offset_last_n() changed to return a struct fcb_entry
- Added a test case
- Now properly returns error when there is no item at requested offset

MYNEWT-335

---

kernel/os/include/os/os_dev.h
kernel/os/src/os_dev.c

This enables users who want to share a OS device during init to
access it using the device name.  This should not be called at
runtime.

Expose os_dev_loookup()

---

net/nimble/host/src/ble_uuid.c

When the two uuid values differ in type, one of two things can happen:
1. Access to unallocated or uninitialised memory
2. Unaligned access to 16/32-bit values
Both of these cause crashes, so always make sure we are comparing like types.

Fix invalid memory accesses in ble_uuid_cmp

---

hw/mcu/stm/stm32f4xx/src/hal_gpio.c

mcu/stm32f4xx: Fix typo in porting map

---

hw/bsp/stm32f429discovery/include/bsp/cmsis_nvic.h

From st datasheet page 24:
The devices embed a nested vectored interrupt controller
able to manage 16 priority levels, and handle up to 91
maskable interrupt channels plus the 16 interrupt lines
of the Cortex®-M4 with FPU core.

Fix stm32f429 nvic num vectors

---

hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/syscfg.yml

This commit expose the I2C0 interface on the STM32F4 discovery board. I am not very familiar with Mynewt yet, so sorry if this is a weird way to add a peripheral to a board. I took most of the code from the Olimex E407 and adapted it to this board.

Expose I2C0 on STM32F4 Discovery board

---

hw/mcu/stm/stm32f7xx/syscfg.yml

MYNEWT-682
Forgot to add "syscfg.yml" on previous stm32f7 PR. This fixes the flash write size warning.

Add definition/value for MCU_FLASH_MIN_WRITE_SIZE

---

apps/testbench/src/testbench.c

Logging a message on startup will make it easier to tell if a device
rebooted.

Make it easier to tell when a device reboots

---

apps/bletiny/src/bletiny.h
apps/bletiny/src/main.c

This patch fixes scenario when remote device has empty service in his
database. Without that patch bletiny keep searching for characteristics
in same service in infinite loop.

bletiny: Fix for characteristic discovery

---

net/nimble/controller/src/ble_ll_adv.c

Errata 6471 clarifies what AdvA shall be in Scan Resp and nimble does good.
This errata is adopted into Bluetooth 5.0

controller: Minor comment fix

---

hw/bsp/nrf51-blenano/pkg.yml

According to manufacturer the chip has 256kB of flash. This is in
accordance with the linker scripts found for this target.

Fix flash size in Red Bear BLE nano description

---

net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_ctrl.c

Modify how the controller deals with the terminate procedure. The
old method set a pending control procedure bit and it was not the
best way to deal with this since the terminate procedure can
occur while another control procedure is in process. The
new method uses a flag in the connection state machine flags
to denote that the terminate procedure was started. Started means
a control pdu was allocated and enqueued. The disconnect reason
being non-zero means that the connection is to be terminated.
NOTE: I replaced the flag send_conn_upd_event since it was not used.

nimble/controller: MYNEWT-726

---

hw/bsp/ruuvi_tag_revb2/boot-nrf52xxaa.ld
hw/bsp/ruuvi_tag_revb2/bsp.yml
hw/bsp/ruuvi_tag_revb2/include/bsp/boards.h
hw/bsp/ruuvi_tag_revb2/include/bsp/bsp.h
hw/bsp/ruuvi_tag_revb2/include/bsp/cmsis_nvic.h
hw/bsp/ruuvi_tag_revb2/nrf52dk_debug.cmd
hw/bsp/ruuvi_tag_revb2/nrf52dk_debug.sh
hw/bsp/ruuvi_tag_revb2/nrf52dk_download.cmd
hw/bsp/ruuvi_tag_revb2/nrf52dk_download.sh
hw/bsp/ruuvi_tag_revb2/nrf52dk_no_boot.ld
hw/bsp/ruuvi_tag_revb2/nrf52xxaa.ld
hw/bsp/ruuvi_tag_revb2/pkg.yml
hw/bsp/ruuvi_tag_revb2/split-nrf52dk.ld
hw/bsp/ruuvi_tag_revb2/src/arch/cortex_m4/gcc_startup_nrf52.s
hw/bsp/ruuvi_tag_revb2/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/bsp/ruuvi_tag_revb2/src/sbrk.c
hw/bsp/ruuvi_tag_revb2/syscfg.yml

Add BSP for Ruuvi tag revision B3/B4. Not sure if this same BSP
will work on other Ruuvi Tag B revisions. Note that the UART
only uses tx/rx and goes to test points on the board (the
test points are TP10 and TP11).

hw/bsp: MYNEWT-730 Add BSP for Ruuvi tag

---

net/nimble/host/src/ble_att_clt.c

Broken in a refactor in 191acab73c9c77c157a806d8871b653f3c64cbc9, merged as part of https://github.com/apache/incubator-mynewt-core/pull/215.

MYNEWT-732: Fix ble_gattc_disc_svc_by_uuid

---

net/nimble/transport/uart/src/ble_hci_uart.c

Modified the code in ble_hci_uart_tx_char to be faster. This
added a bit more code (should not have increased ram usage) and
should in general be faster than the old method and should also
free the mbufs slightly faster (each one is freed as it is
used).

nimble/transport; MYNEWT-737: Make ble_hci_uart_tx_char more efficient

---

hw/bsp/nrf51-blenano/src/hal_bsp.c
hw/bsp/nrf51-blenano/syscfg.yml

This PR adds support for both I2C on Nordic nrf51-based BLE nano board support package. I tested both interfaces on hardware today and they work correctly.

Add I2C support in BLE nano BSP

---

hw/scripts/jlink.sh
hw/scripts/openocd.sh

1) Fixed launch hanging problem for openocd and jlink gdbserver when
newt debug is run from mingw/bash (installed with msys2).
openocd now starts in a new cmd prompt window.
2) Fixed  to start gdb in a new cmd prompt when newt debug is run
from mingw/bash (installed with msys2). Before the fix, gdb did not
start in a new window and Control-C would cause gdb to exit.
Theses fixes should preserve the same behavior when running newt command
from git-bash, git-cmd, or cmd prompt.

Fix problems with starting debuggers on MSYS2/MINGW

---

hw/mcu/nordic/nrf51xxx/src/hal_spi.c

NRF_SPIM1 didnt appear to exist. I believe its supposed to be NRF_SPI1

hal: nrf51 spi1 fix

---

hw/mcu/microchip/pic32mz2048efg100/src/hal_gpio.c

hw: pic32mz2048efg100: Remove unused variables in hal_gpio

---

hw/bsp/pic32mz2048_wi-fire/src/hal_bsp.c

This function reads the DEVID register which
contains the revision (upper 4 bits) and the
device id (lower 28 bits).

bsp: wifire: Implement hal_bsp_hw_id

---

hw/bsp/pic32mz2048_wi-fire/src/os_bsp.c
hw/mcu/microchip/pic32mz2048efg100/include/mcu/mips_hal.h
hw/mcu/microchip/pic32mz2048efg100/include/mcu/pps.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_uart.c
hw/mcu/microchip/pic32mz2048efg100/src/ppc.c

This pull requests adds:
- A wrapper to configure pins as a peripheral output or input.
- Modify hal_uart to be able to configure pins in ```hal_uart_config```
- Set the UART4 (=CONSOLE_UART) pins at initialization for the Wi-Fire board. This means that no board specific code needs to be written in the user application to get the console uart fully working.
It has been tested on a Wi-Fire board.

pic32mz2048efg100: Add Peripheral Pin Select wrapper and configure CONSOLE_UART at boot

---

net/nimble/controller/include/controller/ble_ll_ctrl.h
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_ctrl.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/controller/syscfg.yml

This provides solution for MYNEWT-526 (connection timeout with Polar H7). This is not a fix, since there is no problem on our side - it's just an configuration option to adjust initial connection event scheduling in a way that broken TI CC254x (which Polar H7 is based on) can work properly. See commit message for details.
...and few minor fixes for LL in Nimble controller.

MYNEWT-526 + few Nimble/controller fixes

---

hw/scripts/jlink.sh
hw/scripts/openocd.sh

Simon's msys2 environment doesn't work without it.
My msys2 works with and without the 2nd explicit COMPSEC /C/
Looks like the only fix that was needed is to move the opening "

Add back the 2nd explict COMSPEC /C.

---

hw/mcu/native/syscfg.yml
kernel/os/src/arch/sim/os_arch_sim_gen.c
kernel/os/src/arch/sim/os_arch_sim_nosig.c
kernel/os/src/arch/sim/os_arch_sim_priv.h
kernel/os/src/arch/sim/os_arch_sim_sig.c
net/ip/native_sockets/src/native_sock.c

This commit splits sim into two separate implementations:
* "signals"
* "no-signals"
The user chooses which implementation to use via the
MCU_NATIVE_USE_SIGNALS syscfg setting (defined in hw/mcu/native).  The
two implementations are described below:
signals:
More correctness; less stability.  The OS tick timer will
cause a high-priority task to preempt a low-priority task.
This causes stability issues because a task can be preempted
while it is in the middle of a system call, potentially
causing deadlock or memory corruption.
no-signals:
Less correctness; more stability.  The OS tick timer only
runs while the idle task is active.  Therefore, a sleeping
high-priority task will not preempt a low-priority task due
to a timing event (e.g., delay or callout expired).
However, this version of …

MYNEWT-745 Sim - deadlock involving system calls

---

hw/bsp/nina-b1/bsp.yml
hw/bsp/nina-b1/nrf52dk_debug.cmd
hw/bsp/nina-b1/nrf52dk_download.cmd
hw/bsp/stm32f767-nucleo/bsp.yml
hw/bsp/stm32f767-nucleo/nucleo767_debug.cmd
hw/bsp/stm32f767-nucleo/nucleo767_download.cmd

They are added for the following boards:
1) stm32f767-nucleo (tested)
2) nina-b1 (not tested - I don't have the board and also we do not have a tutorial that uses it). 
Note: The following boards do not have debug.sh and download.sh  so I did not add .cmd files for them:
1. ci40
2. pic32mx470_6lp_clicker 
3. pic32mz2048_wi-fire

Add .cmd files for debug and download scripts for Windows.

---

boot/bootutil/src/image_validate.c
boot/bootutil/src/loader.c

Watchdog timer that was enabled by the app is still running after a soft reset, but without a scheduler the bootloader invariably trips it whenever it has to swap or verify images. The bootloader actually does an incredible job recovering; the only shreds of evidence are longer boot time and a reset reason value of `WATCHDOG` saved in `NRF_POWER->RESETREAS` of the nRF51; which is possibly why this has gone unnoticed.
This is somewhat related to https://issues.apache.org/jira/browse/MYNEWT-618.

boot: Tickle watchdog during image swap and verify

---

hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/include/controller/ble_phy.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_ctrl.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/src/ble_ll_sched.c

This adds basic support for Coded PHY, i.e. connection can be switched to Coded PHY and should work as long as data can fit in Coded PHY timings since constraints for Coded PHY are not enforced yet.

Coded PHY support

---

net/nimble/host/include/host/ble_hs_test.h
net/nimble/host/include/host/ble_store.h
net/nimble/host/src/ble_hs_pvcy.c
net/nimble/host/src/ble_hs_pvcy_priv.h
net/nimble/host/src/ble_store.c
net/nimble/host/src/ble_store_util.c
net/nimble/host/store/ram/include/store/ram/ble_store_ram.h
net/nimble/host/store/ram/src/ble_store_ram.c
net/nimble/host/syscfg.yml
net/nimble/host/test/src/ble_gatts_notify_test.c
net/nimble/host/test/src/ble_hs_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_store_test.c
net/nimble/include/nimble/ble.h

This pull request adds the following three functions to the host store
API:
```
/**
* Deletes all entries from the store that match the specified key.
*
* @param type                  The type of store entry to delete.
* @param key                   Entries matching this key get deleted.
*
* @return                      0 on success;
*                              Other nonzero on error.
*/
int
ble_store_util_delete_all(int type, const union ble_store_key *key)
```
```
/**
* Retrieves the set of peer addresses for which a bond has been
* established.
*
* @param out_peer_id_addrs     On success, the set of bonded peer
*                                  addresses gets written here.
* @param out_num_peers         On success, the number of bonds gets
*                                  written …
```

BLE Host - Store management API additions

---

net/nimble/host/src/ble_hs_conn.c

Addr is NULL when sending le connection request using whitelist.
Error occurs on bsp/native when trying to do ble_addr_cmp
with NULL addr. There is segmentation fault when reading from NULL.

nimble/host: fix find by address when addr is NULL

---

net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/src/ble_ll_scan.c

Parameters set by HCI LE Set Scan Parameters should be stored and then
applied each time scan is enabled using HCI LE Set Scan Enable. This way
scan uses proper parameters as set by host.
Without this fix scan parameters in SM will be overwritten when
initiating new connection. Since also scan type is set to 'initiating'
in such case, no advertising reports will be sent to host until scan
parameters are set once more by the host.

nimble/controller: Fix setting parameters for scanning

---

net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_l2cap.c
net/nimble/host/src/ble_l2cap_priv.h
net/nimble/host/src/ble_sm.c
net/nimble/host/test/src/ble_hs_test_util.c

Couple of fixes after Simon review.

nimble/l2cap: Fix double free when calling ble_l2cap_discard_rx

---

hw/drivers/nimble/nrf52/src/ble_hw.c

removed duplicated #include "nrf52_bitfields.h"

cleanup - double include nrf52_bitfields.h

---

hw/bsp/pic32mz2048_wi-fire/include/bsp/bsp.h
hw/bsp/pic32mz2048_wi-fire/src/hal_bsp.c
hw/bsp/pic32mz2048_wi-fire/syscfg.yml
hw/mcu/microchip/pic32mz2048efg100/include/mcu/mips_hal.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_spi.c

This pull request implements SPI driver for PCI32MZ2048EFG100 present on the Wi-Fire board. The driver only supports master mode, blocking and non-blocking calls.
Three SPI bus are initialized at boot:
- **SPI 1**, pins available on J9 connector
- **SPI 2**, connected to microSD card slot
- **SPI 3**, connected to wifi module
I could not attach probes to SPI 2 and SPI 3 lines, so I checked the driver only with SPI 1.

Wi-Fire: Add SPI support (master mode only)

---

sys/console/full/src/rtt_console.c
sys/console/minimal/src/rtt_console.c

This ensures the RTT memory buffer always has the last 1kb of logs, as opposed to the first 1kb of logs. This is a lot more useful when dumping memory, for example.

Wrap RTT console buffer if full

---

net/nimble/host/src/ble_sm.c

I may be missing something, so please don't hesitate to yell at me if this change breaks some expected use case.
This change address the following scenario:
* Both devices using public addresses; no privacy.
1. A connects to B.
2. A initiates pairing.
3. Pairing succeeds; B indicates that its ID address is the same public
or static random address it was advertising with (i.e., no change in
address).
After this sequence completes, the connection object should be populated
as follows (from A's perspective):
* bhc_peer_addr.type: BLE_ADDR_PUBLIC
However, I see the following instead:
* bhc_peer_addr.type: BLE_ADDR_PUBLIC_ID
This is problematic because BLE_ADDR_PUBLIC_ID indicates that the peer
is using an RPA ("Public Identity Address (Corresponds to Resolved
Private Address)").  The …

BLE Host - Fix peer OTA addr and type on pairing.

---

apps/bleprph_oic/src/main.c
apps/sensors_test/src/main.c
net/oic/include/oic/oc_gatt.h
net/oic/src/port/mynewt/ble_adaptor.c

Earlier, we started using a 16-bit UUID (0x9923) instead of the 128-bit
UUID for this service.  The 128-bit UUID was actually the iotivity
service UUID which we want to support.  This commit adds the 128-bit
UUID back.

Re-add 128-bit iotivity service UUID.

---

hw/mcu/nordic/nrf51xxx/src/hal_i2c.c
hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

1st the incorrect initialization of the SCL and SDA GPIOs and 2nd, the typo in generation SCL clock.

Corrected two issues in I2C clear bus function. 

---

hw/bsp/rb-blend2/pkg.yml
hw/bsp/rb-blend2/src/hal_bsp.c
hw/bsp/rb-blend2/syscfg.yml

I noticed that both uart0 and uart1 were configured as hardware UARTs on the blend v2.
This PR fixes that and makes uart1 bitbanged (same as the other nrf52832 based boards).

make uart1 on rb-blend2 bitbanged

---

net/nimble/host/src/ble_hs_startup.c

The host intends to enable the following events at start up:
/**
* Enable the following events:
*     0x0000000000000001 Inquiry Complete Event
*     0x0000000000000002 Inquiry Result Event
*     0x0000000000000004 Connection Complete Event
*     0x0000000000000008 Connection Request Event
*     0x0000000000000010 Disconnection Complete Event
*     0x0000000000000020 Authentication Complete Event
*     0x0000000000000040 Remote Name Request Complete Event
*     0x0000000000000080 Encryption Change Event
*     0x0000000000000100 Change Connection Link Key Complete Event
*     0x0000000000000200 Master Link Key Complete Event
*     0x0000000000000400 Read Remote Supported Features Complete Event
*     0x0000000000000800 Read Remote Version Information Complete Event
*     0x0000000000001000 …

MYNEWT-772 BLE Host - Rsrvd bits in set-event-mask

---

net/nimble/host/include/host/ble_gatt.h
net/nimble/host/src/ble_gattc.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_hs_mbuf.c
net/nimble/host/src/ble_hs_mbuf_priv.h
net/nimble/host/test/src/ble_gatts_notify_test.c

This feature is described in https://issues.apache.org/jira/browse/MYNEWT-550.
In addition, I noticed two issues in the code:
* Custom notifications don't generate a GAP event to the application.  Only non-custom notifications do.
* In a few places, "ACL" was misspelled as "ACM".

Indicate custom

---

apps/testbench/pkg.yml
apps/testbench/src/tbb.c
apps/testbench/src/testbench.c
apps/testbench/src/testbench.h
apps/testbench/syscfg.yml

Currently, the testbench app uses plain newtmgr.  This PR modifies the app so that newtmgr messages are sent via CoAP instead.

MYNEWT-760  Switch testbench app over to CoAP (from plain NMP)

---

hw/mcu/microchip/pic32mz2048efg100/src/hal_reset_cause.c

Tested on a Wi-Fire board the following resets: POR, Watchdog, EXTR (MCLR pin) and soft reset caused by hal_system_reset. I did not manage to cause a BOR reset.

hw: mcu: pic32mz2048efg100: Implement hal_reset_cause

---

net/ip/mn_socket/include/mn_socket/mn_socket.h
net/ip/native_sockets/include/native_sockets/native_sock.h
net/ip/native_sockets/src/native_sock.c

This adds unix domain socket support to the mn_socket / native_sockets packages.  This is needed for blehostd.

mn_socket: Unix domain socket support.

---

apps/lorashell/src/main.c
net/lora/node/src/mac/LoRaMac.c

If the only way the timer expiration function can be called is
from the timer callback there is no need to stop the cputime
timer as it is already stopped.

No jira ticket: remove unnecessary calls to os_cputime_timer_stop

---

sys/shell/syscfg.yml

Using the nmgr_shell transport (newtmgr over shell), some incoming commands get dropped.  The problem seems to be caused by an exhaustion of shell events.  By default, the shell only allocates a single event.
The sequence looks like this:
1. Client sends newtmgr command to device.
2. Console passes newtmgr command to shell.
3. Shell allocates the only event and fills it with the data.
4. Shell processes event, hands data to newtmgr code.
5. Newtmgr processes command and sends response.
6. Client sees response and sends follow-up command.
7. Console passes newtmgr command to shell.
8. Shell has no events left; drops incoming command.
9. Initial event gets freed.
By changing the default event count from 1 to 2, we ensure there is always a spare event available.  Since we will never send the …

MYNEWT-774 Serial errors in newtmgr messages

---

hw/bsp/rb-blend2/src/hal_bsp.c

This code at the end of the rb-blend2/src/hal_bsp.c files requires the hal_i2c.h headers.
```
#if MYNEWT_VAL(I2C_0)
rc = hal_i2c_init(0, (void *)&hal_i2c_cfg);
assert(rc == 0);
#endif
```

Ensure Redbear Blend2 has i2c headers

---

hw/bsp/rb-nano2/rb-nano2_download.sh
hw/scripts/openocd.sh

- removing write protection in download script by setting the write
protection bits in the BPROT config registers. Also, setting the
DISABLEINDEBUG register.

MYNEWT-681 rb-nano2 remove flash write protection in download scripts 

---

hw/mcu/microchip/pic32mz2048efg100/src/hal_uart.c

The UART TXIF flag is set when there is some space in the TX FIFO.
In the current implementation, only one byte is sent every time
the interrupt is handled.
This change modifies the behaviour of the UART TX interrupt
handler by sending as many bytes as possible until no more bytes
are available or the TX FIFO is full.

hw: mcu: pic32mz2048efg100: Reduce number of UART TX interrupts

---

hw/drivers/sensors/bme280/pkg.yml
hw/drivers/sensors/bme280/src/bme280_shell.c
hw/drivers/sensors/bno055/pkg.yml
hw/drivers/sensors/bno055/src/bno055_shell.c
hw/drivers/sensors/tcs34725/pkg.yml
hw/drivers/sensors/tcs34725/src/tcs34725_shell.c
hw/drivers/sensors/tsl2561/pkg.yml
hw/drivers/sensors/tsl2561/src/tsl2561_shell.c
hw/sensor/include/sensor/sensor.h
hw/sensor/pkg.yml
hw/sensor/src/sensor_shell.c

- Use util/parse package for parsing instead of using
sensor_shell_stol() or parsing functions in individual drivers.
- Removing the sensor_shell_stol() API.

MYNEWT-777 SensorAPI: Use util/parse pkg instead of using   sensor_shell_stol()

---

hw/drivers/sensors/tcs34725/src/tcs34725.c
hw/drivers/sensors/tcs34725/src/tcs34725_shell.c

- Removing os_time_delay() from driver and moving it to shell for using it with shell.
- Sensor framework polling timer should be used for reading instead of os_time_delay().

MYNEWT-779 tcs34725 driver: remove os_time_delay()

---

hw/drivers/sensors/bno055/src/bno055_shell.c
hw/drivers/sensors/bno055/syscfg.yml
hw/drivers/sensors/tcs34725/src/tcs34725_shell.c
hw/drivers/sensors/tcs34725/syscfg.yml
hw/drivers/sensors/tsl2561/src/tsl2561_shell.c
hw/drivers/sensors/tsl2561/syscfg.yml

Sensor driver shells should expose ADDR syscfg since the shell should use a specific address to talk to a sensor device.

MYNEWT-780 Sensor driver shells: expose ADDR syscf

---

hw/bsp/stm32f7discovery/include/bsp/stm32f7xx_hal_conf.h
hw/bsp/stm32f7discovery/src/hal_bsp.c
hw/bsp/stm32f7discovery/src/system_stm32f7xx.c
hw/mcu/stm/stm32f7xx/src/hal_system_start.c

Function generated using Cube MX, with the STM32F7-DISCOVERY board
definition. Uses internal oscillator at 16 MHz.

Increase MCU clock speed on STM32F7-Discovery to maximum 168 MHz.

---

apps/blecent/src/main.c
apps/bleprph/src/main.c
apps/bleprph_oic/src/main.c
apps/blesplit/src/main.c
apps/bletiny/src/main.c
apps/bleuart/src/main.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_sm.h
net/nimble/host/include/host/ble_store.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_lgcy.c
net/nimble/host/src/ble_sm_sc.c
net/nimble/host/test/src/ble_sm_lgcy_test.c
net/nimble/host/test/src/ble_sm_test_util.c
net/nimble/host/test/src/ble_sm_test_util.h

This pull request addresses the issue identified in MYNEWT-750 (https://issues.apache.org/jira/browse/MYNEWT-750).
This PR incorporates changes from another PR: 277 (#277). Therefore, this PR should only be merged after 277.

Repeat pairing

---

apps/bleprph_oic/pkg.yml
apps/bleprph_oic/src/main.c
apps/bleprph_oic/syscfg.yml
net/oic/include/oic/port/oc_connectivity.h
net/oic/src/port/mynewt/ble_adaptor.c

This allows registering multiple services for OIC. Server will respond using notification characteristic which matches write characteristic for incoming request.
Also add syscfg knob to bleprph_oic, which allows choosing whether to advertise the 16-bit UUID for OIC, or 128-bit UUID. At the moment only one of them will be allowed.

Multiple oic service uuids

---

hw/mcu/microchip/pic32mz2048efg100/src/hal_spi.c

Two issues were found in ```hal_spi```:
* The formula to compute ```SPIxBRG``` was wrong.
* Potential underrun of the RX FIFO in ```hal_spi_txrx```

hw: mcu: pic32mz2048efg100: Fix issues in hal_spi

---

boot/bootutil/src/loader.c

bootloader would still boot image in slot0 with invalid signature.

boot/bootutil; security fix - if BOOTUTIL_VALIDATE_SLOT0 was set,

---

net/nimble/host/include/host/ble_att.h
net/nimble/host/src/ble_att.c
net/nimble/host/syscfg.yml
net/nimble/host/test/src/ble_hs_conn_test.c

This commit introduces two changes:
1. Reduce the default preferred ATT MTU from 527 to 256.  This is
desirable because supporting such a large MTU requires more mbuf space
than the example apps allocate.  Furthermore, such a large MTU requires
more stack space from higher layer protocols.
2. Make default preferred MTU configurable via the following syscfg
setting:
BLE_ATT_PREFERRED_MTU:
description: The preferred MTU to indicate in MTU exchange commands.
value: 256

BLE Host - decrease default mtu; make configurable at build time.

---

apps/btshell/pkg.yml
apps/btshell/src/bletiny.h
apps/btshell/src/btshell.h
apps/btshell/src/cmd.c
apps/btshell/src/cmd.h
apps/btshell/src/cmd_gatt.c
apps/btshell/src/cmd_gatt.h
apps/btshell/src/cmd_l2cap.c
apps/btshell/src/cmd_l2cap.h
apps/btshell/src/gatt_svr.c
apps/btshell/src/main.c
apps/btshell/src/misc.c
apps/btshell/src/parse.c
apps/btshell/syscfg.yml
net/nimble/host/include/host/ble_gatt.h
net/nimble/host/src/ble_gatts.c
net/nimble/host/src/ble_gatts_lcl.c

Features improved command naming and tab completion functionality.
In the future it could replace bletiny. Later some commands
implementations could me placed inside respective packages and added
to shell as separate modules, e.g. l2cap, gatt, gap, etc.

apps/btshell: add bletiny clone that uses new shell

---

apps/slinky/pkg.yml

The slinky app includes i2c_scan, but this causes a build error
on HAL ports which don't include an i2c driver. This change only
includes i2c_scan when some I2C_x switch is enabled.

Enable i2c_scan only when there is I2C peripheral

---

apps/sensors_test/src/main.c
apps/sensors_test/syscfg.yml
hw/bsp/ruuvi_tag_revb2/pkg.yml
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/sensor/creator/src/sensor_creator.c

- Fix onbaord sensor config by adding it to sysinit
- removing DEVICE_READY check from config functions as it is not
needed as the check already happens in os_dev_open()
- Fixing comments

Fix onboard sensor config & misc

---

hw/mcu/native/src/hal_uart.c
net/oic/include/oic/oc_rep.h
net/oic/src/port/mynewt/ip4_adaptor.c
net/oic/src/port/mynewt/ip_adaptor.c
sys/config/src/config.c
sys/id/include/id/id.h
sys/id/src/id.c

- encoding byte arrays in oic responses was wrong
- export serial number, manufacturing id as global symbols from sys/is
- allow config handlers to not specify get routine
- cut'n'past to native console deadlocks the system
- failing to create ipv4 sockets was closing ipv6 socket for oic

Misc fixes

---

hw/bsp/nrf51dk/syscfg.yml
hw/bsp/nrf52840pdk/syscfg.yml
hw/bsp/nrf52dk/syscfg.yml
hw/drivers/nimble/native/src/ble_phy.c
hw/drivers/nimble/nrf51/include/ble/xcvr.h
hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/include/ble/xcvr.h
hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/include/controller/ble_ll_sched.h
net/nimble/controller/include/controller/ble_phy.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/controller/syscfg.yml
net/nimble/include/nimble/ble.h

This removes controller code which uses 1MHz clock so we always use code for 32.768kHz clock.

MYNEWT-785: Remove support for 1MHz clock in nimble

---

net/nimble/host/include/host/ble_hs.h
net/nimble/host/store/config/include/store/config/ble_store_config.h
net/nimble/host/store/config/pkg.yml
net/nimble/host/store/config/src/ble_store_config.c
net/nimble/host/store/config/src/ble_store_config_conf.c
net/nimble/host/store/config/src/ble_store_config_priv.h
net/nimble/host/store/config/syscfg.yml
net/nimble/host/store/ram/pkg.yml
net/nimble/host/syscfg.yml
net/nimble/host/test/pkg.yml
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_sm_test_util.c
net/nimble/host/test/src/ble_store_test.c
net/nimble/host/test/syscfg.yml

This pull request adds a new package: ble/host/store/config.  This package holds security material and CCCDs in RAM, and optionally saves them to sys/config.  Because this package is a superset of store/ram, it deprecates that one.
This PR incorporates changes from other PRs:
* 277 (#277)
* 279 (#279)
Therefore, this PR should only be merged after those.

BLE Host - Persist bonding material to sys/config

---

net/nimble/controller/syscfg.yml

When BLE_EXT_ADV is set to 0 then we got:
Error: Syscfg restriction violations detected:
BLE_LL_CFG_FEAT_LL_EXT_ADV=MYNEWT_VAL_BLE_EXT_ADV requires
BLE_EXT_ADV be set, but BLE_EXT_ADV=0
Setting history (newest -> oldest):
BLE_EXT_ADV: [net/nimble:0]
BLE_LL_CFG_FEAT_LL_EXT_ADV:
[net/nimble/controller:MYNEWT_VAL_BLE_EXT_ADV]
This is because BLE_LL_CFG_FEAT_LL_EXT_ADV value is other flag which is
not resolved yet.
This patch remove restrictions. It should still work fine until user use
BLE_EXT_ADV to configure extended advertising - will put it in
documentation

nimble/controller: Remove not working restrictions

---

net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/src/ble_ll_conn.c

phy_data is only initialized when PHY support is enabled so we can
remove it from non-phy builds to save some RAM.
This also fixes regression where phy_data was used without proper
initialization when PHY support was disabled.

nimble/controller: Remove phy_data from non-phy builds

---

README.md
hw/bsp/vbluno52/boot-nrf52xxaa.ld
hw/bsp/vbluno52/bsp.yml
hw/bsp/vbluno52/include/bsp/bsp.h
hw/bsp/vbluno52/include/bsp/cmsis_nvic.h
hw/bsp/vbluno52/nrf52xxaa.ld
hw/bsp/vbluno52/pkg.yml
hw/bsp/vbluno52/split-vbluno52.ld
hw/bsp/vbluno52/src/arch/cortex_m4/gcc_startup_nrf52.s
hw/bsp/vbluno52/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/vbluno52/src/hal_bsp.c
hw/bsp/vbluno52/src/sbrk.c
hw/bsp/vbluno52/syscfg.yml
hw/bsp/vbluno52/vbluno52_debug.cmd
hw/bsp/vbluno52/vbluno52_debug.sh
hw/bsp/vbluno52/vbluno52_download.cmd
hw/bsp/vbluno52/vbluno52_download.sh
hw/bsp/vbluno52/vbluno52_no_boot.ld

The VBLUno52 board from VNG (Nordic nRF52832 Cortex-M4 SoC based)
+ Abstract
nRF52832 Cortex-M4
Bluetooth Low Energy 5.0 (new)
DAPLink interface: Flash, Debug, Virtual COM port
UNO pinout
4 power
Signed-off-by: iotvietmember <robotden@gmail.com>

Add support for the VBLUno52 board

---

net/nimble/host/test/src/ble_gap_test.c
net/nimble/host/test/src/ble_hs_conn_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h
net/nimble/host/test/src/ble_os_test.c
net/nimble/host/test/src/ble_sm_test_util.c

After connection complete event host will read peers features and then
will use this information when selecting procedure for connection
parameters update. Both changes requires unittests to be updated:
- phony ack is added for complete event since it will send extra HCI
command if connection is successful
- features event is injected to set features properly
- connection update failover from HCI to L2CAP is removed since this
is selected based on features

nimble/test: Update unittests after features exchange changes

---

kernel/os/include/os/os_cputime.h
kernel/os/src/os_cputime.c

Report errors from hal_timer functions for os_cputime_timer_start()
and os_cputime_timer_relative().

MYNEWT-792: Return hal_timer error codes from os_cputime functions

---

net/nimble/controller/include/controller/ble_ll.h

Seems like this was enabled some time ago by mistake and consumed
4K of RAM for no reason.

nimble/controller: Disable LL logs

---

sys/shell/include/shell/shell.h
sys/shell/src/shell.c
sys/shell/src/shell_os.c
sys/shell/src/shell_priv.h
sys/shell/src/shell_prompt.c
sys/shell/syscfg.yml

This patch introduces simplifications and improvements suggested by @cwanda.
Changes include:
* bringing back shell_evq_set
* directly using shell_register api in internal shell modules
* asserting when max number of modules exceeded 
* removing module name length limit
* adding prompt suffix option to syscfg
* some whitespace fixes

Shell improvements before 1.1

---

net/nimble/host/src/ble_sm.c

This issue is documented in: https://issues.apache.org/jira/browse/MYNEWT-749
This commit implements the following behavior:
If either peer indicates a key distribution flags value of 0, then don't persist security material when pairing completes.
It isn't clear from the spec what should happen when both peers indicate bonding support, but one indicates a 0 key distribution field.  I think proceding with pairing and just not persisting makes the most sense. This is also what Lightblue (or CoreBluetooth, I guess) seems to do.

BLE Host - Don't persist security material if either key distribution field is 0

---

net/mqtt/eclipse/LICENSE.txt
net/mqtt/eclipse/include/mqtt/MQTTConnect.h
net/mqtt/eclipse/include/mqtt/MQTTFormat.h
net/mqtt/eclipse/include/mqtt/MQTTPacket.h
net/mqtt/eclipse/include/mqtt/MQTTPublish.h
net/mqtt/eclipse/include/mqtt/MQTTSubscribe.h
net/mqtt/eclipse/include/mqtt/MQTTUnsubscribe.h
net/mqtt/eclipse/include/mqtt/StackTrace.h
net/mqtt/eclipse/pkg.yml
net/mqtt/eclipse/src/MQTTConnectClient.c
net/mqtt/eclipse/src/MQTTConnectServer.c
net/mqtt/eclipse/src/MQTTDeserializePublish.c
net/mqtt/eclipse/src/MQTTFormat.c
net/mqtt/eclipse/src/MQTTPacket.c
net/mqtt/eclipse/src/MQTTSerializePublish.c
net/mqtt/eclipse/src/MQTTSubscribeClient.c
net/mqtt/eclipse/src/MQTTSubscribeServer.c
net/mqtt/eclipse/src/MQTTUnsubscribeClient.c
net/mqtt/eclipse/src/MQTTUnsubscribeServer.c

1: Eclipse/Paho's MQTTPacket [1] contains the lowest level C library with the smallest requirements. This supplies simple serialization and de-serialization routines. It is up to the application writer to implement read/write over the network. 
2: Please ignore my previous pull request, i.e. #358 
[1] https://github.com/eclipse/paho.mqtt.embedded-c

Adding Eclipse Paho 'C' client for embedded platforms.

---

net/nimble/transport/socket/src/ble_hci_socket.c
net/nimble/transport/socket/syscfg.yml

This prevents deadlock while the host waits for a command-complete event from the controller.  This is a slightly modified patch written by @rymanluk (changes include: adding a few syscfg settings, minor renames).

Give HCI socket transport its own task.

---

apps/bleprph/syscfg.yml
apps/bleprph_oic/syscfg.yml
apps/blesplit/syscfg.yml
apps/bletiny/pkg.yml
apps/bletiny/src/cmd.c
apps/bletiny/syscfg.yml

There are several scenarios in which the sample BLE apps fail to run:
_bleprph and bleprph_oic_
* *Low MTU.*  Several devices use a BLE ATT MTU of 104 (e.g., Mac OS).  With this MTU, some newtmgr responses failed to send.  The fix is to increase the number of mbufs and decrease their size
* *Image upgrade.*  Image upgrade requires a fairly large main stack.  The default values for both bleprph apps was too low, resulting a crash during processing of the upload request.
_bletiny_
Bletiny had grown too large to fit on an nRF51.  This PR reduces bletiny's code size in the following ways:
* Remove support for newtmgr-over-shell.  Newtmgr isn't included in bletiny anyway, so this change removes unused functionality.
* Make bletiny help optional via the BLETINY_HELP syscfg setting.
* Make …

Make BLE sample apps more robust

---

mgmt/newtmgr/include/newtmgr/newtmgr.h
mgmt/newtmgr/src/newtmgr.c
mgmt/newtmgr/transport/ble/src/newtmgr_ble.c

When queried for the connection's ATT MTU, the BLE newtmgr transport assumes the peer is connected.  If the peer is no longer connected when the query occurs, a failed assert is triggered.
The assumption that the peer is still connected is not always vaild.  A well-timed control-c during a newtmgr image upgrade can trigger this crash:
```
Program received signal SIGTRAP, Trace/breakpoint trap.
__assert_func (file=<optimized out>, line=<optimized out>, func=<optimized out>, e=<optimized out>) at kernel/os/src/arch/cortex_m4/os_fault.c:137
137            asm("bkpt");
(gdb) whe
#0  __assert_func (file=<optimized out>, line=<optimized out>, func=<optimized out>, e=<optimized out>) at kernel/os/src/arch/cortex_m4/os_fault.c:137
#1  0x00025c8e in nmgr_ble_get_mtu (req=<optimized out>) at …
```

nmgr_ble - don't crash if peer disconnected during MTU query

---

apps/test/src/test.c
boot/boot_serial/test/src/boot_test.c
boot/bootutil/test/src/boot_test.c
crypto/mbedtls/test/src/mbedtls_test.c
encoding/base64/test/src/encoding_test.c
encoding/cborattr/test/src/test_cborattr.c
encoding/json/test/src/test_json.c
fs/fcb/test/src/fcb_test.c
fs/nffs/test/src/nffs_test.c
kernel/os/test/src/os_test.c
net/ip/mn_socket/test/src/mn_sock_test.c
net/nimble/host/test/src/ble_hs_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/oic/test/src/test_oic.c
sys/config/test-fcb/src/conf_test_fcb.c
sys/config/test-nffs/src/conf_test_nffs.c
sys/flash_map/test/src/flash_map_test.c
sys/log/full/test/src/log_test.c
test/testutil/include/testutil/testutil.h
test/testutil/pkg.yml
test/testutil/src/testutil.c
util/cbmem/test/src/cbmem_test.c

All selftest main() functions had the same initialization sequence for the testutil package:
1. `ts_config.ts_print_results = 1;`
2. `tu_init();`
3. (sometimes) `tu_parse_args(argc, argv);`
The issues with this are:
* Since (1) is always present, it could be performed by the `tu_init()` function call automatically.
* (2) is inconsistent with regular apps.  An app calls `sysinit()` from main, but selftest programs call `tu_init()`, which in turn calls `sysinit()`.
* (3) is obsolete; `newt run <test-pkg>` takes care of argument parsing now.
This commit addresses these issues as follows:
1. Move `ts_config.ts_print_results = 1;` into `tu_init()`.
2. Turn `tu_init()` into a sysinit function.  That is, have it get called automatically by sysinit.
3. Remove `tu_parse_args()` entirely.
4. In …

testutil - Remove init boilerplate

---

net/nimble/host/include/host/ble_store.h
net/nimble/host/src/ble_store.c
net/nimble/host/test/src/ble_store_test.c

(Jira ticket: https://issues.apache.org/jira/browse/MYNEWT-268)gg
This commit adds a new function to the host API:
/**
* Deletes all objects from the BLE host store.
*
* @return                      0 on success; nonzero on failure.
*/
int
ble_store_clear(void)
This function can be used to effect a factory reset.

MYNEWT-268 BLE Host - enable factory reset

---

apps/sensors_test/src/main.c

Fix the following compilation error:
main.c:76:12: error: 'sensor_oic_gap_event' declared 'static' but never defined [-Werror=unused-function]
static int sensor_oic_gap_event(struct ble_gap_event *event, void *arg);
^

Fix compilation error in apps/sensors_test/main.c when SENSOR_OIC is disabled

---

hw/bsp/bbc_microbit/microbit_debug.sh
hw/bsp/bbc_microbit/microbit_download.sh
hw/bsp/bbc_microbit/syscfg.yml

Helpful as a 'free' Segger RTT device via JLINK OB firmware from Segger
Youll need to change the uploader firmware on your board to the new jlink firmware using the following guide from Segger
https://www.segger.com/products/debug-probes/j-link/models/other-j-links/bbc-microbit-j-link-upgrade/?L=0
(NOTE if you ever want to go back to the original daplink (cmsisdap) firwmare for you microbit, follow those instructions:
https://www.mbed.com/en/platform/hardware/prototyping-production/daplink/daplink-on-kl26z/)

microbit bsp: add JLINK_DEBUG option to switch to jlink

---

hw/bsp/hifive1/hifive1.ld
hw/bsp/hifive1/hifive1_app.ld
hw/bsp/hifive1/hifive1_boot.ld
hw/bsp/hifive1/riscv_openocd.cfg
hw/mcu/sifive/src/ext/freedom-e-sdk_3235929/LICENSE

Few files lacked Apache licenses.
Freedom-e-sdk license file also included for completeness.

bsp/fe310: Add missing licenses

---

libc/baselibc/src/tinyprintf.c
net/nimble/host/include/host/ble_monitor.h
net/nimble/host/pkg.yml
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_hs_dbg.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_priv.h
net/nimble/host/src/ble_l2cap_sig.c
net/nimble/host/src/ble_monitor.c
net/nimble/host/src/ble_monitor_priv.h
net/nimble/host/syscfg.yml
sys/console/full/src/ble_monitor_console.c
sys/console/full/src/console.c
sys/console/full/syscfg.yml

See here for details: http://mail-archives.apache.org/mod_mbox/incubator-mynewt-dev/201706.mbox/%3CCADAkoF4LQOdqH%3DLh%3D5GgBPC9nEaXV95TV_uQPXXWuhrpCXfbtQ%40mail.gmail.com%3E
This is core monitor protocol functionality extracted from https://github.com/apache/mynewt-core/pull/362 so logging stuff does not block it.

nimble: add monitor protocol/interface

---

apps/blecent/src/blecent.h
apps/bletiny/src/gatt_svr.c
apps/btshell/src/gatt_svr.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_gatt.h
net/nimble/host/src/ble_att.c
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_gatt_priv.h
net/nimble/host/src/ble_gatts.c
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_uuid.c

* Add API documentation in comments above some public functions.
* Move prototypes for non-API functions into "[...]_priv.h" headers.
* Delete some obsolete and unused functions.

BLE Host - Add comments; move non-API declarations to private headers.

---

net/nimble/controller/include/controller/ble_ll_adv.h
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_sched.c

MYNEWT-810: This fixes the scheduler error where the controller
would send the wrong state machine to the advertising halt
function and an incorrect event would get sent to the LL for
processing.

nimble/controller: Fix scheduler advertising halt error

---

apps/bleprph_oic/src/main.c
apps/testbench/src/tbb.c
net/oic/include/oic/oc_gatt.h
net/oic/src/port/mynewt/ble_adaptor.c

Prior to this commit, we were using an arbitrarily-chosen UUID: 0x9923.
The real UUID (0xfe18) is reserved with the Bluetooth SIG.

Use real runtime Bluetooth svc UUID (0xfe18).

---

libc/baselibc/src/sprintf.c
libc/baselibc/src/vsprintf.c

repos/apache-mynewt-core/libc/baselibc/src/sprintf.c:15:5: error:
specified bound 4294967295 exceeds maximum object size 2147483647
[-Werror=format-truncation=]
rv = vsnprintf(buffer, SIZE_MAX, format, ap);
~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-core/libc/baselibc/src/vsprintf.c:10:9: error:
specified bound 4294967295 exceeds maximum object size 2147483647
[-Werror=format-truncation=]
return vsnprintf(buffer, ~(size_t) 0, format, ap);
GCC limits maximum object size to MAX_SIZE/2 (or PTRDIFF_MAX).

baselibc: Fix compilation with GCC7

---

net/nimble/controller/src/ble_ll_conn.c

Slave connction was always created with 1M PHY instead of last used
one. This fix connection on 1M and coded PHYs.

slave connection fix

---

sys/console/full/src/console.c

fixing the following issues:
- Non-printable characters except for the newtmgr control characters being
input to the console were ignored.
- console_read() was replacing single characters by '\0'

MYNEWT-811 Console compatibility broken

---

net/ip/native_sockets/src/native_sock.c
net/ip/native_sockets/syscfg.yml

The motivation for this change was to allow the polling interval to be changed.  The default value, 200ms, was making blehostd rather sluggish during image upgrade.

native_sockets - Add syscfg settings.

---

hw/scripts/jlink.sh

'newt run' was not always updating the flash on nrf52dk. With this workaround in place it seems to work every time.
Not sure why this fixes it. Trying to dump the contents of flash to a file after 'restore' did NOT fix it. Not only that, dump returns the data that I was trying to write, as if it had worked. Attaching to target afterwards showed that flash had not been updated.
Might be some write caching issue, but not sure where it is at.

jlink.sh; dump registers after writing flash.

---

hw/bsp/ada_feather_nrf52/include/bsp/boards.h
hw/bsp/bbc_microbit/include/bsp/boards.h
hw/bsp/nrf51-arduino_101/include/bsp/boards.h
hw/bsp/nrf51-blenano/include/bsp/boards.h
hw/bsp/nrf51dk-16kbram/include/bsp/boards.h
hw/bsp/nrf52-thingy/include/bsp/boards.h
hw/bsp/nrf52dk/include/bsp/boards.h

ADC tutorial (and things that use the nordic sdk like upcoming PWM work) is erroring on lots of nordic targets with:
```
Error: In file included from repos/mynewt_nordic/hw/mcu/nordic_sdk/src/ext/nRF5_SDK_11.0.0_89a8197/components/drivers_nrf/spi_master/spi_5W_master.c:26:0:
repos/mynewt_nordic/hw/mcu/nordic_sdk/src/ext/nRF5_SDK_11.0.0_89a8197/components/drivers_nrf/spi_master/spi_5W_master.h:18:20: fatal error: boards.h: No such file or directory
#include "boards.h"
^
compilation terminated.
```
Many targets seem to have an empty boards.h so that was copied to all other nordic targets.

bsps: nordic sdk errors without boards.h

---

boot/boot_serial/pkg.yml
boot/bootutil/pkg.yml
boot/split/pkg.yml
hw/bsp/nrf52840pdk/pkg.yml
mgmt/imgmgr/pkg.yml
sys/coredump/pkg.yml

Add bootloader as an API; and from packages which depend on boot/bootutil, depend on the API rather than the actual package.
This makes it easier to use bootloader from mcuboot project.

Bootloader api

---

apps/bleprph/pkg.yml
apps/bleprph_oic/pkg.yml
apps/testbench/pkg.yml
boot/boot_serial/test/pkg.yml

Prev checkin broke few apps which did not depend on bootutil explicitly.

testbench/boot serial unittest; add dependency to bootutil.

---

hw/drivers/rtt/include/rtt/SEGGER_RTT_Conf.h
hw/drivers/rtt/syscfg.yml

- Segger RTT takes input of 16 max based on BUFFER_SIZE_DOWN defined in
hw/drivers/rtt/include/rtt/SEGGER_RTT_Conf.h. This should be made a
syscfg. I was seeing issues with Thingy with jLinkExe version 6.00c, where I
could not issue sensor read command on it, based on the echo it seems
that the code just takes 16 characters of input.
Fix is to define MYNEWT_VAL(RTT_BUFFER_SIZE_DOWN) in syscfg.yml and set
it by default to a higher number if somebody would like to get it
working with jLinkExe version 6.00c.

MYNEWT-813 RTT console i/p limited to 16 chrs

---

encoding/tinycbor/include/tinycbor/compilersupport_p.h

GCC 7 reports a bad option is -ffunction-sections is specified through
pragma. Since this never really worked also in older versions of GCC
just remove it.
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81368

tinycbor: Fix compilation with GCC 7

---

boot/bootutil/src/loader.c
boot/bootutil/syscfg.yml

This makes possible to configure via syscfg.yml the ability to
validate slot 0 on every boot.

Enable configuration of slot 0 boot validation

---

boot/bootutil/src/image_validate.c

This removes use of key-id when looking for a sign key and tries to
validate images using every available key in the bootloader, adding
compatibility with "newt resign-image" command which accepts whatever
key-id was supplied by the user.

Enables newt resigned images

---

hw/bsp/nrf51dk/include/bsp/bsp.h
hw/bsp/nrf52dk/include/bsp/bsp.h

hw/bsp/nrf52dk/include/bsp/bsp.h was lacking on some LED, button and pin value definitions.
This commit adds the missing macro definitions.

Adding  LED, button and pin values to bsp.h

---

hw/drivers/nimble/nrf52/src/ble_phy.c

The CRCSTATUS register is not cleared automatically by hardware so it
may not reflect current state of CRC check in some cases. The better way
to check CRC is to clear EVENT_CRCOK when starting to receive a packet
and then check its state when done.

[MYNEWT-285] nimble/phy: Fix CRC checking

---

boot/bootutil/src/image_validate.c

Reverts apache/mynewt-core#430
We decided on removing this "hack" and postpone this feature, to do a properly designed solution in mcuboot 1.0 and Mynewt 1.2.

Revert "Enables newt resigned images"

---

net/nimble/controller/src/ble_ll_scan.c

In legacy scanning next_phy is unconfigured so we should not try to
configure channels for next_phy as it will corrupt some random
memory.
Also add assert to make sure cur_phy is always configured, because it
should be.

nimble/controller: Fix legacy scanning

---

hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/syscfg.yml

- Adding API for setting sensor poller in ms
- Also fixing the sensor manager poller which was trying to reset the
callout to absolute time instead of relative time
- Changing the syscfg for SENSOR_MGR_WAKEUP_RATE to 2000 ms

MYNEWT-816 SensorAPI: Add API for sensor poller & fix the poller callout

---

hw/drivers/sensors/bme280/src/bme280.c
hw/drivers/sensors/bno055/src/bno055.c
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/sim/src/generic_accel.c
hw/drivers/sensors/sim/src/generic_mag.c
hw/drivers/sensors/tcs34725/src/tcs34725.c
hw/drivers/sensors/tsl2561/src/tsl2561.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/src/sensor_oic.c
hw/sensor/src/sensor_shell.c

- Adding type field as a parameter to data_func callback and the listener function. It helps in letting the callback and listener know which type of data the callback or the listener is looking at.
- Fixing bno055 driver read function so that all data can be read instead of reading data for a single sensor type.
- Calling listener only for a specific type, filtering based on the mask. Earlier the listener would not honor the listener.

MYNEWT-815 SensorAPI: Add type to data_func,listen

---

hw/bsp/vbluno51/src/arch/cortex_m0/gcc_startup_nrf51.s

Add `BL hal_system_init` in startup file (` hw/bsp/vbluno51/src/arch/cortex_m0/gcc_startup_nrf51.s`) for VBLUno51 board
Signed-off-by: iotvietmember <robotden@gmail.com>

Add hal_system_init in startup file for VBLUno51 board

---

hw/bsp/vbluno51/include/bsp/bsp.h
hw/bsp/vbluno52/include/bsp/bsp.h

Clear LED define for the VBLUno51, VBLUno52 board.
Because `LED` was be used in other file
Signed-off-by: iotvietmember <robotden@gmail.com>

Clear LED define for the VBLUno51, VBLUno52 board.

---

hw/drivers/nimble/nrf52/src/ble_phy.c

nRF52 does not have symbols for 125/500 data rates in CCM defined (for
LE Coded PHY - we only allow 1M on nRF52 anyway).
Error: repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c: In
function 'ble_phy_get_ccm_datarate':
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:505:16:
error: 'CCM_MODE_DATARATE_125Kbps' undeclared (first use in this
function)
return CCM_MODE_DATARATE_125Kbps << CCM_MODE_DATARATE_Pos;
^~~~~~~~~~~~~~~~~~~~~~~~~
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:505:16:
note: each undeclared identifier is reported only once for each function
it appears in
repos/apache-mynewt-core/hw/drivers/nimble/nrf52/src/ble_phy.c:507:16:
error: 'CCM_MODE_DATARATE_500Kbps' undeclared (first use in this
function)
return CCM_MODE_DATARATE_500Kbps …

nimble/phy: Fix build error on nRF52

---

hw/drivers/nimble/nrf52/src/ble_phy.c

g_ble_phy_rx_buf is declared as uint32_t[] so [3] and [5] does not
really point where I expected...

nimble/phy: Fix resolving address

---

net/nimble/host/test/src/ble_hs_test_util.c

This addresses the following compiler error encountered in macOS:
```
Compiling net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.c: In function 'ble_hs_test_util_create_rpa_conn':
net/nimble/host/test/src/ble_hs_test_util.c:411:79: error: macro "memcpy" passed 10 arguments, but takes just 3
memcpy(evt2.features, (uint8_t[]){ conn_features, 0, 0, 0, 0, 0, 0, 0 }, 8);
^
net/nimble/host/test/src/ble_hs_test_util.c:411:5: error: statement with no effect [-Werror=unused-value]
memcpy(evt2.features, (uint8_t[]){ conn_features, 0, 0, 0, 0, 0, 0, 0 }, 8);
^
```
This error occurs on the mac because its standard library implements `memcpy()` as a macro rather than a function.  The reason for the error is explained here: …

Fix host unit test compiler error on mac

---

util/parse/include/parse/parse.h
util/parse/src/parse.c

This function should return an unsigned long long; it was returning long long instead.

util/parse: Fix parse_ull return type.

---

net/nimble/host/src/ble_hs_hci_util.c

This fix extended advertising with random address provided by application.

nimble: Fix setting advertising instance random address

---

hw/bsp/pic32mx470_6lp_clicker/include/bsp/bsp.h
hw/bsp/pic32mx470_6lp_clicker/src/hal_bsp.c
hw/bsp/pic32mx470_6lp_clicker/syscfg.yml
hw/mcu/microchip/pic32mx470f512h/include/mcu/mcu.h
hw/mcu/microchip/pic32mx470f512h/include/mcu/mips_hal.h
hw/mcu/microchip/pic32mx470f512h/include/mcu/pps.h
hw/mcu/microchip/pic32mx470f512h/src/hal_gpio.c
hw/mcu/microchip/pic32mx470f512h/src/hal_i2c.c
hw/mcu/microchip/pic32mx470f512h/src/hal_spi.c
hw/mcu/microchip/pic32mx470f512h/src/hal_timer.c
hw/mcu/microchip/pic32mx470f512h/src/hal_uart.c
hw/mcu/microchip/pic32mx470f512h/src/pps.c

This pull request adds the following features for the 6LoWPAN Clicker:
- GPIO (+ LED's)
- Peripheral Pin Select
- SPI (master only)
- I2C
- Timer
- Some improvements regarding to UART
The implementation is very similar to the code I wrote for the Wi-Fire (PIC32MZ).

Clicker: Implement GPIO, SPI, I2C and Timer HAL

---

sys/shell/src/shell.c

PR #361 added shell_evq_set function to shell API. This PR fixes a bug introduced in that patch. When shell_evq_set was used it didn't reset console queues, which led to still using the main eventq. This patch fixes this issue. When shell_evq_set is used both shell and console use the specified eventq.
Moreover, this patch renames a local function to a more appropriate name.

sys/shell: fix shell_evq_set not updating console queues

---

hw/sensor/src/sensor.c
hw/sensor/syscfg.yml

- Make sensor_mgr_evq_set() static
- Make sensor_mgr_evq_set() arg a syscfg with default picking up default evq.

Sensor evq

---

hw/mcu/nordic/nrf51xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/hal_timer.c

The hal_timer code for the nordic MCU's was not turning on the HFXO if one of the non-RTC timers was used by an application. The HFCLK source was running but was using HFINT (the internal oscillator) which is not very accurate. The code now turns on the HFXO. As noted in the commit, this does increase current consumption. It might be a good idea to add a config variable to use either HFINT or HFXO but I suspect that if people want to turn on these timers they want it more accurate than the HFINT (which I have seen be 6000 ppm off!)

hw/mcu/nordic: HFXO was not being turned on by hal timer

---

hw/sensor/src/sensor.c
kernel/os/include/os/os_eventq.h
kernel/os/src/os_eventq.c
mgmt/newtmgr/src/newtmgr.c
mgmt/oicmgr/src/oicmgr.c
net/nimble/host/src/ble_hs.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h
net/nimble/host/test/src/ble_os_test.c
net/oic/src/port/mynewt/adaptor.c
sys/shell/src/shell.c
test/runtest/src/runtest.c

Packages currently have two initialization phases: 1) init, and 2) start:
*init:* Runs automatically during sysinit.
*start:* A start event can optionally be put on the package's event queue; it runs when the event is processed.
The second phase is useful when the package has some settings that must be configure at runtime, but before the package starts.
The problem arises when a package is assigned a dedicated task and event queue.  If the task is higher priority than the default task, it will preempt the default task with the package's start event, before the application has had a chance to finish configuring the package.
This PR makes it so that start events always run in the default task, even if the package has been configured to run in a different one.  This ensures the start events …

Delay start events until end of main()

---

kernel/os/include/os/arch/pic32/os/os_arch.h
kernel/os/src/arch/pic32/os_arch_pic32.c

Sometimes the stack was not 8-aligned causing FPU load/store problems (and is incompatible with the ABI). Changing the type to uint64_t seems to fix it but I don't think this is portable so if anyone has any ideas for a better fix please let me know!

PIC32: Fix stack align

---

net/nimble/host/include/host/ble_gatt.h
net/nimble/host/include/host/ble_uuid.h
net/nimble/host/src/ble_att_priv.h
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_gatt_priv.h
net/nimble/host/src/ble_gatts.c
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_uuid.c
net/nimble/host/test/src/ble_gatts_notify_test.c
net/nimble/host/test/src/ble_gatts_read_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h

Prior to this change, supported GATT services could only be registered once.  This change allows the set of supported servces to be replaced "on the fly".
```
/**
* Resets the GATT server to its initial state.  On success, this function
* removes all supported services, characteristics, and descriptors.  This
* function requires that:
*     o No peers are connected, and
*     o No GAP operations are active (advertise, discover, or connect).
*
* @return                      0 on success;
*                              BLE_HS_EBUSY if the GATT server could not be
*                                  reset due to existing connections or active
*                                  GAP procedures.
*/
int
ble_gatts_reset(void)
/**
* Makes all registered services available to peers.  This function …
```

Allow GATT services to be registered after startup

---

net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/host/src/ble_hs_hci_util.c
net/nimble/host/src/ble_hs_pvcy.c
net/nimble/host/src/ble_hs_startup.c
net/nimble/host/src/ble_sm.c
net/nimble/include/nimble/hci_common.h

This refactors the way HCI commands are constructed and pass to
controller. Instead of embedding opcode and len in command parameters
buffer just pass it along with it. This has few adventages:
- opcode OCF/OGF are contructed once on build time
- buffer is always pass along with len
- code is less confusing for static analysis tools (0 len buffer is
always pass as NULL so no dangling pointers)
- it is easier to follow (and debug)
Nice bonus is ROM size reduction of net_nimble_host.a (54304->53710).
This is also first step to making use of packed structures for HCI
command instead of builders functions. This should reduce code size
even further.

nimble/host: Refactor HCI commands sending functions

---

apps/bletiny/src/cmd.c
net/nimble/host/include/host/ble_gatt.h
net/nimble/host/src/ble_att_priv.h
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_gatts.c

This is substitute for registering and unregistering services in runtime.
Instead of the above, we allow already registered service to be hidden from clients (its attributes are removed from attributes list in ATT server). This can be done at any time and does not need any in terms of GATT services handling - we just move attributes from "default" list to "hidden" list so they are not picked by any ATT API.
So basically, if there are services A and B which cannot exists in ATT DB at the same time (like in Mesh), application should register both of them and then just toggle visibility in runtime.

nimble: Allow to hide/restore services from clients in runtime

---

net/nimble/host/src/ble_gatts.c

We should stop looking for descriptors on first attribute *beyond*
service handles range, not on the one that matches service end handle.

nimble/host: Fix searching for descriptor in gatts

---

net/nimble/host/src/ble_hs.c

While the host is resetting, it attempts to restart the HCI transport.  This may involve some communication with hardware.  For example, when the UART transport resets, it closes, reopens, and reconfigures the UART.
If the HCI transport fails to restart due to a hardware failure, the host aborts its reset.  As a consequence, stale connections remain open, and the reset callback does not get called.
The host restarts the HCI transport and assumes success.  If the transport failed to reset, the host will reset itself again when it fails to sync with the controller.

BLE Host - Don't abort reset if HCI restart fails.

---

sys/shell/src/shell_os.c

Prior to this commit, the OS shell commands were only available in non-compatibility mode.

shell - Enable OS commands in compatibility mode.

---

net/nimble/host/src/ble_gatts.c

Previous check resulted in assert in ble_gap_subscribe_event when
prev_flags had BLE_GATTS_CLT_CFG_F_MODIFIED bit set

nimble/host: fix event flag check

---

sys/shell/src/shell_os.c

As pointed out by Chris Merck, a command entry with all-fields-null was getting registered.  This made subsequently registered commands inaccessible.

shell - Don't register NULL command.

---

hw/mcu/nordic/nrf51xxx/src/hal_os_tick.c
hw/mcu/nordic/nrf52xxx/src/hal_os_tick.c

The nRF51 and nRF52 MCUs require exactly one low-frequency timer setting to be enabled.  Syscfg restrictions ensure that no more than one is enabled, but is not capable of verifying that at least one is enabled.  This PR adds a compile-time check that at least one of these settings is enabled.

nRF MCUs: build-time check for an enabled low-frequency timer

---

boot/boot_serial/src/boot_serial.c
boot/boot_serial/src/boot_serial_priv.h
boot/boot_serial/src/boot_uart.c
boot/boot_serial/test/src/testcases/boot_serial_setup.c
sys/console/stub/syscfg.yml

This is for space savings. Before the change:
objsize
text	   data	    bss	    dec	    hex	filename
16248	     84	   5352	  21684	   54b4	/Users/marko/src2/incubator-mynewt-blinky/bin/targets/boot_nrf52_serial/app/apps/boot/boot.elf
After the change:
text	   data	    bss	    dec	    hex	filename
14816	     76	   4996	  19888	   4db0	/Users/marko/src2/incubator-mynewt-blinky/bin/targets/boot_nrf52_serial/app/apps/boot/boot.elf

boot_serial; access uart driver directly instead of going through console.

---

kernel/os/include/os/os_mempool.h
kernel/os/src/os_mempool.c

I used this function to debug a memory corruption issue recently.  I thought it might come in handy again at some point.
```
/**
* Performs an integrity check of the specified mempool.  This function
* attempts to detect memory corruption in the specified memory pool.
*
* @param mp                    The mempool to check.
*
* @return                      true if the memory pool passes the integrity
*                                  check;
*                              false if the memory pool is corrupt.
*/
bool
os_mempool_is_sane(const struct os_mempool *mp)
```

os_mempool_is_sane() debug function.

---

net/oic/include/oic/oc_api.h
net/oic/include/oic/oc_ri.h
net/oic/include/oic/port/oc_connectivity.h
net/oic/src/api/oc_ri.c
net/oic/src/api/oc_server_api.c
net/oic/src/port/mynewt/adaptor.c
net/oic/src/port/mynewt/adaptor.h
net/oic/src/port/mynewt/ble_adaptor.c
net/oic/syscfg.yml

Each resource can be configured to require transport layer encryption, transport layer authentication, neither, or both.  When a peer accesses the resource, the OIC server verifies the security properties of the underlying connection.  If the minimum security requirements are not
met, the server responds with a 403 forbidden error.
This form of security is an alternative to the "coaps" DTLS security that is defined in the CoAP spec.

oic: Per-resource transport layer sec requirements

---

hw/scripts/jlink.sh

Newlines from the gdb output was removed, so it was really hard to find the real error in the blob of text that was output to the shell. Just adding quotes around the variable when echoing fixes the problem.
Without quotes:
With quotes:

Fix newlines removed from gdb output

---

hw/drivers/lora/sx1276/src/sx1276-board.c
hw/drivers/lora/sx1276/src/sx1276.c
net/lora/node/include/node/lora_priv.h
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

A few additional changes with this commit. The first was to
disable the sx1276 spi before configuration. This should not
be needed but in case the spi was enabled prior to running
this image this change makes sure to disable it first. The second change
was to check for the lora timer number to be -1 (and not 0).
This insures that a timer number was set in the syscfg. The user
must choose a valid timer number. The last change was to make sure
that we check for additional enqueued transmissions after we are
finished with one.

net/lora: Additional modifications

---

net/nimble/controller/src/ble_ll_conn.c

If connection is disconnected because it has not been established,
error code 0x3e should be used.

nimble/controller: Fix disconnection event status

---

net/nimble/host/src/ble_store.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h
net/nimble/host/test/src/ble_sm_test_util.c

In order to not brake existing applications lets use privacy
device mode instead of network mode which is default in the
Controller accorting to BT 5 specification.

nimble/sm: Use privacy device mode as default

---

hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/include/nimble/ble.h

This patch fixes corrupted long advertising data when BLE_EXT_ADV is
used. It is allowed now that advertising data are in the chain of
os_mbufs.

nimble/controller: Fix scan long advertising packets

---

net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_scan.c

If the BLE_HCI_EVT_BUF_SIZE is too small for advertising events,
then adv will be dropped. There is also stats adv_evt_dropped added
for debuging purposes

nimble/controller: Drop adv event if it is too big

---

net/nimble/controller/src/ble_ll.c

Default stack size for ble_ll_task is too low.
Failing scenario can be reproduced using optimized bleprph build for
nRF51 (M0). We have following call stack:
os_eventq_put() at os_eventq.c:99 0x8d7e
ble_hs_enqueue_hci_event() at ble_hs.c:431 0x14204
ble_hs_hci_rx_evt() at ble_hs_hci.c:357 0x14d4a
ble_hci_trans_ll_evt_tx() at ble_hci_ram.c:95 0x1b860
ble_ll_hci_event_send() at ble_ll_hci.c:79 0xec90
ble_ll_conn_comp_event_send() at ble_ll_conn_hci.c:250 0xd6a2
ble_ll_adv_send_conn_comp_ev() at ble_ll_adv.c:2,849 0xb490
ble_ll_conn_created() at ble_ll_conn.c:2,511 0xc0e4
ble_ll_conn_slave_start() at ble_ll_conn.c:4,076 0xd2e6
ble_ll_adv_conn_req_rxd() at ble_ll_adv.c:2,341 0xb3f0
ble_ll_adv_rx_pkt_in() at ble_ll_adv.c:2,456 0xb3f0
ble_ll_rx_pkt_in() at ble_ll.c:720 0xa43a …

nimble/ll: Increase stack for ble_ll_task

---

hw/bsp/telee02/src/hal_bsp.c

The internal one is of no use.  We always want to use the external.

Enable the external antenna for the SX1276 on the EE-02 board.

---

sys/shell/pkg.yml

These packages are used only by newtmgr part of shell code.

sys/shell: add condition to newtmgr dependencies

---

libc/baselibc/src/tinyprintf.c

**libc/baselibc: fix decoding 64-bit values in printf**
It was probably done this way to support 16-bit systems which we
don't support. Although the 32-bit numbers were read in wrong order.
The first 32 bits should be shifted left. The fix could also look
like this:
val = ((unsigned long long)va_arg(*va, unsigned long)) << 32;
val |= ((unsigned long long)va_arg(*va, unsigned long));
**libc/baselibc: ignore 'z' char in printf**
We can ignore size_t ('z') format specifier, because we support only
32-bit systems. It will also make it easier to port external libraries
which support 64-bit systems.

Printf fixes

---

hw/bsp/ada_feather_nrf52/syscfg.yml
hw/bsp/ble400/syscfg.yml
hw/bsp/bmd200/syscfg.yml
hw/bsp/nina-b1/syscfg.yml
hw/bsp/nrf51dk-16kbram/syscfg.yml
hw/bsp/nrf51dk/syscfg.yml
hw/bsp/nrf52-thingy/syscfg.yml
hw/bsp/nrf52840pdk/syscfg.yml
hw/bsp/nrf52dk/syscfg.yml
hw/bsp/rb-blend2/syscfg.yml
hw/bsp/ruuvi_tag_revb2/syscfg.yml
hw/bsp/telee02/syscfg.yml
hw/bsp/vbluno51/syscfg.yml
hw/bsp/vbluno52/syscfg.yml

This has no effect on behavior.  These values are used exclusively in `#if MYNEWT_VAL(~)` contexts.
The inexperienced reader is led to wonder what significance the quotes might have.

Unquote quoted zeros and ones in bsp syscfg files.

---

net/lora/node/src/lora_node.c

Needed to make sure some static functions were not included for
old lorashell and loraping apps.
NOTE: this commit is untested.

net/lora: Get old apps building.

---

kernel/os/src/os_task.c

So they can be modified by the architecture dependent stack init.
As discussed [here](https://github.com/apache/mynewt-core/pull/474#discussion_r131878603)

os_task: Moved the initialisation of t_stacktop and t_stacksize.

---

sys/console/full/src/console.c

The weak symbol will be used if all consoles are disabled effectively
disabling console io, but retaining console code so application still
builds without problems. This makes easy to just disable console in
particular target without need to modify the application.

sys/console: Provide default implementation of console_out()

---

kernel/os/src/arch/sim-armv7/os_arch_stack_frame.s
kernel/sim/src/sim_sched_nosig.c
kernel/sim/src/sim_sched_sig.c

…for tasks was violating ARM call rules.
Task stack init routine departed with $sp pointing to value which was not aligned to 8 byte boundary.

native-armv7; stack initialization 

---

hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/sensor/creator/src/sensor_creator.c

This PR avoids repetitive warnings in the shell when the LSM303DLHC is used.
The default values corresponds to the IC values coming out of reset (+/-1.3 gauss and 15Hz sample rate on the magnetometer).

Set explicit default values for LSM303DLHC mag

---

apps/btshell/src/cmd.c

To prevent 'defined but not used' error

apps/btshell: compile out help message structs

---

hw/bsp/telee02/syscfg.yml

On nRF52, SPI 0 shares resources with I2C 0, so they cannot both be enabled at the same time.
Also add I2C_1 (with analogous restrictions with SPI 1).  Don’t add SPI_1 yet as we had trouble getting it to work.
More ideally, it seems like we ought to be able to use both SPI 0 and I2C 0, not simultaneously but by disabling them at runtime while they are not in use.  This is surely a much larger change.

Do not allow both SPI 0 and I2C 0 to be enabled on the EE-02 board.

---

hw/bsp/telee02/src/hal_bsp.c

This code assumed that pins 26 and 28 would be used for I2C, but this is not dictated by the EE-02 design.  It does not belong in the generic BSP.

Remove I2C0 initialization code from the EE-02 BSP.

---

net/nimble/transport/socket/src/ble_hci_socket.c

This include was causing build errors on a Linux system with the following identity:
```
Linux bleh 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
The build errors were:
```
In file included from repos/apache-mynewt-core/kernel/os/include/os/os.h:77:0,
from repos/apache-mynewt-core/net/nimble/transport/socket/src/ble_hci_socket.c:46:
repos/apache-mynewt-core/kernel/os/include/os/endian.h:43:40: error: expected declaration specifiers or ‘...’ before ‘(’ token
#define os_bswap_32(x)    ((uint32_t) ((((x) & 0xff000000) >> 24) | (((x) & 0x00ff0000) >>  8) | (((x) & 0x0000ff00) <<  8) | (((x) & 0x000000ff) << 24)))
^
In file included from repos/apache-mynewt-core/kernel/os/include/os/os.h:77:0,
from …
```

Remove extraneous #include.

---

repository.yml

Core 1.1.0+ requires newt 1.1.0+ (feature: self-overrides).  This change enforces that requirement through a compatibility rule.

Add compat. rule to require newt 1.1.0+.

---

net/oic/src/api/oc_server_api.c

oic; explicitily fail with assert() if running out of entries in

---

apps/sensors_test/src/main.c
apps/sensors_test/syscfg.yml
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/src/sensor_oic.c
hw/sensor/syscfg.yml

- Add API for setting threshold based on polling mechanism
- Also allow the API to set thresholds based on interrupts mechanism
- Design is as follows: 
i. It adds a list of structures sensor_traits_list to the sensor structure which keeps track of per type thresholds, oic resources, algorithm, etc. These thresholds are then compared with the readings from the sensor at the specific poll rates based on algorithms decided by the developer: `SENSOR_THRESH_ALGO_WINDOW` and `SENSOR_THRESH_ALGO_WATERMARK`. 
`SENSOR_THRESH_ALGO_WINDOW`: Sensor data is compared to thresholds making a window.
`SENSOR_THRESH_ALGO_WATERMARK`: Sensor data is compared to thresholds based on watermarks
Notifications are sent if conditions are satisfied as per the above algorithms.
If a set_thresh callback is specified …

MYNEWT-828 SensorAPI: Sensor OIC notifications/triggers

---

net/nimble/host/include/host/ble_gap.h

This can be considered API change but the symbol name is obviously
invalid as it does not follow naming scheme so let's change it anyway.

nimble/host: Fix invalid symbol name

---

net/nimble/controller/src/ble_ll_adv.c

This comment is no longer valid as with Extended Advertising all
channels are used for advertising.

nimble/controller: Remove misleading TODO

---

hw/drivers/nimble/native/src/ble_phy.c
hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/include/ble/xcvr.h
hw/drivers/nimble/nrf52/src/ble_phy.c
hw/drivers/nimble/nrf52/syscfg.yml
net/nimble/controller/include/controller/ble_phy.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c

This changes T_IFS control from hardware to software. This is required in order to have proper T_IFS on LE Coded PHY since now we're ~16 usecs over the limit which means we can't maintain connection with other devices (except for another Mynewt).
Basically what's need to be done is to schedule TXEN/RXEN using TIMER0 exactly 150 usecs after end of TX/RX which is stored in CC[2]. It's a bit more complicated though as we need to take into account various delays in TX/RX pipeline which are not specified in nRF documentation so they were measured instead - code used to do this is also included as I think it can be useful for debugging purposes later.
The result is the same T_IFS on all phys: 150 +/- 1 usecs.
In addition, code to calculate wfr timer is upgraded to be more precise by including …

[MYNEWT-783] nimble/phy: Fix T_IFS on coded phy

---

repository.yml

When the user's project.yml file specifies a floating version for a repo
(e.g., 0-latest), newt records a fake version in the project.state file
(e.g., 0.0.0).  This is a problem when determining if the version of a
newt is compatible with the current version of the repo, since the
actual version is not known.
This commit is a short-term workaround to prevent the warning from being
displayed.  It allows 0.0.0 of core to work with all versions of newt.
A long term fix is needed: we need to be able to determine the actual
version of the repo present in the user's project.

Prevent newt compatility warning for 0.0.0

---

net/nimble/host/src/ble_gap.c

Not sure why this was not allowed, but it is perfectly ok to do so and
controller will update data while advertising. And even if for some
reason it won't, there will be proper error returned.

nimble/host: Allow setting adv data when advertising

---

apps/blemesh/src/main.c
net/nimble/host/mesh/src/access.c

Fix following error emitted by GCC 7.1:
Error: repos/apache-mynewt-core/apps/blemesh/src/main.c:83:38: error:
duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
static const struct bt_mesh_model_op const gen_onoff_op[] = {
^~~~~
repos/apache-mynewt-core/apps/blemesh/src/main.c:132:38: error:
duplicate 'const' declaration specifier [-Werror=duplicate-decl-specifier]
static const struct bt_mesh_model_op const gen_level_op[] = {
^~~~~

mesh: Fix compilation with GCC 7.1

---

hw/sensor/src/sensor_shell.c

- Fix the sensor shell interval option in command read to use
microseconds directly for settign up the timer instead of converting
it to ticks.

MYNEWT-845 Sensor shell: cputimer for itvl usecs

---

net/nimble/host/mesh/src/net.c

Proxy configuration messages are allowed (in fact required) to use
unassigned addresses, so they should be exempt from this check.
Ported from Zephyr

mesh: Fix dropping valid proxy configuration messages

---

crypto/tinycrypt/include/tinycrypt/ecc_platform_specific.h
net/nimble/host/mesh/src/mesh.c
net/nimble/host/src/ble_sm_alg.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/src/ble_sm_sc.c

TinyCrypt requires rand function to be implemented by user. Instead of
hardcoding it, user is required to provide own implementation by
uECC_set_rng. This allows to provide different implementations
depending on supported features (eg BLE controller).

nimble: Don't hardcode TinyCrypt rand function

---

net/nimble/host/include/host/ble_hs_test.h
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_hs_misc.c
net/nimble/host/src/ble_hs_priv.h
net/nimble/host/src/ble_hs_pvcy.c
net/nimble/host/src/ble_hs_pvcy_priv.h
net/nimble/host/src/ble_store.c
net/nimble/host/test/src/ble_hs_pvcy_test.c
net/nimble/host/test/src/ble_hs_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h

(Jira ticket: https://issues.apache.org/jira/browse/MYNEWT-841)
Identity information gets persisted during pairing, but it is never restored after a reboot.
At startup and on stack reset, the host populates the resolving list with the persisted entries.

BLE Host - Populate resolving list with persisted IRKs at startup

---

apps/bleprph/src/bleprph.h
apps/bleprph/src/main.c
apps/bleprph/src/phy.c
apps/bleprph/syscfg.yml

PHY support can be enabled using BLEPRPH_LE_PHY_SUPPORT syscfg val.
Once enabled, we have 4 buttons and 3 LEDs to work with:
- buttons 1-4 change phy preference to 1M, 2M, Coded S=2 or Coded S=8
respectively,
- LEDs 1-3 display current phy on active connection as 1M, 2M or Coded
respectively.
For now we just assume symmetric phy on link.
This works ootb on nRF52840 PDK, for other BSPs GPIO pins may need
to be adjusted using syscfg vals.

apps/bleprph: Add simple support for non-1M LE PHYs

---

net/nimble/controller/src/ble_ll_conn.c

Initial value for number of consecutive bits should be 1, i.e. single
bit is "1 consecutive bit".
With this set to 0 we calculate number of consecutive bits 1 less than
we should and thus allow for 7 consecutive bits in AA which is invalid.
Also, in case 7 msb have the same value, we would detect this at the
last iteration of loop which means mask value is already set to final
value so invalid sequence won't be detected. To make this simple, let's
just set mask value to 0 in case consecutive bits violation is detected
so it is always properly detected as invalid sequence.

nimble/ll: Fix consecutive bits detection in AA

---

hw/bsp/pic32mz2048_wi-fire/syscfg.yml
hw/mcu/microchip/pic32mx470f512h/src/hal_spi.c
hw/mcu/microchip/pic32mz2048efg100/src/hal_spi.c

I found out that hal_spi was not setting the correct SPI mode since I used the sampling edge to deduce the values of CKP/CKE instead of the toggling edge. 
I also fixed the build for the wifire board: some defines concerning SPI_MASTER were left in the bsp.

clicker/wifire: Fix SPI mode

---

net/nimble/host/test/src/ble_att_svr_test.c
net/nimble/host/test/src/ble_gap_test.c
net/nimble/host/test/src/ble_gatt_conn_test.c
net/nimble/host/test/src/ble_gatt_disc_s_test.c
net/nimble/host/test/src/ble_hs_adv_test.c
net/nimble/host/test/src/ble_hs_conn_test.c
net/nimble/host/test/src/ble_hs_hci_test.c
net/nimble/host/test/src/ble_hs_pvcy_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h
net/nimble/host/test/src/ble_hs_test_util_hci.c
net/nimble/host/test/src/ble_hs_test_util_hci.h
net/nimble/host/test/src/ble_l2cap_test.c
net/nimble/host/test/src/ble_os_test.c
net/nimble/host/test/src/ble_sm_test_util.c

The BLE host test code was getting out of hand, and this is a small step towards making it manageable again.  This commit moves all the HCI-related test utility functions into a new file:
`net/nimble/host/test/src/ble_hs_test_util_hci.c`.  Furthermore, all the functions in this file have been renamed to use the common prefix `ble_hs_test_util_hci_`.

BLE Host - Move HCI test util code into a new file

---

net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_hs.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_hs_pvcy.c
net/nimble/host/src/ble_store.c
net/nimble/host/test/src/ble_hs_pvcy_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util.h
net/nimble/host/test/src/ble_hs_test_util_hci.c

If an attempt to add a peer's IRK to the resolving list fails, the failure is not reported, and the operation is not reattempted. Adding to the resolving list fails if the host is scanning or advertising at the time, so this is a common occurrence.
This commit address this problem as follows.  Before attempting to add an entry to the resolving list, the host stops all active GAP procedures.  After the entry has been successfully added, the application must restart interrupted procedures as needed.
Interrupted procedures are reported with a reason or status code of `BLE_HS_EPREEMPTED`.  Furthermore, an attempt to initiate a new GAP procedure during preemption fails with a return code of `BLE_HS_EPREEMPTED`.
There is one additional requirement which complicates this feature: interrupted …

MYNEWT-842  BLE Host - Handle failure to add entry to resolving list

---

net/nimble/host/src/ble_hs_startup.c

repos/apache-mynewt-core/net/nimble/host/src/ble_hs_startup.c:125:8:
error: 'pktlen' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
rc = ble_hs_hci_set_buf_sz(pktlen, max_pkts);
^
repos/apache-mynewt-core/net/nimble/host/src/ble_hs_startup.c:106:14:
note: 'pktlen' was declared here
uint16_t pktlen;
^
repos/apache-mynewt-core/net/nimble/host/src/ble_hs_startup.c:125:8:
error: 'max_pkts' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
rc = ble_hs_hci_set_buf_sz(pktlen, max_pkts);
^
repos/apache-mynewt-core/net/nimble/host/src/ble_hs_startup.c:105:14:
note: 'max_pkts' was declared here
uint16_t max_pkts;
^
repos/apache-mynewt-core/net/nimble/host/src/ble_hs_startup.c:117:18:
error: 'le_max_pkts' may be used uninitialized in this function …

nimble/host: Fix build issue

---

hw/hal/src/hal_flash.c

bsp.h is unused here and causes a circular dependency when hw/bsp/* depends on this.

Remove inclusion of bsp.h

---

net/nimble/host/mesh/src/cfg.c

The feature bits for Proxy and Friend were missing in the composition
data and heart beat messages.
Ported from Zephyr PR #4345

mesh: Fix missing feature bits

---

net/nimble/host/mesh/src/cfg.c

Both count and period must be non-zero for message publication
Stop publication when count becomes zero
Add count to debug message in hb_publish
Ported from Zephyr PR #4354

mesh: Heartbeat fixes for message count

---

apps/bleprph_oic/src/main.c

This conforms the sample light resource in the bleprph_oic
sample app to the binary switch resource type as defined
in the OCF Resource Type Spec:
https://openconnectivity.org/draftspecs/OCF_Resource_Type_Specification_v1.0.0.pdf

Conform the sample light resource to binary switch

---

encoding/cborattr/src/cborattr.c
net/oic/src/port/mynewt/lora_adaptor.c

Change fragmentation header. Reduce mbuf use on TX. cborattr_read_object() was not returning when it was asked to decode an incomplete object.

Coap over Lora changes

---

apps/bleprph_oic/src/main.c

Last change updated the interface from OIC_IF_RW to OC_IF_A in resource definition. I forgot to make this change in the handler function's switch statement. My bad.

change OC_IF_RW to OC_IF_A in handler

---

net/oic/src/port/mynewt/ble_adaptor.c

Error: repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:
In function 'oc_send_buffer_gatt':
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:380:14:
error: unused variable 'attr_handle' [-Werror=unused-variable]
uint16_t attr_handle;
^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:379:14:
error: variable 'conn_handle' set but not used
[-Werror=unused-but-set-variable]
uint16_t conn_handle;
^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:378:14:
error: unused variable 'mtu' [-Werror=unused-variable]
uint16_t mtu;
^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c:377:28:
error: unused variable 'pkt' [-Werror=unused-variable]
struct os_mbuf_pkthdr *pkt;
^
repos/apache-mynewt-core/net/oic/src/port/mynewt/ble_adaptor.c …

oic/ble_adapter: Fix build errors build for oc_client configuration

---

net/nimble/transport/socket/src/ble_hci_socket.c

For large incoming ACL packets, the "current offset" field was rolling over, making it look like the packet was being dropped.  The fix is to change the offset member from `uint8_t` to `uint16_t`.

BLE socket transport - don't drop large frames.

---

net/lora/node/include/node/mac/LoRaMac.h
net/lora/node/src/lora_app.c
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

The code was not fully modified to deal with mbufs. The previous
code assumes flat buffers and while some of the changes were
made to support mbufs, the code still assumed that all data
was contiguous in one mbuf and that mbufs were not chained.
This new code should now copy data from the mbuf into the
global lora mac buffer.

net/lora: Fix assumption of flat buffers

---

net/nimble/host/mesh/src/net.c

This patch fixes issue when receiving iv index greater than current
index + 42 in update mode. According to Specification when node is in update
state it should only accept iv index equal to the current iv index. When
node is in normal mode it should ignore index that is greater than current
index + 42.
This allows to pass MESH/NODE/IVU/BI-02-C.
Also this patch cleans up the iv update procedure, to make it easier to
read.

mesh: Fix and clean up iv update procedure

---

net/lora/node/include/node/mac/LoRaMac.h
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

There are two basic issues fixed with this commit: 1) If the
server sends MAC commands "constantly" the code would not
send any data until the MAC commands stopped being sent. Now, if
we cannot send any MAC commands because the application data is
too large, we will send a MAC commands, at most, every other
frame. 2) The code will now attempt to add as many MAC commands
as it can to each transmission. Prior code would either attempt
to add the entire MAC command buffer or do nothing.

net/lora: Fix MAC command issues

---

apps/sensors_test/src/main.c
hw/drivers/sensors/bmp280/src/bmp280.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/syscfg.yml
kernel/os/include/os/os_time.h

- Support per type polling
- Fix os_time macros by using typedef for signed os_time_t
- Fix stack overflow with bmp280 driver
- Clean and reorganize some parts of the code
- Fix poll rate for multiple sensors
- Adding a poller ram test log which is conditional based on SENSOR_POLL_TEST_LOG
Configuration example:
struct sensor_type_traits stt_ms_temp;
struct sensor_type_traits stt_ms_press;
struct sensor_type_traits stt_bmp_temp;
struct sensor_type_traits stt_bmp_press;
/* Poll rates for MS5837 */
sensor_set_poll_rate_ms("ms5837_0", 60);
stt_ms_temp = (struct sensor_type_traits) {
.stt_sensor_type = SENSOR_TYPE_AMBIENT_TEMPERATURE,
.stt_poll_n      = 2
};
sensor_set_n_poll_rate("ms5837_0", &stt_ms_temp);
stt_ms_press = (struct sensor_type_traits) {
.stt_sensor_type = SENSOR_TYPE_PRESSURE, …

MYNEWT-861: Sensor per type polling

---

apps/bletiny/src/main.c
apps/btshell/src/main.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/src/ble_gap.c
net/nimble/host/test/src/ble_gap_test.c

Cancelled connect procedures are reported as:
* event.type: `BLE_GAP_EVENT_CONNECT`
* event.connect.status: `BLE_HS_EAPP`
Discussion regarding this change can be found here:
https://lists.apache.org/thread.html/6575cbf8faef793381845aaa99bea7c4c053926af43928c82f62e236@%3Cdev.mynewt.apache.org%3E

BLE Host - Remove BLE_GAP_EVENT_CONN_CANCEL

---

apps/blecent/src/main.c
apps/bleprph/src/main.c
apps/bleprph_oic/src/main.c
apps/blesplit/src/main.c
apps/bletiny/src/main.c
apps/bleuart/src/main.c
apps/btshell/src/main.c
apps/ocf_sample/src/ocf_ble.c
apps/sensors_test/src/main.c
apps/testbench/src/tbb.c
net/nimble/host/src/ble_hs.c

On startup, the host executes the following steps:
1. HCI startup sequence
2. Call sync callback
3. Restore IRKs from flash
The problem is that step 3 (IRK restoration) causes a GAP preemption if
there are any persisted IRKs.  If the application initiates a GAP
procedure during the sync callback, it will be immediately preempted.
This happens in the bleprph app, for example.
Don't call the sync callback until after IRK restoration is complete.

BLE Host - Delay sync callback after IRK restore

---

net/nimble/host/mesh/src/mesh.c
net/nimble/host/mesh/src/prov.c
net/nimble/host/mesh/src/prov.h

Fail on Mesh initialization if provisioning is enabled and keys were
not generated. This make it simpler to debug misconfigured devices.
Ported from Zephyr PR #4691

mesh: Fail init on keys generation error

---

net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_sched.c

This commit should fix the issue where the HFXO was not being
turned off when advertising is stopped. The code needed to turn
off the HFXO even if the LL state was in standby. Furthermore,
it needed to make sure the rfclk timer was stopped, otherwise
it might fire off and turn back on the HFXO.

net/nimble: MYNEWT-862 HFXO not always turning off

---

net/lora/node/include/node/lora_priv.h
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

The changes to the code fix the problem with sending an app
link check. There was also a bug with the code that would
form a packet when only mac commands (a port 0 packet) were
contained in the message.

net/lora: Fix link check command failing

---

kernel/os/include/os/os_sem.h
kernel/os/src/os_mbuf.c
net/nimble/host/services/ias/src/ble_svc_ias.c
net/nimble/host/src/ble_att.c
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_monitor.c

Main addition is new os_sem_get_count() API - it is then used in nimble where applicable.
+ some random fixes inside nimble and os code.

Add new semaphore API + some nimble/os fixes

---

net/nimble/host/mesh/src/net.c
net/nimble/host/mesh/src/net.h

The implementation of the Network Message Cache has so far been
suboptimal, since it has treated the same packet with different TTL
values as different packets. Since one of the purposes of this cache
is to prevent unnecessary relaying, it's important that we don't let
the TTL value influence the "hash" that's used for matching messages.
This patch changes the hash to consist of most of the IV Index (three
least significant bytes of it), the sequence number and the source
address, which should give fairly optimal matching behavior.
Ported from: https://github.com/zephyrproject-rtos/zephyr/pull/4514/

mesh: Improve Network Message Cache behavior

---

mgmt/imgmgr/include/imgmgr/imgmgr.h
mgmt/imgmgr/src/imgmgr.c

find target slot to operate in. Separate that into a function.

imgmgr; imgmr_erase() and imgr_upload() had shared code regarding

---

mgmt/imgmgr/src/imgmgr.c

the optional ver parameter was passed in.

imgmgr; imgmgr_read_info() was not checking image header magic unless

---

hw/mcu/ambiq/apollo2/src/hal_os_tick.c
hw/mcu/ambiq/apollo2/src/hal_timer.c

The code assumes that when it does not reschedule the OS tick timer (STIMER), it will expire on the next OS tick.  This assumption failed on the first tick after startup, as the ISR hadn't run yet.  Consequently, the idle task would never terminate if a scheduling event occurred on the first tick.
The fix is to set the STIMER to expire on the next OS tick at init time.
I also snuck in a few minor fixes (second and third commits).

apollo2 - Ensure OS tick timer is running.

---

apps/bletiny/src/cmd.c
apps/btshell/src/btshell.h
apps/btshell/src/cmd.c
apps/btshell/src/main.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/include/host/ble_hs_adv.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_hs_adv.c
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/host/src/ble_hs_hci_util.c
net/nimble/host/test/src/ble_gap_test.c
net/nimble/host/test/src/ble_hs_conn_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_hs_test_util_hci.c
net/nimble/host/test/src/ble_os_test.c
net/nimble/include/nimble/hci_common.h

This adds host GAP support for all features provided by Extended Advertising:
- multiple advertising instances
- advertising TX power configuration
- alternate PHYs configuration
- large advertising data
Applications are now able to control multiple advertising instances and configure them separately.
btshell application is also extended with support for all new functionalities.

Extended Advertising API

---

apps/btshell/src/cmd.c

Add missing #if directive to fix use of undeclared variable.

apps/btshell: Fix compilation with BLE_EXT_ADV disabled

---

hw/bsp/nucleo-f401re/include/bsp/stm32f4xx_hal_conf.h

Required for the compilation of /hw/mcu/stm/stm32f4xx/src/hal_timer.c

STM32F4 HAL: Enable timer module

---

net/nimble/host/mesh/src/health_cli.c

repos/apache-mynewt-core/net/nimble/host/mesh/src/health_cli.c:49:16:
error: dereferencing pointer to incomplete type 'struct
bt_mesh_health_cli'
if (health_cli->op_pending != OP_HEALTH_FAULT_STATUS) {

mesh: Fix build issue

---

kernel/os/src/os_mempool.c

This is regression from abd8c4598b as it was changing API incorretly.
Documentation says that 'block_size' parameter in os_mempool_init() is
"Minimum size of an individual element in pool"
It does not required from the user to take into account of 'block_size'
an internal overhead which is sizeof(struct os_memblock).
The only requirement on user is to make sure that provided 'membuf' has
enough bytes which can be calculated using OS_MEMPOOL_BYTES() macro.
Without this patch we have assert when creating mempool with block_size=4

kernel/os_mempool: Fix for incorrect check on os_mempool_init

---

kernel/os/src/os_sched.c

kernel/os: fix errors in os_sched.c related to TAILQ_INSERT_TAIL
The code needs to check if the list is empty before calling TAILQ_INSERT_TAIL as that macro does not set the first element in the list if the list is empty.

MYNEWT-879: OS scheduler issues with TAILQ_INSERT_TAIL

---

net/nimble/host/src/ble_hs.c

Prior to this change: the host asserted that IRK restoration succeeds at sync time.
After change: If IRK restoration at startup fails because there is no store package present, don't crash.

BLE Host - Don't crash if no store package.

---

net/nimble/controller/src/ble_ll_conn.c

This patch removes initial feature xchg from controller when connected
as a slave due to observed problems with recent iPhones (8 and X).

nimble/ll: Do not initiate features xchg as a slave

---

apps/lora_app_shell/src/main.c
net/lora/node/src/mac/LoRaMac.c

Got tired of seeing an index instead of actual transmit power in dbm.

net/lora: display transmit power in dbm

---

net/lora/node/include/node/lora.h
net/lora/node/include/node/lora_priv.h
net/lora/node/include/node/mac/LoRaMac.h
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

These changes were made to remove the MCPS and MLME request/confirm
primitives from the code. They have not been entirely removed but
there was duplication between these and the use of mbufs. Wanted
to move the code to use mbufs instead of the prior stack.
No functionality change should have occurred with this change with
the exception being that a link check callback will now occur
whenever a link check response is received by an end device even
if a link check request was not sent. This should not occur, but
the old code prevented the callback from occurring.

net/lora: Remove MLME and MAC primitives from code

---

hw/bsp/telee02/syscfg.yml
hw/drivers/lora/sx1276/src/sx1276-board.c
hw/drivers/lora/sx1276/src/sx1276-board.h
hw/drivers/lora/sx1276/src/sx1276.c
hw/drivers/lora/sx1276/syscfg.yml

Not all boards will have an antenna switch. Add a mynewt variable
(defined in hw/drivers/lora/sx1276) called SX1276_HAS_ANT_SW to
distinguish boards with/without antenna switches. Note that the value should be set in the bsp (default is 0).

net/lora  Add config variable for antenna switch

---

apps/btshell/src/cmd.c

Won't compile without COC due to unused symbol (gatt_show_coc_help).

apps/btshell: Fix l2cap-show-coc command

---

net/nimble/controller/src/ble_ll_hci.c

When host sets random address when advertising extensions are enabled,
we need to make sure that same address is used for instance 0 which is
legacy advertising instance

nimble/controller: Make sure random address is set correctly

---

docs/os/core_os/API.rst
docs/os/core_os/context_switch/context_switch.rst
docs/os/core_os/mynewt_os.rst
docs/os/os_user_guide.rst
kernel/os/include/os/os_sched.h
kernel/os/src/os_sched.c
kernel/os/src/os_sem.c

Update os_sched() inline doxygen docs to match what is displayed at:
https://mynewt.apache.org/latest/os/core_os/context_switch/os_sched/
@sterlinghughes let me know it you want to go down this route. It will require a lot of updates to source to get their comments to match the current docs.
also @aditihilbert

match os_sched() doxygen with mynewt-site

---

kernel/os/include/os/os_mempool.h
kernel/os/src/os_mempool.c
kernel/os/test/src/mempool_test.c
kernel/os/test/src/mempool_test.h
kernel/os/test/src/testcases/os_mempool_test_ext_basic.c
kernel/os/test/src/testcases/os_mempool_test_ext_nested.c
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_hs.c
net/nimble/host/src/ble_hs_conn_priv.h
net/nimble/host/src/ble_hs_flow.c
net/nimble/host/src/ble_hs_flow_priv.h
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/host/src/ble_hs_priv.h
net/nimble/host/src/ble_hs_startup.c
net/nimble/host/syscfg.yml
net/nimble/include/nimble/ble.h
net/nimble/include/nimble/ble_hci_trans.h
net/nimble/include/nimble/hci_common.h
net/nimble/transport/emspi/src/ble_hci_emspi.c
net/nimble/transport/emspi/syscfg.yml
net/nimble/transport/ram/src/ble_hci_ram.c
net/nimble/transport/uart/src/ble_hci_uart.c
util/mem/include/mem/mem.h
util/mem/src/mem.c

(Jira ticket: https://issues.apache.org/jira/browse/MYNEWT-287)
Controller to host flow control (hereon called "flow control") stops the controller from sending more ACL data packets than the host can accommodate.  Briefly, this feature is implemented as follows:
* On startup, host tells controller:
* That flow control is being used.
* About its ACL data buffer supply:
* Total number of buffers.
* Size of each buffer.
* After startup, host sends updates to controller containing: The number of ACL data buffers it has freed since the last update, and which connection handle each buffer was associated with.
* Host provides updates periodically (default: once per second).
* Host sends an immediate update if the number of buffers freed since the last update exceeds a threshold (default: …

BLE Host flow control

---

net/oic/src/port/mynewt/ble_adaptor.c

because here the header size is < 6 bytes. We erroneously are checking return code from os_mbuf_copydata() and asking it to copy less bytes than there are in the packet.

net/oic BLE; was not able to receive small requests.

---

net/nimble/host/src/ble_hs_hci_cmd.c

This limiation was removed in BT5 spec so there is no need to keep this
when build with nimBLE controller. Since nimBLE host doesn't verify
controller version for now we allow this on combined build only.

nimble/host: Allow low interval on non-connectable advertising

---

hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_ll_sched.h
net/nimble/controller/include/controller/ble_phy.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_dtm.c
net/nimble/controller/src/ble_ll_dtm_priv.h
net/nimble/controller/src/ble_ll_hci.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/controller/src/ble_ll_supp_cmd.c
net/nimble/controller/syscfg.yml
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/include/nimble/hci_common.h
net/nimble/src/hci_common.c

With this patch, by setting BLE_LL_DIRECT_TEST_MODE flag it is possible
to use HCI transceiver and receiver commands as specified in Bluetooth 5
specification.

nimble/ble_ll: Add support for HCI Test commands

---

hw/drivers/sensors/lis2dh12/src/lis2dh12.c

Recent PR broke the the callbacks. Fixing it by making it specific.

LIS2DH12: fix build issues after merging recent PR

---

net/nimble/host/mesh/src/cfg_srv.c

The timer should be reset before sending to ensure correct publication period.
This patch allows to pass MESH/NODE/CFG/HBP/BV-02-C.

mesh: Reset Heartbeat Publication timer before sending message

---

net/nimble/controller/src/ble_ll_dtm.c

Error: repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_dtm.c:
In function 'ble_ll_dtm_tx_sched_cb':
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_dtm.c:187:5:
error: implicit declaration of function 'ble_phy_mode_set'; did you mean
'ble_phy_reset'? [-Werror=implicit-function-declaration]
ble_phy_mode_set(ctx->phy_mode, ctx->phy_mode);
^~~~~~~~~~~~~~~~
ble_phy_reset
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_dtm.c: In
function 'ble_ll_dtm_ctx_free':
repos/apache-mynewt-core/net/nimble/controller/src/ble_ll_dtm.c:346:5:
error: implicit declaration of function 'ble_ll_xcvr_rfclk_stop'; did
you mean 'ble_ll_sched_stop'? [-Werror=implicit-function-declaration]
ble_ll_xcvr_rfclk_stop();
^~~~~~~~~~~~~~~~~~~~~~
ble_ll_sched_stop
cc1: all warnings being treated …

nimble/ll: Fix DTM build without 2M/Coded PHY enabled

---

hw/drivers/nimble/native/src/ble_phy.c
hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_phy.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c

This makes some optimizations in the way controller uses memory/mbufs:
* use mbufs for storing adv data so we don't need to allocate a lots of memory for adv data if we're not going to use it
* make ble_phy_tx create PDUs on-the-fly so there is no need to create temporary mbufs and copy data over and over again
It will be especially useful for advertising data chaining, but it speeds things up even for legacy code.

nimble: mbuf optimization in controller

---

net/nimble/controller/src/ble_ll_dtm.c

From Core Specification:
"This command is used to stop any test which is in progress. The
Number_Of_Packets for a transmitter test shall be reported as 0x0000.
The Number_Of_Packets is an unsigned number and contains the number of
received packets."

nimble/controller: Fix LE Test End Command return value

---

net/nimble/controller/src/ble_ll_conn_hci.c

Commit 04bf9592 removed automatic feature exchange procedure after
connection when in slave role. This breaks HCI LE Read Remote Features
command since it expected that this procedure is always started so it
did not even try to start it, just sets bit in state machine that reply
is pending.
This patch fixes this regression by starting features exchange procedure
if not already done.

nimble/ll: Fix HCI LE Read Remote Features command

---

apps/boot/pkg.yml

apps/boot specified the .OVERWRITE flag when `BOOT_SERIAL` was set.  This flag should not be here, as the serial boot loader requires all the normal dependencies (boot/bootutil, kernel/os, and sys/console/stub).  These are required to satisfy other dependencies' API requirements.

apps/boot - Remove .OVERWRITE flag

---

net/nimble/host/src/ble_hs_startup.c

Host didn't enabled that event in controller but is expecting this
when re-encrypting connection with new LTK.
This was affecting TP/SEC/AUT/BV-13-C qualification test.

nimble: Enable missing Encryption Key Refresh Complete Event

---

apps/blemesh/src/main.c

To avoid issues with implementation which does not support testing
company id 0xffff, lets use valid one.

nimble/blemesh: Use valid company id

---

hw/drivers/debounce/include/debounce/debounce.h
hw/drivers/debounce/pkg.yml
hw/drivers/debounce/src/debounce.c
hw/drivers/debounce/syscfg.yml

Added hw/drivers/debounce for debouncing an input pin, relies on hal_gpio(_irq) and hal_timer.
See debounce.h for the API description and example use.

Driver for debouncing an input pin.

---

net/nimble/controller/src/ble_ll_dtm.c
net/nimble/controller/src/ble_ll_sched.c

With this patch DTM works properly when XTAL is not ON all the time.

nimble/ll_dtm: Couple of fixes for DTM code

---

apps/bletiny/src/main.c
apps/btshell/src/main.c

Symbols for data status in extended advertising reports were changed in
a1000b8d6 so we need to adjust them in apps... or they won't build ;)

apps: Fix symbol names for ext advertising data

---

net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_ll_sched.h
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_sched.c

This adds support for advertising data fragmentation. It does not need any special configuration - as soon as adv data are too big to fit in single AUX_ADV_IND, controller will fragment them and send in subsequent ADV_CHAIN_IND. Also host preference for fragmentation is ignored for now, we just fragment data so they are sent as fast as possible.
The main problem here is scheduling: original code for handling secondary adv channel can schedule only single aux PDU, but we need to have subsequent PDU already scheduled before txing current one in order to calculate AuxPtr. We could try to schedule aux on the fly but it means scheduling is done in interrupt context which is probably not the best idea.
The solution is to schedule 2 aux PDUs at the same time: current and next one. This way …

nimble/ll: Add support for advertising and scan response data fragmentation

---

net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/host/src/ble_hs_pvcy.c

Few fixes for privacy.
Apparently, in some cases we need to use our identity address even when using privacy. This happens if other device is not on our resolving list so we do not have entry with local IRK to generate RPA.
- for non-directed advertising host specifies peer address as 00:00:00:00:00:00 and assuming there is corresponding entry in resolving list we use this local IRK to generate RPA for AdvA (already works like this, had to fix RPA refreshing though)
- for scanning a device which is not in our resolving list we do not have local IRK to generate RPA for ScanA, but we are allowed to use NRPA so we can safely scan anything in the vicinity (fixed here)
- for initiating with a device which is not in our resolving list we do not have local IRK to generate RPA for InitA and we …

nimble: Fixes for privacy

---

sys/config/src/config_cli.c
sys/config/syscfg.yml

It prints out all persisted data entries, and therefore can expose confidential data which otherwise would not be visible.

sys/config; add a separate syscfg for cli command 'config dump saved'.

---

hw/drivers/adc/src/adc.c

I noticed this while working on the nrfx drivers. This check was actually off by one I beleive

adc driver impl: correct incoming arg check

---

apps/pwm_test/src/main.c
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c

This PR adds blinking to pwm_test and fixes https://github.com/apache/mynewt-core/issues/820

Adding blinking to pwm_test, fixing os_dev_close 

---

hw/drivers/uart/uart_hal/src/uart_hal.c
hw/mcu/nordic/nrf52xxx/src/hal_uart.c

The original commit and PR was not correct. It worked if only either
uart0 or uart1 was enabled; if both were enabled it failed. This
should address both uarts being enabled.

hal/uart: Fix nrf52840 (and nrf52) uart1 addition.

---

net/nimble/controller/src/ble_ll_sched.c

The code which calculates earliest connection event start does not take
BLE_LL_CONN_INIT_MIN_WIN_OFFSET into account, but we still update tx
windows offset in state machine with its value. As a result when this
setting is set to non-zero value we schedule first connection event
earlier than what slave calculates from CONNECT_IND PDU so connection
cannot be established.

nimble/ll: Fix BLE_LL_CONN_INIT_MIN_WIN_OFFSET

---

hw/mcu/nordic/include/nrfx_glue.h

This PR fixes the Global Symbol Conflict on sr_from_macro

fixing sr_from_macro global symbol conflict

---

apps/blecent/src/peer.c
apps/bletiny/src/bletiny.h
apps/bletiny/src/main.c
apps/bletiny/src/misc.c
apps/bsncent/src/peer.c
apps/btshell/src/btshell.h
apps/btshell/src/main.c
apps/btshell/src/misc.c

This fixes an issue with GATT discovery in few sample apps which
results in an infinite loop with characteristics discovery if peer's
database has service with no characteristics due to invalid check for
empty service.
The same fix is applied to bletiny and btshell which do not have this
issue anymore, but the original fix just hidden the issue instead of
fixing the root cause.

apps/ble: Fix GATT discovery in some apps

---

apps/sensors_test/src/main.c
hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c

- There are two issues for calling lis2dh12_sensor_set_trigger_thresh() multiple times:
1. gpio irq was not being released before doing a re-initialization
2. srec was malloced and calling the function multiple times would have
malloced additional memory without freeing it.
Solution:
1. Release the gpio irq
2. Remove the malloc and add a ptr for the sensor in each type trait so
that a sensor read could be performed in the irq handler.
- Add sensor_clear_low_thresh() and sensor_clear_high_thresh() APIs

MYNEWT-881: SensorAPI: Add sensor_clear_high/low_thresh() API and LIS2DH12 set threshold cb fix

---

net/nimble/host/services/gap/include/services/gap/ble_svc_gap.h

- This was causing a build failure

nimble: Adding missing inttypes.h include

---

hw/sensor/src/sensor_oic.c
net/oic/include/oic/oc_api.h
net/oic/include/oic/oc_client_state.h
net/oic/include/oic/oc_core_res.h
net/oic/include/oic/oc_ri.h
net/oic/include/oic/oc_ri_const.h
net/oic/include/oic/port/mynewt/transport.h
net/oic/src/api/oc_ri.c

- Because of the enum forward declaration, oc_resource_t
arrangement was different for oc_ri.c and oc_core_res.c
source files.
- This fixes #834

oic: fixing `oc_resource_t` structure arrangement

---

hw/sensor/include/sensor/sensor.h

- This is required for bma253 sensor driver
- It was removed as part of the fix for lis2dh12 setting thresholds multiple times. For bma253 it still gets used, so probably it's best to keep it around for read evts.

SensorAPI: Re-adding sensor_read_evt_ctx

---

hw/drivers/uart/uart_hal/src/uart_hal.c

The current implementation allocates a structure with a single integer to store the ID of the uart. This PR uses the memory space of the opaque pointer to store said integer value directly and thus removes the dependency on dynamic memory allocation.
The stored ID is artificially incremented by 1 in order to distinguish between a not initialized device ID and uart "0".
Application size of a simple app using the console with the original implementation:
```
Size of Application Image: app
FLASH   CCRAM    SRAM 
63       0     410 *fill*
841       0     649 apps_rfcomm.a
874       0     112 hw_bsp_nucleo-f303k8.a
72       0       0 hw_cmsis-core.a
260       0       0 hw_drivers_uart_uart_hal.a
148       0       0 hw_hal.a
4662       0     200 hw_mcu_stm_stm32f3xx.a
4880       0    8229 …
```

Remove dynamic memory allocation from hal_uart.

---

hw/mcu/stm/stm32f1xx/include/mcu/mcu.h
hw/mcu/stm/stm32l1xx/include/mcu/mcu.h
kernel/os/src/arch/cortex_m3/os_arch_arm.c

@mkiiskila As previously suggested SVC IRQ number moved to macro in `mcu/mcu.h`.

Replace hardcoded SVC IRQ number with #define

---

sys/console/minimal/src/console.c

This enables building console/minimal when CONSOLE_UART and CONSOLE_RTT are both disabled, and allows console to be effectively "disabled" when no uart/rtt was built but console/minimal was added as dependency.
This mimics a change that was already applied on console/full.

Fix build when no console device is selected

---

hw/bsp/stm32f3discovery/boot-stm32f3discovery.ld
hw/bsp/stm32f3discovery/bsp.yml
hw/bsp/stm32f3discovery/include/bsp/bsp.h
hw/bsp/stm32f3discovery/include/bsp/bsp_sysid.h
hw/bsp/stm32f3discovery/include/bsp/cmsis_nvic.h
hw/bsp/stm32f3discovery/include/bsp/stm32f3xx_hal_conf.h
hw/bsp/stm32f3discovery/pkg.yml
hw/bsp/stm32f3discovery/src/arch/cortex_m4/startup_stm32f303xc.s
hw/bsp/stm32f3discovery/src/hal_bsp.c
hw/bsp/stm32f3discovery/src/sbrk.c
hw/bsp/stm32f3discovery/src/system_stm32f3xx.c
hw/bsp/stm32f3discovery/stm32f3discovery.ld
hw/bsp/stm32f3discovery/stm32f3discovery_debug.cmd
hw/bsp/stm32f3discovery/stm32f3discovery_debug.sh
hw/bsp/stm32f3discovery/stm32f3discovery_download.cmd
hw/bsp/stm32f3discovery/stm32f3discovery_download.sh
hw/bsp/stm32f3discovery/syscfg.yml

Add support for: http://www.st.com/en/evaluation-tools/stm32f3discovery.html
Deprecates https://github.com/runtimeco/mynewt_stm32f3/

Add support for the stm32f3-discovery board

---

hw/mcu/nordic/nrf52xxx/include/mcu/nrf52_hal.h
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_spi.c

The incorrect port was being accessed if any SPI pin was using
a pin number greater than 31 (on port 1). This issues should be
fixed with this commit.

hw/mcu/nordic/nrf52xxx: HAL spi broken for 52840.

---

hw/drivers/sensors/ms5837/src/ms5837.c

- Fixing build failure due to over the bounds write of the array in logs

ms5837: build failure due to over the bounds access

---

hw/bsp/puckjs/src/hal_bsp.c
hw/bsp/puckjs/syscfg.yml

These were missed in the puckjs bsp

puckjs: i2c syscfg

---

hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/drivers/lora/sx1272/src/sx1272-board.c
hw/drivers/lora/sx1272/src/sx1272-board.h
hw/drivers/lora/sx1272/src/sx1272.c
hw/drivers/lora/sx1272/syscfg.yml

The main changes in this commit were to make all GPIO that interface
the chip to the MCU MYNEWT_VALs so they can be configured either
in a target or bsp. This makes creating a bsp + shield combo
simple by defining the interface GPIO in a target.
Some additional fixes/changes are in this commit such as:
1) Using the proper reset sequence.
2) Fixing a bug with the spi/read write command.
3) Adding a MYNEWT_VAL to select a separate spi routine to be
used to read/write buffers to the chip. The blocking,
byte-by-byte hal spi api is not working on the 52840
when combined with the sx1272 for some reason so this is a
temporary work-around.

hw/drivers/sx1272: Make driver shield compatible and fix driver issues.

---

net/nimble/controller/src/ble_ll_adv.c

When using legacy advertising commands

nimble/ll: Allow setting scan rsp data before configuring advertising

---

net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/syscfg.yml

The calculations for sending this HCI event periodically seem strange,
probably something was mixed up in the past here.
After fix I believe this does what it is supposed to do: every X ticks
we'll just go through all connections and send HCI event no matter if
there is something to send or not.
Also added some with reference to spec section.

nimble/ll: Fix sending HCI Number of Completed Packets event

---

hw/drivers/lora/sx1272/src/sx1272.c

Decided to bring this file up to date with latest code in semtech
repo. Changes were all coding style except for the setting of
FIFO address pointer after a received frame. While this change
may not be needed given how we access the FIFO it is more correct
to have it than not.

net/lora: Update sx1272 to latest semtech code.

---

net/ip/include/arch/sys_arch.h

The `sys_now` function is supposed to calculate milliseconds since boot.  However, the operands were not in the correct order, so the units were off.
In sim, this caused the `tcpip_thread()` task handler to never yield to other tasks during timeout calculation.

lwip - Fix time calculation

---

encoding/json/src/json_decode.c

This caused the library to skip some characters after parsing
an object from a list. When it encountered a character it didn't expect
the library returned an error.
We don't need to consume white space here because it is done after
returning from this function.

encoding/json: Remove unnecessary reads when parsing

---

libc/baselibc/src/tinyprintf.c

This implementation supports only 3 decimal digits.
Left-align is not supported. When specifying width it is
counted with 3 decimal digits, point character, and sign,
if a number is negative.

libc: Add support for float in printf

---

hw/bsp/ble400/src/hal_bsp.c
hw/bsp/bmd200/src/hal_bsp.c
hw/bsp/bmd300eval/src/hal_bsp.c
hw/bsp/nrf51-arduino_101/src/hal_bsp.c
hw/bsp/nrf51dk-16kbram/src/hal_bsp.c
hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/rb-blend2/src/hal_bsp.c
hw/bsp/rb-nano2/src/hal_bsp.c
hw/bsp/vbluno51/src/hal_bsp.c

Fixes issues building the bootloader, with not peripherals enabled (non used var warning) or UART include errors when no UART is enabled.

Fix build errors in BSPs

---

libc/baselibc/src/tinyprintf.c

Libs doing float computations take a lot of text space,
so it shouldn't be compiled by default.

libc: Conditionally compile float support in printf

---

net/nimble/host/services/ans/src/ble_svc_ans.c

Removed pow function, and math.h include

service/ans: don't depent on libm for creating bitmask

---

sys/log/full/include/log/log.h
sys/log/full/src/log_cbmem.c
sys/log/full/src/log_console.c
sys/log/full/src/log_fcb.c

This seems like a good candidate for static function inside FCB log
handler only: it was added specifically to FCB handler, it is not
defined by any other handler and cannot even be used by an application
since it lacks actual implementation.

sys/log: Remove undefined log_rtr_erasei()

---

apps/pwm_test/pkg.yml
apps/pwm_test/src/main.c
hw/drivers/pwm/include/pwm/pwm.h
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c
hw/drivers/pwm/src/pwm.c

PWM add cycle interrupt handling to pwm_nrf52 driver

---

time/datetime/include/datetime/datetime.h
time/datetime/src/datetime.c

The conversion functions used internally in the time/datetime library are quite useful. I see no reason why they should not be exposed. Hence this small PR :)

Expose timeval <-> clocktime conversion functions from time/datetime library

---

hw/drivers/lora/sx1272/src/sx1272-board.c
hw/drivers/lora/sx1272/syscfg.yml
hw/drivers/lora/sx1276/src/sx1276-board.c
hw/drivers/lora/sx1276/syscfg.yml

The sx1272 and 1276 have different possible RF output paths. The
code was assuming that PABOOST was always used for the sx1272
and that PABOOST was used for the HF band on the sx1276 always.
The new code allows the bsp/app/target/etc to specify the RF
output path for transmit. The added configuration variables are:
SX1272_USE_PA_BOOST and SX1276_HF_USE_PA_BOOST and
SX1276_LF_USE_PA_BOOST. The default is to use the normal RF
output path in all cases.

hw/drivers/lora: Add MYNEWT_VALs to select PA_BOOST or RFO

---

sys/log/full/src/log_console.c
sys/log/full/src/log_shell.c

After PRs #888 and #890 fixed stack and malloc to use proper 8-byte
alignment uint64_t should also work with printfs.

sys/log: Print timestamp as proper uint64

---

hw/bsp/nucleo-f303k8/syscfg.yml
hw/bsp/nucleo-f303re/syscfg.yml
hw/bsp/stm32f3discovery/syscfg.yml

This allows building/testing with slinky on stm32f3.

Add flash area config for nffs/reboot/config/coredump

---

sys/shell/src/shell.c

The function shell_cmd_register() accepts help as part of the shell_cmd structure, however this is never taken across into compat_commands. This PR makes sure the help pointer is copied across if the SHELL_CMD_HELP variable is set.

Shell: Registering help for commands registered with shell_cmd_register

---

apps/spitest/src/main.c
apps/spitest/syscfg.yml

This adds new syscfg options to pass the number of the slave/master peripheral to use in the tests. This customization is required when testing on boards that have SPI0 pins already used for other purposes or not easily reachable in the conn headers.
This also allows for using a single board doing spi testing between two different SPI peripherals.

Add option do configure spi master/slave number

---

time/datetime/include/datetime/datetime.h
time/datetime/src/datetime.c

Take in account time zone for converting clocktime <-> timeval. Was use in timeval_to_clocktime but not clocktime_to_timeval

datetime: use timezone for clocktime_to_timeval

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

NRF52832 has support for a third SPIM or SPIS peripheral. Just making that available. 
Credit to Marcus Engholm for helping with this.

Adding support for SPI_2 for nrf52

---

boot/boot_serial/src/boot_serial.c
boot/boot_serial/src/boot_uart.c
boot/boot_serial/syscfg.yml

*Note: This feature was requested by a user.  If we are unsure if this feature belongs in the boot loader in its current state, I am happy to just point him to this branch in the meantime.  Also, maybe this should be filed against MCUboot instead?*
If enabled, the serial boot loader listens on the UART for a string for a configurable amount of time.  If the string is detected, the boot loader enters serial mode.  If the string is not detected when the timeout expires, the boot loader proceeds in normal (non-serial) mode.
This feature is intended for setups that lack a suitable pin to use for enabling serial mode (either the pins are inaccessible or inconvenient to use).
Enabling this feature added 248 bytes to the boot loader binary when built on the nRF52dk with the default string …

boot_serial - Allow UART string for serial mode.

---

hw/drivers/adc/include/adc/adc.h

The adc api was missing the adc_read_channel function.

ADC: Added missing function for blocking read of channel.

---

hw/mcu/nordic/nrf51xxx/src/hal_system.c
hw/mcu/nordic/nrf52xxx/src/hal_system.c

This patch changes clock startup code to have common part which enables
LF clock for each of possible configurations. Also it fixes bitmasking
operations which had values and masks from different registers mixed.

hw/mcu/nordic: Refactor clock startup code

---

apps/btshell/src/btshell.h
apps/btshell/src/cmd.c
apps/btshell/src/cmd_l2cap.c
apps/btshell/src/main.c

With this patch it is possible to create server which will response with
error for each connection request. This is needed for PTS tests.

btshell: Add way to reject LE CoC connection request

---

hw/bsp/ada_feather_nrf52/src/hal_bsp.c
hw/bsp/arduino_primo_nrf52/src/hal_bsp.c
hw/bsp/bmd200/src/hal_bsp.c
hw/bsp/bmd300eval/src/hal_bsp.c
hw/bsp/calliope_mini/src/hal_bsp.c
hw/bsp/dwm1001-dev/src/hal_bsp.c
hw/bsp/nina-b1/src/hal_bsp.c
hw/bsp/nrf51-arduino_101/src/hal_bsp.c
hw/bsp/nrf51-blenano/src/hal_bsp.c
hw/bsp/nrf51dk-16kbram/src/hal_bsp.c
hw/bsp/nrf51dk/src/hal_bsp.c
hw/bsp/nrf52-thingy/src/hal_bsp.c
hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/nrf52dk/src/hal_bsp.c
hw/bsp/puckjs/src/hal_bsp.c
hw/bsp/rb-blend2/src/hal_bsp.c
hw/bsp/rb-nano2/src/hal_bsp.c
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/bsp/telee02/src/hal_bsp.c
hw/bsp/vbluno51/src/hal_bsp.c
hw/bsp/vbluno52/src/hal_bsp.c
hw/drivers/adc/adc_nrf51/include/adc_nrf51/adc_nrf51.h
hw/drivers/adc/adc_nrf51/src/adc_nrf51.c
hw/drivers/adc/adc_nrf52/include/adc_nrf52/adc_nrf52.h
hw/drivers/adc/adc_nrf52/src/adc_nrf52.c

When doing some work with ADC I've noticed that in both adc drivers for nrf51/nrf52 uses static variables for global_adc_config and init_adc_config  with different types which does not match each other. So far so good. However, init_adc_config is stored from init function and global_adc_config from open function. The issue here is that on both open and init functions takes same configuration type. Not sure how it works so far. Hope this PR straight it up.

hw/nrfxx/adc: Fix handling ADC configuration

---

hw/bsp/olimex-p103/src/hal_bsp.c
hw/mcu/stm/stm32f1xx/include/mcu/stm32f1_bsp.h
hw/mcu/stm/stm32f1xx/src/hal_gpio.c
hw/mcu/stm/stm32f1xx/src/hal_uart.c

This fixes the UART configuration on Olimex STM32-P103 and also fixes the uart driver for STM32F1 which uses a slightly different mechanism for configuring alternate function for GPIOs. Hopefully this will live a short life and be replaced by a unified stm32-common uart driver!

Fix stm32f1xx/olimex-p103 UART

---

net/ip/lwip_base/pkg.yml

The latest version of lwIP (2.0.3) provokes `unused-const-variable` warnings in some versions of gcc.  For example:
```
Error: net/ip/lwip_base/src/apps/httpd/fsdata.c:137:27: error: 'dummy_align__index_html' defined but not used [-Werror=unused-const-variable=]
static const unsigned int dummy_align__index_html = 2;
^~~~~~~~~~~~~~~~~~~~~~~
```
We can't disable this particular warning in the `lwip_core` package's cflags, because older versions of gcc complain when they don't recognize the command line option:
```
cc1: error: unrecognized command line option '-Wno-unused-const-variable' [-Werror]
```
This commit disables all "unused" warnings in the `lwip_core` package by adding the `-Wno-unused` cflag.

lwIP - Disable -Werror

---

net/oic/src/port/mynewt/lora_adaptor.c

For seq 0 hold the latest arrival, for other segments toss away
the 2nd arrival.

net/oic; detect duplicate frames using fragmentation seq number.

---

hw/util/button/include/button/button.h
hw/util/button/pkg.yml
hw/util/button/src/button.c
hw/util/button/syscfg.yml

Common dev board or iot projects usually have a minimal set of buttons (1 or 2),  This package will ease the use of theses buttons by handling common user interaction (click, double click, long click, auto-repeating, 3 button emulation). Code size can be reduced by using various syscfg.

implementation of common button events

---

hw/mcu/stm/stm32f3xx/src/hal_flash.c

This updates `hal_flash` on the stm32f3 to use the native sector size for this mcu (2k).

Update to 2k sector size on stm32f3

---

mgmt/imgmgr/src/imgmgr.c

This fixes an issue found on stm32f3 where newtmgr after writing an odd sized packet, would hardfault on the next write due to trying to write an odd address which is not valid on stm32f3 flash.

Fix imgmgr to follow flash write alignment

---

apps/bleuart/pkg.yml
apps/bsnprph/pkg.yml

This PR modifies two apps:
* bleuart
* bsnprph
These two apps depend on `boot/split`, which requires the `bootloader` API.  This PR satisfies this requirement by adding the `boot/bootutil` package to both apps' dependency lists.

Fix build errors - Add required bootutil dependency to a few apps

---

hw/mcu/stm/stm32f3xx/src/hal_uart.c

When an overrun happened it would never leave the overrun state and it would basically halt from receiving packets.

Fix stm32f3 uart overrun handling

---

boot/boot_serial/src/boot_serial.c

This fixes an issue found on stm32f3 where newtmgr after writing an odd sized packet, would hardfault on the next write due to trying to write an odd address which is not valid on stm32f3 flash.

Fix boot_serial to follow flash write alignment

---

hw/hal/include/hal/hal_timer.h
libc/baselibc/include/assert.h
sys/sysinit/include/sysinit/sysinit.h

`os/mynewt.h` includes a set a of headers.  None of the headers in this set should include `os/mynewt.h`.

Don't include os/mynewt.h from primitive headers.

---

sys/console/full/src/uart_console.c

This fixes an issue were `os_default_irq` is trying to print dump information before UART initialization was completed, causing a fault and losing all stack/backtrace data, making debug impossible.

Fix printf fault before UART was initialized

---

sys/console/minimal/include/console/console.h
sys/console/minimal/src/console.c

console minimal was using `console_echo()` function to set echo, but this function is empty on the minimal version. It is only implemented on `console/full`.

Fix console echo in minimal console

---

fs/fcb/include/fcb/fcb.h
fs/fcb/src/fcb.c
sys/log/full/include/log/log.h
sys/log/full/include/log/log_fcb_slot1.h
sys/log/full/src/log.c
sys/log/full/src/log_cbmem.c
sys/log/full/src/log_fcb.c
sys/log/full/src/log_fcb_slot1.c
sys/log/full/syscfg.yml
util/cbmem/include/cbmem/cbmem.h
util/cbmem/src/cbmem.c

Few improvements to logging subsystem to allow putting more data to log entries:
- allow to log directly from mbuf
- add data type to log entry (to distinguish between text/CBOR/whatever entries)
- special log handler to put data on unused slot1
Things to consider:
- Log version is bumped from 2 to 3, but there is no backwards compatibility retained - this means data from fcb written with v2 will be unreadable. Does it matter? Previous updates to log header did not care about it.
- Should slot1 be unlockable i.e. slot1 is locked, data is collected to cbmem, then unlocked and data is copied back to fcb. I removed this piece of code from PR since it was not working well for me yet, but I wonder if we'd actually need it. I imagine when image is uploaded to slot1 we have restart after which …

sys/log: Better handling for long/non-text entries

---

hw/drivers/sensors/lps33hw/include/lps33hw/lps33hw.h
hw/drivers/sensors/lps33hw/src/lps33hw.c

The previous version fo the lps33hw did not include support for SPI interface.  In this PR we add this support.  
Testing/Verification - via sensor CLI read sensor pressure value.

Add SPI to lps33hw driver

---

net/ip/mn_socket/test/src/mn_sock_test.c
net/ip/mn_socket/test/src/mn_sock_util.c
net/ip/native_sockets/src/native_sock.c

In unix, `connect()` on a non-blocking socket returns -1 and sets `errno` to EINPROGRESS.  `native_sock_connect()` was incorrectly interpreting this condition as a failure.  This was not getting caught by the unit tests because the `mn_socket` self-test was always returning 0, regardless of test failures.
This PR changes `native_sock_connect()` returns 0 under these conditions, and eventually indicates the result of the connect attempt by calling the socket's "writable" callback.  It also changes the `mn_socket` self-test to report test failures.

native_sockets - handle non-blocking connects.

---

kernel/os/src/os_time.c

The os_time_ms_to_ticks assumes the multiplication always proceeds the division in the following piece of code: 
```
ticks = (uint64_t)ms * OS_TICKS_PER_SEC / 1000;
```
With an OS_TICKS_PER_SEC < 1000 the division could result in 0 and give the wrong number of ticks. This PR adds () to force multiplication before division. Thus:
```
ticks = ((uint64_t)ms * OS_TICKS_PER_SEC) / 1000;
```

os_time: Prevent 0 ticks returned when OS_TICKS_PER_SEC < 1000

---

apps/btshell/src/cmd.c

Parsing was called twice resulting always storing default value (0).

btshell: Fix parsing of high_duty parameter

---

boot/boot_serial/src/boot_serial.c
boot/boot_serial/syscfg.yml
hw/hal/include/hal/hal_nvreg.h
hw/mcu/nordic/nrf52xxx/src/hal_nvreg.c

This is a first attempt at a hal interface to retained registers. (And added support for serial bootloader to use it to enter bootloader on reset if a specific value is saved in one of them)
Various microcontrollers have a few registers that survive a soft reset. This interface exposes them (if available) via hal_nvreg (Happy to change the name if we can think of something better).
I was thinking nv for nonvolatile, which isn't always true since they will get cleared after hard reset (in some devices). Another options was hal_retained_reg, which is a bit long, but also works.
* `void hal_nvreg_write(unsigned int reg, uint32_t val);`
* Stores value to retained register at index <reg>
* `uint32_t hal_nvreg_read(unsigned int reg);`
* Returns value of retained register at index <reg>
* …

WIP: hal_nvreg (Retained register interface)

---

sys/console/full/src/console.c
sys/console/full/src/uart_console.c
sys/console/full/syscfg.yml

There is possible deadlock when doing rx and tx at the same time, i.e. if tx buffer is full and rxd character triggers some output (e.g. echo) it is not possible to put new character to tx buffer and also tx buffer cannot be drained since we're in interrupt handler already.
To mitigate this there was workaround added which detected this condition and just dropped txd characters. This patch replaces this workaround with more generic solution: there is intermediate RX ringbuffer where data form UART are received and are not handled in interrupt context but in task context instead. Buffer can be disabled to retain original behaviour if necessary.

console: Add asynchronous RX handling for UART

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c

Change config structure to use bitfields to reduce structure size. 
Fix bit shift value and if else style as well.

LIS2DW12 add bitfields

---

mgmt/imgmgr/src/imgmgr.c

gcc 5.4.1 reports the following warning when `BOOTUTIL_IMAGE_FORMAT_V2` is enabled:
```
Error: repos/apache-mynewt-core/mgmt/imgmgr/src/imgmgr.c: In function 'imgr_read_info':
repos/apache-mynewt-core/mgmt/imgmgr/src/imgmgr.c:202:16: error: 'data_end' may be used uninitialized in this function [-Werror=maybe-uninitialized]
if (data_off + IMGMGR_HASH_LEN > data_end) {
^
```
This is a spurious warning; `data_end` is always initialized at this point.  The fix is to initialize `data_end` to 0 at the start of the function.

imgmgr: Prevent `maybe-uninitialized` warning.

---

hw/sensor/src/sensor.c

- Earlier this was multiplexing multiple events for a single notification
- This fixes #1021

Sensor API: Support only one event per notifier/notification

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/sensor/include/sensor/sensor.h

- lis2dw12: Support sleep change event for notifications
- Also cleaning up a bit, removing extraneous spaces, adding comments
- Also fixes #1020, lis2dw12: int2 not routable for sensor notifications
- This fixes #1022

lis2dw12: Support sleep change event for notifications

---

sys/shell/src/shell.c

With this patch every piece of help (summary, usage, params)
can be printed if is provided for a command.
```
btshell> help l2cap-update
Summary:
update l2cap parameters for connection
Parameters:
conn                          connection handle, usage: =<UINT16>
interval_min                  usage: =[0-UINT16_MAX], default: 30
interval_max                  usage: =[0-UINT16_MAX], default: 50
latency                       usage: =[UINT16], default: 0
timeout                       usage: =[UINT16], default: 0x0100
```

sys/shell: Improve command help information

---

kernel/os/include/os/os_mempool.h
kernel/os/src/os_mempool.c
kernel/os/test/src/mempool_test.h
kernel/os/test/src/testcases/os_mempool_test_case.c

This is used to clear mempool (ie all block taken are invalidated)
without doing full initialisation of it. Unlike init this function
can be called multiple time on same mempool.

mempool: Add os_mempool_clear function

---

fs/fs/src/fsutil.c

The documentation for fsutil_write_file states that it should truncate the file if it already exists.   That's not the case right now, but this patch fixes that.   I think this is the right behavior, rather than updating the docs to match the code.

fsutil_write_file: open the file, truncating if it exists

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/sensor/creator/src/sensor_creator.c

- Set/Clear individual interrupt cfg bits
- Change config in sensor creator
- Change int_active to int_active_low to be more explicit
- Change lis2dw12_set_int_active() to lis2dw12_set_int_active_low()

lis2dw12: Add support for set/clear int cfg bits

---

boot/boot_serial/pkg.yml

Now that the serial boot loader accesses the UART directly, it doesn't require a console package.

boot_serial: Remove required API "console"

---

kernel/sim/src/sim_sched_gen.c
net/ip/mn_socket/test/src/mn_sock_test.c
net/ip/mn_socket/test/src/mn_sock_test.h
net/ip/mn_socket/test/src/mn_sock_util.c
net/ip/mn_socket/test/src/testcases/inet_ntop_test.c
net/ip/mn_socket/test/src/testcases/inet_pton_test.c
net/ip/mn_socket/test/src/testcases/socket_tests.c
net/oic/test/src/test_discovery.c
net/oic/test/src/test_getset.c
net/oic/test/src/test_observe.c
net/oic/test/src/test_oic.c
net/oic/test/src/testcases/oic_tests.c
test/testutil/include/testutil/testutil.h
test/testutil/src/testutil.c

Most tests don't utilize the OS scheduler; they simply run in main(), outside the context of a task.  However, sometimes the OS is required to fully test a package, e.g., to verify timeouts and other timed events.
This commit simplifies the implementation of test cases that require the OS.  This is done by the addition of a macro: `TEST_CASE_TASK()`.  This macro is identical in usage to `TEST_CASE()`, except the test case it defines performs some additional preliminary work:
1. Calls `sysinit()`
2. Creates the default task.
3. Creates the "test task" (the task where the test itself runs).
4. Starts the OS.
The `TEST_CASE_TASK()` function body is what actually runs in the test task.
This eliminates the need to define two tasks, two stacks, and two handlers for each test case.
This commit …

Simplify unit tests that run in the OS

---

docs/os/modules/fs/fs/fsutil_write_file.rst

I'm fairly sure that this is the intention for this example code fragment.
It certainly needs to be fixed, since FS_EALREADY doesn't exist anywhere that grep can find.

docs: use the proper error code in example

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

I'm working on a board on which I read a lot of data from the i2c bus. Resets in the middle of one of these transfers can cause a slave on the bus to hold the sda pin low - i.e. hang the i2c bus. Even though the hal_i2c_init runs the hal_i2c_clear_bus() function at boot, which should be able to clear the i2c bus at startup, the system does not recover from a hanged i2c bus without a power cycle. 
hal_i2c_clear_bus clears the bus by checking if it's held low and outputs clock cycles on scl until the slave lets go. However, because of the weird mode the sda pin was in - output but still with the input_buffer enabled input buffer, the actual value from outside was never read. This because hal_gpio_read(sda_pin) only reads the input buffer if the port-DIR was set to input. 
Not sure this is …

nrf52xxx_i2c: Fix to allow hal_i2c_clear_bus to read from input-buffer 

---

net/ip/mn_socket/src/mn_socket_aconv.c

This commit fixes the following build error:
```
Error: repos/apache-mynewt-core/net/ip/mn_socket/src/mn_socket_aconv.c: In function 'mn_inet6_pton_segment':
repos/apache-mynewt-core/net/ip/mn_socket/src/mn_socket_aconv.c:139:11: error: implicit declaration of function 'htons' [-Werror=implicit-function-declaration]
u16 = htons(u16);
```
`mn_socket_aconv.c` requires `htons`, which is declared in `os/endian.h`.  The fix is to include the catch-all header `os/mynewt.h`.

mn_socket - Fix build error due to missing include

---

kernel/os/include/os/os_time.h
kernel/os/src/os_time.c

This is complementary to os_time_ms_to_ticks and allows to have more
OS abstraction in code by avoiding use of OS_TICKS_PER_SEC explicitly.

os: Add os_time_ticks_to_ms

---

hw/util/button/include/button/button.h
hw/util/button/src/button.c

It doesn't look useful to have the whole button structure exposed in the user callback

util/button: Use the button id in callback instead of button pointer

---

kernel/os/src/os_callout.c

Not sure why these 2 APIs expected to be called within critical section
only, but let's make them callable from anywhere just like other APIs.

 kernel/os: Make os_callout_remaining_ticks thread-safe

---

net/oic/include/oic/port/mynewt/serial.h
net/oic/src/port/mynewt/lora_adaptor.c
net/oic/src/port/mynewt/serial_adaptor.c

net/oic; export ids for serial and lora transports. Used when creating

---

hw/drivers/sensors/adxl345/src/adxl345.c
hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bma2xx/src/bma2xx.c
hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/src/sensor_oic.c
hw/sensor/src/sensor_shell.c
hw/sensor/syscfg.yml

- Earlier the notifications were stacked to give one single callback
for a combination of event notifications, as part of this commit the
notifications events are handled as separate events so that events do
not get missed while the notifications are being serviced
- Adding an event pool for the notifications with a default size of 5,
this is configurable using SENSOR_NOTIF_EVENTS_MAX mynewt syscfg
variable
- Adding stats for notifications to track which event notification got
triggered
- Fixing doxygen style comments in sensor.h.
- Changing other drivers to use the event_put API per type of event,
specifying an event
- Adding Sleep and Wake Up event support

SensorAPI: lis2dw12: Breaking up sensor notifications

---

hw/bsp/ada_feather_nrf52/include/bsp/bsp.h

This button is labelled as DFU, and is a general purpose IO line

Define BUTTON_1 for the Adafruit nrf52 Feather

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/pkg.yml
hw/drivers/flash/spiflash/src/spiflash.c
hw/drivers/flash/spiflash/syscfg.yml

SpiFlash driver can be used with any hal that supports SPI in master mode.
application syscfg.yml must specify SPI parameters, it must also specify
manufacturer data that 0x9F command returns.
SPIFLASH_MANUFACTURER, SPIFLASH_MEMORY_TYPE, SPIFLASH_MEMORY_CAPACITY is
used to verify that correct flash is detected.

Add SpiFlash driver

---

apps/trng_test/pkg.yml
apps/trng_test/src/main.c
apps/trng_test/syscfg.yml
hw/bsp/nrf52840pdk/pkg.yml
hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/drivers/trng/include/trng/trng.h
hw/drivers/trng/pkg.yml
hw/drivers/trng/src/trng.c
hw/drivers/trng/trng_nrf52/include/trng_nrf52/trng_nrf52.h
hw/drivers/trng/trng_nrf52/pkg.yml
hw/drivers/trng/trng_nrf52/src/trng_nrf52.c
hw/drivers/trng/trng_nrf52/syscfg.yml
hw/mcu/nordic/nrf52xxx/syscfg.yml

This is proposed hal_trng which abstracts TRNG (True Random Number Generator) available on many SoCs. It exposed just few simple APIs which should be enough for typical operation:
- read single u32 value
- fill buffer with random data - blocking and non-blocking

hw/drivers/trng: Add driver for True Random Number Generator (TRNG)

---

hw/charge-control/include/charge-control/charge_control.h
hw/charge-control/syscfg.yml

There was missing end of comment that is now fixed.
By default function is called that is not defined in any place.
It may be that someone forgot to check in shell support files,
or it was planned and not finished.

Fix build when charge_control is enabled

---

apps/btshell/src/cmd.c

When starting legacy scan code was also trying to start extended scan
with garbage parameters.

btshell: Fix scan command in legacy mode

---

net/lora/node/src/mac/LoRaMac.c

The code would not automatically go into receive mode if
the device was CLASS C and it transmitted an unconfirmed and
received a packet in window 1.
Also noticed that the code would not stop unconfirmed frame
repetitions if it received a valid packet during window 1.

net/lora: Fix issue with radio stop receiving

---

apps/blemesh_light/pkg.yml
apps/blemesh_light/src/light_model.c
apps/blemesh_light/src/light_model.h
apps/blemesh_light/src/main.c
apps/blemesh_light/src/ws2812.c
apps/blemesh_light/src/ws2812.h
apps/blemesh_light/syscfg.yml

This app serves as an example of using Generic models to
implement a Lighting app. You can control it from Silicon Labs'
Android Mesh app. Configure it the device as Level model and use slider
to control the lightness. You can use LEDs on board controlled with PWMs
or use NEOPIXEL LED matrix.
This app uses a special API that was exposed for demo purposes.

apps/blemesh_light: Add demo app that uses Light Lightness model

---

version.yml

Newt uses the `version.yml` file to determine the version of a checked out repo.  This should always be 0.0.0 in the master branch.
Please see https://github.com/apache/mynewt-newt/pull/165 for more information about newt uses this file.

Add `version.yml` to master.

---

hw/mcu/stm/stm32f3xx/include/mcu/mcu.h
hw/mcu/stm/stm32f7xx/include/mcu/mcu.h

During the discussion about pwm pin types I noticed that several gpio ports are mapped into the same range - making them indistinguishable from each other.

Fixed typos in stm32 gpio port mapping.

---

apps/blemesh/src/main.c
apps/blemesh_shell/src/main.c

Since it is possible to have mesh along with regular BLE, lets allow to
make it use in btshell.

blemesh: Remove bt_mesh_register_gatt from app code

---

kernel/os/src/os_mempool.c

Once we removed block from mempool, we can check it outside critical
section so we do not block interrupts unnecessarily.

kernel/os: Check mempool pattern outside critical section

---

hw/drivers/drv2605/include/drv2605/drv2605.h
hw/drivers/drv2605/src/drv2605.c
hw/drivers/drv2605/src/drv2605_priv.h
hw/drivers/drv2605/src/drv2605_shell.c

This patch adds support for ERM motors to the DRV2605 module, which heretofore only supported LRA devices.   
There are also a handful of documentation corrections for the drv2605 driver included as well.

drv2605 erm support

---

sys/config/include/config/config.h
sys/id/include/id/id.h
sys/id/src/id.c
sys/reboot/include/reboot/log_reboot.h
sys/reboot/src/log_reboot.c

These particular items would be available through conf_get_value() interface, but access via direct symbol would be easier.

Export few key variables for direct use.

---

apps/btshell/syscfg.yml

Memory error may occure while operating with enabled mesh and additional
instances of advertising. This update was tested agains initialized mesh
and one separate instance of advertising.

app/btshell: Increase block count if mesh enabled

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

Z tap threshold was wrongly masked with register number LIS2DW12_REG_TAP_THS_Z
instead of mask LIS2DW12_TAP_THS_Z_THS.

sensor/lis2dw12: Fix lis2dw12_set_tap_cfg

---

hw/bsp/bbc_microbit/syscfg.yml
hw/bsp/ble400/syscfg.yml
hw/bsp/bmd200/syscfg.yml
hw/bsp/calliope_mini/syscfg.yml
hw/bsp/vbluno51/syscfg.yml

This removes sysdefs `ADC_0_REFMV_0`, `ADC_0_REFMV_1`, `ADC_0_REFMV_VDD` that are already present on `mcu/nordic/nrf51xxx/syscfg.yml`

Remove ADC sysdefs already present on nrf51xx MCU

---

hw/drivers/sensors/adxl345/src/adxl345.c
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bno055/src/bno055.c
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/mpu6050/src/mpu6050.c
hw/drivers/sensors/tcs34725/src/tcs34725.c
hw/drivers/sensors/tsl2561/src/tsl2561.c

Several sensor drivers has formating issues that would be detected if log_error() has __attribute((format..) added.
First commit removes errors with extra placeholders.
Second cleans up formating so no warning will pop up in the future.

Senesor error format fix

---

hw/drivers/tlc5971/include/tlc5971/tlc5971.h
hw/drivers/tlc5971/pkg.yml
hw/drivers/tlc5971/src/tlc5971.c

This is the first cut at a TLC5971 driver. This allows the user to control the global brightness and individual RGB leds in each of the four channels of the chip.

hw/drivers: Add TLC5971 driver

---

compiler/riscv64/compiler.yml
hw/bsp/hifive1/src/hal_bsp.c
hw/mcu/sifive/fe310/src/hal_spi.c
hw/mcu/sifive/fe310/syscfg.yml

Hal was missing SPI driver.
Now two SPI controllers can be configured.
Those two controller can only work as masters.
There is no 16 bits support nor slave (hardware limitation).
MISO/MOSI/SCK pins are hardwired and can't be configured.
Hardware suport slave select pin selection, but SPI HAL does cover chip select handling.
Optimization flag -O1 change to -Og for batter debug experience.

HiFive1 add missing peripheral driver

---

apps/btshell/src/btshell.h
apps/btshell/src/cmd.c
apps/btshell/src/main.c

This patch extends btshell with cmd_set_scan_opts command, that
limit the data printed out to the serial console during
scanning. It has been noticed that the large amount of data
sent on UART might cause the LE Extended Adverising packets
to be truncated.
The command params are:
* ignore_legacy - to not print legacy advertisements
* decode_limit - to limit the data to be printed out to serial
console.

apps/btshell: Add cmd_set_scan_opts command

---

compiler/arm-none-eabi-m0/compiler.yml
hw/cmsis-core/src/cmsis_nvic.c
hw/cmsis-core/src/ext/cmsis_armcc.h
hw/cmsis-core/src/ext/cmsis_armclang.h
hw/cmsis-core/src/ext/cmsis_compiler.h
hw/cmsis-core/src/ext/cmsis_iccarm.h
hw/cmsis-core/src/ext/cmsis_version.h
hw/cmsis-core/src/ext/core_armv8mbl.h
hw/cmsis-core/src/ext/core_armv8mml.h
hw/cmsis-core/src/ext/core_cm0.h
hw/cmsis-core/src/ext/core_cm0plus.h
hw/cmsis-core/src/ext/core_cm23.h
hw/cmsis-core/src/ext/core_cm33.h
hw/cmsis-core/src/ext/core_cm4.h
hw/cmsis-core/src/ext/core_sc000.h
hw/cmsis-core/src/ext/core_sc300.h
hw/cmsis-core/src/ext/mpu_armv7.h
hw/cmsis-core/src/ext/mpu_armv8.h
hw/cmsis-core/src/ext/mynewt_cm0_vectab.h
hw/cmsis-core/src/ext/tz_context.h

This is a RFC for upgrading to CMSIS 5.3.0.
CMSIS 5.x provides per arch `NVIC_SetVector` and `NVIC_GetVector` which is being used here for CM3/4/7. For CM0 I added a custom header which uses the `__vector_tbl_reloc__` symbol from the linker files. This might not be the most clean way to do it, because I ended up adding defines to the m0 compiler flags.
I tested this on at least one target of each currently supported ARM cpu.

RFC - upgrade CMSIS to 5.3.0

---

hw/mcu/nordic/include/nrfx_glue.h
hw/mcu/nordic/nrf52xxx/include/mcu/cortex_m4.h
hw/mcu/nordic/nrf52xxx/pkg.yml
hw/mcu/nordic/nrf52xxx/src/hal_flash.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/nordic/pkg.yml

This PR hopes to add support for the NRF52810 series.
It fixes the issues addressed in #845 (AFAIK)
It does require updating to the CMSIS 5 header, which are also included.
An example project with an NRF52810 BSP can be found here: https://github.com/alvarop/blemesh

[WIP] NRF52810 Support

---

hw/mcu/native/src/hal_system.c

This fix controller unit tests build failure.

hw/native: Add hal_debugger_connected implementation

---

hw/scripts/jlink.sh

This allows the previous arguments specified in the script to be overridden by the user. 
This has been an issue for us, since some of our devices require lower speeds to program/debug properly.

Put extra jtag commands at end of command

---

sys/shell/src/shell.c

Shell code expects last shell_cmd entry to be empty as it used
as a mark for the end of registered commands.
When number of registered commands reached maximum (SHELL_MAX_COMPAT_COMMANDS) then
'help' command triggred crash as below:
001632 compat> help
001837 help
001837 stat
001837 config
001837 log
001837 ln_log
001837 imgr
001837 tasks                         show os tasks
001837 mpool                         show system mpool
001837 date                          show system date
001837 lms
001837 rcc
001837                               Unhandled interrupt (3), exception sp 0x200016d0
001837  r0:0x200009ec  r1:0x20001728  r2:0x00f92005  r3:0x00f92004
001837  r4:0x00000000  r5:0x200009ec  r6:0x200009ec  r7:0x20001728
001837  r8:0x00000000  r9:0x00000000 r10:0x00000000 r11:0x00000000 …

shell: Fix crash on 'help' in shell/compat

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

Per datasheet configuration that was supposed to switch on
positive self test mode, did it, but also turned off register
auto increment functionality.
This effectively disabled possibility to read
normal values from accelerometer since those reading are
done in blocks and not single registers.
After the self test, original configuration was meant to be restored,
alas it used multi register write that was just turned off,
so the configuration was not restored.
Now IF_ADD_INC is set in per-datasheet configuration.

lis2dw12: Fix self testing function error

---

docs/os/core_os/mbuf/mbuf.rst

Change the `code` tags to use `code-block` for syntax highlighting

mbuf code samples use code-block

---

mgmt/oicmgr/src/oicmgr.c
mgmt/oicmgr/syscfg.yml

Also got rid of using start event to register coap resource; this has not been needed for a while.

oicmgr; add config knob to enable transport level security.

---

net/ip/native_sockets/include/native_sockets/native_sock.h
net/ip/native_sockets/src/native_sock.c

This PR moves the native_sock functions into the public API.  This allows an app to use both lwIP and native IP.
Example use case: a network of simulated devices that communicate via TCP.  Such an app needs the native socket functions to communicate with other simulator instances, but it may require lwIP for the network protocol it is simulating.

Allow native_sock functions to be called directly.

---

hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/pkg.yml
hw/drivers/bq27z561/src/bq27z561.c
hw/drivers/bq27z561/src/bq27z561_shell.c
hw/drivers/bq27z561/syscfg.yml

This is the initial cut at a driver for the bq27z561 fuel
gauge. No interrupt support but basic functionality is present.
No security either; just supports basic reads/writes and flash
read/writes.

hw/drivers: Initial bq27z561 driver

---

hw/mcu/native/src/hal_flash.c

New MacOS headers are complaining about tmpnam() being deprecated.

native hal_flash; use mktemp() instead of tmpnam() to generate name for temp flash file.

---

repository.yml

Core 1.4 requires newt 1.4 for repo dependencies. Also make -core
(on master branch only) depend on nimble 0-dev.

Update repository dependencies

---

sys/log/full/src/log_nmgr.c

Skipped log entries should not be counted when encoding for nmgr.

sys/log: Fix counting log entries

---

apps/bleprph/src/main.c
apps/blesplit/src/main.c
apps/bsnprph/src/main.c
apps/iptest/src/main.c
apps/sensors_test/src/main.c
apps/slinky/src/main.c
apps/slinky_oic/src/main.c
apps/splitty/src/main.c
apps/testbench/src/testbench.c
sys/config/src/config.c

Before PR: the application needed to manually restore the persisted configuration via a call to `conf_load()`, typically from `main()`.
After PR: `conf_load()` gets called automatically at startup.  It doesn't get called directly from `sysinit()`, as the underlying storage hasn't been configured at that point.  Instead, values are loaded by an event which config init function enqueues to the default event queue.  When `main()` has completed its runtime configuration, including that of the sys/config storage, it processes the default eventq, at which point `conf_load()` gets called.
There is one danger here: some packages may try to use a configuration setting before `conf_load()` has been called.  However, this is not a new issue; high priority tasks, created by `sysinit()`, would already …

sys/config: Automatically restore on startup

---

encoding/tinycbor/src/cbor_buf_reader.c
encoding/tinycbor/src/cbor_mbuf_reader.c

cmp functions are used as IteratorFunc and expected behaviour is to
return non-zero value on success so the opposite of what memcmp-like
function do.

tinycbor: Fix cmp return value from readers

---

hw/mcu/nordic/nrf52xxx/pkg.yml
hw/mcu/nordic/nrf52xxx/syscfg.yml

A syscfg value to enable pin reset on the `nrf52xxx` instead of using it as a normal GPIO.

syscfg to enable nRF52 pin reset

---

net/ip/include/lwipopts.h
net/ip/lwip_base/include/lwip/opt.h
net/ip/lwip_base/src/core/ipv6/icmp6.c
net/ip/lwip_base/src/core/ipv6/ip6.c
net/ip/lwip_base/src/core/ipv6/nd6.c
net/ip/lwip_base/src/core/netif.c
net/ip/lwip_base/src/core/tcp.c
net/ip/lwip_base/src/core/tcp_in.c
net/ip/lwip_base/src/core/timeouts.c

IPv6 neighbor discovery is enabled by default.  Define `LWIP_ND6` equal to 0 to disable it.
This is useful in case you don't want lwIP sending packets automatically.  If accepted, we will want to try to get this change upstreamed into lwIP.

lwip_base: Make IPv6 neighbor discovery cfgable

---

apps/pwm_test/src/main.c
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c

This PR makes pwm_stop not crash when called from seq_end_handler.

nrf52_pwm: catch NRFX_PWM_EVT_STOPPED events

---

libc/baselibc/src/memcpy.c

This adds a bit more optimized version of memcpy() for Cortex-M written
in inline assembly.
Naive implementation optimized by GCC (7.2.1) takes 12 cycles per byte
on Cortex-M0:
```
memcpy:
0000a706:   movs    r3, #0
9        {
0000a708:   push    {r4, lr}
23        	while (n--) {
0000a70a:   cmp     r2, r3
0000a70c:   bee.n   0xa710 <memcpy+10>
29        }
0000a70e:   pop     {r4, pc}
24        		*q++ = *p++;
0000a710:   ldrb    r4, [r1, r3]
0000a712:   strb    r4, [r0, r3]
0000a714:   adds    r3, #1
0000a716:   b.n     0xa70a <memcpy+4>
29        }
```
Inline assembly version takes only 8 cycles per byte.
For Cortex-M3/4/7 we can make it even faster as they support unaligned
memory access so we can easily copy by word.

libc/baselibc: Add optimized memcpy() for Cortex-M

---

hw/drivers/lora/sx1272/src/sx1272.c

The code appears to have been copied from SX1272WriteBuffer without being modified. The original code was probably tested with BSP_USE_HAL_SPI = 1, which is why this bug was missed.

Fixed SPI Read in SX1272ReadBuffer

---

hw/drivers/chg_ctrl/adp5061/pkg.yml
hw/drivers/chg_ctrl/adp5061/src/adp5061_shell.c

* Make `#include` directives conditional along with the code.
* Depend on `util/parse` when the CLI is enabled.

adp5061 - Fix build when CLI is not enabled

---

compiler/arm-none-eabi-m7/compiler.yml

Debug builds were omitting the frame pointer in Cortex-M7 which broke the usage of `__set_MSP` since CMSIS was upgraded to 5.x.

Fix debug builds on Cortex-M7

---

hw/bsp/nrf52840pdk/nrf52840pdk_debug.sh
hw/bsp/nrf52840pdk/nrf52840pdk_download.sh

resulting in inability to program last half of flash. Closes #1192

nrf52840pdk: fix incorrect jtag configuration

---

kernel/os/include/os/os_callout.h
kernel/os/include/os/os_mutex.h
kernel/os/include/os/os_sem.h
kernel/os/include/os/os_time.h
kernel/os/src/os_callout.c
kernel/os/src/os_mutex.c
kernel/os/src/os_sem.c
kernel/os/src/os_time.c

This patch changes callout, mutex, sem and time APIs to use os_time_t
consistently in all APIs that take or return ticks as arguments/return
value. This way we define explicitly which parameters expect values in
ticks rather than other time units.
This should not affect any existing code since most args were uint32_t
anyway which is the same as os_time_t.

kernel/os: Fix APIs to use os_time_t for ticks arguments

---

kernel/os/include/os/os_mbuf.h
kernel/os/src/os_mbuf.c
kernel/os/test/src/mbuf_test.c
kernel/os/test/src/testcases/os_mbuf_test_widen.c

Increases the length of an mbuf chain by inserting a gap at the specified
offset.  The contents of the gap are indeterminate.  If the mbuf chain
contains a packet header, its total length is increased accordingly.
This function never frees the provided mbuf chain.
@param om                    The mbuf chain to widen.
@param off                   The offset at which to insert the gap.
@param len                   The size of the gap to insert.
@return                      0 on success; SYS_[...] error code on failure.

kernel/os - Add os_mbuf_widen() function

---

hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f413re/src/hal_bsp.c
hw/bsp/nucleo-f413zh/src/hal_bsp.c
hw/bsp/olimex_stm32-e407_devboard/src/hal_bsp.c
hw/bsp/stm32f429discovery/include/bsp/bsp.h
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/mcu/stm/stm32f4xx/include/mcu/stm32f4_bsp.h
hw/mcu/stm/stm32f4xx/src/hal_flash.c

All STM32F4 MCUs were sharing the same flash sector + size configs though it varies a lot between different parts so those configs are now being moved to the BSPs.

[STM32F4] move flash sector and size configs to BSPs

---

sys/console/full/src/rtt_console.c
sys/console/full/syscfg.yml

Timeout counter was missing "static" keyword thus we always used 50ms
as polling interval for every single character in buffer. This commit
fixes the problem and also refactors polling code a bit to make RTT
input more responsive.
We will now read all available data on RTT in single run and then start
with polling interval of 10ms, increasing it by 10ms on every idle run
until it reaches max interval set by syscfg value (default 250ms). This
means there may be tiny delay when reading 1st character after longer
idle period, but then complete input can be processed in no time.

sys/console: Fix RTT input polling

---

boot/split/src/split.c
sys/config/include/config/config.h
sys/config/src/config.c
sys/config/src/config_store.c

This removes the need for a manual call to `conf_load()` in `main()`, prior to the call to `split_app_go()`
`split_app_go()` is the function which decides whether to boot into the second app or to proceed with the current one).  This function requires that the configuration has been loaded, as the action it takes depends on the `split/status` config setting.

boot/split: Ensure conf loaded before status read

---

hw/drivers/pwm/include/pwm/pwm.h
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c
hw/drivers/pwm/pwm_stm32/include/pwm_stm32/pwm_stm32.h
hw/drivers/pwm/pwm_stm32/src/pwm_stm32.c
hw/drivers/pwm/src/pwm.c

If you disable pwm and then close the device, it attempts to nrfx_pwm_uninit the same device twice and assert crashes.
Now we check if a device is 'playing' before we nrfx_pwm_uninit

pwm_nrf52: fix crash on close not checking playing status

---

hw/bsp/apollo2_evb/src/hal_bsp.c
hw/bsp/pic32mz2048_wi-fire/src/hal_bsp.c
hw/hal/include/hal/hal_bsp.h
hw/mcu/native/src/hal_hw_id.c
hw/mcu/nordic/nrf51xxx/src/nrf51_hw_id.c
hw/mcu/nordic/nrf52xxx/src/nrf52_hw_id.c
hw/mcu/nxp/MK64F12/src/hal_hw_id.c
hw/mcu/stm/stm32_common/src/stm32_hw_id.c

This function retrieves the length, in bytes, of the hardware ID.  The existing function, `hal_bsp_hw_id()`, retrieves the ID and truncates it to the size of the provided buffer, if necessary.  This new function is necessary for sizing your buffer to avoid truncation.

hw/hal: Add hal_bsp_hw_id_len() function

---

kernel/os/src/arch/sim-armv7/os_arch_stack_frame.s

Without symbol type GNU ld does not properly detect call to ARM code
from Thumb code and does not generate proper instruction to switch
modes which results in a crash.

kernel/sim-armv7: Fix os_arch_frame_init symbol type

---

apps/sensors_test/src/main.c
hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/sensor/creator/src/sensor_creator.c

Needs testing, I dont have this device this is just my set of notes from porting. Happy to rebase or remove any commits.
Id especially like to see if self test is still passing for people as it had a few problems still. I dont personally feel like its properly implemented even yet.
AN5038 Section 8 says
> The procedure consists of:
> 1. enabling the accelerometer
> 2. averaging five samples before enabling the self-test
> 3. averaging five samples after enabling the self-test
> 4. computing the difference in absolute value for each axis and verifying that it falls within
> a given range. The min and max values are provided in the datasheet.
And Im not sure I consider the current implementation following that quote
This https://github.com/apache/mynewt-core/pull/948/commits/787e2a2a915b9f3e …

Lis2dw12 fixes from lis2ds12 port

---

sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/full/src/log_console.c
sys/log/modlog/include/modlog/modlog.h
sys/log/modlog/pkg.yml
sys/log/modlog/src/modlog.c
sys/log/modlog/syscfg.yml
sys/log/modlog/test/pkg.yml
sys/log/modlog/test/src/modlog_test.c
sys/log/modlog/test/src/modlog_test.h
sys/log/modlog/test/src/modlog_test_util.c
sys/log/modlog/test/src/modlog_test_util.h
sys/log/modlog/test/src/testcases/modlog_test_case_append.c
sys/log/modlog/test/src/testcases/modlog_test_case_basic.c
sys/log/modlog/test/src/testcases/modlog_test_case_printf.c
sys/log/modlog/test/src/testcases/modlog_test_case_prio.c
sys/log/modlog/test/syscfg.yml
sys/log/stub/include/log/log.h

The modlog facility allows log entries to be written to numeric modules identifiers.  In typical usage, startup code maps 8-bit module IDs to one or more log objects, and other parts of the application log events by writing entries to module IDs.  This usage differs from the underlying `sys/log` facility, which requires clients to provide a log object to write to rather than just a module identifier.
Benefits provided by the modlog package are:
* Improved modularity - configuration and usage are distinct.
* Ability to write to several logs with a single function call.  If one module ID is mapped to several logs, a write to that ID causes all mapped logs to be written.
* Default mappings.  Writes to unmapped module IDs get written to an optional set of default logs.
* Minimum log level per …

log/modlog - Module-mapped logging

---

sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/full/src/log_level.c
sys/log/full/syscfg.yml
sys/log/full/test/src/log_test.c
sys/log/full/test/src/testcases/log_level.c

Defines a global map of per-module log levels.  Writes with a level less than the module's minimum level are discarded.
This allocates 128 bytes of bss.  To disable this feature, set `LOG_LEVEL_MAP` to 0.

sys/log/full: Allow min-level per module

---

mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/src/imgmgr_priv.h

1st chunk of data can include "datahash" field which is simply SHA256
computer over all data to be uploaded. This hash is stored in upload
state so in case transfer was interrupted we can detect this on next
attempt and simply resume transfer at previous location by replying
with latest offset from upload state.
"datahash" field is not mandatory so if it is missing we'll just start
new upload as usual.

mgmt/imgr: Add support to resume image upload

---

kernel/os/include/os/os_time.h
time/timesched/include/timesched/timesched.h
time/timesched/pkg.yml
time/timesched/src/timesched.c

This patch adds new package which implements timer operating on clock time. These timers do not replace e.g. `hal_timer` since they do not guarantee high accuracy, but are just a convenience wrapper over `os_callout` APIs to fire at specified clock time (`os_timeval`) instead of at ticks interval.

time/timesched: Add package to create timers using clock time

---

hw/battery/include/battery/battery.h
hw/battery/include/battery/battery_drv.h
hw/battery/include/battery/battery_prop.h
hw/battery/pkg.yml
hw/battery/src/battery.c
hw/battery/src/battery_prop.c
hw/battery/syscfg.yml
hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/pkg.yml
hw/drivers/bq27z561/src/bq27z561.c

Battery management provides abstraction layer so an application
can get information about battery without hardware specific (fuel gauge)
code.
The battery is associated with set of properties (provided by hardware
driver or battery manager itself). Properties represent physical
values measured by fuel gauges or ADC converter that application may
be interested in.
The application specify how frequently battery information should be read
and can subscribe to some subset of data that is interesting for the application.
Typically application will subscribe to voltage, temperature or current readings.
On the lower layer battery API specifies simple interface that fuel gauge need to
provide.
The battery information can be provided by several drivers (fuel gauge and ADC).
This pull request also …

Battery manager

---

hw/drivers/sensors/bma253/src/bma253_shell.c
hw/drivers/sensors/bmp280/src/bmp280_shell.c
hw/drivers/sensors/lis2dw12/src/lis2dw12_shell.c

Several sensor shell modules were including shell/shell.h and parse/parse.h even when the package CLI's are disable. The shell and/or parse packages are conditional dependencies that don't get included when the CLI is disabled, and this was resulting in a compile error.

Move includes to avoid compile error when CLIs are not enabled

---

hw/battery/include/battery/battery_adc.h
hw/battery/src/battery.c
hw/battery/src/battery_adc.c
hw/battery/src/battery_shell.c
hw/battery/syscfg.yml
hw/drivers/bq27z561/src/bq27z561.c

This adds shell command line that allows to read battery properties provided by battery drivers.
This PR also adds driver for reading battery voltage using ADC.

Battery Shell

---

hw/drivers/adc/adc_stm32f4/src/adc_stm32f4.c

Some STM32F4xx MCUs do not have 3 ADCs.
This change allows to build ADC code for those MCUs that
do not have some ADCs.

adc_stm32f4: Fix build when not all ADC are present

---

hw/drivers/adc/adc_nrf51/src/adc_nrf51.c
hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
hw/drivers/adc/adc_stm32f4/src/adc_stm32f4.c
hw/drivers/adc/include/adc/adc.h
hw/drivers/adc/src/adc.c

ADC driver function pointers do not need to be kept in
RAM. Moving them to read only section should reduce
RAM usage.

adc: Move function pointers from .data to .rodata

---

kernel/os/src/os_task.c

Before this change, a newly-created high-priority task would not immediately preempt the current one.  Preemption would not occur until the next call to `os_sched()` (e.g., via a mutex unlock).
This PR causes `os_sched()` to be called whenever a new task is created (so long as the OS has been started).
The motivation for this change is to facilitate running of multi-task unit tests.  When a unit test creates a high priority task, the new task needs to start running immediately so that it can process events generated by the main test task.

kernel/os: Preempt when high priority task created

---

kernel/os/src/os_callout.c
net/oic/include/oic/port/oc_connectivity.h
sys/console/full/src/console.c
sys/console/full/src/uart_console.c
test/crash_test/src/crash_test.c

Dangerously declared OIC macros were probably causing wrong code to be generated.
And other misc changes to compile slinky/blinky with llvm for native.

fix os_callout_reset() parameter checking

---

apps/blemesh_light/src/main.c

This is already done by sysinit when initializing mesh package.

apps/blemesh_light: Remove registering gatt services on init

---

hw/drivers/chg_ctrl/adp5061/src/adp5061_shell.c

dump command now has optional parameter 'decode' which allows
to decode register fields and makes it easier for humans.
help command is explicitly added

adp5061: Decode register fields in dump

---

hw/drivers/rtt/pkg.yml

With only `CONSOLE_RTT` enabled (other RTT features disabled) there is
only single up/down buffer thus buffer index !=0 is invalid. When
building RTT target code with optimizations enabled GCC emits an "array
subscript is above array bounds" error (`-Werror=array-bounds`) at line
1422 below because this code is accessed only if `BufferIndex` is larger
than 0 (thus out of array bounds). However, this will not happen due to
check in line 1419 as `MaxNumUpBuffers` is set to array size.
```
1419   if (BufferIndex < (unsigned)_SEGGER_RTT.MaxNumUpBuffers) {
1420     SEGGER_RTT_LOCK();
1421     if (BufferIndex > 0u) {
1422       _SEGGER_RTT.aUp[BufferIndex].sName        = sName;
```
Since there is external code which we don't want to modify and also
there is no error in code, let's just disable …

rtt: Disable spurious warning in optimized build

---

sys/config/include/config/config.h
sys/config/src/config_store.c

Using this handler can tell if value is coming from persisted storage
or from somewhere else.
Also remove obsolete XXX; functions mentioned there have been implemented.

sys/config; add conf_set_from_storage().

---

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
hw/drivers/adc/include/adc/adc.h

Even though NRF52 have multiple chanels that could be used for
reading current implementation allowd only one task to open
device.
This patch allows to use single channel readings from channels
by different task by using mutex that was previously used
for locking device in open.
Mutex is no longer acquired in open.
Multiple opens are allowed.
Mutex is used to synchronize concurrent readings.

NRF52/ADC: Allow concurrent usage

---

util/rwlock/include/rwlock/rwlock.h
util/rwlock/pkg.yml
util/rwlock/src/rwlock.c
util/rwlock/syscfg.yml
util/rwlock/test/pkg.yml
util/rwlock/test/src/rwlock_test.c
util/rwlock/test/src/rwlock_test.h
util/rwlock/test/src/testcases/rwlock_test_case_basic.c
util/rwlock/test/syscfg.yml

I needed this to implement a different feature, but I am submitting it as a separate PR.
This is a lock for multiple readers, single writer.
This lock is write-preferring.  That is:
* If there is no active writer and no pending writers, read-acquisitions do not block.
* If there is an active writer or a pending writer, read-acquisitions block.
* When the last active reader or the active writer releases the lock, it is acquired by a pending writer if there is one.  If there are no pending writers, the lock is acquired by all pending readers.

util/rwlock: Readers–writer lock

---

mgmt/imgmgr/include/imgmgr/imgmgr.h
mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/src/imgmgr_priv.h

Allow a callback to configured in the imgmgr module.  If one is configured, the callback is called immediately before the request is processed.  The callback has the following properties:
```
The callback's return code determines whether the upload request is
accepted or rejected.  If the callback returns 0, processing of the
upload request proceeds.  If the callback returns nonzero, the request
is rejected with a response containing an `rc` value equal to the return
code.
@param offset                The offset specified by the incoming
request.
@param size                  The total size of the image being uploaded.
@param arg                   Optional argument specified when the
callback was configured.
@return                      0 if the upload request should be accepted;
nonzero …
```

mgmt/imgmgr: Allow app to reject image upload reqs

---

apps/testbench/src/testbench.c

The "testtask" task was running before some variables were initialized, causing a divide by zero error in this line:
```
os_time_delay(OS_TICKS_PER_SEC / blinky_blink);
```

testbench: Initialize globals before creating task

---

sys/console/full/include/console/console.h
sys/console/full/src/console.c
sys/console/full/src/rtt_console.c
sys/console/full/src/uart_console.c
sys/shell/src/shell.c

sys/console: Add proper flow control
Flow control in console was pretty much non-existent since we always returned success from console_handle_char(). This means there was no way for "character source" to apply some kind of flow control.
To fix this console has to know when new line events are put back to queue which means queue of available line events has to be handled by console itself, not by the client. In case there is no free line event available to handle new character, RX is stalled in console and resumed when new line event is put back to queue. This automatically triggers flow control on UART, if enabled (otherwise we'll just drop characters, but this is "works as designed").
The above also works well with asynchronous UART RX since we no longer remove "oldest" character from …

sys/console: Add proper flow control

---

sys/log/modlog/pkg.yml
sys/log/modlog/src/modlog.c

Modlog (module-mapped logging) involves almost no writes compared to reads.  The modlog state is only written to when the application adds or changes a module mapping, but it is read every time a message is logged.
Using a regular mutex can cause some performance issues, as the logging task will be blocked until other tasks are done logging.  This commit replaces the regular mutex with a "readers-writer lock", which allows multiple tasks to log at the same time.

log/modlog: Use rwlock instead of mutex

---

mgmt/imgmgr/src/imgmgr.c

Some implementations of gcc-arm-none-eabi (e.g., 4.9 from home brew) do not define this constant, causing a
```
'ULLONG_MAX' undeclared
```
build error.
This commit replaces occurrences of `ULLONG_MAX` with the equivalent `-1`.

mgmt/imgmgr: Remove references to `ULLONG_MAX`

---

mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/src/imgmgr_priv.h

This changes SHA256 to SHA1 to be used for data check before allowing
image upload to be resumed.

mgmt/imgmgr: Update data hash handling (for image resume)

---

sys/log/full/syscfg.yml
sys/log/modlog/include/modlog/modlog.h
sys/log/modlog/src/modlog.c

If the stub logging implementation is being used, then also stub out the modlog functions.  This allows packages to use the modlog API whether a full logging implementation is available or not.

sys/log/modlog: Empty functions when stub log impl

---

hw/bsp/bbc_microbit/src/hal_bsp.c
hw/bsp/bbc_microbit/syscfg.yml
hw/bsp/ble400/src/hal_bsp.c
hw/bsp/ble400/syscfg.yml
hw/bsp/bmd200/src/hal_bsp.c
hw/bsp/bmd200/syscfg.yml
hw/bsp/calliope_mini/src/hal_bsp.c
hw/bsp/calliope_mini/syscfg.yml
hw/bsp/nrf51-arduino_101/src/hal_bsp.c
hw/bsp/nrf51-arduino_101/syscfg.yml
hw/bsp/nrf51-blenano/src/hal_bsp.c
hw/bsp/nrf51-blenano/syscfg.yml
hw/bsp/nrf51dk-16kbram/src/hal_bsp.c
hw/bsp/nrf51dk-16kbram/syscfg.yml
hw/bsp/nrf51dk/src/hal_bsp.c
hw/bsp/nrf51dk/syscfg.yml

First commit fixes a bunch of nrf51 bsp i2c inconsistencies 
I2C_0_FREQ -> I2C_0_FREQ_KHZ
I2C_0_FREQUENCY -> I2C_0_FREQ_KHZ
I2C_1_FREQUENCY -> I2C_1_FREQ_KHZ
I2C_1_SDA_PIN -> 	I2C_1_PIN_SDA
I2C_1_SCL_PIN -> I2C_1_PIN_SCL
I2C_0_SDA_PIN -> I2C_0_PIN_SDA
I2C_0_SCL_PIN  -> I2C_0_PIN_SCL
Second commit I added i2c1 (as well as i2c0 where necessary) no guarantees on pin choices as I dont have all these boards, but at least they can be overridden now.

Fix nrf51 bsp i2c inconsistencies

---

sys/config/include/config/config_fcb.h
sys/config/src/config_fcb.c
sys/config/test-fcb/src/conf_test_fcb.c
sys/config/test-fcb/src/testcases/config_test_custom_compress.c

This allows user to pick and choose what persisted data they want
to keep.

sys/config; add a custom filtering option when compressing FCB config.

---

hw/battery/src/battery_shell.c
hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/src/bq27z561.c

Battery drivers can have writable properties (i.e. threshold values).
This extends bq27z561 driver with access to threshold values and also exposes those values to battery API.
Write command for battery properties was also added so property writes can be tested.

Battery property write

---

hw/drivers/flash/spiflash/src/spiflash.c

A typo... we were using invalid buffer pointer so each write operation
would write from the beginning of input buffer.

hw/drivers/spiflash: Fix write over page boundary

---

hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/test/pkg.yml
hw/sensor/test/src/sensor_test.c
hw/sensor/test/src/sensor_test.h
hw/sensor/test/src/testcases/sensor_test_case_poll_err.c
hw/sensor/test/syscfg.yml

Allow "sensor error listeners" to be registered with a sensor.  When a read from a sensor fails, all error listeners that match the read attempt are notified of the error.

hw/sensor: Report read errors

---

hw/bsp/native/src/hal_bsp.c
hw/hal/include/hal/hal_i2c_sim.h
hw/mcu/native/include/mcu/mcu_sim_i2c.h
hw/mcu/native/src/hal_i2c.c
hw/mcu/native/syscfg.yml
test/i2c_scan/src/i2c_scan.c

This PR adds a **hal_i2c.c** file with stubs to the native MCU target to simulate I2C access. This can then be extended to simulate a specific device by listening for a dedicated I2C address, etc.
A minor change was also made to **test/i2c_scan/src/i2c_scan.c** since the simulator check is no longer required with the changes in this PR.
**NOTE**: Only `I2C_0` is implemented at present.

Added stubs for I2C simulation

---

hw/battery/include/battery/battery_prop.h
hw/battery/src/battery_shell.c
hw/drivers/bq27z561/src/bq27z561.c

* Battery state of health added to battery properties.
* Fuel gauge driver exposes this property.
* Battery shell can show SOH

Add State of health for battery interface and fuel gauge driver

---

hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c

This change disconnects the input buffer on a gpio when the gpio
is configured to be an output. This should save current.

hw/mcu/nordic: Disconnect input buffer when gpio made an output.

---

util/cmdarg/include/cmdarg/cmdarg.h
util/cmdarg/pkg.yml
util/cmdarg/src/cmdarg.c

Utility package for parsing `<key>=<value>` pairs among shell command arguments.

util/cmd: Package for parsing <key>=<value> pairs.

---

hw/drivers/rtt/syscfg.yml

New "newt" can emit a warning when deprecated settings are overridden.

rtt: Mark old RTT settings as deprecated

---

libc/baselibc/include/ctype.h

Makes libc more compliant, allows a subset of C++ standard header compilation with up to arm-none-eabi-gcc 5.4

Fix missing isgraph() from baselibc

---

hw/battery/include/battery/battery_adc.h
hw/battery/src/battery_adc.c

Battery voltage reading often uses resistor divider that is
actiaved with GPIO pin for energy saving (divider is not powered
when not needed).
This change allows to specify GPIO pin that must be activated
before ADC can be used.
GPIO level also can be specified allowing divider activation with 0 and 1.

battery/adc: Add activation pin support

---

hw/bsp/calliope_mini/syscfg.yml
hw/bsp/nrf51-blenano/syscfg.yml
hw/bsp/nrf51dk-16kbram/syscfg.yml
hw/bsp/nrf51dk/syscfg.yml

Attempt to at least give some warnings about these recent my i2c changes in 
https://github.com/apache/mynewt-core/pull/1247

nrf51 bsps: deprecate old i2c flag names

---

repository.yml

mynewt-core 1.4.1 was missing a dependency on mynewt-nimble.  So, if the user gets 1.4.1, newt won't automatically install / upgrade / sync nimble.
This commit adds a dependency on mynewt-nimble 1.0.0 (the only version of mynewt-nimble).

Add nimble dependency to 1.4.1.

---

hw/bsp/calliope_mini/syscfg.yml
hw/bsp/nrf51-blenano/syscfg.yml
hw/bsp/nrf51dk-16kbram/syscfg.yml
hw/bsp/nrf51dk/syscfg.yml

Fix missing value flag and defunct instead of deprecated, relies on https://github.com/apache/mynewt-newt/pull/194
Looks like this:
```
Building target targets/boot-nrf51dk
Error: Override of defunct settings detected:
I2C_0_FREQUENCY: Use I2C_0_FREQ_KHZ instead
Setting history (newest -> oldest):
I2C_0_FREQUENCY: [targets/boot-nrf51dk:100, @apache-mynewt-core/hw/bsp/nrf51dk:100]
```

nrf51 bsps: defunct old i2c flags

---

hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c

According to BME280 sensor datasheet these values are recommended for weather
monitoring mode of operation.

hw/ruuvi_tag_revb2: Fix bme280 config to recommended values

---

hw/mcu/nordic/nrf51xxx/include/mcu/mcu.h
hw/mcu/nxp/mkw41z/include/mcu/mcu.h
kernel/os/src/arch/cortex_m0/os_arch_arm.c

STM32L0 changed the naming as had previously happened on Cortex-M3 which was fixed on #851.

Add SVC IRQ name to mcu.h to avoid naming issues

---

hw/drivers/sensors/lis2ds12/src/lis2ds12.c

Looks like lis2ds missed an include in the modlog prs, without this:
```
Error: repos/apache-mynewt-core/hw/drivers/sensors/lis2ds12/src/lis2ds12.c: In function 'lis2ds12_i2c_writelen':
repos/apache-mynewt-core/hw/drivers/sensors/lis2ds12/src/lis2ds12.c:85:5: error: implicit declaration of function 'MODLOG_ERROR' [-Werror=implicit-function-declaration]
MODLOG_ ## lvl_(MYNEWT_VAL(LIS2DS12_LOG_MODULE), __VA_ARGS__)
^
repos/apache-mynewt-core/hw/drivers/sensors/lis2ds12/src/lis2ds12.c:144:9: note: in expansion of macro 'LIS2DS12_LOG'
LIS2DS12_LOG(ERROR, "I2C access failed at address 0x%02X\n",
^
```

lis2ds12: fix modlog include

---

encoding/tinycbor/include/tinycbor/cbor.h
encoding/tinycbor/src/cborencoder.c
net/oic/include/oic/oc_rep.h

This avoid memory copies when encoding byte strings where data is not contiguous in memory.

tinycbor/oic; byte string encoding with data as iovec.

---

hw/drivers/flash/spiflash/src/spiflash.c

0 causes divide-by-zero faults on users who try to follow restrictions on flash writes.

flash/spiflash; set flash alignment restrictions to 1 byte.

---

hw/mcu/stm/stm32_common/src/hal_gpio.c
hw/mcu/stm/stm32_common/src/hal_i2c.c
hw/mcu/stm/stm32_common/src/hal_uart.c
hw/mcu/stm/stm32_common/src/stm32_driver_mod_i2c_v1.c
hw/mcu/stm/stm32_common/src/stm32_driver_mod_i2c_v2.c
hw/mcu/stm/stm32_common/src/stm32_driver_mod_spi.c
hw/mcu/stm/stm32f1xx/syscfg.yml
hw/mcu/stm/stm32f3xx/syscfg.yml
hw/mcu/stm/stm32f4xx/syscfg.yml
hw/mcu/stm/stm32f7xx/syscfg.yml
hw/mcu/stm/stm32l1xx/syscfg.yml
hw/mcu/stm/stm32l4xx/syscfg.yml

This moves family specific `#ifdefs` to syscfg to avoid having to modify the driver sources every time a new family is added. Also `#ifdefery` was updated to use `MYNEWT_VAL` instead of SDK provided macros where possible.

[STM32] syscfg hal choices

---

compiler/arm-none-eabi-m0/compiler.yml

This must be added due to what seems to be a gcc regression: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=85606

Fix cortex-m0 compilation on gcc 8.1

---

hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/src/bq27z561.c

@vrahane @wes3 @kasjer 
bq27z561 changes to look at battery_status initialization bit.
bp_valid bit is not set depending on a valid read based on successful register read AND init bit set.
Without this change the listeners can return invalid values if polling occurs when fuel gauge is still initializing.

checking device initialization register for init completed

---

hw/drivers/lora/sx1272/include/radio/radio.h
hw/drivers/lora/sx1272/src/sx1272-board.c
hw/drivers/lora/sx1272/src/sx1272-board.h
hw/drivers/lora/sx1272/src/sx1272.c
hw/drivers/lora/sx1272/src/sx1272.h
hw/drivers/lora/sx1276/include/radio/radio.h
hw/drivers/lora/sx1276/src/sx1276-board.c
hw/drivers/lora/sx1276/src/sx1276-board.h
hw/drivers/lora/sx1276/src/sx1276.c
hw/drivers/lora/sx1276/src/sx1276.h
net/lora/node/src/mac/LoRaMac.c

These changes should fix non-atomic access to the spi. When attempting to transmit, the start of a reception could cause SPI access during an ISR. This could occur when the device is sending a transmit buffer to the device. This could cause the device to hang.

Lora spi fix

---

hw/mcu/stm/stm32l1xx/src/hal_flash.c
hw/mcu/stm/stm32l1xx/syscfg.yml

- Fix alignment;
- Disable write protection just while erasing/writing instead of always leaving the flash unlocked. Since the watchdog was left on in Mynewt when asking for an upgrade, and not initialized on MCUBoot, the tickle in this driver was causing an invalid write to the flash, that was unprotected, as well as a restart failing verification of the swapped image. A related watchdog issue is being submitted to MCUBoot;
- Other small refactorings applied to ease merging L4/L1/L0 into one single configurable flash driver.

Fix some issues with the L1/L0 flash driver

---

hw/mcu/nordic/nrf52xxx/src/hal_watchdog.c

Because of precision requirements the watchdog was using a uint64_t division cause it allowed any possible timeout to be used. This updates the code to rely only on uint32_t division with the limitation of a maximum timeout of around 17 min. It shrinks the code due to not linking in the div emulation code.

[RFC] [NRF52] Remove uint64_t div in watchdog init

---

sys/log/stub/include/log/log.h
sys/log/stub/src/log.c

Prior to this PR, it was the stub log header that defined each log handler.  This caused each source file that included the stub header to have its own instance of each handler, causing newt to raise an error similar to the following:
Global Symbol Conflict: log_fcb_handler from packages mgmt/newtmgr/transport/ble and nimble/host/store/config
This PR moves the handler definitions to a C file, and makes the declarations in the header file `extern`.

sys/log/stub: Define one instance of log handlers

---

hw/hal/src/hal_flash.c
hw/hal/syscfg.yml
kernel/os/syscfg.yml

This commit adds a new syscfg setting:
OS_DEBUG_MODE
This setting doesn't do anything by itself, but enabling it causes several other settings to be enabled.  Currently, this setting enables the following:
OS_CRASH_STACKTRACE
OS_CTX_SW_STACK_CHECK
OS_MEMPOOL_CHECK
OS_MEMPOOL_POISON
HAL_FLASH_VERIFY_WRITES
HAL_FLASH_VERIFY_ERASES

kernel/os: Add debug mode syscfg setting

---

hw/hal/pkg.yml
hw/hal/src/hal_flash.c

hal_flash.c was using `MYNEWT_VAL()` without including `os/mynewt.h`.

Fix unit test build errors

---

sys/log/modlog/include/modlog/modlog.h
sys/log/modlog/syscfg.yml

Create a syscfg setting: `MODLOG_LOG_MACROS`.  If enabled, this setting retires the old `LOG_[...]` macros and redefines them to use modlog.

log/modlog: Allow LOG_[...] macros to use modlog

---

docs/os/modules/testutil/testutil.rst

This fixes #1225.
* Docs mentioned nonexistent struct `tu_config`.  This struct is now called `ts_config` and has new members.
* Docs implied that the user needs to call `tu_init`.  This function is now called automatically by `sysinit`, so remove this verbiage.
* Fix broken link to unit test tutorial.

docs: Update outdated testutil docs

---

fs/fcb/src/fcb.c
fs/fcb/src/fcb_elem_info.c
hw/bsp/native/pkg.yml
hw/bsp/native/src/hal_bsp.c
hw/bsp/nrf52dk/pkg.yml
hw/bsp/nrf52dk/src/hal_bsp.c
hw/bsp/nrf52dk/syscfg.yml
hw/drivers/flash/enc_flash/ef_nrf5x/include/ef_nrf5x/ef_nrf5x.h
hw/drivers/flash/enc_flash/ef_nrf5x/pkg.yml
hw/drivers/flash/enc_flash/ef_nrf5x/src/ef_nrf5x.c
hw/drivers/flash/enc_flash/ef_tinycrypt/include/ef_tinycrypt/ef_tinycrypt.h
hw/drivers/flash/enc_flash/ef_tinycrypt/pkg.yml
hw/drivers/flash/enc_flash/ef_tinycrypt/src/ef_tinycrypt.c
hw/drivers/flash/enc_flash/include/enc_flash/enc_flash.h
hw/drivers/flash/enc_flash/include/enc_flash/enc_flash_int.h
hw/drivers/flash/enc_flash/pkg.yml
hw/drivers/flash/enc_flash/src/enc_flash.c
hw/hal/include/hal/hal_flash.h
hw/hal/include/hal/hal_flash_int.h
hw/hal/pkg.yml
hw/hal/src/hal_flash.c
sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

This is done with a pseudo flash device, which provides hal_flash interface.
Device is split into common part, and architecture specific part. Only nrf51/nrf52 implementation is within this PR. So the current split might need adjusting when/if other platforms are added. Split is done so that you can take advantage of crypto acceleration when available.
Internally it uses AES-128 CTR mode where counter values comes from block offset.
At the moment the use cases are a bit limited; we'd need to augment hal_flash interface a bit to allow use of this device for things like FCB and image storage. Specifically, they'd need a routine with which to query the flash device whether underlying flash is empty or not.
As a example I modified one BSP to show how to set this up.

Encrypted flash

---

sys/log/full/src/log.c
sys/log/stub/include/log/log_fcb_slot1.h

sys/log/full: clear module list at startup
This allows unit tests to start from a clean state after calling sysinit().
sys/log/stub: Remove unneeded cbmem dep

Minor fixes to fix some unit tests

---

hw/mcu/nordic/nrf52xxx/src/hal_qspi.c

For now it is used for debugging purposes however later it can be used
to optimize read from flash

nrf52/qspi: Set the XIPOFFSET according to Nordic datasheet

---

hw/battery/src/battery.c

repos/apache-mynewt-core/kernel/os/include/os/os_time.h:109:59: error: 'next_poll' may be used uninitialized in this function [-Werror=maybe-uninitialized]
This is a spurious warning `next_poll` is initialized before it is used.
This warning is detected in debug build only, optimized code does not
see it as a problem.
Added initialization to disable warning.

battery: Prevent `maybe-uninitialized` warning

---

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
hw/drivers/adc/include/adc/adc.h

This PR  fixes assert() when ADC offset calibration is done with nrfx_saadc_calibrate_offset()
This PR does not provide HAL API to trigger ADC calibration (maybe it should be simple adc_offset_calibrate() ?),
however last patch adds support to send ADC_EVENT_CALIBRATED to the user when calibration is completed. 
https://github.com/apache/mynewt-core/commit/ec294361aa11bb3ea425f13f45b9404b7a7cf784
For now I just need first two patches, however open to hear comments on API for this.

adc/adc_nrf52: Handle ADC calibration done event.

---

sys/log/full/src/log_console.c

Log messages printed to the console included a misleading timestamp.  The timestamp had an "ssb" (seconds since boot) suffix.  This is wrong for two reasons:
1. units are microseconds, not seconds
2. the time isn't necessarily "since boot", it is since 1970/01/01 if the device has synced time.
This PR changes the suffix to "us".

log_console: Change timestamp suffix "ssb" -> "us"

---

hw/bsp/hifive1/syscfg.yml
hw/mcu/sifive/fe310/syscfg.yml

MCU specific peripherals definition now moved to mcu
instead of BSP.
BSP now just enables peripherals defined by MCU.

hifive: Peripheral cleanup in riscv board

---

apps/metrics/pkg.yml
apps/metrics/src/main.c
apps/metrics/syscfg.yml
sys/metrics/include/metrics/metrics.h
sys/metrics/pkg.yml
sys/metrics/src/cli.c
sys/metrics/src/metrics.c
sys/metrics/src/metrics_priv.h
sys/metrics/syscfg.yml

This is proposed framework for logging aggregated data for events.
The idea is simple: there is an event which has multiple metrics we want to log. Each metric is either a simple value (overwritten each time) or data series (appended each time). When event is (re)started each data logged from now on is aggregated internally. At the end of event its contents can be serialized using CBOR and written to mbuf for further processing or writing to logging subsystem (need to add append_mbuf API to logging for this). Now event can be restarted and this starts again.
There is no limit for number of events other than memory capacity.
There is tentative limit for number of metrics for each event (32) due to internal state variabled, but can be increased in future if necessary.
There is sample app …

[WIP] sys/metrics: Add framework for logging events data

---

hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/nrf52dk/src/hal_bsp.c
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c
hw/drivers/pwm/soft_pwm/src/soft_pwm.c
hw/mcu/nordic/nrf52xxx/src/nrf52_periph.c
kernel/os/include/os/os.h
kernel/os/include/os/util.h

Original code allocated separate `int` for each instance id. After nRF52 refactoring this was changed to single `int` created on stack but since initialization is not done immediately when device is created, this pointer is invalid when actual initialization takes place.
To avoid creating redundant global variables for each PWM instance we allow to pass instance id as simple in casted to pointer. Some helper macros were added to make this easier - such macros are already used in projects as Zephyr or BlueZ and are very convenient way to pass simple integers via user-data pointers.

Fix handling of PWM instances in nRF52 MCU/BSP

---

mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/syscfg.yml

If enabled, most of interesting errors will have "rsn" field in response
with verbose error message. This is helpful for debugging since the same
error code is returned in many different cases.

mgmt/imgmgr: Add option to enable verbose error messages

---

hw/mcu/stm/stm32l4xx/src/hal_flash.c

This removes custom error clearing code. Calls to `erase` and `program` already do pretty good error checking and clearing on both beginning/end. This code was causing flash corruption when swap
upgrades were performed with interruptions.

[STM32L4] Remove error clearing on flash driver

---

sys/coredump/src/coredump.c

Fix the size computation when region has to be split into
multiple areas.

sys/coredump; fix case where core does not fit to allocated area.

---

hw/mcu/stm/stm32_common/include/stm32_common/mcu.h
hw/mcu/stm/stm32_common/src/hal_gpio.c
hw/mcu/stm/stm32f1xx/include/mcu/mcu.h
hw/mcu/stm/stm32f3xx/include/mcu/mcu.h
hw/mcu/stm/stm32f4xx/include/mcu/mcu.h
hw/mcu/stm/stm32f7xx/include/mcu/mcu.h
hw/mcu/stm/stm32l1xx/include/mcu/mcu.h
hw/mcu/stm/stm32l4xx/include/mcu/mcu.h

All `MCU_AFIO_PORTx(...)` macros called `MCU_AFIO_GPIO` with the arguments in the wrong order. While fixing that it seemed like a good time to consolidate the duplication into a single file and include that.

Fixed stm32 AF macros and consolidated in single header file.

---

hw/bsp/nucleo-f767zi/boot-nucleo-f767zi.ld
hw/bsp/nucleo-f767zi/nucleo-f767zi.ld
hw/mcu/stm/stm32f1xx/stm32f103.ld
hw/mcu/stm/stm32f4xx/stm32f413.ld
hw/mcu/stm/stm32f7xx/stm32f746.ld
hw/mcu/stm/stm32f7xx/stm32f767.ld
hw/mcu/stm/stm32l1xx/stm32l152.ld
hw/mcu/stm/stm32l4xx/stm32l476.ld

This sets `_estack` symbol to ORIGIN + LENGTH of RAM (of DCM, DTCM, etc), allowing future reuse of linker scripts without having to fix on RAM amount changes. Also fixed the amount of RAM present in the nucleo-f767zi BSP.

Stm32 stack fixes

---

libc/baselibc/src/memcmp.c

This takes advantage of unaligned access on Cortex-M3/4/7 and compares
memory by-word instead of by-byte, if possible. Any remaining data at
the end are compared by-byte.

libc: Add optimized memcmp() for Cortex-M3/4/7

---

fs/fcb/include/fcb/fcb.h
sys/log/common/include/log_common/log_common.h
sys/log/full/include/log/log.h
sys/log/full/pkg.yml
sys/log/full/src/log.c
sys/log/full/src/log_cbmem.c
sys/log/full/src/log_fcb.c
sys/log/full/src/log_fcb_slot1.c
sys/log/full/src/log_nmgr.c
sys/log/full/src/log_shell.c
sys/log/full/syscfg.yml

This adds two new APIs to log subsystem:
- `storage_info` which allows to query log storage for total storage size and currently used storage
- `set_watermark` which allows to set watermark on log (by index) and thus mark e.g. last item read
watermark for each log is stored persistently in `config` and restored on reboot

sys/log: Add log storage usage tracking and watermarking

---

hw/drivers/uart/include/uart/uart.h
hw/drivers/uart/uart_hal/src/uart_hal.c
kernel/os/include/os/os_dev.h
kernel/os/src/os_dev.c

This is not complete, just an attempt to be able to disable UART to save some power without hacks like closing and reopening it. The whole `os_dev_suspend`/`os_dev_resume` framework needs more work since it was likely never used before so I just quickly fixed it to make this work.

Add simple PM for UART device driver

---

test/flash_test/src/flash_test/flash_test.c

Adds `<flash-id>` option to allow flash command to work on a device that is not 0 (optional on dump command).
> `flash <flash-id>` -- dumps sector map
> `flash <flash-id> read <offset> <size>` -- reads bytes from flash
> `flash <flash-id> write <offset>  <size>` -- writes incrementing data pattern 0-8 to flash
> `flash <flash-id> erase <offset> <size>` -- erases flash
This probably conflicts with https://github.com/apache/mynewt-core/pull/1324 so might wait for that one to be merged.

Add flash-id parameter to flash cli command

---

sys/config/include/config/config_generic_kv.h
sys/config/src/config_fcb.c
sys/config/src/config_store.c

This adds simple API to use config_fcb engine as generic key-value
storage without need to use config module. The main difference is that
config values need to be somehow handled by registered module thus it is
useful for pre-defined settings.
With config_fcb_kv API it is possible to read and write any key at any
time and they are immediately persisted and loaded directly from FCB so
there is no need to store them in RAM. This can be used as kind of a
scratchpad and is definitely not intended as replacement for sys/config
module.

sys/config: Add API to use FCB as generic key-value storage

---

sys/console/full/include/console/console.h
sys/console/full/src/ble_monitor_console.c
sys/console/full/src/console.c
sys/console/full/src/rtt_console.c
sys/console/full/src/uart_console.c
sys/console/minimal/include/console/console.h
sys/console/minimal/src/console.c
sys/console/minimal/src/rtt_console.c
sys/console/minimal/src/uart_console.c
sys/console/stub/include/console/console.h
util/parse/src/parse.c

- Add support for silencing output from the console
- Change parse_ull_bounds to check for range and return SYS_ERANGE error

sys/console: add support for silencing output from the console

---

sys/config/conf_mmap/include/conf_mmap/conf_mmap.h
sys/config/conf_mmap/pkg.yml
sys/config/conf_mmap/src/conf_mmap.c
sys/config/include/config/config.h
sys/config/include/config/config_fcb.h
sys/config/include/config/config_file.h
sys/config/include/config/config_store.h
sys/config/src/config_cli.c
sys/config/src/config_fcb.c
sys/config/src/config_file.c
sys/config/src/config_store.c
sys/id/include/id/id.h
sys/id/src/id.c
sys/id/syscfg.yml

sys/id; added device model/manufacturer fields under config branch id/
sys/config/conf_mmap; new package making it easy to export memory mapped structured data as config (e.g. from NRF UICR, STM32 OTP region etc.)

helpers for exporting manufacturing time data via sys/confg

---

sys/shell/src/shell.c

When trying to complete parameters for a command for which there are other
commands with the same prefix, get_command_from_module function would return the
first command with matching prefix instead of the first command that matches exactly.
For the following example, when trying to list available params for command
'set' the shell would print out parameters for command 'set-scan-opts'.
```
set-scan-opts
set
set-adv-data
set-scan-rsp
set-priv-mode
```
This patch fixes this issue by ensuring that the found command matches exactly with
the typed one.

sys/shell: Fix command parameters completion

---

kernel/os/src/os_task.c

`os_task_remove()` ensures that a task does not remove itself.  It does this by comparing the specified task's `t_taskid` member with that of the current task's.
This is not a reliable way to detect duplicate tasks.  Task IDs are not guaranteed to be unique.  If tasks are repeatedly added and removed, the `g_task_id` variable will wrap, leading to duplicate IDs.
Duplicate task IDs is a bigger problem that this PR does not address.  This PR just fixes `os_task_remove()` - it detects self-removal by comparing task addresses rather than task IDs.

kernel/os: Don't compare t_taskid

---

apps/metrics/syscfg.yml

Syscfg restriction violations detected:
Setting LOG_CLI(1) requires: SHELL_TASK
Setting history (newest -> oldest):
LOG_CLI: [@apache-mynewt-core/apps/metrics:1, @apache-mynewt-core/sys/log/full:0]
SHELL_TASK: [@apache-mynewt-core/sys/shell:0]

apps/metrics: Fix violated syscfg restriction

---

apps/loraping/syscfg.yml

Error: Settings defined by multiple packages:
LORA_MAC_TIMER_NUM: @apache-mynewt-core/apps/loraping @apache-mynewt-core/hw/drivers/lora
Error: repos/apache-mynewt-core/hw/drivers/lora/sx1276/src/sx1276.c:29:2: error: #error "Must define a Lora MAC timer number"
#error "Must define a Lora MAC timer number"
^~~~~

apps/loraping: Fix compilation issues

---

hw/mcu/native/syscfg.yml
kernel/os/src/os.c
kernel/os/syscfg.yml

Not really sure why this was hardcoded, but these values were never changed.
This should be configurable, just not sure where. I think syscfg gives us flexibility here since it can be adjusted anywhere easily, also for testing. But also it could make sense to have dedicated defines in either `mcu/mcu.h` or `bsp/bsp.h` with values which will be used in `os.c` with fallback to default values if these are not provided. In such case I think BSP makes more sense since it's easier to override if someone creates own product with own BSP.

kernel/os: Add syscfg for tickless min/max period

---

hw/bsp/native-mips/syscfg.yml
hw/bsp/native/syscfg.yml
hw/mcu/native/syscfg.yml

Settings from kernel/os cannot be overriden in MCU since both packages
have the same priority - but BSP is also good place to override it.
Priority violations detected (Packages can only override settings \
defined by packages of lower priority):
Package: @apache-mynewt-core/hw/mcu/native overriding setting: \
OS_IDLE_TICKLESS_MS_MIN defined by @apache-mynewt-core/kernel/os

hw: Move tickless idle period override from MCU to BSP

---

net/nimble/controller/pkg.yml
net/nimble/controller/test/pkg.yml
net/nimble/host/mesh/pkg.yml
net/nimble/host/pkg.yml
net/nimble/host/services/ans/pkg.yml
net/nimble/host/services/bleuart/pkg.yml
net/nimble/host/services/gap/pkg.yml
net/nimble/host/services/gatt/pkg.yml
net/nimble/host/services/ias/pkg.yml
net/nimble/host/services/lls/pkg.yml
net/nimble/host/services/tps/pkg.yml
net/nimble/host/store/config/pkg.yml
net/nimble/host/store/ram/pkg.yml
net/nimble/host/test/pkg.yml
net/nimble/host/util/pkg.yml
net/nimble/pkg.yml
net/nimble/transport/emspi/pkg.yml
net/nimble/transport/pkg.yml
net/nimble/transport/ram/pkg.yml
net/nimble/transport/socket/pkg.yml
net/nimble/transport/uart/pkg.yml

These packages shall be removed before next release, but since we now
have transient packages let's use them for now so people see warnings
and can finally switch to proper packages.
Note that this requires latest 'newt' to work properly.

net/nimble: Change packages to transient

---

kernel/os/include/os/arch/cortex_m0/os/os_arch.h
kernel/os/include/os/arch/cortex_m3/os/os_arch.h
kernel/os/include/os/arch/cortex_m4/os/os_arch.h
kernel/os/include/os/arch/cortex_m7/os/os_arch.h

If SystemView is enabled, we need a bit more stack for idle task since
replying on SystemView requests which can happen in idle task may
overflow current stack.
Max idle stack usage with SystemView was observed as 78, so 80 should be
enough.

kernel/os: Add some idle task stack for SystemView

---

apps/blecent/pkg.yml
apps/blecsc/pkg.yml
apps/blehci/pkg.yml
apps/blehr/pkg.yml
apps/blemesh/pkg.yml
apps/blemesh_light/pkg.yml
apps/blemesh_shell/pkg.yml
apps/bleprph/pkg.yml
apps/bletest/pkg.yml
apps/btshell/pkg.yml

We now have traisnent packages support in newt so let's add (re)moved
NimBLE apps as transient packages and keep them for at least one more
release. This way people still using old packages can be warned by newt
about using old packages and can update to new ones.
But eventually we need to remove all transient packages for NimBLE :)

apps: Add transient package for removed NimBLE apps

---

boot/bootutil/src/loader.c

If sector count declared in bsp is greater than boot loader
specified 120 sectors, random memory can be overwritten.
This type of error can be difficult to detect.
It is much easier to add assert to detect error condition earlier.

Boot loader: Add assert for sector count

---

hw/mcu/nordic/nrf52xxx/src/hal_uart.c

Fixes issue with missing last characters when suspending the console device.

nrf52xx uart; drain UART TX fifo when device is getting closed.

---

hw/bsp/frdm-k64f/MK64FN1M0xxx12_flash.ld
hw/bsp/frdm-k64f/boot-MK64FN1M0xxx12_flash.ld

`newt size -F/-R` use hardcoded names for FLASH and RAM sections, this commit updates frdm_k64f BSP which is currently using NXP custom names to use FLASH/RAM as well.

Rename linker sections for newt size compatibility

---

hw/sensor/syscfg.yml

It requires OIC support to be enabled so usually it needs to be anyway
manually disabled in app/target.

hw/sensor: Disable OIC sensor server by default

---

hw/drivers/bq27z561/src/bq27z561.c

Fix some build errors that happen with BQ27Z561_LOG: 1

Fix broken build when BQ27Z561_LOG: '1'

---

hw/drivers/led/lp5523/include/lp5523/lp5523.h
hw/drivers/led/lp5523/src/lp5523.c

The lp5523 should not always be reset before configuration registers are written. This adds a prereset field to the configuration block to select whether or not the reset is performed.

Make lp5523 reset optional

---

compiler/gdbmacros/mbuf.gdb
compiler/gdbmacros/os.gdb

It was not possible to call os_callouts directly, had to call os_wakeups
instead.

compiler/gdbmacros; mbuf_pool struct was updated. Reflect it here.

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/sensor/include/sensor/sensor.h

Add sensor event X_L, X_H, Y_L, Y_H, Z_L and Z_H
- Old _X_ events were restrictive since we did not get the direction out of them
- Maintain backwards compatibility for lis2ds12 by keeping old _X_ events

hw/sensors: lis2dw12: lis2dw12 breakup orientation notification events

---

fs/fcb/src/fcb_append.c

When log_walk function is called with lo_ts = -1 (read last entry)
return value is only valid before first write. It correctly reports
logs that were stored in FCB before system started.
This happens because f_active->fe_data_off is not updated during
writes and it is used for read.
This change updated fe_data_off during writes along fe_element_off.

fcb: Fix read of the last entry

---

hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f413zh/src/hal_bsp.c
hw/bsp/olimex_stm32-e407_devboard/src/hal_bsp.c
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/drivers/flash/enc_flash/src/enc_flash.c
hw/hal/include/hal/hal_flash.h
hw/hal/include/hal/hal_flash_int.h
hw/hal/src/hal_flash.c
hw/mcu/ambiq/apollo2/src/hal_flash.c
hw/mcu/microchip/pic32mx470f512h/src/hal_flash.c
hw/mcu/microchip/pic32mz2048efg100/src/hal_flash.c
hw/mcu/native/src/hal_flash.c
hw/mcu/nordic/nrf51xxx/src/hal_flash.c
hw/mcu/nordic/nrf52xxx/src/hal_flash.c
hw/mcu/nxp/MK64F12/src/hal_flash.c
hw/mcu/sifive/fe310/src/hal_flash.c
hw/mcu/stm/stm32f1xx/src/hal_flash.c
hw/mcu/stm/stm32f3xx/src/hal_flash.c
hw/mcu/stm/stm32f7xx/src/hal_flash.c
hw/mcu/stm/stm32l1xx/src/hal_flash.c
hw/mcu/stm/stm32l4xx/src/hal_flash.c
sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

This updates support for devices that are erased to zero instead of 0xff.
@mkiiskila I slightly changed the low-level interfaces you have initially written but should be 100% compatible from the user perspective.

Allow flash devices to specify erase value

---

hw/drivers/flash/at45db/src/at45db.c
hw/drivers/flash/spiflash/src/spiflash.c
hw/mcu/nordic/nrf52xxx-compat/src/hal_flash.c
hw/mcu/nordic/nrf52xxx-compat/src/hal_qspi.c
hw/mcu/nordic/nrf52xxx/src/hal_flash.c
hw/mcu/nordic/nrf52xxx/src/hal_qspi.c

This `struct hal_flash` member wasn't specified for some MCUs.  This resulted in an "erased value" of 0.  Consequently, the FCB initialization function did not view an erased sector as actually erased, so it failed the magic number test instead.

Fill in missing `hf_erased_val` for some MCUs

---

sys/log/full/pkg.yml
sys/log/full/src/log_shell.c

log/full; fix CLI crash when log entry data is larger than 127 bytes.

---

hw/mcu/nordic/nrf52xxx-compat/include/mcu/cortex_m4.h
hw/mcu/nordic/nrf52xxx-compat/src/hal_system.c
hw/mcu/nordic/nrf52xxx/include/mcu/cortex_m4.h
hw/mcu/nordic/nrf52xxx/src/hal_system.c
kernel/os/include/os/arch/cortex_m0/os/os_arch.h
kernel/os/include/os/arch/cortex_m3/os/os_arch.h
kernel/os/include/os/arch/cortex_m4/os/os_arch.h
kernel/os/include/os/arch/cortex_m7/os/os_arch.h
kernel/os/include/os/os_time.h
kernel/os/src/os_time.c

This allows conversions to be evaluated by compiler in case argument is a constant expression which results in faster code.
Note that it may increase code size a bit since all conversions where argument is not a constant expression will be inlined and not evaliated by compiler, but the difference should be negligible. For example, for `bleprph` app it's 64 bytes more.

 kernel/os: Make os_time ms<->ticks conversions static inline 

---

fs/fcb/src/fcb.c
fs/fcb/src/fcb_elem_info.c
hw/drivers/flash/enc_flash/src/enc_flash.c
hw/drivers/flash/enc_flash/test/src/testcases/enc_flash_flash_map.c
hw/drivers/flash/enc_flash/test/src/testcases/enc_flash_hal.c
hw/hal/include/hal/hal_flash.h
hw/hal/include/hal/hal_flash_int.h
hw/hal/src/hal_flash.c
mgmt/imgmgr/src/imgmgr.c
sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

sys/flash_map; flash_area_isempty_at() also returns data from the location.
Addresses issue @utzig mentioned before. Common case for checking whether flash area is empty is followed by checking what kind of data is there.

hw/hal; hal_flash_isempty() also returns data from the location.

---

sys/log/common/include/log_common/log_common.h
sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/full/test/util/include/log_test_util/log_test_util.h
sys/log/full/test/util/src/log_test.c
sys/log/full/test/util/src/testcases/log_test_case_append_cb.c
sys/log/stub/include/log/log.h

This PR augments `struct log` with an "append callback."  If a log's callback is set, it gets called each time the log is appended to.
The callback has the following type:
```
/** @typedef log_append_cb
* @brief Callback that is executed each time the corresponding log is appended
* to.
*
* @param log                   The log that was just appended to.
* @param idx                   The index of newly appended log entry.
*/
typedef void log_append_cb(struct log *log, uint32_t idx);
```

sys/log: Execute callback when log is appended to

---

fs/fcb/include/fcb/fcb.h
fs/fcb/src/fcb_area_info.c
fs/fcb/test/src/fcb_test.c
fs/fcb/test/src/testcases/fcb_test_area_info.c
sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/full/src/log_fcb.c
sys/log/full/syscfg.yml
sys/log/modlog/src/modlog.c

Adds optional statistics per-log. Stat block name comes from the name of the log.
Statistics are kept for number of log entries written, logs filtered out because of log level
settings, log entries dropped due to log collection not fetching (clearing) them on time, and errors while writing.
Note that log entries dropped from cbmem are not counted yet.

Log statistics

---

hw/hal/include/hal/hal_flash.h
hw/hal/src/hal_flash.c

This function is like `hal_flash_isempty()`, except the caller does not need to provide a buffer.  Instead, a buffer of size `MYNEWT_VAL(HAL_FLASH_VERIFY_BUF_SZ)` is allocated on the stack.

 hw/hal: hal_flash_isempty_no_buf()

---

kernel/os/pkg.yml
kernel/os/src/arch/cortex_m4/os_fault.c
kernel/os/syscfg.yml
mgmt/newtmgr/nmgr_os/src/newtmgr_os.c
sys/reboot/include/reboot/log_reboot.h
sys/reboot/src/log_reboot.c
sys/reboot/syscfg.yml

This PR introduces two changes to the reboot log.
Prior to this commit, a reboot entry contained the following information:
* reason (`rsn`)
* count (`cnt`)
* image version (`img`)
This commit adds the following:
* image hash (`hash`)
* file:line, if available
* value of PC register, if available
Prior to this PR, some crashes would result in two entries being written to the reboot log.  For example, on a failed assert, an entry gets logged with the die file and die line.  `__assert_func()` then triggers a nonmaskable interrupt in order to generate a core, which results in a second entry being written to the reboot log.
Finally, after resetting, an additional entry would often (always?) get written to the log.
This PR changes the reboot log semantics as follows:
* When the system resets …

sys/reboot: Add info to log entries and limit writes to one per boot

---

kernel/os/syscfg.yml

Enabling this setting by default created API dependencies in every app (`bootloader` and `newtmgr`).  Don't break existing code; disable this setting by default.

kernel/os: Disable OS_CRASH_LOG by default

---

kernel/os/include/os/os_time.h
kernel/os/src/os_time.c
kernel/os/syscfg.yml
kernel/os/test/src/os_test.c
kernel/os/test/src/os_test_priv.h
kernel/os/test/src/testcases/os_time_test_change.c
kernel/os/test/src/time_test.c
kernel/os/test/syscfg.yml

This PR enables the registration of time-change listeners.  When the time is set via a call to `os_settimeofday()`, all registered listeners are notified.  The following information gets passed to each listener:
```
struct os_time_change_info {
/** UTC time prior to change. */
const struct os_timeval *tci_prev_tv;
/** Time zone prior to change. */
const struct os_timezone *tci_prev_tz;
/** UTC time after change. */
const struct os_timeval *tci_cur_tv;
/** Time zone after change. */
const struct os_timezone *tci_cur_tz;
/** True if the time was not set prior to change. */
bool tci_newly_synced;
};
```
plus an optional listener-specific `void *arg`.
As indicated in the doxygen comments, the listener registration and removal functions are not thread safe.  In the typical case, I expect …

kernel/os: Registration of time-change listeners

---

kernel/os/include/os/arch/rv32imac/os/os_arch.h
kernel/os/src/arch/rv32imac/os_arch_rv32imac.c
kernel/os/src/arch/rv32imac/os_fault.c

There was conflict for os_default_irq_asm.
Function with this name had different signature from other
platforms. When common architecture functions were put in
separate header function prototype start to differ from
implementation.
os_default_irq_asm is used in other platforms as interrupt starting
address while in riscv it was used to handle plic interrupts.
Now default handler for plic interrupts is named plic_default_isr.

fe310: change default plic isr name

---

hw/util/i2cn/src/i2cn.c

gcc 7.1 when -Og is specified does not see that rc variable
is always initialized.
repos/apache-mynewt-core/hw/util/i2cn/src/i2cn.c:23:12: error: 'rc' may be used uninitialized in this function [-Werror=maybe-uninitialized]
This adds initialization. It does not impact optimized builds
since compiler detects that assigning 0 is not needed.

hw/util/i2cn: Remove false positive warning

---

hw/mcu/sifive/fe310/include/mcu/fe310_hal.h
hw/mcu/sifive/fe310/src/hal_spi.c

To avoid situation when RX data is lost due to RX FIFO overrun,
number of bytes put in the TX FIFO can not be greater than the number
of bytes read from the RX FIFO plus FIFO size (8).

fe310: Fix SPI blocking read

---

.travis.yml

This allows IGNORED_BSPS to be configured on travis.yml to automatically ignore BSPs known to fail on build. The list of BSPs is automatically loaded from the "hw/bsp" so that new BSPs are already on by default and to ignore them it is not required to change this repo (only need to add to IGNORED_BSPS in .travis.yml from mynewt-core).

Update script to get ignored BSPs from travis.yml
