apache/mynewt-core

hw/drivers/bq27z561/src/bq27z561.c
hw/drivers/bq27z561/syscfg.yml
hw/drivers/chg_ctrl/adp5061/src/adp5061.c
hw/drivers/chg_ctrl/adp5061/syscfg.yml
hw/drivers/led/lp5523/src/lp5523.c
hw/drivers/led/lp5523/syscfg.yml
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bmp280/syscfg.yml
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/syscfg.yml
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lis2dw12/syscfg.yml
hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33hw/syscfg.yml
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/drivers/sensors/lps33thw/syscfg.yml
hw/drivers/sensors/ms5837/src/ms5837.c
hw/drivers/sensors/ms5837/syscfg.yml
hw/drivers/sensors/ms5840/src/ms5840.c
hw/drivers/sensors/ms5840/syscfg.yml

Most I2C devices will respond in well under 1ms but currently the timeout in most drivers is specified as OS_TICKS_PER_SEC/10. This causes undue latency in recovering from I2C errors. This change adds syscfg to some drivers to specify a smaller I2C timeout of 3 OS ticks. 
Also changes BQ27Z561_LOG default value to 1, since the original default value of 0 can cause I2C errors on the device to go unnoticed.

Reduce I2C timeout values to reduce system latency when failures take place

---

hw/mcu/nordic/nrf52xxx-compat/src/nrfx_saadc_mod.c
hw/mcu/nordic/nrf52xxx/src/nrfx_saadc_mod.c
hw/mcu/nordic/pkg.yml
hw/mcu/nordic/src/ext/nrfx/drivers/src/nrfx_saadc.c

The current nordic SDK does not allow the enabling/disabling of a SAADC channel with calling nrfx_channel_init() and nrfx_channel_uninit(). This means that to enable/disable a channel you need to reconfigure the channel each time. These helper functions allow one to configure a SAADC channel and leave it with the configuration if it does not need to be reconfigured (which is probably a more common case).
Note that this modification was only done for any project that sets the  BSP_NRF52 syscfg value. This might be somewhat arbitrary and we might consider doing this for all NRF52 related BSP's (52840, for example).

Add enable/disable SAADC channel to nordic SDK

---

hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/src/lps33thw.c

Fixes bug in lps33hw and lps33thw driver where last_op was set to 1 in i2c write function call.

Bug fix in lps33hw/thw

---

hw/drivers/flash/enc_flash/src/enc_flash.c
sys/flash_map/src/flash_map.c

- Update flash_area_is_empty to use the new hal_flash_isempty_no_buf call
- When enc_flash is testing for an empty flash, now it checks that the lower-level driver returned an empty flash already and avoids reading data that when it is known to be empty.

Fix double read on enc_flash driver

---

hw/battery/include/battery/battery.h
hw/battery/include/battery/battery_prop.h
hw/battery/src/battery.c

With these changes battery manager will only poll battery properties which at lest one listener is subscribed for. This can reduce polling time significantly (depends on number of subscribed properties).

hw/battery: Make property polling more robust

---

kernel/os/include/os/arch/common.h
kernel/os/include/os/arch/cortex_m0/os/os_arch.h
kernel/os/include/os/arch/cortex_m3/os/os_arch.h
kernel/os/include/os/arch/cortex_m4/os/os_arch.h
kernel/os/include/os/arch/cortex_m7/os/os_arch.h
kernel/os/include/os/arch/mips/os/os_arch.h
kernel/os/include/os/arch/pic32/os/os_arch.h
kernel/os/src/arch/mips/os_arch_mips.c
kernel/os/src/arch/pic32/os_arch_pic32.c

Added implementation for Cortex-M.
MIPS and PIC32 already had local implementation so just moved this to public header.
RISC-V is missing.

kernel/os: Add os_arch_in_isr() API

---

.travis.yml

The gcc-multilib was bringing in full gcc-4.8 (including g++-4.8), so remove it and add kernel headers dep manually.
Also removed `gcc-7-multlib` from ARM target tests.

Remove gcc-multilib dependency

---

sys/console/full/src/rtt_console.c
sys/console/full/syscfg.yml

This fixes 2 problems with RTT console:
1. output data may be corrupted
2. output data may be skipped when writing lots of data at once to RTT
1st problem is because we write data using function which can overwrite existing data in buffer - this should not be used when host is reading data since both sides may modify write pointer without sync (thus data corruption). To resolve this we use proper function which skips data instead of overwriting - this is safe.
2nd problem is because we can write data to RTT quickly, but host reads data by polling periodically thus it may not start reading data when we fill buffer. To solve this we will now wait a bit when buffer is full and retry which gives host some time to start reading data. Retry number and delay is configurable. Also we will not …

RTT console fixes

---

.travis.yml

Add homebrew package caching and only check for ARM tooling on machines that run ARM builds (must be merged before https://github.com/runtimeco/mynewt-travis-ci/pull/10)

Travis cache homebrew

---

libc/baselibc/src/tinyprintf.c

This adds support for field width passed as a parameter, e.g.: `printf("%0*d", width, value);`

tinyprintf: Add support for parametrized field width

---

sys/metrics/src/metrics.c

`metrics_event_to_cbor()` frees the provided mbuf on failure.  Therefore, callers of this function must not free the mbuf a second time.

sys/metrics: Fix mbuf double free

---

hw/drivers/sensors/adxl345/src/adxl345.c
hw/drivers/sensors/adxl345/src/adxl345_shell.c
hw/drivers/sensors/adxl345/syscfg.yml
hw/sensor/creator/src/sensor_creator.c

couple of issues were detected when accelerometer was added to project
- compile error in adxl345.c (due to log_register call that should be removed)
- compile error in sensor creator due to missing function end
- alternative address can be selected for accelerometer in syscfg
- shell dump command had some mismatched prints
- shell dump command was reading registers in assert call that could be compiled out and prints would display garbage

adxl345 accelerometer fixes

---

hw/drivers/flash/spiflash/chips/pkg.yml
hw/drivers/flash/spiflash/chips/syscfg.yml
hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c
hw/drivers/flash/spiflash/syscfg.yml

SpiFlash chips are often compatible to some extent even
when they come from different vendors.
It is quite possible to have same product that will use
different spiflash even in production.
Now it is possible to specify more than one flash chip.

spiflash: Add support for multiple chips

---

hw/scripts/common.sh
hw/scripts/jlink.sh
hw/scripts/openocd.sh

This contains cherry-picked change from https://github.com/apache/mynewt-core/pull/1401. Here it is extended to be used also for 'newt debug' with Jlink, as well as use with openocd.

allow user to override TCP port gdb and jtag emulator use to communicate

---

libc/baselibc/src/tinyprintf.c

Need to make sure speficied field width is within uchar range, otherwise
this may have unpredictable results.

tinyprintf: Limit allowed values for variable field length

---

compiler/arm-none-eabi-m0/compiler.yml
compiler/arm-none-eabi-m3/compiler.yml
compiler/arm-none-eabi-m4/compiler.yml
compiler/arm-none-eabi-m7/compiler.yml
hw/drivers/rtt/pkg.yml
sys/sysview/pkg.yml
sys/sysview/vendor/pkg.yml

This adds new build profile called `speed` [1] (to ARM compilers for now) which basically enables `-O3` and also changes RTT and SystemView packages to always use this profile since we want this code to run as fast as possible (so it has minimal impact on normal system operation).
[1] I don't have any better name for this...

Add speed-optimized build profile

---

net/oic/include/oic/port/mynewt/ble.h
net/oic/src/port/mynewt/ble_adaptor.c

Add a function to determine if the provided OIC endpoint is the GATT (BLE) endpoint.  This is an analogue of the existing `oc_endpoint_is_ip` function.
This function is useful for oc_sec_recv callbacks; to inspect an endpoint's details, the callback must first determine the type of endpoint being used.

net/oic: Function to determine if endpoint is GATT

---

hw/mcu/sifive/fe310/src/arch/rv32imac/start.s
hw/mcu/sifive/fe310/src/init.c

fe310 bsp had function called _init that was used during startup.
Recent rename of __libc_init_array to _init resulted in
multiple definition.
bsp function was just renamed to SystemInit that is commonly used
in other platforms.

fe310 fix build

---

apps/slinky_oic/syscfg.yml

`OS_MAIN_STACK_SIZE` was being overridden with the value 512.  This is too small to support the `image upload` command when encoded with CoAP; a stack overflow would result.

apps/slinky_oic: Enlarge main stack (512->1024)

---

kernel/os/include/os/os_fault.h
kernel/os/syscfg.yml
libc/baselibc/include/assert.h
libc/baselibc/syscfg.yml
sys/sys/include/sys/debug_panic.h
sys/sys/syscfg.yml

The `DEBUG_PANIC()` macro triggers a crash if the `DEBUG_PANIC_ENABLED` syscfg setting is enabled.  If this setting is disabled, the macro expands to nothing.
This feature is discussed briefly here: https://lists.apache.org/thread.html/0ce981b90eb74226fd660f25ba88f4ce6804eea2943edac70bf8731e@%3Cdev.mynewt.apache.org%3E

sys/sys: Add `DEBUG_PANIC()` macro

---

kernel/os/include/os/mynewt.h
kernel/os/include/os/os.h
kernel/os/src/os.c
mgmt/newtmgr/nmgr_os/src/newtmgr_os.c
sys/shell/src/shell_os.c
sys/sysdown/include/sysdown/sysdown.h
sys/sysdown/pkg.yml
sys/sysdown/src/sysdown.c
sys/sysdown/syscfg.yml

NOTE: This commit requires a newt tool update (a38614ebc22959231ad9597c24467e34ed0e5068).
Upon application-triggered restart, execute each package's shutdown subprocedure.  This feature is discussed here:
https://lists.apache.org/thread.html/ebd53c9b56230184650ea57e5534d5bcfbfc170b97547a1a26f100b5@%3Cdev.mynewt.apache.org%3E

Use generated sysdown() function

---

compiler/arc/compiler.yml
compiler/arm-none-eabi-m0/compiler.yml
compiler/arm-none-eabi-m3/compiler.yml
compiler/arm-none-eabi-m4/compiler.yml
compiler/arm-none-eabi-m7/compiler.yml
compiler/mips/compiler.yml
compiler/riscv64/compiler.yml
compiler/sim-mips/compiler.yml
compiler/xc32/compiler.yml
test/runtest/src/runtest.c

Overly long segments (test case name, suite name, and message) were not being null-terminated.  This caused malformed JSON to be included in the log.

test/runtest: Null-terminate segments of log entry

---

kernel/os/include/os/mynewt.h

This PR is submitted in the context of https://github.com/apache/mynewt-newt/pull/221.  This PR does not require the newt PR, but it is not useful without it.
Modify `mynewt.h` to take advantage of the new logcfg newt feature.  Now, `mynewt.h` includes the generated logcfg header.

mynewt.h: Include generated `logcfg/logcfg.h` file

---

kernel/os/src/os_mempool.c

Hi,
I think that there is an issue with the assignment of the "g_os_mempool_list.stqh_last" member into the "os_mempool_unregister" function.
According to me, the pointed contents is modified instead of the pointer itself (like it is done with the "STAILQ_REMOVE" macro).
What do you think ?

Invalid g_os_mempool_list.stqh_last assignment

---

hw/mcu/native/src/hal_flash.c

When the user does not specify a flash filename, sim uses one of these temporary files.  In this case, unlink the file immediately after opening it.  This prevents the user's `/tmp` directory from filling up
with these files.

sim: Unlink temporary `native_flash.XXXXXX` files

---

hw/drivers/chg_ctrl/adp5061/src/adp5061_shell.c
hw/drivers/chg_ctrl/adp5061/syscfg.yml

Shell command dump can decode bit fields of all the registers.
This functionality can be quite useful but it uses a lot of flash
for all decoded filed values (strings).
This patch make decode functionality optional (disabled by default).
It reduced flash usage for ADP5061 driver with CLI from 10KB to 4KB.

adp5061: Make decode functionality optional

---

kernel/os/src/os_callout.c

It is an error to reset a callout prior to initializing it, as it has no event queue to post to on expiry.  This commit asserts that a callout has been initialized before it is reset (if `OS_DEBUG` is enabled).

 kernel/os: If OS_DEBUG, ensure callouts initialized

---

hw/mcu/sifive/fe310/src/arch/rv32imac/start.s
hw/mcu/sifive/fe310/src/init.c

fe310 bsp had function called _init that was used during startup.
Recent rename of __libc_init_array to _init resulted in
multiple definition.
bsp function was just renamed to SystemInit that is commonly used
in other platforms.

fe310: Fix build after _init was added

---

hw/battery/src/battery.c
hw/battery/src/battery_shell.c

These are just some assorted `hw/battery` fixes.  The main change is:
*hw/battery: Don't open battery device during init*
**Prior to commit:** The battery shell opened the battery device at init time.  If the open failed, a sysinit panic was triggered.
**After commit:** The battery shell opens the battery device as needed, per command.  If the open fails, the command fails with a `SYS_ENODEV` error.
**Rationale:** A hardware fault may render the battery device inoperable.  It is better for the application to decide how to handle this condition rather than the shell triggering a crash.
```

Misc. battery fixes

---

hw/drivers/flash/enc_flash/test/src/testcases/enc_flash_hal.c
hw/hal/include/hal/hal_flash.h
hw/hal/src/hal_flash.c

In certain cases (i.e. low voltage) it may be wise to prevent
writes to flash since it may result in flash corruption.
New function hal_flash_write_protect() allows to block/unblock writes
to flash.
@InternetofAwesome please take a look if that is what you had in mind

Hal flash write protection

---

kernel/os/include/os/os_dev.h
kernel/os/src/os_dev.c

Device name is not modified anywhere so can be const.

kernel/os: Add missing const to parameters in os_dev

---

crypto/mbedtls/include/mbedtls/gcm.h
crypto/mbedtls/src/gcm.c

mbedtls; add mbedtls_gcm_setkey_noalloc(), which allows use of GCM

---

net/oic/src/api/oc_ri.c
net/oic/src/port/mynewt/ble_adaptor.c

1. Remove registered observers when BLE connection closes. This can lead to observe requests to start failing.
2. Was cancelling timer for periodic notifications for resource when observer cancels with a get request.

oic; observer bug fixes

---

kernel/os/include/os/util.h

This is a convenience macro to calculate original pointer of "parent"
object using a pointer to one of its members. It's commonly used in
e.g. Linux kernel and Zephyr Project so it should be also useful in
Mynewt :)
For example, with following structure:
```
struct foo {
int a;
struct bar bar;
int c;
}
```
Let's assume we have:
```
struct foo g_foo;
struct bar *x = &g_foo.bar;
```
And we can use `CONTAINER_OF` to calculate pointer to `g_foo` using `x`:
```
struct foo *foo = CONTAINER_OF(x, struct foo, bar);
```

kernel/os: Add helper CONTAINER_OF macro

---

hw/scripts/common.sh

Pointed out by saul at cionic.com.

hw/scripts; was using bash syntax when filtering EXTRA_JTAG_CMD.

---

fs/fcb2/README.md
fs/fcb2/include/fcb/fcb.h
fs/fcb2/pkg.yml
fs/fcb2/src/fcb.c
fs/fcb2/src/fcb_append.c
fs/fcb2/src/fcb_area_info.c
fs/fcb2/src/fcb_elem_info.c
fs/fcb2/src/fcb_getnext.c
fs/fcb2/src/fcb_priv.h
fs/fcb2/src/fcb_rotate.c
fs/fcb2/src/fcb_walk.c
fs/fcb2/test/pkg.yml
fs/fcb2/test/src/fcb_test.c
fs/fcb2/test/src/fcb_test.h
fs/fcb2/test/src/testcases/fcb_test_append.c
fs/fcb2/test/src/testcases/fcb_test_append_fill.c
fs/fcb2/test/src/testcases/fcb_test_append_too_big.c
fs/fcb2/test/src/testcases/fcb_test_area_info.c
fs/fcb2/test/src/testcases/fcb_test_empty_walk.c
fs/fcb2/test/src/testcases/fcb_test_init.c
fs/fcb2/test/src/testcases/fcb_test_last_of_n.c
fs/fcb2/test/src/testcases/fcb_test_multiple_scratch.c
fs/fcb2/test/src/testcases/fcb_test_reset.c
fs/fcb2/test/src/testcases/fcb_test_rotate.c
sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

This fcb has smaller RAM footprint (no table describing all sector)
It is more failure resistant.
It adds fcb_read and fcb_write functions that detach
user from underlying flash access functions.

fcb2: second generation of fcb

---

sys/fault/fault_cli/pkg.yml
sys/fault/fault_cli/src/fault_cli.c
sys/fault/fault_cli/syscfg.yml
sys/fault/include/fault/fault.h
sys/fault/pkg.yml
sys/fault/src/fault.c
sys/fault/src/fault_conf.c
sys/fault/src/fault_priv.h
sys/fault/syscfg.yml
sys/sys/include/sys/debug_panic.h

This package is intended to handle unexpected runtime failures (e.g., hardware failures, heap allocation failures, etc).  An application might handle such failures with any of the following actions:
* Log the failure
* Retry the failed operation
* Attempt to recover with a system reboot
* Disable the failing module entirely
Which action(s) the application takes might depend on how much, and how chronically, the operation has failed.
For a more complete description of this package, please see the comments at the top of `sys/fault/include/fault.h`.

sys/fault: Global fault management

---

net/lora/node/src/lora_node.c

LoRaMac node crashed on calling a callback whose adress was taken
from the stack and was random, as the structure passed to LoRaMac
was a local variable from the calling function. This sitiuation
occured each time the device processed the DevStatusReq MAC
command.

net/lora/node/src/lora_node.c: crash fix

---

hw/mcu/nordic/nrf51xxx/include/mcu/nrf51_clock.h
hw/mcu/nordic/nrf51xxx/src/nrf51_clock.c
hw/mcu/nordic/nrf52xxx-compat/include/mcu/nrf52_clock.h
hw/mcu/nordic/nrf52xxx-compat/src/nrf52_clock.c
hw/mcu/nordic/nrf52xxx/include/mcu/nrf52_clock.h
hw/mcu/nordic/nrf52xxx/src/nrf52_clock.c

This commit adds API so that an application can request the
hfxo and release it. Requesting the hfxo will turn on the hfxo
if it is not already on. Releasing the hfxo will turn it off if
it is not already off. The implementation includes a one byte
reference counter. Each request must have a corresponding release
or the hfxo will always be on. A release without a request is
an error. Note that the API does not wait for any crystal
settling time nor does it check to see if the hfxo actually
turned on.

hw/mcu/nordic: Add hfxo request/release API

---

hw/scripts/common.sh

and the target uses openocd, PORT was extracted incorrectly.
E.g
```
newt target show blinky_stm32f3
targets/blinky_stm32f3
app=apps/blinky
bsp=@apache-mynewt-core/hw/bsp/stm32f3discovery
build_profile=debug
```
And then:
```
newt debug blinky_stm32f3 --extrajtagcmd="-port 3334"
```

hw/scripts; if port was passed as last parameter in --extrajtagcmd,

---

sys/stats/full/include/stats/stats.h
sys/stats/full/pkg.yml
sys/stats/full/src/stats.c
sys/stats/full/src/stats_conf.c
sys/stats/full/src/stats_persist.c
sys/stats/full/src/stats_priv.h
sys/stats/full/syscfg.yml

Persistent stat functionality can be enabled with the `STATS_PERSIST`
syscfg setting.  This feature is described in more detail here:
https://ponymail-vm.apache.org/_GUI_/thread.html/d14032985bc959af468f1f0300b725fb15a8a17df8c2f171c25b469c@%3Cdev.mynewt.apache.org%3E
A persistent stat group is defined using the `STATS_PERSISTED_SECT_START` macro.
A persistent stat group is registered using the `stats_persist_init()` function.
A few questionable decisions in this PR:
1. The `STATS_INC()` macros sacrifice some efficiency to ensure correctness.  Every increment includes a check against the stat group's `STAT_HDR_F_PERSISTED` flag to see if the group's flush timer needs to be scheduled.  If the user knows a stat is non-persistent, he can use `STATS_INC_RAW()` instead, which is as efficient as …

sys/stats/full: Persistent stats

---

hw/mcu/nordic/nrf51xxx/src/nrf51_clock.c
hw/mcu/nordic/nrf52xxx/src/nrf52_clock.c
kernel/os/include/os/os_fault.h
libc/baselibc/include/assert.h

os_trace_api.h uses local #defined symbols from .c file to determine
whether traces should be enabled for given file or not. In order for
this to work properly it has to be included only after such symbols
are #defined.
However, assert.h includes os/mynewt.h and the nasty side-effect is
that we have os_everything included by including one of std library
includes.
Let's assert.h just include os_fault.h instead as this should not have
any side-effects.

kernel/os: Fix os_trace APIs

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

This seems to be done by mistake in some earlier commit, but we should
not put stop condition on bus after every write - only if we were asked
to (or in case of error).

hw/mcu/nordic: Fix stop on I2C write

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c

If several task would try to use spiflash at the same time they
could get wrong result and even deadlock waiting for some SPI
state that would not happen.
Adding mutex to most of the functions makes spiflash usable from
multiple tasks.
For boot loader sake spiflash can be built without locking.

spiflash: Make spiflash thread safe

---

hw/mcu/nordic/nrf52xxx-compat/syscfg.yml
hw/mcu/nordic/nrf52xxx/src/hal_qspi.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

I found this issue while trying to "emulate" a 8KB sector sized device on the QSPI flash (`QSPI_FLASH_SECTOR_SIZE: 8192`). While mcuboot was able to swap the images, the resulting image in slot1 is corrupted because not all sectors were erased. The current implementation seems to work by coincidence because the 2 LSb of 4096 are zero!

Fix nrf52 qspi erase

---

hw/battery/include/battery/battery_drv.h
hw/charge-control/include/charge-control/charge_control.h
hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/src/bq27z561.c
hw/drivers/chg_ctrl/adp5061/include/adp5061/adp5061.h
hw/drivers/chg_ctrl/adp5061/src/adp5061.c
hw/drivers/led/include/led/led_itf.h
hw/drivers/led/lp5523/include/lp5523/lp5523.h
hw/drivers/led/lp5523/src/lp5523.c
hw/drivers/sensors/bma253/include/bma253/bma253.h
hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bmp280/include/bmp280/bmp280.h
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lps33hw/include/lps33hw/lps33hw.h
hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/include/lps33thw/lps33thw.h
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/drivers/sensors/ms5837/include/ms5837/ms5837.h
hw/drivers/sensors/ms5837/src/ms5837.c
hw/drivers/sensors/ms5840/include/ms5840/ms5840.h
hw/drivers/sensors/ms5840/src/ms5840.c
hw/sensor/include/sensor/sensor.h

This updates some of drivers to support new bus driver. Old code is still there and thus they can still work just fine without bus driver - the proper way to access bus is selected automatically in build time depending if bus driver is included or not.
Each driver have now helper function to quickly create bus node so there's no need to figure out how to call `os_dev_create` properly - just use helper instead.
Modified drivers seem to work fine, however I was not able to check each and every single functionality there - just ran this on few existing device with sensors I have here and they all work fine.

hw/drivers: Add bus driver support to some of existing drivers

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

Current workaround for unresponsive TWI will be triggered every time
there is operation timeout which has some drawbacks: it will be
applied to every operation that times out, it takes entire operation
time to recover and it will make operation fail so caller needs to
retry.
It is possible to detect this condition and apply workaround quicker
without making operation fail by using simple hack: after triggering
START task SCL line should be pulled low to make START condition and
also when address is written. We can just wait a moment to see if SCL
is pulled low during this time - if not, restart controller and try
again.
This seems to work fine with LP5523 on the bus which can be used to
easily trigger this condition by sending reset command.

hw/mcu/nordic: Rework workaround for unresponsive TWI

---

hw/drivers/chg_ctrl/adp5061/include/adp5061/adp5061.h
hw/drivers/chg_ctrl/adp5061/pkg.yml
hw/drivers/chg_ctrl/adp5061/src/adp5061.c
hw/drivers/chg_ctrl/adp5061/syscfg.yml

This change allows to disable all code related charge_control.
It will be possible to used ADP5061 API with alternative
charging manager, possibly reducing code size of application.

adp5061: Make charge_control dependency optional

---

hw/drivers/flash/spiflash/src/spiflash.c

Nordic hal requrires SPI to be disabled before hal_spi_config() is called.
hal_spi_disable() is called just before hal_spi_config() to satisfy this.

hw/drivers: Fix spiflash initialization function

---

hw/bsp/hifive1/bsp.yml

Order of linker script entries in bsp.yml result in warning that is
visible during build only when some other link error happens.
repos/apache-mynewt-core/hw/bsp/hifive1/hifive1.ld:32: warning: memory region `flash' not declared
repos/apache-mynewt-core/hw/bsp/hifive1/hifive1.ld:131: warning: memory region `ram' not declared
repos/apache-mynewt-core/hw/bsp/hifive1/hifive1_boot.ld:22: warning: redeclaration of memory region `flash'
repos/apache-mynewt-core/hw/bsp/hifive1/hifive1_boot.ld:23: warning: redeclaration of memory region `ram'
Changing order of entries in bsp fixes this.

bsp/hifive1: Fix linker warning

---

hw/battery/include/battery/battery.h
hw/battery/src/battery.c

Adding an extra parameter to potentially delay the first event.

Battery - Optional Start Delay

---

.rat-excludes
hw/bsp/nordic_pca10040/bsp.yml
hw/bsp/nordic_pca10040/syscfg.yml
hw/mcu/nordic/nrf52xxx/nrf52_ram_resident.ld

instead of flash. Show a sample on how to use this with one BSP.

nrf52; create a linker script for compiling apps which are loaded to RAM,

---

hw/battery/src/battery.c

Added a millisecond to tick conversion before calling os_callout_reset(). This now matches the API comment mentioned in battery.h.

Convert Ticks to Millisecond In Battery Polling

---

hw/drivers/sensors/bme280/src/bme280.c

Code was using undefined macro to access field.

hw/drivers/bme280: Fix build errors

---

sys/id/src/id.c
sys/id/syscfg.yml

NOTE: This PR requires a newt PR to be merged first: https://github.com/apache/mynewt-newt/pull/250.  This PR won't break anything for older newt versions, but the feature won't work.
If the `ID_TARGET_PRESENT` syscfg setting is enabled, the target name is readable through the `id/target` config setting.
This feature requires a recent version of newt (prior versions did not inject the target name into the syscfg).  If an old version of newt is used in a build where `ID_TARGET_PRESENT` is enabled, the build will fail with a syscfg restriction violation error.

Export `id/target` setting if configured

---

sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

Prior to this PR, `flash_area_close()` was a function with an emptybody.
To save code space in the boot loader, remove this function, and define it as an empty macro instead.  If `flash_area_close()` ever needs to perform a task, the macro can be removed and the function re-implemented.
In my setup, this reduced the size of the boot loader from 16028 to 15876.

Redefine `flash_area_close()` as an empty macro

---

hw/drivers/sensors/bme280/pkg.yml
hw/drivers/sensors/bme280/src/bme280.c
hw/drivers/sensors/bme280/syscfg.yml
hw/drivers/sensors/bmp280/include/bmp280/bmp280.h
hw/drivers/sensors/bmp280/pkg.yml
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bmp280/syscfg.yml

There were couple of issues in bme280 and bmp280 drivers:
- unneeded difference of return value of temperature and pressure between different compilation variants
- unclear syscfg description
- incorrect constant was used to check for invalid value of temperature and pressure
- computation of pressure and humidity could be incorrect if temperature was not requested by the user of was read at very slow rate

fix bmp280 bme280 issues

---

sys/fault/src/fault.c
sys/flash_map/src/flash_map.c

If no flash areas were found in the MMR, keep using the hardcoded flash map instead of an empty one.

sys/flash_map: Don't replace default flash map with empty flash map

---

hw/drivers/sensors/lps33thw/src/lps33thw_shell.c

Broken by another build fix (4a82c33c) so fixing again. Now it should build fine with and without bus driver...
This fixes https://github.com/apache/mynewt-core/issues/1569

hw/drivers/lps33thw: Fix CLI build

---

hw/drivers/bq27z561/src/bq27z561.c

Code generated with this small change does not use double precision anymore that can benefit platforms that have single precision FPUs only.

hw/drivers/bq27z561: Remove double precision constant

---

hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/src/lps33thw.c

- single precision constant remove need for double precision calculations
- manual sign extension of int constructed from bytes is not needed

lps33[t]hw performance improvements

---

sys/fault/src/fault.c
sys/fault/src/fault_stub.c
sys/fault/syscfg.yml

This commit adds a new syscfg setting: FAULT_STUB.  When enabled, all fault functions are turned into no ops.  This is useful for unit testing or other similar applications when system-wide fault management is not wanted.

sys/fault: Stub implementation

---

hw/scripts/common.sh
hw/scripts/stlink.sh

The default behaviour for st-util is to reset the target on startup, which should only be done when RESET shell variable is set.

Avoid resetting target when debugging with st-util

---

hw/bsp/nucleo-l476rg/nucleo-l476rg_debug.sh
hw/bsp/nucleo-l476rg/nucleo-l476rg_download.sh

As reported previously, openocd 0.10.0 and git master have changed the script name about one year ago which forces users to have to edit the configuration files according to the openocd version they have
installed. This switches to more friendly st-link based tooling which has more regular releases and does auto-detect the stm32 line MCU in use.

Use stlink tooling for stm32l4

---

hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/drivers/sensors/ms5840/src/ms5840.c
hw/util/i2cn/include/i2cn/i2cn.h
hw/util/i2cn/src/i2cn.c

New `i2cn_master_write_read_transact` should be used for reading from common sensors instead of separate write and read as it guarantees that in case of read failure write will be done before retrying. Without retry, it may happen that after writing register address, read fails after some bytes are already left and register pointer inside sensor already moved to new location. Reading again, without write, would then result in invalid registers being read.
Note: there are few more sensors to fix, I'll try to update soon

hw/util/i2cn: Add write-read transaction support

---

hw/bus/drivers/i2c_nrf52_twim/include/bus/drivers/i2c_nrf52_twim.h
hw/bus/drivers/i2c_nrf52_twim/pkg.yml
hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c
hw/bus/drivers/i2c_nrf52_twim/syscfg.yml
hw/mcu/nordic/nrf52xxx/pkg.yml
hw/mcu/nordic/nrf52xxx/src/nrf52_periph.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

This adds optimized I2C bus driver which can be used with nRF52xxx MCUs instead of default `i2c_hal` driver.
The difference here is that it uses TWIM instead of TWI which means it uses DMA for transfer in the background and is synchronized by semaphore instead of using busy loops. This allows other tasks to execute while transfer is ongoing.
Driver can be automatically enabled with new syscfg in MCU package:
`MCU_BUS_DRIVER_I2C_USE_TWIM: 1`
The only limitation here compared to `i2c_hal` driver is that it's not possible to make a read operation with `NOSTOP` flag. This is due to missing shortcut in TWIM peripheral to trigger `TASK_SUSPEND` on `EVENT_LASTRX`. It would be possible to workaround this with PPI, however I do not think read with NOSTOP is really that useful - `i2c_hal` does …

hw/bus: Add I2C bus driver for nRF52xxx TWIM (DMA)

---

sys/log/full/include/log/log.h
sys/log/full/src/log.c

Changing log level at runtime for specific logger could be
useful for blocking logs that normally would go to the console
while newtmgr over serial port is used.
Ideally function names should be log_level_set/get but those
are already taken by modlog related code.

log: Add functions for log level manipulation

---

boot/boot_serial/test/pkg.yml
boot/bootutil/test/pkg.yml
crypto/mbedtls/test/pkg.yml
encoding/base64/test/pkg.yml
encoding/cborattr/test/pkg.yml
encoding/json/test/pkg.yml
fs/fcb/test/pkg.yml
fs/fcb2/test/pkg.yml
hw/drivers/flash/enc_flash/test/pkg.yml
net/ip/mn_socket/test/pkg.yml
sys/config/test-fcb/pkg.yml
sys/flash_map/test/pkg.yml
util/cbmem/test/pkg.yml
util/debounce/test/pkg.yml
util/rwlock/test/pkg.yml

A recent change caused `sys/mfg` to depend on `sys/log/modlog`.  This introduces a LOG API requirement on several other packages, causing some self tests to fail to build.
This commit adds dependencies on `sys/log/stub` to several self tests.

Add stub log dependency to self tests

---

hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c

Adding #include "stats/stats.h" to i2c_nrf52_twim.c. I encountered a build error with I2C_NRF52_TWIM_STAT: 1. I'm using arm-none-eabi-gcc v7.2.1.

Add missing include to fix build error with I2C_NRF52_TWIM_STAT: 1

---

apps/boot/pkg.yml

A recent commit (`b10cbea5ef882e7f91d1c34ffcf2506d3e183003`) imposes the `LOG` API requirement on the `sys/mfg` package. To fix broken builds, make the boot app depend on `sys/log/stub`.

apps/boot: Add `sys/log/stub` dependency

---

sys/fault/src/fault.c

sys/fault: Only crash when in error state
This change only affects debug builds (when `DEBUG_PANIC_ENABLED` is set).
Prior to this change, (when debug mode is used) a crash was triggered whenever the a fault recorder changed state.  There are three fault states:
* GOOD
* WARN
* ERROR
Typically, an application is configured to log a message when a recorder enters the WARN state, and to reboot the system upon entering the ERROR state.  However, in debug mode, the device would crash as soon as the WARN state was entered.
After commit: debug builds only crash when the ERROR state is entered.  The WARN state behaves the same in debug and non-debug builds.

sys/fault: Only crash when in error state

---

hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c
hw/drivers/sensors/lis2dw12/src/lis2dw12_shell.c
hw/drivers/sensors/tcs34725/src/tcs34725_shell.c

Three sensor had code inside assert macro that could be removed while code was expected to be executed always.
tcs34725 would not compile for obvious reason and this is fixed now.

few sensor fixes

---

boot/bootutil/src/image_ec256.c

While loading a new EC point, when it was smaller than the expected number of bytes, a zero padding was being written beyond the end of the buffer instead of at the initial position.

Fix a buffer overflow on EC point load

---

hw/mcu/stm/stm32_common/src/hal_nvreg.c

The STM32L4xx family has 32 32-bit RTC backup registers.
These can be used to store data that persists after a system reset.
Tested on the STM32L432KC.

Adding hal_nvreg.c for STM32L4xx devices.

---

hw/mcu/stm/stm32l4xx/src/hal_flash.c

Some parts in the STM32L4xx family do not have a FLASH_BANK_2.
(The STM32L432 for example)
This results in a compile error. Added #define to prevent this.

Only erase FLASH_BANK_2 when available

---

hw/bus/drivers/i2c_nrf52_twim/pkg.yml
hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c
hw/bus/drivers/i2c_nrf52_twim/syscfg.yml

i2c_nrf52_twim: add dependency to stats. Turn off statistics by

---

kernel/os/include/os/os_mutex.h
sys/console/full/include/console/console.h
sys/console/full/src/console.c
sys/console/full/src/rtt_console.c
sys/console/full/src/uart_console.c
sys/console/full/syscfg.yml
sys/console/minimal/include/console/console.h
sys/console/minimal/src/console.c
sys/console/minimal/syscfg.yml
sys/console/stub/include/console/console.h
sys/shell/src/shell_nlip.c

When newtmgr is used over serial port it is easy to have errors when some task prints on serial console during newtmgr communication (for example during coredump download).
It happens due to lack of locks in console code.
This PR adds locking functionality to console and updates shell_nlip to actually lock console during packet transmission.
Without this locking transmitted packets byte could interleave with logs and that would lead to communication failure.

console newtmgr coexistance

---

kernel/os/include/os/arch/common.h
kernel/os/include/os/arch/rv32imac/os/os_arch.h
kernel/os/include/os/arch/sim-armv7/os/os_arch.h
kernel/os/include/os/arch/sim-mips/os/os_arch.h
kernel/os/include/os/arch/sim/os/os_arch.h

Sim build, unlike other architectures, had only prototype for
os_arch_in_isr while other architectures have static inline version
of this function.
Once function was started to be used in some code sim build stared to
fail since there is no actual non-static-inline implementation anywhere.
Now sim also have this function present as static inline returning always 0.

kernel/os: Move os_arch_in_isr() for sim to arch

---

hw/bus/include/bus/bus.h
hw/bus/include/bus/bus_driver.h
hw/bus/src/bus.c
hw/bus/syscfg.yml
kernel/os/include/os/os_mutex.h

This adds some power management capabilities to bus devices. By default, it just allows to disable bus device by calling `os_dev_suspend` and enable it by calling `os_dev_resume`.
Extra pm capabilities can be enabled with `BUS_PM: 1` which adds automatic pm mode. It can be enabled in runtime at any time and allows to control enabled state of bus device automatically depending on its inactivity, i.e. it will enable bus device before transaction and will disable it when not needed. This allows for simpler app and avoids duplicating code unnecessarily.

hw/bus: Add power management for bus devices

---

mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/syscfg.yml

* Erasing the entire flash image size at once can take significant time, causing a bluetooth disconnect or significant battery sag.  Instead, we erase immediately prior to crossing a sector while writing the image.
* We could check for empty to increase efficiency.  However, for simplicity and consistency we will always erase lazily.
* wrap with `MYNEWT_VAL(IMGMGR_LAZY_ERASE)`.  Set IMGMGR_LAZY_ERASE to 0 to disable (default, same as existing behavior), or 1 to enable.

Fix disconnect during OTA by spacing out erases

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c
hw/drivers/flash/spiflash/syscfg.yml

This adds new API which allows to enable auto power down for SPI flash.
Application can define timeout after which power down command will be
sent to flash. It will be automatically release from power down for any
new request from application.
Note: There should be some delay between sending power down release
command and using flash, but the required delay was so small on flashes
I tested that it does not really matter. If required at some point, we
should add this to SPI flash configuration matrix.

hw/drivers/spiflash: Add auto power down

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c

Code to enable bus driver in spiflash.
To use this bus package must be included and hal should add spiflash device with
call to bus_spi_node_create() with correct SPI parameters.

spiflash bus driver support

---

kernel/os/src/os_mutex.c

There is possible race between `os_mutex_release()` and `os_mutex_pend()` due to modification of `mu_level` outside critical section. The scenario is as follows:
1. `os_mutex_release()` decrements `mu_level` on mutex which is not nested this means that now `mu_level==0` and will be unlocked
2. current task is preempted by another one which calls `os_mutex_pend()` on the same mutex
3. `os_mutex_pend()` checks if `mu_level==0` (i.e. unlocked) and locks it by setting `mu_level=1` and `mu_owner=<task>`
4. previous task resumes execution and enters critical section which should unlock the mutex and overwrites `mu_owner=NULL` (assuming there is no other task waiting to lock this mutex)
5. the result is that mutex has `mu_level>0` so it is assumed locked, but at the same time `mu_owner==NULL` …

kernel/os: Fix possible race in os_mutex_release()

---

hw/mcu/ambiq/apollo2/pkg.yml

this is now specified in bsp.yml

apollo2; remove dependency for compiler from MCU package;

---

crypto/mbedtls/src/x509_crt.c

Error: repos/apache-mynewt-core/crypto/mbedtls/src/x509_crt.c: In function 'x509_crt_find_parent_in':
repos/apache-mynewt-core/crypto/mbedtls/src/x509_crt.c:2097:30: error: 'signature_is_good' may be used uninitialized in this function [-Werror=maybe-uninitialized]
*r_signature_is_good = signature_is_good;
~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
exit status 1

mbedtls; fix build warning of uninitialized variable.

---

apps/flash_loader/src/fl.c

This app runs without OS, so this has to be done manually.

flash_loader; initialize watchdog in the start.

---

hw/mcu/nordic/nrf52xxx/src/hal_uart.c

Wait for UART TX FIFO drain was subject to race condition.
Function waited for nrf_uart->EVENTS_ENDTX while this register
was also read and cleared by interrupt handler.
In case interrupt code read register first hal_uart_close()
would end up in infinite loop.
Fixed code reads variable that is set when transfer is finished.

nrf52xx uart: Fix UART close function

---

hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

Current implementation of interrupts in `hal_gpio` uses `GPIOTE` pin events which allows for easier and more accurate handling of multiple pins but in this mode HFCLK is always running which increases power consumption.
Another option is to use `GPIOTE` port event which does not require HFCLK but has some limitations like less accurate detection, level state sensing only and uses single event (or-ed) for all pins.
This patch adds syscfg option which enables `hal_gpio` to use `GPIOTE` port event for handling interrupts. This involves some extra logic which is required to translate single event into events for specific pin.
To enable set `MCU_GPIO_USE_PORT_EVENT: 1`.

hw/mcu/nrf52: Add option to use GPIOTE port event

---

hw/hal/include/hal/hal_flash.h
hw/hal/src/hal_flash.c

Prior to this commit: the hal_flash functions mostly returned -1 on error.
After commit: these functions return the following error codes:
* 0 on success
* `SYS_EINVAL` on bad argument error
* `SYS_EACCES` if flash region is write protected
* `SYS_EIO` on flash driver error
This is useful for applications that specifically need to identify hardware failures.
Alternatively, rather than always return `SYS_EIO` on driver error, we could just forward the driver function's return code to the caller.  I opted for the consistency of a single return code because I don't think there is any more information that could be conveyed to the caller in a generic way.  I am certainly open to alternative points of view, though!

hw/hal: Return SYS_E[...] errors from flash API

---

hw/hal/include/hal/hal_gpio.h
hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/stm/stm32_common/src/hal_gpio.c

Current implementation does not allow to uninitialize a pin which has been previously initialized.
An uninitialized pin means a pin in state "unconnected", or at least in the same state after a boot (not input, not output, not analog...).
It is useful in some cases to be able to revert a `hal_gpio_init_*()` call.
I created the prototype in the `hal/hal_gpio.h`.
Then, I have implemented this into 2 different MCU references (stm32 + nrf51/52) as the first step, but it is not blocking if your MCU doesn't implement it, as long as you don't call the `hal_gpio_deinit()`.
We can discuss about it with pleasure if you have other questions.

Hal gpio deinit

---

sys/metrics/include/metrics/metrics.h
sys/metrics/src/cli.c
sys/metrics/src/metrics.c

The main purpose of this PR is to change the `sys/metrics` API to use the `SYS_E[...]` return codes.  This is needed specifically so that the application can distinguish flash write failures from other error conditions.
I included a few other minor fixes as well.
There is one other commit I wanted to mention here: `f19b152 sys/metrics: Free mbuf on failure`.  I'm a bit perplexed by this... it seems I broke this myself a while back while fixing a double free.  Now, instead of freeing an mbuf trice, the code doesn't free it at all!  Anyway, I think the code is finally correct now, but since I got this wrong last time, I would appreciate a close look by the reviewer.

 sys/metrics: Use SYS_E[...] return codes

---

hw/mcu/nordic/nrf51xxx/src/hal_system_start.c
hw/mcu/nordic/nrf52xxx/src/hal_system_start.c

While current implementation of hal_system_start works fine now, it is
possible that compiler will "optimize" [1] code in a way that it will
not work properly because we first set stack pointer to new location
and then execute some more code which uses local variables.
To make sure this always works fine, let's use inline assembly here to
set stack pointer and then jump to image.
[1] while working with other Cortex-M MCU it happened to me that just
before jumping to image, GCC inserted "ldmia sp! {r3, lr}" which
basically attempted a read outside RAM area since stack pointer was
already at the very end of RAM area.

hw/mcu/nordic: Fix hal_system_start

---

kernel/os/include/os/os_eventq.h
kernel/os/src/os_eventq.c
kernel/os/syscfg.yml

Add a new syscfg setting: `OS_EVENTQ_DEBUG`.  When this setting is enabled, each eventq remembers its most recently processed event.
This feature is only useful when debugging with gdb.

kernel/os: Track most recent event in debug builds

---

hw/mcu/nordic/nrf52xxx/src/hal_timer.c

This PR implements a suggested work around to achieve low power with timer off.
**NRF52832 Errata v1.9 - 3.19 [78] TIMER: High current consumption when using
timer STOP task only**
**Symptoms**
Increased current consumption when the timer has been running and the STOP task is used to stop it.
**Conditions**
The timer has been running (after triggering a START task) and then it is stopped using a STOP task only.
**Consequences**
Increased current consumption.
**Workaround**
Use the SHUTDOWN task after the STOP task or instead of the STOP task.

NRF52 Timer - Achieve Low Power When Off

---

hw/bsp/frdm-k64f/MK64FN1M0xxx12_flash.ld
hw/bsp/frdm-k64f/boot-MK64FN1M0xxx12_flash.ld
hw/bsp/frdm-k64f/bsp.yml

This makes the bootloader 40kb (from 24kb) to have enough space to do encrypted image testing, and reduces slot 0/1 sizes from 480KB to 472KB which does not seem very significant.
Also the linker script size of the bootloader was correctly adjusted to what is defined on the BSP avoiding non-caught errors when the bootloader size is big enough to overflow the configured space.

[FRDM-K64F] Increase size of bootloader slot

---

compiler/gdbmacros/os.gdb

This commit adds two public gdb scripts:
```
usage: os_task_stack_dump <task>
Dumps the specified task's stack, including symbol info.
```
```
usage: os_task_stack_dump_all
Dumps all task stacks, including symbol info.
```

compiler/gdbmacros: scripts to dump stacks

---

kernel/os/include/os/util.h

-  Check if ARRAY_SIZE is already defined before defining in the OS

Check if ARRAY_SIZE is already defined

---

net/oic/include/oic/messaging/coap/observe.h
net/oic/include/oic/port/mynewt/adaptor.h
net/oic/include/oic/port/mynewt/ble.h
net/oic/include/oic/port/mynewt/transport.h
net/oic/include/oic/port/oc_connectivity.h
net/oic/src/messaging/coap/observe.c
net/oic/src/port/mynewt/adaptor.c
net/oic/src/port/mynewt/ble_adaptor.c
net/oic/src/port/mynewt/conns.c
net/oic/syscfg.yml

- observer cleanup when BLE connection is going away was running (potentially) in wrong task context
- add a generic mechanism for init/cleanup notifications for connections when using coap
- allow more flexibility for transport to report whether particular endpoint is running over a connection or if it is connectionless

CoAP; cleanups for observing resources when using transport(s) with connections

---

mgmt/imgmgr/src/imgmgr.c

This fixes #1493.
When an `image erase` command is successfully processed, reset the in-progress upload (if any).  Prior to this commit, a subsequent upload could resume an aborted upload, even if the partial image had since been erased.

mgmt/imgmgr: Clear upload state on erase

---

kernel/os/test/src/testcases/os_mempool_test_case.c
kernel/os/test/src/testcases/os_mempool_test_ext_basic.c
kernel/os/test/src/testcases/os_mempool_test_ext_nested.c

The "extended mempool" tests were causing stack corruption.  These tests registered mempools that were allocated on the stack and never unregistered them.  So, after these tests ran, the global mempool list contained some invalid entries.  Subsequently attempting to iterate or append to the list resulted in a crash or other unpredictable behavior.
The solution is:
1. Statically allocate the mempools.
2. Always unregister the relevant mempool at the start of each test.
This is now the non-extended tests are already implemented.

mempool_tests: Fix stack corruption bug

---

hw/battery/src/battery_shell.c
hw/drivers/bq27z561/src/bq27z561.c

Driver now exposes full charge capacity prop, shell also supports
this property.

hw/drivers/bq27z561: Add full charge capacity prop

---

kernel/os/src/os_mempool.c

Unsigned arguments cannot be <0...

kernel/os: Fix redundant checks in os_mempool_init

---

hw/drivers/flash/spiflash/src/spiflash.c

Each flash has known time which is needed to erase sector.
Having this in mind we can wait a bit before reading status after sector
erase.
Note: This could be done smarter along with adjusting longest time which
might be needed. For now we choose some "default" value

spiflash: Improve erase sectors

---

hw/drivers/flash/spiflash/src/spiflash.c

Assume that when spiflash_wait_ready() is called in general flash should
be ready, therfore while() in this function should not take long.
If any delay is needed for given operation it should be applied outside
this function e.g. erase

spiflash: Remove delay when reading ready status

---

hw/scripts/jlink.sh

After writing the binary to flash, reset the device a second time.  Some devices seem to be stuck in a weird state when they are programmed (e.g., looping in a default interrupt handler).  The reset clears the bad state.
This "weird state" mostly happens when the device's internal flash is automatically erased via JTAG lockout protection.  However, I have occasionally seen this issue even when JTAG lockout is disabled.
I did not test this on a wide variety of devices, but I think this is an innocuous change.
Also, do we need something similar in the openocd script?

hw/scripts: Issue 2nd reset after jlink load

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

When switching between the blocking and non-blocking interfaces
it is possible to lockup the SPI in hal_spi_stop_transfer() if
the SPI master is enabled but no transfer started as setting
TASKS_STOP will not always generate an EVENTS_STOPPED. Calling
hal_spi_disable() will check to see if the xfr_flag is set before
calling hal_spi_stop_transfer().

hw/mcu/nordic/nrf52xxx: Fix possible SPI lockup

---

compiler/sim/compiler.yml

In macOS, the sim compiler package invokes the `gcc-5` binary.  This is not ideal - gcc5 is rather old now, so most mac users won't have it on their machine.
The reason the compiler package does not just specify `gcc` is that macOS ships with an "imposter" gcc binary: an outdated version of clang with the filename "gcc".  Until recently, much of the unit test code would not build with clang, so `gcc-5` was specified as a workaround.
To get the code building with clang, this commit adds some compiler flags in macOS:
* `-Wno-missing-braces`
* `-Wmissing-field-initializers`
The first flag silences a spurious warning caused by a bug in clang ("suggest braces around initialization of subobject").  This bug has supposedly been fixed in the latest clang: …

 compiler/sim: Use `gcc` in macOS, not `gcc-5`

---

hw/mcu/nordic/nrf51xxx/src/hal_uart.c
hw/mcu/nordic/nrf52xxx/src/hal_uart.c

This PR addresses https://github.com/apache/mynewt-core/issues/1579
The added baud rates are not supported by minicom or screen, so these changes were tested on nRF52dk using [this pyserial script](https://gist.github.com/mlaz/84658bb75e258211e96870d78159584d).

mcu/nordic: Add missig baud rates

---

kernel/os/src/os_time.c

If the OS scheduler is disabled (`!MYNEWT_VAL(OS_SCHEDULING)`), then turn `os_time_delay()` into a no-op.
Prior to this PR, this function would hang forever when scheduling is disabled.
The motivation for this PR is the `flash_loader` app.  The scheduler is not enabled in this app.  If it is run on a device with SPI flash, the calls to `os_time_delay()` in the SPI flash driver cause the app to hang.

kernel/os: Don't hang in os_time_delay() if OS scheduler disabled

---

sys/config/include/config/config.h
sys/config/src/config_store.c

- Earlier we would load all configuration values together, this API gives us a way to load just one value.
- conf_load() still loads everything the way it used to.

sys/config: Add API for conf_load_one()

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

The hal for nrf52840 currently doesn't allow spim frequencies above 8MHz whilst the hardware can handle it. Pretty minor change really.

NRF52840 Hal: Enabling 16 and 32MHz spi frequencies 

---

hw/drivers/flash/spiflash/src/spiflash.c

This is small change that allows to specify constants often
defined in bsp.h for pins.

spiflash: Include bsp.h

---

hw/bsp/hifive1/src/hal_bsp.c
hw/bsp/hifive1/syscfg.yml
hw/mcu/sifive/fe310/include/mcu/fe310_periph.h
hw/mcu/sifive/fe310/pkg.yml
hw/mcu/sifive/fe310/src/fe310_periph.c
hw/mcu/sifive/fe310/src/hal_uart.c
kernel/os/src/arch/rv32imac/os_arch_rv32imac.c

- MCU specific devices are not created in mcu_periph.c (like in nordic platform)
- fix that allow to use stack checking
- small code reduction in UART
- spiflash now can be easily enabled on hifive1 board
- added hwl_bsp_hw_id() stub function

couple of fixes and changes for RISCV platform

---

sys/defs/include/defs/sections.h

In some cases it is desired or required to put some code in RAM and
execute it from there thus we should have a common def for section which
can be then handled in MCU package, i.e. be defined to proper section
name and put in proper place in linker script.

sys/defs: Add common def for section to place code in RAM

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

Cast when writing data length to register is redundant on nRF52832 but
also can cause truncation on nRF52840 since that register is 16-bit
long.

hw/mcu/nordic: Fix invalid cast for data length

---

fs/fcb/include/fcb/fcb.h
fs/fcb/src/fcb_bmark.c
hw/mcu/native/src/hal_flash.c
sys/log/full/selftest/fcb_bookmarks/pkg.yml
sys/log/full/selftest/fcb_bookmarks/src/log_test_fcb_bookmarks.c
sys/log/full/selftest/fcb_bookmarks/src/log_test_fcb_bookmarks.h
sys/log/full/selftest/fcb_bookmarks/src/log_test_fcb_bookmarks_util.c
sys/log/full/selftest/fcb_bookmarks/src/testcases/s0_l1_b0_p100.c
sys/log/full/selftest/fcb_bookmarks/src/testcases/s0_l1_b1_p100.c
sys/log/full/selftest/fcb_bookmarks/src/testcases/s100_l500_b10_p2000.c
sys/log/full/selftest/fcb_bookmarks/src/testcases/s10_l100_b10_p2000.c
sys/log/full/selftest/fcb_bookmarks/src/testcases/s10_l100_b1_p200.c
sys/log/full/selftest/fcb_bookmarks/syscfg.yml
sys/log/full/src/log_fcb.c
sys/log/full/syscfg.yml

Bookmarks are an optimization to speed up lookups in FCB-backed logs.  The concept is simple: maintain a set of flash area+offset pairs corresponding to recently found log entries.  When we perform a log lookup, the walk starts from the bookmark closest to our desired entry rather than from the beginning of the log.
Bookmarks are stored in a circular buffer in the fcb_log object.  Each time the log is walked, the starting point of the walk is added to the set of bookmarks.
FCB rotation invalidates all bookmarks.
By default, this optimization is disabled.  To enable it, set the `LOG_FCB_BOOKMARKS` syscfg setting to 1.  Each FCB-backed log must then be configured with bookmark storage at runtime.

Bookmarks optimization for FCB-backed logs

---

fs/fcb/src/fcb_append.c
sys/log/full/selftest/fcb_bookmarks/src/log_test_fcb_bookmarks_util.c
sys/log/full/src/log_fcb.c

If user tries to start a walk beyond the end of the log, return early without walking.

log_fcb: Don't walk if requested index too great

---

hw/mcu/nordic/nrf52xxx/src/hal_system.c
hw/mcu/nordic/nrf52xxx/syscfg.yml
kernel/os/src/arch/cortex_m4/os_fault.c

- Add MCU_DEBUG_IGNORE_BKPT syscfg
- To be set if one wants to ignore debugger check

nrf52: Add debugger override syscfg

---

compiler/arm-none-eabi-m33/compiler.yml

DSP extension is optional and thus may not be supported by some MCUs.
Let's make this package generic one and disable DSP extension by
default - those who want to use DSP extension in their BSP can create
own compiler package with proper settings.

compiler: Disable DSP extension for Cortex-M33

---

hw/mcu/native/src/hal_flash.c

This is an experimental fix for a recurring failure in some macOS travis tests.  In these tests, `mkstemp()` fails when a template starting with `/tmp` is used.
This experiment is to use `$TMPDIR` instead of `/tmp`, if `$TMPDIR` is set (i.e., if this is macOS).

mcu/native: Write flash files to macOS TMPDIR

---

hw/mcu/native/src/hal_flash.c

Prior to this commit, the native hal flash implementation was not closing the simulated flash file.  If the code repeatedly opened a flash file (e.g., if `sysinit()` is called more than once), the old file descriptor is leaked.  This was eventually causing calls to `mkstemp()` to fail due to too many open files.  This caused the nimble host unit tests to fail.

Fix nimble host unit tests

---

hw/mcu/stm/stm32_common/src/hal_spi.c

HAL has one function for doing read and or write.
For write only transactions rxbuf would be NULL.
Unfortunately it called ST provided function that
required both pointer to be not NULL.
Now when rxbuf is NULL HAL_SPI_Transmit is called
instead of HAL_SPI_TransmitReceive.
It fixed #1705

stm32/hal_spi: Fix hal_spi_txrx for writes

---

net/oic/src/api/oc_ri.c

Previously it would only disregard the observer option if the request was rejected within common RX processing. Now also prevent observer being added if the resource handler rejects the request.

net/oic; if resource handler fails a request, don't honor observer option.

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c
hw/drivers/flash/spiflash/syscfg.yml
hw/hal/include/hal/hal_flash_int.h
hw/hal/src/hal_flash.c

- Wait times after erase and program are not configurable as specified in spiflash datasheets.
this should optimize Read Status Register command after writes to actual timing requirements.
- hal_flash interface was extended to allow erases using block size instead of sector size only
- spiflash erase functions are not public and can be used by application
- waiting time should work better for bootloader where os_time_delay is not used any more.

spiflash performance improvements

---

mgmt/newtmgr/nmgr_os/src/newtmgr_os.c
time/timepersist/include/timepersist/timepersist.h
time/timepersist/pkg.yml
time/timepersist/src/time_persist_config.c
time/timepersist/src/time_persist_nvreg.c
time/timepersist/syscfg.yml

This is to help platforms which don't have RTC retaining time over resets.
Offer 2 options initially, sys/config (works for all, remembers time from long time back) or nvreg (will work for some architectures).

time/timepersist; allow user to persist device time.

---

compiler/gdbmacros/os.gdb

Using %s to print debugger generated strings does not work
to well.
printf "%s", "gdbstring"
on stlink it does not work at all
on jlink+arm, openocd+riscv it works except that it allocates memory
on the platform being debugged and memory is not freed.
This is output of os_tasks command exectued 3 times on HiFive1 board:
(gdb) os_tasks
prio state      stack  stksz       task name
* 255   0x1 0x80000a38     64 0x800029d0 idle
127   0x2 0x80000ef8    304 0x80000ef8 main
130   0x2 0x800029d0    240 0x800025b8 Ftsk0
8   0x2 0x800031e0    192 0x80001ddc task1
9   0x2 0x800032f0     64 0x80001e2c task2
(gdb) p brk
$2 = 0x800035b0 ""
(gdb) os_tasks
prio state      stack  stksz       task name
* 255   0x1 0x80000a38     64 0x800029d0 idle
127   0x2 0x80000ef8    304 0x80000ef8 main
130   0x2 …

compiler/gdbmacros: Fix printf formatting problem

---

hw/mcu/sifive/fe310/src/fe310_periph.c

Argument change in function bus_spi_hal_dev_create() for asynchronous
spi handling.
This simply changes old type of argument to new one.

mcu/fe310: Adjust mcu to api changes in bus driver

---

kernel/os/src/os.c
kernel/os/src/os_mempool.c

Change the order of os_msys_init() and os_mempool_module_init() so that memory pools allocated by msys show up in the mempool list. Removed the initialization of g_os_mempool_list as it is initialized when the module init function is called. Looking at the code I wonder if the order of where things are done in os_pkg_init() might be an issue. For example, os_dev_initialize_all() is called which will call os device initialization functions if their init stage is OS_DEV_INIT_KERNEL.

kernel/os: MSYS memory pool not in mempool list

---

hw/bsp/nucleo-l476rg/src/hal_bsp.c

Two minor fixes.
- MOSI pin was not from the same group as MISO and CLK
- cpu timer was not initialized in bsp

nucleo-l476 bsp fixes

---

sys/config/src/config_cli.c
sys/config/syscfg.yml
sys/shell/src/shell_os.c
sys/shell/syscfg.yml

Currently in a state of flux but the idea is fairly simple. We want to be able to compile out read/write capability of config and date commands in the CLI.

sys/config, date CLIs: add syscfgs for read/write

---

hw/bsp/ruuvitag_rev_b/syscfg.yml

WARNING: Ignoring illegal expression for setting "": `!LIS2DH12_ONB ||
BSP_RUUVITAG_REV >= 3` cannot apply >= to `BSP_RUUVITAG_REV`; operand
not a number

hw/ruuvitag_rev_b: Fix typo in board restrictions

---

hw/bsp/nucleo-l476rg/syscfg.yml

Recently added code to provide cputimer requires at least one
timer to be enabled.
OS_CPUTIME_TIMER_NUM has default value 0 so timer 0 is needed.

bsp/nucleo-l476rg: Enable TIMER_0 by default

---

hw/mcu/stm/stm32f1xx/src/hal_flash.c

Invalid pre-condition was used before sector erase.
This affects only f1xx platform, other STM32 versions
have correct condition if needed.

stm32f1xx: Fix sector erase

---

hw/scripts/openocd.sh

openocd expects unix style file names even on Windows.
Before pathc:
$ newt load hifive1-boot
Loading bootloader
Error:
Downloading bin\targets\hifive1-boot\app\apps\boot\boot.elf.bin to 0x20000000
GNU MCU Eclipse 64-bit Open On-Chip Debugger 0.10.0+dev-00462-gdd1d90111 (2019-01-18-11:42)
Licensed under GNU GPL v2
...
...
auto erase enabled
Error: couldn't open bin        argetshifive1-bootppppoooot.elf.bin
Windows style path was passed and \ was treated as escape \t - tab
After patch is applied flashing of hifive1 and bluepill works

openocd: Fix openocd_load for Windows

---

hw/bsp/ble400/syscfg.yml

Maps to pins on UART connector, instead of leaving UART on a generic GPIO connector.

Change BLE400 UART pinout

---

hw/drivers/chg_ctrl/adp5061/include/adp5061/adp5061.h

Missing macro value `ADP5061_VTRM_4V22`
Macro values 4.14V to 4.22V were off.

ADP5061 Macro Values

---

mgmt/imgmgr/src/imgmgr.c
mgmt/oicmgr/include/oicmgr/oicmgr.h
mgmt/oicmgr/src/oicmgr.c
net/oic/include/oic/port/mynewt/serial.h
net/oic/src/port/mynewt/serial_adaptor.c

This commit adds an additional boolean field to the "image upload" request: `upgrade`.  If this field is true, the firmware will only accept an upload attempt if the new image's version number is greater than that of the currently running image (using a semver-compatible comparision).
If the `upgrade` field is false or missing, no version check is performed.
The firmware only processes the `upgrade` field on the first image chunk.  It is harmless, but pointless, for a client to specify `upgrade` in any subsequent chunks.
Note: This PR has siblings:
* newtmgr: https://github.com/apache/mynewt-newtmgr/pull/120
* mcumgr: https://github.com/apache/mynewt-mcumgr/pull/25

mgmt/imgmgr: Allow upgrade-only requests

---

sys/console/full/src/console.c

- NLIP output was not passing through when g_console_silence_non_nlip
was set

sys/console: NLIP output was not passing through

---

kernel/os/src/os_msys.c

This PR does two things
1) When it search for mpool for given data size it pick mempool with a databuf_len closes to requested datasize. With this Mynewt tries to me smart and not used mempools with big block size for small data 
2) When user requests msys mbuf with data size 0, Mynewt assumes that data might be big, therefore it will assign mempool with biggest block size. It is done because if there would be msys_2 available with small block size for e.g. some headers as in https://github.com/apache/mynewt-nimble/pull/380, those small msys blocks would be consumed by  others e.g. OIC, where datasize 0 is requested for the reason that it is hard to estimate how big mbuf is needed.

kernel/os_msys: Improve finding mpool

---

hw/mcu/dialog/da1469x/syscfg.yml

Fixed minor typos as a way to try out the contribution workflow.

Minor typos in DA1469x MCU syscfg

---

sys/log/full/src/log_fcb.c

We were already (correctly) clearing bookmarks when an FCB log gets rotated.  We were not clearning them when the log gets fully erased!

log_fcb: Clear bookmarks when log gets erased

---

util/taskpool/include/taskpool/taskpool.h
util/taskpool/pkg.yml
util/taskpool/src/taskpool.c
util/taskpool/syscfg.yml

This package allows you to create and remove generic tasks at runtime. The initial use case is multithreaded unit tests, but this package can be used in other applications as well.
This package creates a single global task pool.  Each allocated task uses the same size stack.  The task count and stack size settings are specified via syscfg.
It might be useful to allow multiple task pools and / or variable stack sizes.  This would add quite a bit of complexity to the API, and I did not deem it useful enough to justify the expense.  If we need these features, we can add them to the API later.

util/taskpool: New package

---

kernel/os/selftest/src/mutex_test.c
kernel/os/selftest/src/testcases/os_mutex_test_basic.c
kernel/os/selftest/src/testcases/os_mutex_test_case_1.c
kernel/os/selftest/src/testcases/os_mutex_test_case_2.c
kernel/os/selftest/src/testcases/os_sem_test_basic.c
kernel/os/selftest/src/testcases/os_sem_test_case_1.c
kernel/os/selftest/src/testcases/os_sem_test_case_2.c
kernel/os/selftest/src/testcases/os_sem_test_case_3.c
kernel/os/selftest/src/testcases/os_sem_test_case_4.c
kernel/os/selftest/syscfg.yml
test/runtest/include/runtest/runtest.h
test/runtest/pkg.yml
test/runtest/src/runtest.c
test/runtest/syscfg.yml
test/testutil/src/case.c
util/cbmem/hosttest/include/cbmem_test/cbmem_test.h
util/cbmem/hosttest/src/cbmem_test.c
util/cbmem/hosttest/src/testcases/cbmem_test_case_1.c
util/cbmem/hosttest/src/testcases/cbmem_test_case_2.c
util/cbmem/hosttest/src/testcases/cbmem_test_case_3.c
util/cbmem/selftest/src/cbmem_test.c
util/cbmem/selftest/src/testcases/cbmem_test_case_1.c
util/cbmem/selftest/src/testcases/cbmem_test_case_2.c
util/cbmem/selftest/src/testcases/cbmem_test_case_3.c
util/taskpool/include/taskpool/taskpool.h
util/taskpool/pkg.yml
util/taskpool/src/taskpool.c
util/taskpool/syscfg.yml

Remove the task pool functionality from `test/runtest` and use `util/taskpool` instead.
Convert unit test packages to use `util/taskpool`.

Use taskpool package in unit tests

---

mgmt/oicmgr/include/oicmgr/oicmgr.h
mgmt/oicmgr/src/oicmgr.c

This function would include status in the CoAP response that it sent, but would not indicate status to the caller.  It may be helpful to return a status code here in case the caller wants to perform additional work after successfully processing an oicmgr request.

mgmt/oicmgr: make omgr_oic_put() return status

---

mgmt/mgmt/include/mgmt/mgmt.h
sys/log/full/src/log.c
sys/log/full/src/log_nmgr.c

- if an entry type gets corrupted, we should assert() and not let it
through, it would be useful to analyze cores

sys/log:Add MGMT_ERR_ECORRUPT for corrupt logentry

---

README.md

Update to reamdme file now that DA1469x supported has been added.

Added DA1469x Pro DK to list of supported hardware platforms

---

hw/bsp/dialog_da1469x-dk-pro/include/bsp/bsp.h

Unfortunately there is only 1 LED that can be controlled by a GPIO on the DA1469x development kit boards (daughter plus motherboard). Therefore LED_2 is defined to to use the same GPIO as LED_1, which will be ok as long as they are not both used by the same application...

LED_2 is used by the blemesh example application 

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh
hw/bsp/dialog_da1469x-dk-pro/src/arch/cortex_m33/gcc_startup_da1469x.S
hw/bsp/dialog_da1469x-dk-pro/syscfg.yml
hw/mcu/dialog/da1469x/da1469x.ld
hw/mcu/dialog/da1469x/da1469x_ram_resident.ld
hw/mcu/dialog/da1469x/include/mcu/da1469x_pd.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_pdc.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_prail.h
hw/mcu/dialog/da1469x/include/mcu/mcu.h
hw/mcu/dialog/da1469x/src/arch/cortex_m33/da1469x_m33_sleep.S
hw/mcu/dialog/da1469x/src/da1469x_cmac.c
hw/mcu/dialog/da1469x/src/da1469x_pd.c
hw/mcu/dialog/da1469x/src/da1469x_pdc.c
hw/mcu/dialog/da1469x/src/da1469x_prail.c
hw/mcu/dialog/da1469x/src/da1469x_priv.h
hw/mcu/dialog/da1469x/src/da1469x_sleep.c
hw/mcu/dialog/da1469x/src/hal_gpio.c
hw/mcu/dialog/da1469x/src/hal_os_tick.c
hw/mcu/dialog/da1469x/src/hal_system.c
hw/mcu/dialog/da1469x/src/system_da1469x.c
hw/mcu/dialog/da1469x/syscfg.yml

This adds support for entering deep sleep on M33 core. It can decrease power consumption quite a lot, but there are still few things to be configured before we can go from miliamps to microamps. Deep sleep is disabled by default since it seems to break CMAC sometimes, working on this.
Also, it configures power rails to switch LDOs to more optimal configuration - this is not yet configurable, but will be.

da1469x: Add some power saving (M33 deep sleep + power rails)

---

.travis.yml

CI currently expects target tree inside targets directory and uses a hardcoded path. The targets directory might not exist on some of the repos tested, so create it first here. CI will be updated to use the repo slug to determine which repo's targets it should build.

Fix copying CI targets

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h
hw/mcu/dialog/da1469x/src/hal_gpio.c

This adds some logic to control PD_COM inside hal_gpio so power domain
can be disabled if not needed and we can save some power.

hw/mcu/dialog: Add PD_COM control to hal_gpio

---

apps/boot/src/boot.c

Watchdog is used during image swap unconditionally.
If watchdog is not initialized kicking it may result in
undesired behaviour.

boot: Init watchdog

---

hw/hal/include/hal/hal_system.h
hw/mcu/nordic/nrf51xxx/src/hal_reset_cause.c
hw/mcu/nordic/nrf52xxx/src/hal_reset_cause.c
sys/reboot/include/reboot/log_reboot.h

Continuation of this [PR](https://github.com/apache/mynewt-core/pull/1743).
Adding the same reset reasons between NRF51 and NRF52.

Updated NRF51 Wake Up Reasons

---

hw/mcu/dialog/da1469x/src/hal_spi.c

Wrong bit mask was used for masking bits in SPI_CTRL_REG.
One mask was taken from totally different register.
Second mask was not really needed.

hw/mcu/dialog: Fix hal_spi_config()

---

sys/log/full/src/log_shell.c

I noticed timestamps in the `log` CLI output were all the same, with only the upper 8 bits of the value set. The actual log entry data is correct and the issue is with the log reader's cbor decoder for uint32_t types, where a uint8_t was used by mistake. Logs are decoding correctly now with this fix.

Fix wrong type in log reader's uint32_t decoder

---

repository.yml

Before this commit, the latest version of core depended on "1-latest" of mcuboot.  I.e.,
```
mcuboot:
type: github
user: JuulLabs-OSS
repo: mcuboot
vers:
master: 1-latest
```
This is a problem for a user who wants to use the latest version of both repos.  If the user's project.yml specifies "0.0.0" for both repos, `newt upgrade` fails with the following error:
```
Error: Repository conflicts:
Installation of repo "mcuboot" is blocked:
project.yml requires mcuboot ==0.0.0
apache-mynewt-core,0.0.0 requires mcuboot ==1.3.0
```
The fix is to make the latest mynewt-core depend on the latest mcuboot:
```
mcuboot:
type: github
user: JuulLabs-OSS
repo: mcuboot
vers:
master: 0-dev
mynewt_1_6_0_tag: 1-latest
```

repository.yml: latest core dep on latest mcuboot

---

repository.yml

repository.yml: 1.6.0 should not depend on mcuboot

repository.yml: 1.6.0 should not depend on mcuboot 

---

hw/drivers/adc/sdadc_da1469x/src/sdadc_da1469x.c

da1469x_sdadc_resolve_pins took wrong pin, it checked srcn
but took srcp.

hw/driver/adc: Fix pin resolution in da1469x SDADC

---

hw/drivers/sensors/lis2de12/include/lis2de12/lis2de12.h
hw/drivers/sensors/lis2de12/pkg.yml
hw/drivers/sensors/lis2de12/src/lis2de12.c
hw/drivers/sensors/lis2de12/src/lis2de12_priv.h
hw/drivers/sensors/lis2de12/src/lis2de12_shell.c
hw/drivers/sensors/lis2de12/syscfg.yml

Add driver for 8 bit accelerometer LIS2DE12
Driver supports the following features:
- polling read
- stream read
- full configuration (ODR, FS, basic gesture recogn.)
- interrupt configuration
Driver tested on STM32F4-Discovery board as "off board" device
connected to I2C master interface.

hw/drivers/lis2de12: Added driver support to LIS2DE12

---

hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/sensor/src/sensor.c

1. Fixes two issues in sensor.c when an event queue other than the default queue is configured to be used:
- Adds an `extern` needed to resolve the name of the outside queue.
- Adds `&` to get the queue address without requiring the ampersand as part of the name in the syscfg value.  
2.  The lps33hw and lps33thw now use whatever queue the sensor layer is configured to use.

lps33hw/lps33thw: Fix sensor usage of non-default event queue

---

sys/log/full/src/log_nmgr.c
sys/log/full/syscfg.yml

Add a syscfg value (LOG_NMGR_MAX_RSP_LEN) which will limit the size of a newtmgr log response. If the response exceeds this limit and there is only one entry in the response the entry type is set to string and the message "error: entry too large (xxx bytes)" is encoded as in the message portion of the response. If the response contains multiple entries the code is unchanged (the additional entry is not added and the encode function returns OS_ENOMEM).
Note that the previous code had a hard-coded limit of 400 bytes for a newtmgr log response but this was not applied to a response with a single log entry in it. This fix applies the same limit to a response with one or more entries in it.

sys/log/full: Allow for limiting size of newtmgr log response

---

hw/bsp/black_vet6/boot-stm32f4ve.ld
hw/bsp/black_vet6/bsp.yml
hw/bsp/black_vet6/include/bsp/bsp.h
hw/bsp/black_vet6/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/black_vet6/pkg.yml
hw/bsp/black_vet6/run_from_flash.ld
hw/bsp/black_vet6/run_from_loader.ld
hw/bsp/black_vet6/run_from_sram.ld
hw/bsp/black_vet6/src/arch/cortex_m4/startup_STM32F40x.s
hw/bsp/black_vet6/src/hal_bsp.c
hw/bsp/black_vet6/src/system_stm32f4xx.c
hw/bsp/black_vet6/stm32f4ve.ld
hw/bsp/black_vet6/stm32f4ve_debug.cmd
hw/bsp/black_vet6/stm32f4ve_debug.sh
hw/bsp/black_vet6/stm32f4ve_download.cmd
hw/bsp/black_vet6/stm32f4ve_download.sh
hw/bsp/black_vet6/syscfg.yml

Support for cheap board with STM32F407VE (168MHz, 192KB Ram and 512 KBFlash)
and external 2MB of spiflash.

[STM32F4]: Add black_vet6 board

---

sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/stub/include/log/log.h

This commit adds the ability to set a maximum log entry for a given log. By default, the log maximum entry length is set to 0. A value of 0 for this field means that no check should be made for maximum log entry length. If set to a non-zero value, the log write routine(s) will check the log body length (does nt include the size of the log entry header) and if it exceeds the maximum, OS_ENOMEM will be returned and the too_long log stat will be incremented. A new API was added named log_set_max_entry_len() which allows the user to set the maximum entry length.

sys/log: Add setting for maximum log entry size when writing.

---

encoding/cborattr/include/cborattr/cborattr.h
encoding/cborattr/selftest/src/test_cborattr.c
encoding/cborattr/selftest/src/test_cborattr.h
encoding/cborattr/selftest/src/test_cborattr_utils.c
encoding/cborattr/selftest/src/testcases/cborattr_encode_omit.c
encoding/cborattr/selftest/src/testcases/cborattr_encode_simple.c
encoding/cborattr/selftest/syscfg.yml
encoding/cborattr/src/cborattr.c

The motivation for this change is to simplify logging of events as CBOR data.  This change allows events to be logged without needing to structure CBOR data with calls into the tinyCBOR API.
The cborattr package allows CBOR data to be decoded to a set of C structs.  This commit implements the reverse functionality: the ability to encode structures to CBOR data.
The existing structure (`struct cbor_attr_t`) is almost appropriate for this new functionality, but not quite.  The semantics between the two operations are sufficiently different to justify implementing a new data structure: `struct cbor_out_attr_t`.  To encode to CBOR, populate an array of these objects, and pass it to one of the `cbor_write_[...]` functions.

encoding/cborattr: Structured encoding

---

hw/drivers/sensors/lsm6dso/include/lsm6dso/lsm6dso.h
hw/drivers/sensors/lsm6dso/pkg.yml
hw/drivers/sensors/lsm6dso/src/lsm6dso.c
hw/drivers/sensors/lsm6dso/src/lsm6dso_priv.h
hw/drivers/sensors/lsm6dso/src/lsm6dso_shell.c
hw/drivers/sensors/lsm6dso/syscfg.yml

Add driver for IMU LDM6DSO device
Driver supports the following features:
- polling read (acc/gyro/temp)
- stream read (acc/gyro)
- configurable FIFO interrupt watermark
- full configuration (ODR, FS, basic functions)
- interrupt configuration
Driver tested on STM32F4-Discovery board as "off board" device
connected to I2C master interface.

hw/drivers/lsm6dso:Added driver support to LSM6DSO

---

hw/drivers/pwm/pwm_da1469x/include/pwm_da1469x/pwm_da1469x.h
hw/mcu/dialog/da1469x/src/da1469x_periph.c

Added header file for da1469x pwm driver (pwm_da1469x.h) as it was missing. Also corrected include path in da1469x_periph so it points to this added header file.

da1469x pwm header file

---

hw/mcu/ambiq/apollo2/src/hal_system.c
hw/mcu/nxp/MK64F12/src/hal_system.c
hw/mcu/nxp/mkw41z/src/hal_system.c

It seems a recent PR broke a few targets.  This PR gets CI passing again.

Fix build errors (missing includes)

---

hw/mcu/stm/stm32_common/src/hal_spi.c

When doing an 8-byte SPI transfer the high byte of the uint16_t return variable was never initialized and could return to the caller whatever was on the stack. This initializes the variable before doing the SPI
transfer.
This issue was first reported here: https://twitter.com/MisterTechBlog/status/1121373727193649152

[STM32] SPI - fix usage of unitialized variable

---

kernel/os/src/os_eventq.c
sys/config/src/config.c

Trigger a crash if the application attempts to put an event on a null or uninitialized event queue.  Without the assert, both of these conditions can put the system in a strange state: the event "thinks" it is enqueued, but it is not actually present in the eventq's list.  As a consequence, the event never gets processed, and it is impossible to queue the event again because it thinks it is already enqueued.
There is a second change in this PR: `sys/config: Only use the dflt evq if it exists`.  This fixes a bug uncovered by the added assert.  During sysinit, `sys/config` enqueues the conf_load event to the default event queue.  If the app is a boot loader (or other app that doesn't use the scheduler), the default event queue never gets initialized, so this is a bug.  I feel like …

kernel/os: Assert that eventq is valid before put

---

sys/log/common/include/log_common/log_common.h
sys/log/full/selftest/util/src/testcases/log_test_case_level.c
sys/log/full/src/log.c
sys/log/full/src/log_level.c

This change patches an inconsistency in the log API.  Most of the log API allowed a log level up to 255.  However, the `log_level_get()` and `log_level_set()` functions limited the max level to 15.  These latter function imposed this limit to save RAM (fit 256 levels in 128 bytes; one per nibble).
I think 16 log levels is plenty.  Currently we use five:
```
#define LOG_LEVEL_DEBUG    (0)
#define LOG_LEVEL_INFO     (1)
#define LOG_LEVEL_WARN     (2)
#define LOG_LEVEL_ERROR    (3)
#define LOG_LEVEL_CRITICAL (4)
```
With the maximum log level reduced, log level arguments saturate at 15.  I.e., if you pass 255 to a log function, it gets converted to 15.  This is done to maintain backwards compatibility.

Reduce LOG_LEVEL_MAX to 15 (was: 255)

---

hw/mcu/dialog/da1469x/src/da1469x_prail.c

Enabling DCDC converter when battery level is low results
in instant reboot even when VBUS is present.
This would make it impossible to charge battery if it drops
below critical level.

hw/mcu/dialog: Enable DCDC only when VBAT is OK

---

hw/mcu/sifive/fe310/include/mcu/fe310.h
hw/mcu/sifive/fe310/src/hal_os_tick.c
hw/mcu/sifive/fe310/src/hal_system.c
hw/mcu/sifive/fe310/syscfg.yml

- WFI if present on FE310 now it is used for idle time
- calculation of next tick time is more accurate
- build error fixed

mcu/fe310: add tickles sleep

---

hw/bsp/dialog_da1469x-dk-pro/include/bsp/bsp.h

Added definition for LED_3 (used by at least one ble mesh application). Assigned to unused pin on DA1469x dev board which is brought out to a header. An an external LED will be have to be wired to it as only one LED is available on the board.

da1469x LED_3

---

hw/drivers/sensors/kxtj3/src/kxtj3.c

Implement KXTJ3 sensor_driver sd_set_config function.

KXTJ3 sensor driver: add missing sd_set_config

---

hw/mcu/stm/stm32_common/src/hal_system.c

Implementation was stubbed and marked to be fixed.
Cortex standard way to detect debugger presence is used.

[STM32]: Fix hal_debugger_connected function

---

hw/mcu/ambiq/apollo2/src/hal_system_start.c
hw/mcu/sifive/fe310/src/hal_system_start.c
hw/mcu/stm/stm32_common/src/hal_system_start.c

Declaration of hal_system_start() has attribute noreturn.
For some MCU definition of hal_system_start() gcc can generate warning
if hal_system_start.c includes hal_system.h.
hal_system_start.c:35:1: error: 'noreturn' function does return [-Werror]
This changes convince gcc that function called by pointer will not
return.

hal/mcu: Fix definitions of hal_system_start

---

hw/drivers/sensors/bma253/README.md
hw/drivers/sensors/bma253/include/bma253/bma253.h
hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bma253/src/bma253_priv.h
hw/drivers/sensors/bma253/src/bma253_shell.c
hw/drivers/sensors/bma253/syscfg.yml
hw/sensor/creator/src/sensor_creator.c

- sensor data read uses burst read to get all axes
- from register read, change param last_op to 0 for i2cn_master_write
- dump registers after DT event notification setup
- reuse get_registers() to simplify get_register()
- more sophiscated fifo read using fifo frame counter info
- add a flag to control the bus read write tracing
- added lpm support with config arbitration for interrupts and data streaming
- refactor struct int_status to bma253_int_stat_t for optimized efficiency and size (struct from 23 bytes to 4 bytes)
- added bma253_clear_fifo
- fix insufficient delay issue after register_write
- spi support was added
- added a log level filter and fine tuned some logs
- changed configuration parameters for data streaming and tapping interrupts
- code clean up: remove some of the …

sensors/bma253: sensor driver with the following changes

---

sys/stats/full/src/stats.c

Adds a check for a statistics instance in `g_stats_registry` with the same address as the one being added (previously duplicates were being rejected only if the name is the same). 
Multiple sensors may use the same driver but some drivers only implement one instance of statistics. This can lead to a loop in the `g_stats_registry` linked list, because currently `stats_register_internal()` assumes that statistics with different names will use unique statistics. 
The problem arises when a statistics instance is registered twice under different names. The actual instance is the same, so the second time it is registered the linked list insertion will cause `s_next` of the entry to point to itself.

Check for existing stats instance before inserting in the global stats registry

---

kernel/os/src/arch/arc/os_arch_arc.c

Local function os_arch_start() has same name as API function
but different prototype.
Now name is changed so there is no prototype collision.
This does not change any functionality.

kernel/arc: Fix function name collision

---

.travis.yml

The usage of RSA that allows for keys of any sizes requires go 1.11 to work.

Bump go requirement to 1.11

---

hw/drivers/sensors/bmp388/README.md
hw/drivers/sensors/bmp388/include/bmp388/bmp388.h
hw/drivers/sensors/bmp388/pkg.yml
hw/drivers/sensors/bmp388/src/bmp388.c
hw/drivers/sensors/bmp388/src/bmp388_priv.h
hw/drivers/sensors/bmp388/src/bmp388_shell.c
hw/drivers/sensors/bmp388/syscfg.yml
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

- new driver for bmp388 
- supports data reading with polling
- supports data reading with data ready interrupt (full/watermark)
- supports data reading with fifo (full/watermark)
- README added
- clean up of debug logs: replace bma253 with bmp388

sensors/bmp388:

---

hw/sensor/src/sensor_shell.c

Next read offset is never reset to 0 so after complete 'read' sequence
next command will request 1st read operation immediately and then next
one will be scheduled after duration of complete previous sequence
because next read offset is still set to that duration.
Need to make sure read offset is reset to 0 before 1st read operation.

hw/sensors: Reset read offset in 'read' shell cmd

---

mgmt/newtmgr/pkg.yml

NEWTMGR_BLE_HOST was removed in
cc8ead34b MYNEWT-492 - Remove unused obsolete settings.

mgmt/newtmgr: Remove dead code

---

mgmt/mgmt/include/mgmt/mgmt.h
mgmt/newtmgr/transport/nmgr_uart/src/nmgr_uart.c
sys/shell/pkg.yml
sys/shell/src/shell_nlip.c

NLIP specifies a maximum frame size of 127 bytes (https://github.com/apache/mynewt-mcumgr/blob/master/transport/smp-console.md).
Prior to this commit, the shell emitted frames larger than 127 bytes. Typically, in a multi-frame response:
* last frame:   135 bytes
* other frames: 131 bytes
This commit ensures outgoing frames have a length <= 127 bytes.
The new code does not take efforts to maximize the length of each frame. In a multi-frame response, each frame typically has a length of 115 bytes.  Filling out the full 127 bytes is somewhat tricky because the frames get base64-encoded and padded (we could do it, but it didn't seem
worth the effort).

sys/shell: Don't emit NLIP frames > 127 bytes

---

kernel/os/src/os_dev.c

A null check on the device has been added before the close happens.
Without this check, the callback pointer will be undefined, and executing it will crash the system.

Added null device check in os_dev_close

---

hw/drivers/adc/gpadc_da1469x/include/gpadc_da1469x/gpadc_da1469x.h
hw/drivers/adc/gpadc_da1469x/src/gpadc_da1469x.c
hw/drivers/adc/sdadc_da1469x/include/sdadc_da1469x/sdadc_da1469x.h
hw/drivers/adc/sdadc_da1469x/src/sdadc_da1469x.c
hw/drivers/chg_ctrl/da1469x_charger/include/da1469x_charger/da1469x_charger.h
hw/drivers/chg_ctrl/da1469x_charger/pkg.yml
hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c
hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger_shell.c
hw/drivers/chg_ctrl/da1469x_charger/syscfg.yml
hw/mcu/dialog/da1469x/pkg.yml
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/mcu/dialog/da1469x/syscfg.yml

This adds code to control built-in charger on DA1469X.
GPADC and SDADC were extended to provide information about battery voltage.

da1469x charger

---

kernel/os/src/os.c
kernel/os/syscfg.yml

Added ability to include `os_sanity` check with `main task`.
Developers will have to create their os_sanity check-in in their application.

[Feature]: Main Task OS Sanity Check

---

encoding/tinycbor/include/tinycbor/cbor.h
encoding/tinycbor/src/cborencoder.c
hw/battery/src/battery_shell.c
kernel/os/include/os/os_error.h
kernel/os/src/os_error.c
mgmt/mgmt/include/mgmt/mgmt.h
sys/console/full/include/console/console.h
sys/console/full/src/console_fmt.c
sys/console/minimal/include/console/console.h
sys/console/stub/include/console/console.h
sys/shell/include/shell/shell.h
sys/shell/pkg.yml
sys/shell/src/shell.c
sys/shell/src/shell_bridge.c
sys/shell/src/shell_bridge_streamer.c
sys/shell/src/shell_os.c
sys/shell/src/shell_priv.h
sys/shell/src/shell_prompt.c
sys/shell/syscfg.yml
sys/stats/full/src/stats_shell.c
test/flash_test/src/flash_test.c
util/streamer/include/streamer/streamer.h
util/streamer/pkg.yml
util/streamer/src/streamer.c
util/streamer/src/streamer_console.c
util/streamer/src/streamer_mbuf.c
util/streamer/syscfg.yml

Implement a new newtmgr command: `shell exec`.  This command allows shell commands to be executed via newtmgr.
This PR requires a sibling change to the newtmgr tool: https://github.com/apache/mynewt-newtmgr/pull/126

Shell newtmgr bridge

---

sys/console/stub/include/console/console.h
util/streamer/src/streamer.c

`newt test all` in a project containing the nimble repo fails with the following errors:
```
va_start(ap, fmt);
Failed tests: [nimble/host/test]
^~~~~~~~
os_start
repos/apache-mynewt-core/util/streamer/src/streamer.c:42:5: error: implicit declaration of function ‘va_end’; did you mean ‘rand’? [-Werror=implicit-function-declaration]
va_end(ap);
^~~~~~
rand
repos/apache-mynewt-core/util/streamer/src/streamer.c:40:5: error: ‘ap’ is used uninitialized in this function [-Werror=uninitialized]
va_start(ap, fmt);
^~~~~~~~~~~~~~~~~
```

Fix some CI test failures

---

hw/mcu/nordic/nrf52xxx/syscfg.yml

Removed backwards compatibility unused settings introduced with nrf5281x support.

mcu/nordic/nrf52xx: Remove unused backwards compatibility setting.

---

hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33hw/syscfg.yml

When passing a pointer to a packed struct member, gcc-9 warns about its inability to do proper alignment. This fixes the issue by using pointer to variables and copying to the struct members.
See: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51628

Fix warning on pointer to packed struct member

---

mgmt/imgmgr/pkg.yml
mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/src/imgmgr_log.c
mgmt/imgmgr/src/imgmgr_priv.h
mgmt/imgmgr/src/imgmgr_state.c
mgmt/imgmgr/syscfg.yml
sys/log/common/include/log_common/log_common.h

This PR adds logging for four image management events.
It will be a nuisance to change the format of these log entries in the future, so we should try to get them right the first time.  Please don't hold back in critiquing the log entry formats!
All events are CBOR-encoded:
```
upstart:
When: upon receiving an upload request with an offset of 0.
Structure:
{
"ev": "upstart",
"rc": <mgmt-error-code (int)>
}
updone:
When: upon receiving an upload request containing the final chunk
of an image OR a failed upload request with a non-zero offset.
Structure:
{
"ev": "updone",
"rc": <mgmt-error-code (int)>
"hs": <image-hash (byte-string)> (only present on success)
}
pend:
When: upon receiving a non-permanent `set-pending` request.
Structure:
{
"ev": "pend",
"rc": <mgmt-error-code (int)>,
"hs": …
```

mgmt/imgmgr: Log image management events

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh

Not sure what happened, but LANG is not doing this for me. LC_CTYPE makes it do the right thing.
I could've sworn that this was working before...

bsp/dialog_da1469x-dk-pro; fix download for bootloader on MacOS.

---

hw/drivers/adc/gpadc_da1469x/pkg.yml
hw/drivers/adc/gpadc_da1469x/src/gpadc_da1469x.c
hw/drivers/adc/sdadc_da1469x/pkg.yml
hw/drivers/adc/sdadc_da1469x/src/sdadc_da1469x.c
hw/drivers/trng/trng_da1469x/src/trng_da1469x.c
hw/mcu/dialog/da1469x/include/mcu/mcu.h

This allows use of the driver on different MCU with same type of
peripheral. Direct them to find the proper definition via mcu/mcu.h.

drivers/*da1469x; don't depend on MCU specific header file directly.

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh

If a valid image is present in flash then the ROM based bootloader
configures the QSPI controller using values found in the product header.
If an image is not present this configuration does not take place. This
causes problems if an application is running out of RAM and needs to
read the flash in QSPI automode. For example if the flash loader
application is loaded into RAM on a board containing a blank flash then
it is able to erase and program the flash as these operations take place
in SPI mode. However it is not able to read the flash as a memory mapped
device because the QSPI controller has not been configured with valid
read commands for use in automode. The inability to read the flash
causes the verify performed as part of the programming process to fail.
This fix resolves this …

bsp/dialog_da1469x-dk-pro: Fix download to empty flash

---

hw/bsp/black_vet6/src/hal_bsp.c
hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f413zh/src/hal_bsp.c
hw/bsp/nucleo-f439zi/src/hal_bsp.c
hw/bsp/nucleo-f746zg/src/hal_bsp.c
hw/bsp/nucleo-f767zi/src/hal_bsp.c
hw/bsp/olimex_stm32-e407_devboard/src/hal_bsp.c
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/drivers/flash/spiflash/src/spiflash.c
hw/mcu/stm/stm32l0xx/src/hal_flash.c
kernel/os/src/os_mempool.c
kernel/os/src/os_time.c
libc/baselibc/include/assert.h
sys/stats/full/include/stats/stats.h
sys/sysdown/src/sysdown.c
test/testutil/include/testutil/testutil.h

Static asserts are part of C11.
There is C language keyword _Static_assert
and convenience macro static_assert.
For C++ there is no _Static_assert while static_assert is defined.
This adds missing macro to assert.h that is defined when compiled
by C compiler.
header files are updated so they could be used by C++.
C files are updated just to make it consistent.

baselibc: Update static asserts definition

---

hw/bsp/black_vet6/src/hal_bsp.c
hw/bsp/black_vet6/syscfg.yml
hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f401re/syscfg.yml
hw/bsp/nucleo-f413zh/src/hal_bsp.c
hw/bsp/nucleo-f413zh/syscfg.yml
hw/bsp/nucleo-f439zi/src/hal_bsp.c
hw/bsp/nucleo-f439zi/syscfg.yml
hw/bsp/nucleo-f746zg/src/hal_bsp.c
hw/bsp/nucleo-f746zg/syscfg.yml
hw/bsp/nucleo-f767zi/src/hal_bsp.c
hw/bsp/nucleo-f767zi/syscfg.yml
hw/bsp/olimex_stm32-e407_devboard/src/hal_bsp.c
hw/bsp/olimex_stm32-e407_devboard/syscfg.yml
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f429discovery/syscfg.yml
hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/syscfg.yml
hw/bsp/stm32f7discovery/syscfg.yml
hw/mcu/stm/stm32_common/src/hal_flash.c

syscfg values STM32_FLASH_NUM_AREAS had number of sectors increased by 1,
probably due to way it was used in asserts.
Value was misleading and did not match description field.
Now STM32_FLASH_NUM_AREAS has accurate value as described in datasheet,
and asserts are corrected.

stm32/flash: Change STM32_FLASH_NUM_AREAS to match spec

---

hw/bsp/sensorhub/src/hal_bsp.c
hw/bsp/sensorhub/src/system_stm32f4xx.c
hw/bsp/sensorhub/syscfg.yml

- AHBPrescTable had different type then in includes.
- APBPrescTable was missing.
- Flash sector defintion was not updated as other BSP were moved to
have common code base.

stm32/bsp: Fix build for sensorhub

---

hw/drivers/sensors/bmp280/include/bmp280/bmp280.h
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bmp280/src/bmp280_shell.c
hw/drivers/sensors/bmp280/syscfg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

There were couple of problems with BMP280
- bus driver implementation was not correctly working with SPI interface
- all bit fields in registers 'config' and 'meas_ctrl' were incorrectly handled
- dump command had too much asserts
- oversample CLI command was not working as designed
- sensor creator did not have bus driver support for this sensor

bmp280 fixes

---

hw/drivers/sensors/bmp280/src/bmp280.c

All writes to bit fields in config and ctrl_meas registers
did not set bit correctly.
Bits were only added and never cleared that could lead
to unpredictable results.
Filter bit field was incorrectly shifted for read and write.

sensors/bmp280: Fix bit filed access

---

hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bme280/src/bme280.c
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bmp388/src/bmp388.c
hw/drivers/sensors/dps368/src/dps368.c
hw/drivers/sensors/kxtj3/src/kxtj3.c
hw/drivers/sensors/lis2de12/src/lis2de12.c
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/drivers/sensors/lsm6dso/src/lsm6dso.c
hw/drivers/sensors/ms5837/src/ms5837.c
hw/drivers/sensors/ms5840/src/ms5840.c

sensor_itf.si_dev has to have valid pointer to node.
It could be done in sensor_itf variable declaration, but often
this is the only filed that needs to be initialize and it is
easy to overlook.
Device creation helpers have both pointer in argument list
so now they setup si_dev to correct value.
This change dose not affect existing code.

sensors: Enhance helper functions

---

hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c

Included `i2c_nrf52_twim.h` to `i2c_nrf52_twim.c` as it contains the variable `TWIM_CUSTOM_FREQUENCY_FREQUENCY_K380` to build properly.

[Fix]: NRF52 Custom Frequency

---

hw/sensor/src/sensor_shell.c

sensor read without count/interval/duration is supposed to read just
one value (set of values).
If read was executed before with interval specified next execution
without arguments ends up in infinite reading loop due to complex
condition.
Now count/interval/duration are reset before parsing arguments so
code is more deterministic.

sensor_shell: Fix infinite read

---

hw/mcu/dialog/da1469x/hosttest/include/da1469x_test/da1469x_test.h
hw/mcu/dialog/da1469x/hosttest/pkg.yml
hw/mcu/dialog/da1469x/hosttest/src/da1469x_test.c
hw/mcu/dialog/da1469x/hosttest/src/testcases/da1469x_snc_test_cases.c
hw/mcu/dialog/da1469x/hosttest/syscfg.yml
hw/mcu/dialog/da1469x/include/mcu/da1469x_snc.h
hw/mcu/dialog/da1469x/src/da1469x_snc.c

Sensor node controller API. This commit allows users to create
SNC programs using the macros in da1469x_snc.h and run them
either under software control or use the PDC to start them. Note
that PDC control of the SNC is not contained here; the PDC api
already contain all that is needed to have the PDC start the
SNC.
Added in this commit is a test program (hosted) that illustrates
how a program can be created and run under software control. The
code for the test program is in hw/mcu/dialong/da1469x/hosttest.
This directory is also intended for other host tests and not
just the SNC test.

hw/mcu/dialog: SNC

---

sys/console/full/src/rtt_console.c

- if multiple tasks write to rtt console when it is not present,
rtt_console_retries_left can be decremented below zero, leading to
near-infinite retry.  This blocks the calling task for a few years.

[console] fix race condition in rtt_console_write_ch

---

apps/bus_test/lis2dh_node/pkg.yml
apps/bus_test/lis2dh_node/src/lis2dh_node.c
apps/bus_test/src/main.c

Bus driver evolved leaving bus_test behind.
Dependency updated.
Includes fixed.
One minor change in the code to match api changes.
One endif in wrong place moved.

apps/bus_test: Fix build after bus driver changes

---

sys/shell/src/shell_os.c

Setting `SHELL_OS_DATETIME_CMD 0` will cause the function shell_os_date_cmd to return `rc` which is uninitialized at this point.

[Fix] Uninitialized Variable

---

apps/coremark/include/core_portme.h
apps/coremark/include/coremark.h
apps/coremark/pkg.yml
apps/coremark/src/core_list_join.c
apps/coremark/src/core_main.c
apps/coremark/src/core_matrix.c
apps/coremark/src/core_portme.c
apps/coremark/src/core_state.c
apps/coremark/src/core_util.c
apps/coremark/syscfg.yml

This is a port of https://github.com/eembc/coremark.
The app runs a suite of tests and delivers some performance measure at the end of the test. The test must run for 10s so the COREMARK_ITERATION might need to be tweaked according to the speed of the MCU running it. A succesfull output will be something like:
```
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 15538
Total time (secs): 15
Iterations/Sec   : 133
Iterations       : 2000
Compiler version : GCC9.1.0
Compiler flags   :
Memory location  : STACK
seedcrc          : 0xe9f5
[0]crclist       : 0xe714
[0]crcmatrix     : 0x1fd7
[0]crcstate      : 0x8e3a
[0]crcfinal      : 0x4983
Correct operation validated. See README.md for run and reporting rules.
```
NOTE: since this is CPU intensive and …

Add coremark benchmarking app

---

hw/drivers/sensors/lis2ds12/src/lis2ds12.c

Shifting after and'ing caused the result to be always 0. Only `val` should be shifted to be aligned with `LIS2DS12_WAKE_DUR_DUR` mask.

fix lis2ds12_set_wake_up_dur

---

hw/bsp/native/pkg.yml
hw/bsp/native/src/hal_bsp.c
hw/drivers/trng/trng_sw/include/trng_sw/trng_sw.h
hw/drivers/trng/trng_sw/pkg.yml
hw/drivers/trng/trng_sw/selftest/pkg.yml
hw/drivers/trng/trng_sw/selftest/src/test.c
hw/drivers/trng/trng_sw/selftest/src/testcases/trng_sw_test_entropy.c
hw/drivers/trng/trng_sw/selftest/src/testcases/trng_sw_test_read.c
hw/drivers/trng/trng_sw/selftest/src/trng_sw_test.h
hw/drivers/trng/trng_sw/src/trng_sw.c

Mostly for use from unit tests, could also be utilized with BSPs which don't have access to HW RNG.

trng driver implemented with software backend

---

hw/bsp/native/src/hal_bsp.c
hw/mcu/native/src/hal_timer.c
hw/mcu/native/syscfg.yml

hal_timer configurable. This allows writing unittests for subsystems which use os_cputime.
This breaks nimble controller unittest. There's going to be a PR against that repo fixing that.

native; enable os_cputime for native BSP. Make task priority for

---

hw/drivers/sensors/bmp388/include/bmp388/bmp388.h
hw/drivers/sensors/bmp388/src/bmp388.c

Multiple instances of the driver were causing a crash due to statistics

bmp388: stats cause a crash on multiple instances of the driver

---

hw/bsp/dialog_da1469x-dk-pro/syscfg.yml
hw/mcu/dialog/da1469x/src/hal_flash.c
hw/mcu/dialog/da1469x/syscfg.yml

Currently writes to flash were hard coded to use Quad Input Page Program
command 32H.
Unlike 02H (Page Program) this command is not shared by all manufacturers.
Now BSP has to specify one of page program commands to use:
QSPI_FLASH_CMD_QUAD_IO_PAGE_PROGRAM
QSPI_FLASH_CMD_QUAD_INPUT_PAGE_PROGRAM
QSPI_FLASH_CMD_DUAL_INPUT_PAGE_PROGRAM
It none is set. Standard 02H Page Program will be used.

da1469x/hal_flash: Add support for non-quad writes

---

hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h

`int lis2dh12_get_op_mode(struct sensor_itf *itf, uint8_t *mode);' was not added to int
lis2dh12.h. Adding it in.

add lis2dh12_get_op_mode to header file

---

hw/drivers/adc/adc_nrf51/pkg.yml
hw/drivers/adc/adc_nrf52/pkg.yml
hw/drivers/adc/adc_stm32f4/pkg.yml
hw/drivers/adc/gpadc_da1469x/pkg.yml
hw/drivers/adc/pkg.yml
hw/drivers/adc/sdadc_da1469x/pkg.yml

- ADC_HW_IMPL was not being used for pkg.apis recommended purpose
It is mainly used to differentiate APIs defined with same names

drivers/adc: Remove ADC_HW_IMPL

---

kernel/os/src/arch/cortex_m0/os_arch_arm.c
kernel/os/src/arch/cortex_m3/os_arch_arm.c
kernel/os/src/arch/cortex_m33/os_arch_arm.c
kernel/os/src/arch/cortex_m4/os_arch_arm.c
kernel/os/src/arch/cortex_m7/os_arch_arm.c

Instead of leaving some (possibly) unused interrupt handlers set to
default values set by startup code, let's just set all of them to
our os_default_irq_asm.
This allows to avoid magic numbers like "-13" for HardFault_IRQn which
for some reason is not defined for some ST MCUs.

kernel/os/arch: Reset all handlers to os_default_irq_asm

---

hw/battery/src/battery_adc.c

This function tries to close `bat_adc->dev` when it should be closing `bat_adc->adc_dev` that corresponds to the underlying ADC device.
In my case calling this function caused a recursion loop and crashed mynewt.

Changing the device closed by battery_adc_close

---

hw/bsp/dialog_da1469x-dk-pro/da1469x_header_tool.py
hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh
hw/bsp/dialog_da1469x-dk-pro/syscfg.yml

This patch adds the capability to produce the appropriate image
headers for booting on the Dialog 1469x platform.  Both secure and
nonsecure image header are supported.  Newly defined system config
settings provide the required security configuration items: slot
indices, ED25519 PEM file, and base64 encoded AES-256-CTR key.
The supplied python script leverages the python keys module that
currently resides in mcuboot/scripts/imgtool.

hw/bsp/dialog: Add generation of dialog header on images

---

libc/baselibc/src/memset.c

This optimized memset() uses aligned word size stores to speed up the
process and is ~4 times faster than simple loop.

libc/baselibc: Add optimized memset for Cortex-M

---

compiler/sim/compiler.yml
net/ip/mn_socket/selftest/src/mn_sock_util.c
net/ip/native_sockets/src/native_sock.c

There is still some v6 UDP socket weirdness which prevents net/oic test from completing successfully.

unittest fixes for FreeBSD

---

libc/baselibc/src/memset.c

Coretex-M0 version was build for all arm CPUs due to __CORTEX_M not
being defined.

libc/baselibc: Build right memset version for Cortex-m4

---

libc/baselibc/src/memset.c

If buffer is unaligned and fits in single word, the number of unaligned
bytes at the end of buffer is calculated as a negative number. This
causes memset to overwrite few bytes before actual buffer.
To fix this we just need to check if calculated value is negative and
use the other routine to fill unaligned bytes.

libc/baselibc: Fix memset on ARM

---

hw/mcu/dialog/da1469x/src/hal_i2c.c

The pin functions for I2C on the DA1469X are push-pull when they need to be open-drain.

Changed i2c pin functions from push-pull to open drain

---

kernel/os/include/os/endian.h
kernel/os/src/endian.c

Those are useful for some BLE and Mesh PDU handling (and probably more).
Instead of user defining own function it should be beneficial to have
common implementation.
Not that this is useful only for flat buffers so only put and get
helpers.

endian: Add le24 and be24 helpers

---

sys/log/full/src/log.c
sys/log/full/src/log_fcb.c
sys/log/full/src/log_nmgr.c
sys/log/full/syscfg.yml

Added `LOG_PERSIST_WATERMARK` for configurability of persisted watermark log values.
Added `LOG_REBOOT_INIT_WATERMARK_UNK` for configurability of setting watermark values to a determined "unknown" value -- `LOG_INIT_WATERMARK_VAL` -- instead of setting it to the first log entry. @ccollins476ad

log: Add configurability to watermark storage

---

.travis.yml

Travis builds are currently failing due to an incompatible version of go.  The latest newt requires go 1.12+.
```
+go get mynewt.apache.org/newt/newt
../../../mynewt.apache.org/newt/newt/downloader/downloader.go:509:14: ee.ExitCode undefined (type *exec.ExitError has no field or method ExitCode)
```
This PR upgrades from 1.11 to 1.12.

travis: upgrade to go 1.12

---

kernel/os/src/arch/cortex_m0/os_arch_arm.c
kernel/os/src/arch/cortex_m3/os_arch_arm.c
kernel/os/src/arch/cortex_m33/os_arch_arm.c
kernel/os/src/arch/cortex_m4/os_arch_arm.c
kernel/os/src/arch/cortex_m7/os_arch_arm.c
kernel/os/src/arch/rv32imac/os_arch_rv32imac.c

New mynewt user may not noticed that tasks function should not
return which is common in other systems.
If user tasks do return for arm and riscv platform PC will be
set to 0 and that will soon result in hard fault exception.
In such case, even if hard fault handler is called, further
stack corruption can happen since SP will reach top and will
point to memory that do not belong to stack any more.
Inexperienced or new myenwt user can find it difficult to
track this simple problem.
This adds minimal changes to arm and riscv architecture code
that can help catch such problems easily.

kernel/os: Catch returns from tasks

---

hw/sensor/creator/src/sensor_creator.c

Bus driver configuration had missing interrupt settings.
Now same configuration for interrupt is applied for
bus-driver and non-bus-driver build.

sensor_creator: Fix ADXL345 configuration for bus driver

---

sys/log/full/src/log_nmgr.c

Watermark should be updated after entries are properly encoded for each
log.

sys/log: Make sure watermark is updated for each log after read

---

sys/log/common/include/log_common/log_common.h

This constant was removed in a recent commit (46a14478933942708562e33a4650f2fede37342e).  We should keep this constant around to maintain backwards compatibility.  Applications may define their own log modules with IDs based on this constant.

sys/log: Re-add LOG_MODULE_PERUSER

---

hw/sensor/creator/src/sensor_creator.c

bme280:
spi configuration variable name had misleading name flash_spi_cfg
now it is called bme280_spi_cfg.
bmp280:
Non-bus-driver build has not configurable address and was hardwired to I2C_0.
Now address and interface respect what is in syscfg.

sensor_creator: Fix bmp280/bme280 configuration

---

hw/drivers/sensors/lis2dh12/src/lis2dh12.c

Fixed lis2dh12_get_full_scale to actually report the correct scale, by not shifting it.
Value returned by lis2dh12_get_full_scale->lis2dh12_get_fs is utilized for calculation in poll_read and stream_read, and would provide incorrect values when utilizing any sensitivity value other than 2G.

Fixed lis2dh12 to work on scales above 2G.

---

apps/hash_test/pkg.yml
apps/hash_test/src/main.c
apps/hash_test/syscfg.yml
crypto/mbedtls/include/mbedtls/config_mynewt.h
crypto/mbedtls/include/mbedtls/sha256_alt.h
crypto/mbedtls/selftest/syscfg.yml
crypto/mbedtls/syscfg.yml
hw/bsp/frdm-k64f/pkg.yml
hw/bsp/frdm-k64f/src/hal_bsp.c
hw/bsp/nucleo-f439zi/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/nucleo-f439zi/pkg.yml
hw/bsp/nucleo-f439zi/src/hal_bsp.c
hw/drivers/hash/hash_k64f/include/hash_context.h
hw/drivers/hash/hash_k64f/include/hash_k64f/hash_k64f.h
hw/drivers/hash/hash_k64f/pkg.yml
hw/drivers/hash/hash_k64f/src/hash_k64f.c
hw/drivers/hash/hash_k64f/src/hash_k64f_cau.c
hw/drivers/hash/hash_stm32/include/hash_context.h
hw/drivers/hash/hash_stm32/include/hash_stm32/hash_stm32.h
hw/drivers/hash/hash_stm32/pkg.yml
hw/drivers/hash/hash_stm32/src/hash_stm32.c
hw/drivers/hash/include/hash/hash.h
hw/drivers/hash/include/hash/sha256_alt.h
hw/drivers/hash/pkg.yml
hw/drivers/hash/src/hash.c
hw/drivers/hash/src/mbedtls_sha256_alt.c
hw/drivers/hash/syscfg.yml
hw/mcu/nxp/MK64F12/syscfg.yml
hw/mcu/stm/stm32f4xx/syscfg.yml

This adds initial support for the HASH HW in K64F and STM32.

[RFC] Add cryptographic HASH driver

---

sys/log/full/src/log_fcb.c
sys/log/full/src/log_nmgr.c

Changing the way `log_fcb_set_watermark` starts the search for the read log. Now using `log_fcb_walk` to reduce the amount of time searching for log. @ccollins476ad

sys/log: log_fcb_set_watermark to use log_fcb_walk

---

hw/drivers/sensors/lis2mdl/include/lis2mdl/lis2mdl.h
hw/drivers/sensors/lis2mdl/pkg.yml
hw/drivers/sensors/lis2mdl/src/lis2mdl.c
hw/drivers/sensors/lis2mdl/src/lis2mdl_priv.h
hw/drivers/sensors/lis2mdl/syscfg.yml

Added driver for LIS2MDL ultra-low-power
high-performance 3-axis magnetometer
Driver supports the following basic features:
- I2C Interface only
- Polling read
- ODR configurable
- Operation mode configurable (only support
LIS2MDL_CONTINUOUS_MODE)
Driver tested on STM32F4-Discovery board as "off board" device
connected to I2C master interface.
Signed-off-by: tesimari <mario.tesi@st.com>

hw/drivers/lis2mdl:Added support to LIS2MDL Mag

---

hw/bus/drivers/i2c_da1469x/include/bus/drivers/i2c_da1469x.h
hw/bus/drivers/i2c_da1469x/pkg.yml
hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c
hw/bus/drivers/i2c_da1469x/syscfg.yml
hw/mcu/dialog/da1469x/src/da1469x_periph.c

Code adds I2C bus driver for da1469x platform.
It uses interrupts and DMA to optimize device access.
Read and write can be tested with various sensors with and without DMA

i2c da1469x bus driver

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

DMA_REQ_MUX_REG value was correctly setup only for
first pair of channels.
Requesting second pair (channels 2/3) modified bit field
DMA45_SEL instead of DMA23_SEL and so on.

hw/mcu/da1469x: Fix DMA for more then one peripheral

---

hw/drivers/sensors/bma253/src/bma253.c

Condition was obviously wrong operator precedence was mixed up.
Added pair of parentheses to fix the issue.

sensors/bma253: Fix invalid preprocessor condition

---

crypto/mbedtls/include/mbedtls/config_mynewt.h
crypto/mbedtls/syscfg.yml

This reduces usage of ROM/RAM (depending on the setting of `MBEDTLS_AES_ROM_TABLES`) to 2KB instead of 8KB. When using fewer tables, a single T-Table is used, and extra lookups require shifts, which has shown to be negligible in practice.
This new syscfg, `MBEDTLS_AES_FEWER_TABLES`, together with `MBEDTLS_AES_ROM_TABLES`, both of which are orthogonal, give me the following numbers, running a swap upgrade on the FRDM-K64F board:
FEWER_TABLES
0                1
+----------------+--------------+
| size: 29984    | size: 29888  |
0 | swap: 18s      | swap: 18s    |
| flash: 13398   | flash: 13302 |
| ram: 8752      | ram: 2608    |    
+----------------+--------------+ ROM_TABLES
| size: 38156    | size: 32028  |
1 | swap: 19s      | swap: 19s    |
| flash: 21570   | flash: 15442 |
| ram: 4 …

[MBEDTLS] Add option to use fewer AES tables

---

hw/drivers/sensors/bma253/src/bma253.c

All other accelerometers report values in m/s2 while bma253
reported in g.
Now bma253 also reports data to user callback in m/s2.

hw/sensors/bma253: Change data units from g to m/s2

---

hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Added lis2dh12 to sensor creator
Change lis2dh12_set_int_pp_od() to lis2dh12_get_int_polarity() - code was copied from lis2dw12 and then modified. Names did not reflect was was actually done.
Interrupt level configuration was changed to look like in other drivers.

Fixes for lis2dh12

---

hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Sensor creator can create BMA253 device for bus driver builds.

sensor_creator: Add BMA253 bus driver support

---

hw/mcu/nordic/nrf52xxx/src/hal_gpio.c

Protecting shared resource if two tasks access the same memory location.
Ensuring to zero out pin variable.

Preventing Simultaneous Access GPIO IRQ Resource

---

hw/bsp/nordic_pca10056/src/arch/cortex_m4/gcc_startup_nrf52840.s
hw/mcu/nordic/nrf52xxx/src/hal_spi.c
hw/mcu/nordic/nrf52xxx/src/nrf52_periph.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

The SPI_3_MASTER interface in NRF52840 has some nice features I felt were missing in mynewt. Primarily because of the 16 or 32MHz speed only spi3m can offer. 
Note that spi3m only works as master, and it only seems to work for non-blocking read/write. Suggestions for making the blocking calls work are most welcome. 
I included the workaround for errata 198 ([nRF52840_Rev_1_Errata_v1.0.pdf](https://infocenter.nordicsemi.com/pdf/nRF52840_Rev_1_Errata_v1.0.pdf)) which may not apply to production boards?

Nrf52840 spi 3

---

hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c

Internal trigger signal from I2C to DMA seems to be active
even when read FIFO is empty after some transactions.
It could be that when RDMAE bit is enabled for some normal
DMA transaction (and it is not cleared afterwards) next
read without DMA also enables trigger.
Then next read with DMA has trigger enabled and read
transfer starts as soon as read DMA is setup even though
I2C transmission did not started yet.
That results in extra byte read by DMA.
Clearing DMA_CR reg solves the issue.
TX only cleared DMA_CR register already.

bus/i2c_da1469x: Fix read with DMA

---

hw/bsp/dialog_da1469x-dk-pro/syscfg.yml
hw/mcu/dialog/da14699/include/mcu/mcu.h
hw/mcu/dialog/da14699/pkg.yml
hw/mcu/dialog/da14699/syscfg.yml
hw/mcu/dialog/da1469x/include/mcu/cmsis_nvic.h
hw/mcu/dialog/da1469x/include/mcu/cortex_m33.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_dma.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_pd.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_pdc.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_retreg.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_snc.h
hw/mcu/dialog/da1469x/src/da1469x_cmac.c
hw/mcu/dialog/da1469x/src/da1469x_dma.c
hw/mcu/dialog/da1469x/src/da1469x_lpclk.c
hw/mcu/dialog/da1469x/src/da1469x_prail.c
hw/mcu/dialog/da1469x/src/da1469x_sleep.c
hw/mcu/dialog/da1469x/src/hal_flash.c
hw/mcu/dialog/da1469x/src/hal_gpio.c
hw/mcu/dialog/da1469x/src/hal_i2c.c
hw/mcu/dialog/da1469x/src/hal_os_tick.c
hw/mcu/dialog/da1469x/src/hal_spi.c
hw/mcu/dialog/da1469x/src/hal_system.c
hw/mcu/dialog/da1469x/src/hal_system_start.c
hw/mcu/dialog/da1469x/src/hal_timer.c
hw/mcu/dialog/da1469x/src/hal_uart.c
hw/mcu/dialog/da1469x/src/hal_watchdog.c
hw/mcu/dialog/da1469x/src/system_da1469x.c

DA1469x is not considered to be a MCU family.
One specific MCU da14699 is defined instead.
Custom chips based on this family can reuse code present in da1469x package.

da1469x split mcu

---

kernel/os/src/os_cputime_pwr2.c

Current routine is optimized-out only in optimized builds (GCC 8.2.1)
but it can be easily made optimizable on all builds by using builtin for
bit counting.
There is also no need for extra check on computed 'shift' value since
os_cputime_pwr2.c is onlu used if OS_CPUTIME_FREQ is >=256 so it will be
removed by compiler anyway after optimization.
Note that comment in original code was a bit misleading since 'shift'
was equal to 'n+1', not 'n' thus different subtraction is used in new
code.

kernel/os: Make ticks_to_usecs optimized on debug build

---

hw/drivers/sensors/bno055/include/bno055/bno055.h
hw/drivers/sensors/bno055/src/bno055.c
hw/drivers/sensors/bno055/src/bno055_shell.c
hw/drivers/sensors/bno055/syscfg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

bno055 can work when bus driver is on
- bus driver code
- shell now uses device that is already added in system. (There was no synchronization between shell access to bno055 (there was not synchronization to i2c at all)). Shell command could interfere with non-shell access.

bno055 bus driver support

---

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c
hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger_shell.c
hw/drivers/pwm/pwm_da1469x/src/pwm_da1469x.c
hw/mcu/dialog/da1469x/pkg.yml

- Few places still included DA1469xAB.h instead of mcu.h.
- When PWM_x is enabled correct packages are included.

da1469x build corrections

---

hw/mcu/dialog/da1469x/src/hal_gpio.c
hw/mcu/dialog/da1469x/syscfg.yml

Value 4 for number of GPIO interrupts may not be sufficient.
This just makes it configurable.
In case GPIO interrupt slots run out it's batter to assert
at meaningful place instead of some driver code.

hw/mcu/da1469x: Make number of GPIO interrupts configurable

---

hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c
hw/drivers/sensors/lis2dh12/syscfg.yml

Shell lis2dh12 command did not work when bus driver was enabled.
It was using own copy of sensor_itf that does not have required
fields in bus driver builds.
Now shell uses system defined device.
syscfg value were updated accordingly.

sensors/lis2dh12: Update shell to work with bus driver

---

hw/sensor/creator/src/sensor_creator.c

Obvious copy/paste error, lis2dh12 code was using
bmp388 syscfg value by mistake.

sensor_creator/lis2dh12: Copy paste error fix

---

hw/drivers/sensors/bmp388/syscfg.yml
hw/drivers/sensors/bno055/syscfg.yml
hw/drivers/sensors/lis2de12/syscfg.yml
hw/drivers/sensors/lsm303dlhc/syscfg.yml
hw/drivers/sensors/lsm6dso/syscfg.yml

Some sensors had same xxx_LOG_MODULE id values.
This prevented usage of those sensor together.
This changes duplicated ID's to unused ones.

Remove _LOG_MODULE conflicts

---

hw/drivers/sensors/lsm6dso/include/lsm6dso/lsm6dso.h
hw/drivers/sensors/lsm6dso/src/lsm6dso.c
hw/drivers/sensors/lsm6dso/src/lsm6dso_shell.c
hw/drivers/sensors/lsm6dso/syscfg.yml
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Small fixes to bus driver build.
Shell now can work with bus driver build
Sensor creator  can create lsm6dso device.
Code was verified to build but was not tested on any hardware due to lack of device.

lsm6dso bus driver updates

---

kernel/os/src/os_cputime_pwr2.c

Function was correctly computing values only when
OS_CPUTIME_FREQ was 32768.
For other values computation could be incorrect depending
on ticks.
Hard-coded mask 0x1FF was only good for 32768.
Now mask is also computed.
To make decision easier assembly before and after change for frequency 32768:
```
080168a4 <os_cputime_ticks_to_usecs>:
uint32_t usecs;
uint32_t shift;
shift = __builtin_popcount(MYNEWT_VAL(OS_CPUTIME_FREQ) - 1) - 6;
usecs = ((ticks >> shift) * 15625) + (((ticks & 0x1ff) * 15625) >> shift);
80168a4:	0a41      	lsrs	r1, r0, #9
80168a6:	f643 5209 	movw	r2, #15625	; 0x3d09
80168aa:	f3c0 0308 	ubfx	r3, r0, #0, #9
80168ae:	fb02 f303 	mul.w	r3, r2, r3
80168b2:	0a5b      	lsrs	r3, r3, #9
return usecs;
}
80168b4:	fb02 3001 	mla	r0, r2, r1, r3
80168b8:	4770      	bx	lr …
```

os/kernel: Fix os_cputime_ticks_to_usecs

---

hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c

Code that opened device was put in wrong place it
was supposed to be called before any device access.
It was added only before r command.
It resulted in crashes when other commands were executed
before r command.
When r command was executed before, other commands worked.
Now device is opened in better place.

sensors/lis2dh12: Fix crash in shell commands

---

hw/drivers/sensors/bno055/src/bno055_shell.c
hw/drivers/sensors/bno055/syscfg.yml
hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c
hw/drivers/sensors/lis2dh12/syscfg.yml
hw/drivers/sensors/lsm6dso/src/lsm6dso_shell.c
hw/drivers/sensors/lsm6dso/syscfg.yml

Recently added syscfg values to specify device that should be
accessed in drivers specific shells did not adhere to convention
adapted by other drivers.
Existing names were: BMA253_SHELL_DEV_NAME, BMP388_SHELL_DEV_NAME, ...
new ones had missing suffix _NAME.
It did not result in any problem but since those are new additions
there is no need to change well adopted schema.
Change names will be:
LIS2DH12_SHELL_DEV_NAME,
BNO055_SHELL_DEV_NAME,
LSM6DSO_SHELL_DEV_NAME

sensors/shell: Minor device name unification for some drivers

---

hw/mcu/dialog/da1469x/src/hal_gpio.c
hw/mcu/dialog/da1469x/syscfg.yml

This adds option to disable retaining of GPIO pins state and simply have
PD_COM always enabled, even if deep sleep is enabled. Such mode is
enabled if number of retained GPIO pins is set to negative value.

hw/mcu/dialog: Add option to have GPIOs always enabled

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
hw/mcu/dialog/da1469x/src/da1469x_clock.c
hw/mcu/dialog/da1469x/src/da1469x_lpclk.c
hw/mcu/dialog/da1469x/syscfg.yml

Changing the code to configure for different low power clock sources. Originally, it was assumed that the XTAL32K would be on board. However, this is not necessarily true. The change here is to make switching to the XTAL32K configurable. Also adding a configurable setting to switch to the RCX if desired. @andrzej-kaczmarek @kasjer

da1469x: enable switching to rcx clock source

---

hw/mcu/stm/stm32_common/src/hal_timer.c

- Prescaler was not correctly handled resulting in slightly wrong time calculation
- using TIM2 (which can be 32 bits on some MCU) could not work correctly
- redundant code removed

stm32 hal_timer small fixes

---

hw/drivers/adc/gpadc_da1469x/src/gpadc_da1469x.c
hw/drivers/adc/sdadc_da1469x/src/sdadc_da1469x.c
hw/mcu/dialog/da14699/include/mcu/mcu.h

Moved da14699 specific adc gpio pin selection out of da1469x_gpadc.c and da1469x_sdadc.c. Defining these in da14699 mcu.h for portability. @kasjer

mcu/dialog: define adc pin selections in mcu.h

---

hw/mcu/dialog/da1469x/src/hal_flash.c
hw/mcu/dialog/da1469x/syscfg.yml

The QSPI_BURSTCMDA_REG and QSPI_BURSTCMDB_REG registers must be configured with specific values for the target flash type. The da1469x will attempt to configure these registers from OTP or from a header prepended to the flash boot image. In the absence of either of these, these register values should be configurable by initialization code. Typically this would be code like apps/flash_loader which runs using RAM_RESIDENT and requires flash access. 
This PR adds syscfgs MCU_QSPI_BURSTCMDA_INIT_VAL and MCU_QSPI_BURSTCMDB_INIT_VAL which can be used to optionally initialize the corresponding registers in hal_flash_init(). The register initialization is done only if the syscfg value is non-empty. 
Restrictions: RAM_RESIDENT must be 1. 
Example (configure QSPIC to single mode): …

hw/mcu/dialog: syscfgs for QSPIC_BURSTCMDA_REG, QSPIC_BURSTCMDB_REG

---

hw/drivers/sensors/bme280/pkg.yml
hw/drivers/sensors/ms5837/pkg.yml

Package description stated that those were light sensors.
BME280 is humidity and pressure sensor
MS5837 is pressure sensor

sensors: Fix BME280 and MS5837 package description

---

hw/drivers/sensors/ms5837/src/ms5837.c
hw/drivers/sensors/ms5840/src/ms5840.c

- both driver suffered from buffer overrun during eeprom reading.
- read eeprom would failed on big endian platforms due to invalid byte order conversion.

Fixes for ms5837 ms5840 drivers

---

hw/drivers/sensors/bma253/src/bma253.c

Function sensor_driver_unset_notification() had not set value
of request_power before call to interim_power().
This could lead to unpredictable behaviour.

sensors/bma253: Fix uninitialized variable usage

---

hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bma2xx/src/bma2xx.c
hw/sensor/include/sensor/sensor.h

There were inconsistency between host_pin filed and it's usages.
host_pin was unsigned and most drivers were expecting it to be signed.
- host_pin changed to be signed
- bma253, bma2xx fixed to handle 0 for host_pin correctly

sensor_itf host_pin fix

---

hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/syscfg.yml

In real life scenario accelerometer will be soldered to the board
and only one interface will be used to access it.
Current code always has built-in function for I2C and SPI due to
runtime checking of interface type.
This change adds syscfg values to enable interface in build
(default both are enabled for old time sake).
This allows to reduce image size.

sensors/lis2dh12: Allow disabling one interface

---

hw/drivers/sensors/dps368/src/dps368.c
hw/drivers/sensors/lis2ds12/src/lis2ds12.c
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/lsm6dso/src/lsm6dso.c
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c

Changes to sensor drivers and sensor creator that will eliminate build errors when all sensor are enabled in sensor creator.
No functionality changes in drivers or sensor_creator.

sensors build fixes

---

hw/mcu/sifive/fe310/include/mcu/fe310.h

Build was broken due to circular include problem.

mcu/fe310: Fix build error

---

apps/trng_test/src/main.c

While building for simulator on Linux, the following warnings were
observed.
```
error: format ‘%ld’ expects argument of type ‘long int’,
but argument 2 has type ‘uint32_t {aka unsigned int}’
[-Werror=format=] console_printf("monobit: (%ld/%d) %f,
block4: (%ld/%d) %f, block8: (%ld/%d) %f\n",
```
Cast blksz, monobit_fails, block4_fails and block8_fails variables
when using in console_printf().
This change builds makes the test compatible for the simulator as well
as da1469x-dk-pro.

trng_test: fix compile time warnings

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

nrf52840 can have two GPIO ports.
Code was not handling correctly pins from port 1.
Writes outside PIN_CNF array were done for port 1 pins.
Now pin index is taken from HAL_GPIO_INDEX() macro as in all
other places.

hw/mcu/nrf52: Fix gpio handling in clear i2c bus

---

hw/drivers/sensors/bma2xx/src/bma2xx.c
hw/drivers/sensors/icp101xx/src/icp101xx.c
hw/drivers/sensors/lis2ds12/src/lis2ds12.c
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lsm6dso/src/lsm6dso.c

Some drivers had incompatible with format specifier argument
list in logging statements.
Those were found by static code analyzing tool.

sensors: Fix printf-style formatting in logs

---

hw/drivers/sensors/lis2dh12/src/lis2dh12.c

Code was written with intention of checking return code after
each function call but setting rc variable is missing in obvious
places.
Error found by static code analyzer tool.

sensors/lis2dh12: Fix control flow in lis2dh12_set_tap_cfg()

---

hw/drivers/sensors/lsm6dso/src/lsm6dso.c

Two curly braces were missing resulting in dead code.
Final
return hal_gpio_init_out(sensor->s_itf.si_cs_pin, 1);
would never be called, which could be a problem.

sensors/lsm6dso: Fix control flow error in lsm6dso_spi_fixup

---

hw/drivers/sensors/adxl345/src/adxl345.c

Obvious copy/paster error where x_enable field was used
in places where y_enable and z_enable should have been.

sensors/adxl345: Fix adxl345_get_tap_settings bit filed handling

---

hw/drivers/sensors/bma2xx/include/bma2xx/bma2xx.h
hw/sensor/creator/src/sensor_creator.c

5 fields from bma2xx sensor were left unset in sensor_creator,
it would result in unpredictable data since variable was on stack.
Now values that correspond to device reset values are defined
in driver and are used in sensor creator.

sensor_creator: Fix bma2xx initialization

---

hw/drivers/trng/trng_da1469x/src/trng_da1469x.c
hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h
hw/mcu/dialog/da1469x/src/system_da1469x.c

Add a helper to enable/disable AMBA clocks in CRG_TOP->CLK_AMBA_REG.
The code was doing an un-protected read-modify-write and if the clock is modified inside ISR's this could cause unpredictable behavior.
The helper will enable/disable interrupts around the setting/clearing of bits in that register. The helpers added are:
da1469x_clock_amba_enable(mask)
da1469x_clock_amba_disable(mask)

hw/mcu/dialog: Add helper to enable/disable AMBA clocks

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_prail.h
hw/mcu/dialog/da1469x/src/da1469x_prail.c

Explicitly disable DCDC converter.

mcu/dialog/da1469x: configurability for explicitly disabling dcdc

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh

Recent versions of newt include repository name in generated files path.

hw/bsp/dialog: Update default path for flash loader

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_lpclk.h
hw/mcu/dialog/da1469x/src/da1469x_cmac.c
hw/mcu/dialog/da1469x/src/da1469x_lpclk.c
hw/mcu/dialog/da1469x/src/hal_system.c

lpclk notification is now triggered also for RCX and includes current
lpclk frequency. If at some point RCX is recalibrated, we can just sent
another notification with new frequency.

hw/mcu/dialog: Improve lpclk notifications

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/mcu/dialog/da1469x/src/hal_uart.c
hw/mcu/dialog/da1469x/syscfg.yml

This code will allow a user to configure an internal pullup on the UART rx pin. It is expected that a BSP would set UART_X_RX_ENABLE_PULLUP if there is no external pullup on the line.
<XXX: will add more here once we test this and see if it works>

[WIP] DA1469x UART rx pullup

---

hw/mcu/dialog/da1469x/src/da1469x_prail.c

The 1V8 rail was being configured to use the retention LDO by default, which is not correct. It should use the normal LDO in ACTIVE mode, the same as for the 1V8P and 3V0 rails.

Keep V18 in normal mode during active, not retention mode

---

net/ip/src/lwip_socket.c

udp_sendto doesn't free the pbuf even though it succeeds in sending it as per comment at /net/ip/lwip_base/src/core/udp.c:854 causing a memory-leak and eventually you can't send udp-packets anymore as pbuf_alloc fails. 
Hence, lwip_sendto will need to free it both for successful and failed sends. 
The pbuf_free(p) should possibly happen before the check of rc even, removing the need to have it twice in the code.

LWIP-UDP: pbuf_free on p as udp_sendto doesn't consume it

---

encoding/base64/include/base64/base64.h
encoding/base64/src/base64.c
sys/stats/full/src/stats_conf.c

- persistent stats were failing on a downgrade if more stats were added
- Fix is to read whatever stats we can based on the size of the buffer
and only fail if the stats fail
- Adding API to base64 to decode by fixed length

base64,stats: add base64 fixedlen decode,fix stats

---

encoding/base64/src/base64.c

- Check for buffer overflow after each pointer increment
since 0 is a valid marker

base64: check for buffer overflow and cleanup

---

hw/drivers/sensors/bmp388/src/bmp388.c

- Don't write device to set mode if the device is already in the request mode
- Don't delay unless device mode was actually changed

bmp388: Fix 2 bugs in bmp3_set_op_mode

---

sys/console/full/include/console/console.h
sys/console/full/src/ble_monitor_console.c
sys/console/full/src/console.c
sys/console/full/src/rtt_console.c
sys/console/full/src/uart_console.c
sys/console/full/syscfg.yml
sys/console/minimal/include/console/console.h
sys/console/minimal/src/console.c
sys/console/stub/include/console/console.h
sys/shell/src/shell.c

This allows to have editable prompt line visible at the bottom of the terminal window.
This can be useful when logs are flooding console and it would be hard to type
complicated commands.
Additionally:
- completion for `select` fixed
- fixed auto completion for complete word (space added when word was already full)
- CTRL-C clears input line
- CTRL-L resets console if something goes wrong
- HOME/END putty work now

console improvements

---

sys/console/full/src/console.c
sys/console/full/syscfg.yml

Code hides cursor in log area to improve console usage experience.

sys/console: Hide cursor in log area

---

hw/mcu/dialog/da14699/include/mcu/mcu.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_trimv.h
hw/mcu/dialog/da1469x/src/da1469x_trimv.c
hw/mcu/dialog/da1469x/src/hal_system.c

We'll need to do something with these values later. This requires OTP driver from https://github.com/apache/mynewt-core/pull/1993

hw/mcu/da1469x: Add support to use trim values from OTP

---

hw/mcu/stm/stm32_common/src/hal_os_tick.c

MCUs from STM32F405, STM32F407, STM32F415, STM32F417 family
have documented error behaviour when exiting from sleep mode
when WFI instruction placed at address ending with xx4 was executed.
See en.DM00037591.pdf section 2.1.3 for details and conditions.
It is more cumbersome to make sure WFI is at safe location so
simplest workaround proposed by ST is implemented:
- Add 3 NOP instructions after WFI.

muc/stm32: Add workaround for STM32F4x5/7 WFI error

---

hw/bsp/black_vet6/src/hal_bsp.c

RCC register for UART2 and UART3 were pointing to APB2ENR
register instead of APB1ENR which is only valid for UART1.
Correct bit-filed was used though so there is no need to
checked datasheet.
Obvious copy/paste error.
Now UART3 was verified to work.

bsp/black_vet6: Fix UART2/3 RCC register address

---

sys/console/minimal/src/console.c

Fix typo that led to the following error:
```
repos/apache-mynewt-core/sys/console/minimal/src/console.c:135:19:
error: 'promot' undeclared (first use in this function); did you mean 'prompt'?
console_write(promot, strlen(prompt));
```

console: Fix typo

---

hw/mcu/stm/stm32_common/src/hal_os_tick.c

Having 3 NOPs after WFI seems not always help for instruction
placed at 0x080xxxx4 addresses.
So now code makes sure that WFI is never placed at dangerous
address by placing it in function with know alignment.

mcu/stm32: STM32F4x5/4x7 Errata fix

---

sys/log/full/src/log_fcb.c
sys/log/full/syscfg.yml

- reboot log entries were getting truncated on an fcb_rotate since
by default we try to restore 10 entries. this change manifested after
the reboot_log entry length increased greater than 128 which happened
recently as part of the reboot_log transition to CBOR encoded one form a
string log.

sys/log: fix reboot log entries

---

sys/log/full/include/log/log_fcb.h
sys/log/full/src/log_fcb.c
sys/log/full/src/log_fcb2.c
sys/log/full/src/log_fcb_bmark.c

sys/log/full; when rotating FCB, only remove bookmarks pointing to

---

encoding/tinycbor/include/tinycbor/cbor.h
hw/sensor/include/sensor/sensor.h

C++ build failed due to more restrictive type checking in c++ over c.
- cbor had wrong return type
- sensor had inline function that with expression dealing with enum types is slightly more strict in c++.

fix issue 2001

---

hw/bsp/dialog_da1469x-dk-pro/otp_tool.py

TEST_ALIVE is a basic test to check if the device has booted
by exchanging data over serial port. The host sends TEST_ALIVE
command via the otp_tool.py script and in response, the payload
is 20 bytes (0x0 - 0x13)

OTP Tool : Add TEST_ALIVE command

---

hw/drivers/chg_ctrl/da1469x_charger/pkg.yml

Charger shell code conditionally includes two modules.
Those two were not added to dependency list.
Missing modules were:
util/parse
hw/drivers/adc/gpadc_da1469x
hw/drivers/adc/sdadc_da1469x

da1469x_charger: Fix deps to included modules

---

sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/pkg.yml
sys/flash_map/selftest/src/flash_map_test.c
sys/flash_map/selftest/src/testcases/flash_map_test_case_new_areas.c
sys/flash_map/src/flash_map.c

Prior to this PR, a device with a flash map in its manufacturing meta region (MMR) would completely ignore the default flash map hardcoded in a firmware image.  The rationale was that changes to the default flash map should not cause devices in the field to lose data present in the affected flash areas.
This is reasonable, but there is one issue - if we add new flash areas to unused portions of flash, devices in the field will not be able to use them since they would not be present in the devices' flash maps.
This PR allows a device to use new flash areas hardcoded in the image.  The device will incorporate such a flash area into its flash map if it meets both of these criteria:
1. The area has a unique ID
2. The area does not overlap with any other flash areas in the MMR flash map.
The …

sys/flash_map: Keep non-overlapping default areas

---

hw/bsp/dialog_da1469x-dk-pro/otp_tool.py

Return the read key for further processing and verification.
Fix comment for `flash_erase()`

otp_tool: return the key read using otp_read_key

---

kernel/os/include/os/os_mbuf.h
kernel/os/selftest/src/mbuf_test.c
kernel/os/selftest/src/testcases/os_mbuf_test_pack_chains.c
kernel/os/src/os_mbuf.c

This commit adds a new API for mbuf handling called os_mbuf_pack_chains.
This API, given two mbuf chains, will concatenate them and copy data
as needed so that each mbuf fully utilizes the data buffer in each mbuf.
Unused mbufs are discarded. This API sacrifices speed for memory and
may cause a lot of copying to occur within the mbuf chains.
Test code has been written for a number of reasonable cases.

kernel/os: Add os_mbuf_pack_chains

---

util/parse/src/parse.c

This is needed as that package sets std=c99, and strcasecmp() is then not visible from string.h.

util/parse; include strings.h to compile on native.

---

sys/console/full/src/rtt_console.c

console_handle_char may return negative value in case console
can't be locked. It can happen when a lot of data is being
transmitted out.
If this happened on first negative value returned from
console_handle_char RTT input was disable by not starting
timer for polling again.
This change makes timer active on console_handle_char failure.

sys/console: Fix RTT input handling with massive output stream

---

hw/mcu/dialog/da1469x/src/hal_flash.c

- returning to automode is done by restoring original value of
QSPIC_CTRLMODE_REG. This will take care of correct bus width
and D2 D3 lines state. There is no automatic switch to quad mode
any more.
- switching to manual mode sequence of call was made:
da1469x_qspi_mode_manual()
da1469x_qspi_mode_single()
now da1469x_qspi_mode_manual() will automatically switch to single mode
and additionally it will send break sequence that should end any
continues read mode.
previous code sent only one byte in single mode that is not enough
to leave dual continuous read.
- da1469x_qspi_mode_dual() and da1469x_qspi_mode_single() now setup
controller in requested state without sending break sequence that
was sent when manual mode was entered.

hw/mcu/da1469x: hal_flash manual mode enhanced

---

hw/mcu/sifive/fe310/src/hal_system.c
hw/mcu/sifive/fe310/syscfg.yml

hal_reset_handler() for fe310 can now act in two ways
- (default) it will jump to the beginning of flash starting
from bootloader _reset_handler.
- when HAL_SYSTEM_RESET_FULL is 0 hal_reset_handler will just
jump to application _reset_handler.
This functionality can be useful when .bssnz section is used,
in this case bootloader will not overwrite it with it's own
data.

hw/mcu/fe310: Add fast reboot path

---

kernel/os/src/os_sched.c
kernel/os/syscfg.yml

- task runtime - t_run_time variable can now be counted in cpu time
ticks if OS_TASK_RUN_TIME_CPUTIME syscfg is set.

kernel/os: count t_run_time in cpu time ticks conditionally

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh
hw/scripts/jlink.sh

This adds support for `JLINK_REMOTE` option which, if set, will make `load` and `debug` commands try to connect to remote `JLinkGDBServer` instead of launching local one.

Add support for load/debug to remote J-Link server

---

hw/mcu/mips/danube/src/hal_system.c
kernel/os/src/arch/mips/os_arch_mips.c

MYNEWT_VAL definition was missing due to lack on os/mynewt.h
timer_handler() was used before it was defined without
forward declaration.

mcu/danube: Fix build errors

---

sys/log/full/src/log.c

When log_find() was called for non existing log after
checking all valid log pointers NULL pointer would be
used for checking name of the log.
Now strcmp() is called only if log pointer is not NULL.

sys/console: Fix NULL pointer dereference in log_find

---

net/oic/src/api/oc_uuid.c

Initialize the uuid buffer with random values before passing it to oc_gen_uuid().
This fixes the following warning generated from code coverage analysis.
```
CID 10028 (#1 of 1): Uninitialized scalar variable (UNINIT)10.
uninit_use_in_call: Using uninitialized element of array uuid.id when calling oc_gen_uuid.
```

oc_core: randomize uuid before use

---

hw/drivers/sensors/bme280/src/bme280_shell.c
hw/drivers/sensors/bme280/syscfg.yml
hw/sensor/creator/src/sensor_creator.c

- bme280 shell now works with bus driver
- fixed typo in sensor creator
- added include bsp.h to sensor_creator
- assert on read registers in bme280 removed

bme280 and sensor_creator fixes

---

sys/log/common/include/log_common/log_common.h

Currently `mcumgr log level_list` command isn't working because it expects LOG_LEVEL_IDX to return NULL instead of the string "UNKNOWN" when a non valid level index is provided.

log/common: Fix misleading comment.

---

compiler/sim/compiler.yml

This patch make sure that image does not contain
not used functions and data as it is done for other targets

compiler/sim: Add --gc-sections option to the linker

---

hw/mcu/native/src/hal_system.c

When BLE_SOCK_USE_LINUX_BLUE is set you can provide hci index which
shall be used. It should be done via BLE_SOCK_LINUX_DEV.
However, you might want to change it without rebuild your target
and now it is possible by providing
--hci <index> parameter when starting your native MyNewt application.

bsp/native: Add way to provide hci index

---

hw/mcu/dialog/da1469x/src/hal_uart.c

The trace api to be called at the end of the isr should be the exit one and not the entry one.

da1469x, hal_uart: fix typo

---

libc/baselibc/include/stdio.h

fflush double definition problem happens when baselibc version (B)
collides with tool chain provided one (A).
It can happen when other symbol located in (A) for example printf()
refers fflush().
(B) provides it's own version of printf() so it is not culprit
that pulls something form (A).
Function that actually pulls fflush() from (A) is putchar().
(B) provided definition of putchar() would work if it was not
for optimization done on simple printf's by gcc.
For one char prints like:
printf("a");
printf("%c", 1);
gcc chooses to change call to printf() with call to putchar(), but
at that time it just expects function putchar() to exists and
in (B) we have only macro that does not produces putchar symbol.
Simple solution is to conjure up symbol putchar in (B) so (A) version
is not needed.

libs/baselibc: Fix double fflush definition problem (#2076)

---

hw/bsp/black_vet6/src/hal_bsp.c

Includes for uart related header only depended on UART_0 being
used.
When UART_0 is not used but UART_1 or UART_2 are, build failed
due to lack of include files.

bsp/black_vet6: Fix build with no UART_0

---

hw/bsp/bluepill/src/hal_bsp.c

Bluepill has 8MHz crystal oscillators on board.
Previously clock was configured to use internal HSI as source
resulting in clock frequency 64MHz.
Now external oscillator is configured instead increasing clock
to 72MHz.
Additionally HSI could not be reliably used as system clock
when USB peripheral is enabled.

bsp/bluepill: Use HSE instead of HSI for clock source

---

sys/config/include/config/config.h
sys/config/src/config_priv.h

Prior to this PR, these two functions were private to the config package.  This PR moves their prototypes to the public `config.h` header.
If another task tries to read or write a setting while the config package is locked, the operation will block until the package is unlocked.  The locking task is permitted to read and write settings as usual.
Typical usage of the config API does not require manual locking.  This functionality is only needed for unusual use cases such as temporarily changing the destination medium for an isolated series of writes.

sys/config: Expose `conf_lock` and conf_unlock`

---

hw/drivers/sensors/tcs34725/include/tcs34725/tcs34725.h
hw/drivers/sensors/tcs34725/src/tcs34725.c
hw/drivers/sensors/tcs34725/src/tcs34725_shell.c
hw/drivers/sensors/tcs34725/syscfg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Now tcs34725 can be configured with I2C bus drivers.

sensors/tcs34725: Add bus driver support

---

sys/config/src/config_cli.c

Add a "config delete" subcommand, e.g.
```
config delete id/serial
```
Note: config groups must implement correct delete behavior (do the right thing when a value is set to "").

sys/config: Add "config delete" CLI command

---

hw/drivers/uart/uart_bitbang/syscfg.yml

The bitbang driver code allows it to be used in tx only mode, so the syscfg.yml should not require an RX pin gpio.

Remove restriction in syscfg to define bitbang RX pin

---

boot/stub/include/bootutil/image.h

- Protected TLV magic was missing in boot/stub, adding it

boot/stub: Protected TLV magic was missing

---

hw/mcu/nordic/nrf51xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/hal_timer.c

In hal_timer there is a workaround for an RTC compare issue which in
some cases fires timer callback too early. The problem with this code
is that timer value read in a callback will be *before* what was set
on timer and this is not what callback expects.
To fix this, in case we detect that new compare is too close to current
timer value we should not trigger timer too early but instead enable
TICK interrupt which occurs on every counter change and disable it once
condition for a workaround is no longer valid. This can cause an extra
interrupt on a tick with no timers being handled, but this is ok.

hw/mcu/nordic: Fix hal_timer firing too early

---

hw/drivers/crypto/crypto_nrf52/src/crypto_nrf52.c
hw/drivers/crypto/include/crypto/crypto.h
hw/drivers/crypto/src/crypto.c
hw/drivers/flash/enc_flash/ef_crypto/pkg.yml

This commit adds a flag to the crypto driver called "in_use".
This flag, and associated API, is intended for use by ISR's to
perform a quick check to see if an underlying crypto hw peripheral
is being used so that the HW peripheral can be used in the ISR
or the use of an associated piece may impact an ongoing crypto
operation.
Currently, this is only implemented for the nrf52. Some changes
were made to the nrf52 crypto code. Some reasoning behind some
of the changes: 1) do not think a counter to bail out of the
loop waiting for the crypto to end or an error to occur is needed.
Either one of the two will occur. 2) Not quite sure if it is
possible but if both EVENTS_ENDECB and EVENTS_ERRORECB can be set
at the same time, the previous could assume success when there was
an error. 3) If …

hw/drivers/crypto: Add crypto_in_use flag.

---

hw/bsp/dialog_da1469x-dk-pro/syscfg.yml
hw/drivers/flash/enc_flash/ef_da1469x/include/ef_da1469x/ef_da1469x.h
hw/drivers/flash/enc_flash/ef_da1469x/pkg.yml
hw/drivers/flash/enc_flash/ef_da1469x/src/hw_enc_flash.c

Add Encrypted Flash Driver that makes use of the AES encrypt engine on
the SoC. The driver supports CTR mode for 256/192/128 bits.
The AES Key which is stored in the OTP area is securely DMA transferred
into the AES engine during the encrypt operation. The OTP area has slots (0-7) that could be used for storing the keys. The slot number is specified with
a MYNEWT configuration parameter.

da1469x: Add Encrypted Flash Driver

---

hw/bsp/nucleo-f439zi/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/nucleo-f439zi/pkg.yml
hw/bsp/nucleo-f439zi/src/hal_bsp.c
hw/bsp/nucleo-f439zi/syscfg.yml

This uses same form-factor and pinout that nucleo-f767zi uses, so it is basically a copy from that configuration. Tested with `apps/iptest`.

bsp: nucleo-f439zi: enable ETH driver

---

hw/mcu/dialog/da1469x/src/hal_system_start.c

`mcuboot: d13318a14f99a5a3947bedc980020ec73800aaeb`
updates the tag type to uint16_t. Use the same.

da1469x: use uint16 TLV tag

---

apps/iptest/src/main.c
hw/drivers/lwip/stm32_eth/src/stm32_eth.c
hw/drivers/lwip/stm32_eth/syscfg.yml

Remove hardcoded MAC address from `apps/iptest` and add it as a syscfg in the STM32 eth driver.

Add new syscfg to set MAC addr for STM32

---

apps/loraping/pkg.yml
apps/lorashell/syscfg.yml

* lorashell: allow "lora rx_cfg" command to work by increasing the maximum number of parameters the shell is able to process.
* loraping: remove dependencies that don't seem necessary which allows for use in constrained devices (eg, b-l072z-lrwan1 with 72K slots).

A few fixes to Lora example apps

---

hw/mcu/dialog/da1469x/src/hal_spi.c

Removes initialization of the SS pin from `hal_spi_init_master` in the mcu/dialog HAL. 
Explanation:
Currently `hal_spi_init_master` initializes the SS pin, which should only be done if the SPI is operating in slave mode. Since no syscfg exists to define the SS pin for master mode, it defaults to 0 and the following code will set port 0 pin 0 to MCU_GPIO_MODE_INPUT:
```
if (cfg->pin_ss >= 0) {
mcu_gpio_set_pin_function(cfg->pin_ss, MCU_GPIO_MODE_INPUT,
spi->hw->spi_ss_func);
}
```

Dialog SPI HAL should not initialize SS pin in master mode

---

uncrustify.cfg

uncrustify: disable var alignment inside structs

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_pd.h
hw/mcu/dialog/da1469x/src/da1469x_pd.c
hw/mcu/dialog/da1469x/src/da1469x_sleep.c
hw/mcu/dialog/da1469x/src/hal_system.c
hw/mcu/dialog/da1469x/src/system_da1469x.c

So far we assumed that 1st stage bootloader applied all trim values
stored in CS and they are valid. However, since power domains can be
disabled we need to make sure proper settings are reapplied once they
are enabled.
This patch automates this process:
- read trim values for each applicable PD on init
- apply trim values once PD is enabled (on 1st acquire)
- apply preferred values on top of this
This means that after waking up from extended sleep (where most of power
domains are disabled) all settings are reapplied correctly.

hw/mcu/dialog: Apply trim and preferred values

---

hw/drivers/sensors/lis2dh12/src/lis2dh12.c

A LIS2DH12 semaphore on an interrupt has a max wait time of 4 seconds. This could cause unintended issues as 4 seconds may block the system from completing its other tasks. This also seems slightly excessive.
Reducing the wait time on a semaphore from 4 seconds to 1 second.

LIS2DH12 Sem Time

---

hw/mcu/dialog/da1469x/src/hal_timer.c

The local variable 'reset' was not initialized prior to use.

hw/mcu/dialog: Fix unitialized variable in hal_timer_stop

---

hw/bsp/stm32f3discovery/syscfg.yml

Fixes two issues:
1) Flash size was declared with the wrong size; since the bsp partitions where declared inside the valid flash size this fix is only for correctness.
2) Re-enable HSI clock. The flash programming interface on the F3 family is directly connected to the HSI clock generator, so without it enabled, trying to run any app that requires flash programming (eg slinky) would result in a hardfault.

Fix stm32f3discovery flash programming

---

apps/sensors_test/pkg.yml
hw/bsp/stm32f3discovery/pkg.yml
hw/bsp/stm32f3discovery/src/hal_bsp.c
hw/bsp/stm32f3discovery/syscfg.yml

Plus commit https://github.com/apache/mynewt-core/commit/6d10c795e3dea57c0d64e17b5a07c2fd8748ccb1 applies a small change to `sensors_test` to allow it to work on non-BLE HW.

bsp: stm32f3discovery: enable LSM303DLHC sensor

---

fs/fatfs/src/mynewt_glue.c

This fixes:
- opendir return code in case of failure
- unlink, rename, makedir were not working due to path handling problem
One warning silenced

FAT filesystem fixes

---

fs/fatfs/src/mynewt_glue.c

fatfs_opendir allocated struct fatfs_dir that was never freed
fatfs_open allocated struct fatfs_file that was never freed
Since there was no documentation that instructed caller that memory
returned by fs_open, fs_opendir should be freed it seems
reasonable to free memory in module that allocates it.

fs/fatfs: Fix memory leaks for each open/opendir

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh
hw/scripts/jlink.sh

JLINK_USB=<serial> env allows to specify JLink USB S/N. This is
convenient shortcut for '--extrajtagcmd "-select usb=<serial>"'.

hw/scripts: Add shortcut for accessing JLink via USB S/N

---

kernel/os/src/os.c
kernel/os/syscfg.yml

Setting WATCHDOG_INTERVAL to 0 will disable watchdog (i.e. will not
start it at boot).

kernel/os: Allow to disable watchdog

---

sys/config/syscfg.yml

This setting is no longer used.  It was replaced by `CONFIG_MGMT` a while back.

sys/config: Remove obsolete setting `CONFIG_NEWTMGR`

---

sys/config/include/config/config.h
sys/config/src/config.c

Prior to this commit, only signed integer types were supported for persisted settings.  This PR adds support for unsigned integer types.

sys/config: Support for unsigned integer types

---

hw/bsp/dialog_da1469x-dk-pro/da1469x_serial.py

Match the script help with the serial load functionality
provided.

hw/bsp/da1469x: Fix help text in serial load script

---

hw/mcu/dialog/da1469x/src/hal_system.c

When hal_system_reset() is called, a reset to execute from
Dialog's primary/ROM bootloader is required to ensure all the
checks in primary and secondary bootloader is performed and image
upgrade steps are performed when needed.

hw/mcu/dialog: set reset values to SYS_CTRL_REG in hal_system_reset

---

sys/config/include/config/config.h
sys/config/src/config.c
sys/config/src/config_cli.c
sys/config/src/config_priv.h
sys/config/src/config_store.c

This PR is needed for the "scfg" feature: https://github.com/apache/mynewt-core/pull/2182.
The four conf_handler callbacks (get, set, commit, and export) do not accept a `void *arg` parameter.  This means every config group must define a dedicated set of callback functions, making it impossible wrap the config API in a generic way.
This PR allows config groups to be defined as "extended".  An extended config group uses slightly different callbacks.  These callbacks do take a `void *arg` parameter.
To define an extended config group, set its `ch_ext` member to 1.

sys/config: Extended callbacks

---

util/scfg/include/scfg/scfg.h
util/scfg/pkg.yml
util/scfg/src/scfg.c
util/scfg/syscfg.yml

The `sys/config` package lets an app persist and restore data in permanent storage.  It is documented here: <http://mynewt.apache.org/latest/os/modules/config/config.html>.
This package does its job well and its design is sound.  It has one minor problem though (in my opinion, in case that needs saying) - it is nearly impossible to use!  Here is an example: <https://github.com/apache/mynewt-core/blob/master/boot/split/src/split_config.c>.  This file implements a single 8-bit setting called `split/status`.  This is not an extreme example; it is how all `sys/config` client code looks.  Speaking for myself, it is a major implementation effort whenever I need to add a new setting, or worse, a new setting group.  As basic and fundamental as data persistence is to an embedded application, this …

util/scfg: Simple config lib on top of sys/config

---

hw/drivers/flash/enc_flash/ef_da1469x/src/hw_enc_flash.c

Key is securely transferred from OTP Key area to AES engine.
Nothing to do with QSPI. Cleanup incorrect code.

encflash/da_1469x: cleanup DMA key transfer function

---

hw/mcu/stm/stm32_common/src/stm32_periph.c

Peripheral initialization unification cut out cpu timer initialization.
So all STM32 BSP are not working correctly.
Code:
rc = os_cputime_init(MYNEWT_VAL(OS_CPUTIME_FREQ));
assert(rc == 0);
was removed from all BSPs but it was not added to stm32_periph.c

Fix stm32 cputimer initialization

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_prail.h
hw/mcu/dialog/da1469x/src/da1469x_prail.c
hw/mcu/dialog/da1469x/src/hal_system.c
hw/mcu/dialog/da1469x/src/system_da1469x.c

Currently DCDC configuration is hardcoded and it's not really possible
to change it in BSP. This patch makes it easier by splitting DCDC
startup into 2 phases: initialization and enabling.
Initialization is done in SystemInit and it only configures registers.
DCDC is then enabled in hal_system_init. This allows to inject extra
configuration in BSP startup code by modifying DCDC registers between
both calls and proper configuration will be retained on wakeup as
expected.

hw/mcu/dialog: Split DCDC startup into 2 phases

---

hw/mcu/stm/stm32f4xx/src/clock_stm32f4xx.c

Fix setting HSI as main clock source in pre-configuration; it was missing the PLLState configuration which would result in random behavior.
Fixes #2193

stm32f4: fix PLL clock initialization

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

In mynewt_1_5 setting regs->TASKS_STARTTX was followed by setting regs->TASKS_RESUME in hal_i2c_master_write. This was removed in mynewt_1_6 resulting in rare but persistent hangs in the i2c master. I.e. once the hang was triggered no future i2c transactions could be performed. Not even disabling and reenabling the driver helped.
This change adds setting regs->TASKS_RESUME back. No hangs have been observed after this change.

NRF52, Re-added TASKS_RESUME in hal_i2c_master_write

---

fs/fatfs/src/mynewt_glue.c

fatfs_file_len() function was returning file size instead
of error code while actual buffer for file size was not touched.

fs/fatfs: Fix file size reading

---

fs/fatfs/src/mynewt_glue.c
fs/fs/include/fs/fs.h
fs/fs/include/fs/fs_if.h
fs/fs/src/fs_file.c
fs/nffs/src/nffs.c

This adds possibility to flush file content to storage
if file system can do this.
This is specially needed in case FAT is used that as such has this functionality.
When logging to file system will be implemented and used with FAT is would be nice to be able to write logs to storage without closing file.

fs: Add file flush functionality

---

hw/mcu/stm/stm32_common/src/stm32_periph.c

Needed to make it extern instead of defining it here.

hw/mcu/stm: Fix incorrect definition of os_bsp_uart1_cfg

---

hw/mcu/stm/stm32_common/src/stm32_periph.c

UART2 initialization went missing when peripherals creation was
moved to MCU.
Several BSP was using it.

[STM32] Add UART2 initialization

---

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c

SAADC_CH_NUM defines maximum number of channels and is used as index
for accessing varous arrays of SAADC_CH_NUM elements.

adc_nrf52: Fix out-of-bound array access

---

encoding/json/src/json_decode.c

Without the fix, decoding an empty array leads to JSON_ERR_BADTRAIL.
When peek is "positive", the read cursor needs to be forwarded to discard the closing "]".

Fix json decoding of empty array

---

hw/mcu/dialog/da1469x/src/da1469x_pd.c

Register trim values from OTP were not being applied. Upon inspection it
was found that da1469x_pd_apply_trimv() was improperly assigning 'reg' to the
address of 'trimv_words[idx *2]'.
With this fix the OTP register values appear to be properly applied.

dialog/da1469x: Fix array pointer de-referencing bug

---

kernel/os/src/arch/cortex_m3/os_arch_arm.c
kernel/os/src/arch/cortex_m33/os_arch_arm.c
kernel/os/src/arch/cortex_m4/os_arch_arm.c
kernel/os/src/arch/cortex_m7/os_arch_arm.c

Using BASEPRI instead of PRIMASK may be beneficial if there is some interrupt in MCU which requires low latency thus preferably it has highest priority and is always enabled. For example, MCU with integrated BLE Core may have interrupt(s) that we need to handle in almost real time to switch between different modes. If there is no need to interact with OS in interrupt handler (as this would break critical sections) it's safe to keep this interrupt always enabled and have minimal latency so MCU code can take advantage of BASEPRI here.

kernel/arch: Add option to use BASEPRI for critical section

---

kernel/os/src/os.c

for STM32 need to avoid calling any watchdog functions if the watchdog is to be disabled

add ifdefs to avoid calling watchdog if WATCHDOG_INTERVAL is 0

---

hw/bsp/ada_feather_stm32f405/ada_feather_stm32f405.ld
hw/bsp/ada_feather_stm32f405/ada_feather_stm32f405_debug.cmd
hw/bsp/ada_feather_stm32f405/ada_feather_stm32f405_debug.sh
hw/bsp/ada_feather_stm32f405/ada_feather_stm32f405_download.cmd
hw/bsp/ada_feather_stm32f405/ada_feather_stm32f405_download.sh
hw/bsp/ada_feather_stm32f405/boot-ada_feather_stm32f405.ld
hw/bsp/ada_feather_stm32f405/bsp.yml
hw/bsp/ada_feather_stm32f405/include/bsp/bsp.h
hw/bsp/ada_feather_stm32f405/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/ada_feather_stm32f405/pkg.yml
hw/bsp/ada_feather_stm32f405/run_from_flash.ld
hw/bsp/ada_feather_stm32f405/run_from_loader.ld
hw/bsp/ada_feather_stm32f405/run_from_sram.ld
hw/bsp/ada_feather_stm32f405/src/arch/cortex_m4/startup_STM32F40x.s
hw/bsp/ada_feather_stm32f405/src/hal_bsp.c
hw/bsp/ada_feather_stm32f405/syscfg.yml
hw/mcu/stm/stm32f4xx/include/mcu/cmsis_nvic.h

This PR adds support for the [Adafruit Feather STM32F405 Express](https://www.adafruit.com/product/4382).
I have tested UART, SPI, and I2C interfaces.

BSP for Adafruit Feather STM32F405 Express

---

hw/bsp/nucleo-f411re/boot-nucleo-f411re.ld

Flash area size for bootloader was different in bsp.yml and
in bootloader linker script.
When FLASH_AREA_REBOOT_LOG flash area was used bootloader area was
corrupted.

bsp/nucleo-f411re: Fix linker script

---

repository.yml

This reverts commit 03b8d33d6fb03b696f9ff2ebad2e6982894045d4.
Fix `newt upgrade` until we resolve the newt rc-infer issues.

Revert "Prepare for Apache Mynewt 1.8.0 release"

---

repository.yml

Reverts apache/mynewt-core#2243
Tags on core should be fixed now (added non-rc tag as workaround) so we can revert this revert.

Revert "Revert "Prepare for Apache Mynewt 1.8.0 release""

---

hw/bsp/native-armv7/syscfg.yml
hw/bsp/native-mips/syscfg.yml
hw/bsp/native/syscfg.yml

Use OS_CRASH_FILE_LINE instead to avoid following message:
Override of defunct settings detected:
BASELIBC_ASSERT_FILE_LINE: Use OS_CRASH_FILE_LINE instead
Setting history (newest -> oldest):
BASELIBC_ASSERT_FILE_LINE: [@apache-mynewt-core/hw/bsp/native:1,
@apache-mynewt-core/libc/baselibc:0]

bsp/native: Don't use deprecated BASELIBC_ASSERT_FILE_LINE

---

docs/os/tutorials/STM32F303.rst

Because support of STM32 is located in mynewt-core, no external repos are necessary.

STM32 blinky tutorial update

---

hw/mcu/stm/stm32_common/include/stm32_common/mcu.h
hw/mcu/stm/stm32_common/src/stm32_bootloader.c
hw/mcu/stm/stm32f0xx/include/mcu/mcu.h
hw/mcu/stm/stm32f1xx/include/mcu/mcu.h
hw/mcu/stm/stm32f3xx/include/mcu/mcu.h
hw/mcu/stm/stm32f4xx/include/mcu/mcu.h
hw/mcu/stm/stm32f7xx/include/mcu/mcu.h
hw/mcu/stm/stm32l0xx/include/mcu/mcu.h
hw/mcu/stm/stm32l1xx/include/mcu/mcu.h
hw/mcu/stm/stm32l4xx/include/mcu/mcu.h
hw/mcu/stm/stm32wbxx/include/mcu/mcu.h

STM32 MCUs have embedded bootloader that can be activated on reset when BOOT pin(s) are in certain state.
This change allows to start bootloader from application that is running from flash, so bootloader can be activated even if BOOT pins are soldered to boot system from flash.

STM32 Allow reboot to bootloader

---

hw/bsp/pinetime/boot-pinetime.ld
hw/bsp/pinetime/bsp.yml
hw/bsp/pinetime/include/bsp/bsp.h
hw/bsp/pinetime/pinetime.ld
hw/bsp/pinetime/pinetime_debug.sh
hw/bsp/pinetime/pinetime_download.sh
hw/bsp/pinetime/pkg.yml
hw/bsp/pinetime/src/arch/cortex_m4/gcc_startup_nrf52.s
hw/bsp/pinetime/src/hal_bsp.c
hw/bsp/pinetime/src/sbrk.c
hw/bsp/pinetime/syscfg.yml

This adds the bsp boilerplate including the pin definitions for the peripherals. A description of the device can be found here: https://wiki.pine64.org/index.php/PineTime
I plan to add drivers for the peripherals later.

bsp/pinetime: Add bsp for PineTime smartwatch

---

sys/id/include/id/id.h
sys/id/src/id.c
sys/id/syscfg.yml

This PR adds a new optional field, id/serial_mfg to be used for alternate serial numbers on devices during the manufacturing process.
The syscfg ID_SERIAL_MFG_PRESENT is disabled by default.

sys/id: Add optional id/serial_mfg field for storing manufacturer serial number

---

hw/bsp/pinetime/pkg.yml
hw/bsp/pinetime/src/hal_bsp.c
hw/drivers/chg_ctrl/sgm4056/include/sgm4056/sgm4056.h
hw/drivers/chg_ctrl/sgm4056/pkg.yml
hw/drivers/chg_ctrl/sgm4056/src/sgm4056.c
hw/drivers/chg_ctrl/sgm4056/syscfg.yml

This adds a driver for the SGM4056 driver. The first commit adds the base driver, second commit adds charge control integration to the base driver. The last commit adds driver initialization to the pinetime BSP.

Add SGM4056 charger driver to pinetime BSP

---

docs/os/bsp/index.rst
docs/os/bsp/pinetime.rst
docs/os/os_user_guide.rst

Add a new section to the documentation which lists the status of BSPs.
The first page is the status of the PineTime BSP.
This is part of an effort to add PineTime support to mynewt. This documents the progress of that effort.

docs/os/bsp: Add board support section

---

sys/log/full/include/log/log.h
sys/log/full/src/log.c
sys/log/stub/include/log/log.h

`const` recently added to `struct os_dev:od_name` (which is great) but using that name with the log module currently gives a compile error.

const correctness log name

---

repository.yml

This removes 'newt' warning when building JDP, since newt upgrade picks 0.0.1 for commit from master and keeps warning that 0.0.1 is not listed in compatibility map.

Adding a version into newt compatilibilty map, for version: 0.0.1

---

hw/bsp/dialog_da1469x-dk-pro/da1469x_serial.py
hw/bsp/dialog_da1469x-dk-pro/otp_tool.py

This PR provides script enhancements to 
1. da146x_serial.py: Makes the reset script optional. Use manual reset method or script to enter serial load mode.
2. da1469x_serial.py: Provide a common function that flushes serial port when initially opened.
3. otp_tool.py: Provide a common function that flushes serial port when initially opened.

da1469x: otp and serial script enhancements

---

mgmt/imgmgr/src/imgmgr_cli.c
sys/shell/src/shell_bridge.c

- This was not updated on transitioning to mcumgr
- Also, imgmgr cli was not updated to work with "shell exec", fixing that as well.
To be merged after: https://github.com/apache/mynewt-mcumgr/pull/76

shell_bridge: update to be used with mcumgr, update imgmgr cli to be used with shell_bridge

---

hw/mcu/stm/stm32f4xx/src/clock_stm32f4xx.c
hw/mcu/stm/stm32f4xx/syscfg.yml

I2SPLL clock configuration was missing so I2S peripheral
would not work without user code initialization.
Now I2SPLL configuration is added to syscfg, and PLL will be
configured when those values are set in BSP.

stm32f4: Add I2SPLL configuration

---

docs/os/modules/drivers/chg_ctrl.rst
docs/os/modules/drivers/chg_ctrl/chg_ctrl.rst
docs/os/modules/drivers/chg_ctrl/sgm4056.rst
docs/os/modules/drivers/driver.rst

This add documentation pages for charger-control and the SGM4056 driver. See also the tutorial in https://github.com/apache/mynewt-documentation/pull/94.

Documentation SGM4056 + Charge Control

---

hw/mcu/stm/stm32f0xx/src/hal_timer_freq.c

Case for TIM2 was missing, rendering this
timer unusable.

[STM32F0] Fix stm32_hal_timer_get_freq

---

hw/battery/src/battery_shell.c
hw/bsp/pinetime/pkg.yml
hw/bsp/pinetime/src/hal_bsp.c

This initializes the ADC for battery voltage measurement for PineTime BSP.
This also places a ifdef around the  battery shell code, as it doesn't compile when BATTERY_SHELL is disabled.

Battery for PineTime BSP

---

apps/flash_loader/src/fl.c
hw/mcu/stm/stm32_common/src/hal_flash.c

When WATCHDOG_INTERVAL is set to zero
- flash loader would try to initialize watchdog with 0 value
that would most likely not work
- hal_flash for STM MCUs would try to tickle uninitialized
watchdog and that would result in hard fault

watchdog: Fix places that ignore WATCHDOG_INTERVAL=0

---

.style_ignored_dirs
hw/bsp/pinetime/pinetime_debug.sh
hw/bsp/pinetime/syscfg.yml
hw/drivers/semihosting/include/semihosting/mbed_semihost_api.h
hw/drivers/semihosting/pkg.yml
hw/drivers/semihosting/src/mbed_semihost_api.c
sys/console/full/pkg.yml
sys/console/full/src/console.c
sys/console/full/src/console_priv.h
sys/console/full/src/semihosting_console.c
sys/console/full/syscfg.yml

This adds ARM semihosting console support to mynewt. It is only the tx side. And it is enabled by default for PineTime BSP.
This first commits adds the actual semihosting driver. It originates from mbed-os, with some modification to make it compatible with mynewt.
The second commit adds semihosting to the full console implementation.
The third commit adds support for the CFG_POST_INIT variable in the openocd script. This was needed to enable semihosting during debug sessions.
The last commit edits the PineTime BSP to enable the semihosting console in syscfg and debug.sh.

ARM semihosting console on pinetime

---

sys/config/src/config_mgmt.c
sys/config/syscfg.yml

Before PR: the `CONFIG_MGMT` syscfg setting disabled or enabled the config newtmgr command in its entirety.  There was no way to enable only the read half of the command (for example).
After PR: there is a second syscfg setting: `CONFIG_MGMT_RW`.  The semantics mirror the `CONFIG_CLI_RW` setting.  That is:
* If `CONFIG_MGMT` is 0, the entire command is disabled.
Otherwise:
* If `CONFIG_MGMT_RW` is 1, only read commands are allowed.
* If `CONFIG_MGMT_RW` is 2, only write commands are allowed.
* If `CONFIG_MGMT_RW` is 3, both reads and writes are allowed.

sys/config: read/write access config for mgmt cmd

---

hw/mcu/stm/stm32f0xx/stm32f0xx.ld

added __text symbol which is required for OS_CRASH_STACKTRACE

added __ text label to stm32f0xx linker script for OS_CRASH_STACKTRACE and alike

---

hw/drivers/i2s/i2s_stm32f1/include/i2s_stm32f1/i2s_stm32f1.h
hw/drivers/i2s/i2s_stm32f1/include/i2s_stm32f1/stm32_pin_cfg.h
hw/drivers/i2s/i2s_stm32f1/pkg.yml
hw/drivers/i2s/i2s_stm32f1/src/i2s_stm32f1.c
hw/drivers/i2s/i2s_stm32f1/syscfg.yml

Code implements I2S driver for STM32F1xx MCUs that have it.

hw/drivers/i2s: Add I2S driver for STM32F1 family

---

hw/drivers/i2s/i2s_nrf52/include/i2s_nrf52/i2s_nrf52.h
hw/drivers/i2s/i2s_nrf52/pkg.yml
hw/drivers/i2s/i2s_nrf52/src/i2s_nrf52.c
hw/drivers/i2s/i2s_nrf52/syscfg.yml

I2S driver implementation for NRF52 MCUs.

hw/drivers/i2s: Add I2S driver for NRF52 family

---

hw/mcu/stm/stm32f4xx/include/mcu/cmsis_nvic.h

Number of vector was not defined for STM32F401xC MCUs.

Define peripheral vectors number for STM32F401xC

---

sys/console/full/src/semihosting_console.c

The semihosting buffer was flush a byte too late, this caused a buffer
overflow.
Sorry for the introduced bug.

sys/console/full: Fix semihosting pointer arithmetic

---

hw/bsp/pinetime/pkg.yml
hw/bsp/pinetime/src/hal_bsp.c
hw/bsp/pinetime/syscfg.yml

This adds a syscfg for the battery and charger drivers. These options
are not available for bootloader builds. This reduces the size of the
bootloader significantly. The build failed before and now fits easily.
$ newt size boot-pinetime
Size of Application Image: app
FLASH     RAM
28     222 *fill*
1152       0 @apache-mynewt-core_crypto_mbedtls.a
382     444 @apache-mynewt-core_hw_bsp_pinetime.a
40       0 @apache-mynewt-core_hw_cmsis-core.a
594       1 @apache-mynewt-core_hw_hal.a
2112      32 @apache-mynewt-core_hw_mcu_nordic_nrf52xxx.a
310      24 @apache-mynewt-core_kernel_os.a
168       0 @apache-mynewt-core_libc_baselibc.a
654     128 @apache-mynewt-core_sys_flash_map.a
518      29 @apache-mynewt-core_sys_mfg.a
6       4 @apache-mynewt-core_sys_sysinit.a
4398    5996 …

hw/bsp/pinetime: Make drivers optional and disable for bootloader

---

encoding/base64/include/base64/base64.h
encoding/base64/selftest/src/base64_test.c
encoding/base64/selftest/src/base64_test_priv.h
encoding/base64/selftest/src/testcases/decode_basic.c
encoding/base64/selftest/src/testcases/decode_chunks.c
encoding/base64/selftest/src/testcases/decode_maxlen.c
encoding/base64/src/base64.c

Add support for chunked decoding.  This is done with a new struct which remembers the partial token it read from the previous (incomplete) chunk.
The main use case for this feature is: a large base64-encoded string split across several mbufs in a chain.  It was not possible to decode this using the old API.  Each buffer may have a length that is not a multiple of four, so a user could not decode each buffer separately.  Furthermore, the entire input may not be null-terminated and it is not always possible to add a terminator (that operation might require allocating another mbuf!).
This also fixes two bugs related to base64 decoding:
1. Never read past the end of the source string (even if its length is not a multiple of four).
2. Return error (-1) on all invalid inputs.  The decode …

encoding/base64: Support decode in chunks

---

hw/battery/src/battery.c

- The calloc failure was causing resource leaks in code using battery code

battery: calloc failure should be accounted for

---

hw/bsp/dialog_da1469x-dk-pro/otp_tool.py

Update comment about Cmds. For application/custom BSP specific
commands, define them in the custom BSP this module. Commands
can be assigned starting at an offset so that this command set
can be expanded if required.

OTP Tool: Add information about supporting custom commands

---

hw/mcu/stm/stm32_common/syscfg.yml

Code in stm32_periph,c use MYNEWT_VAL(SPI_2_MASTER) that are not define in yml file

missing syscfg for SPI2/SPI3 for stm32

---

net/oic/include/oic/oc_api.h
net/oic/include/oic/port/mynewt/ip.h
net/oic/include/oic/port/mynewt/stream.h
net/oic/include/oic/port/mynewt/tcp4.h
net/oic/include/oic/port/oc_connectivity.h
net/oic/pkg.yml
net/oic/src/api/oc_client_api.c
net/oic/src/api/oc_ri.c
net/oic/src/messaging/coap/engine.c
net/oic/src/port/mynewt/ble_adaptor.c
net/oic/src/port/mynewt/ip4_adaptor.c
net/oic/src/port/mynewt/stream.c
net/oic/src/port/mynewt/tcp4_adaptor.c
net/oic/syscfg.yml

This transport uses mn_sockets.
Unlike other transports, this one does not listen for new connections on its own.  Instead, the application needs to populate the transport with connections to be managed using oc_tcp4_add_conn().  There are a few too many parameters that need to be specified when listening for TCP connections.

TCP/IPv4 adaptor for CoAP

---

hw/mcu/nordic/nrf52xxx/include/mcu/cortex_m4.h
hw/mcu/nordic/nrf52xxx/syscfg.yml

Added a syscfg for the nRF52 family to make it so that OS_TICKS_PER_SEC can be customized on a case by case basis. This is particularly useful for cases where the OS event loop needs to respond more quickly, or with more granularity than at 128 ticks per second.
Should only be increased if necessary, as increasing OS_TICKS_PER_SEC increases system power consumption. Note that OS_TICKS_PER_SEC must be a power of 2 on the nRF52. The range values in the syscfg have all been tested working (blinky works) on the nRF52840 dev kit.
Resolves issue #1785.

Make OS_TICKS_PER_SEC configurable for the nRF52 family.

---

hw/drivers/i2s/i2s_stm32f4/include/i2s_stm32f4/i2s_stm32f4.h
hw/drivers/i2s/i2s_stm32f4/src/i2s_stm32f4.c
hw/drivers/i2s/i2s_stm32f4/syscfg.yml

STM32F4 does not have FIFO for SPI/I2S devices.
Driver was swapping DMA buffers in interrupt.
In some cases (depending on sample rate), CPU clock and usage,
DMA could be started to late to handle I2S stream in
worst case odd number of samples could be lost resulting
in channel swapping. If only one channel was used it could
result in random audio disruption.
This change enables hardware double buffering for for DMA.
Hardware buffer swapping leaves more time for software to
handle buffers.
As side effect if driver has only one buffer (application did
not provided next one yet) this single buffer is reused till
new one arrives.  For microphone it just drops incoming data
for speaker it will play same samples again.
Same approach (keeping old buffer till new one arrives)
is used in NRF5x …

hw/drivers/i2s: Use double buffering for STM32F4 family

---

hw/drivers/i2s/src/i2s.c

Function i2s_open() allows to pass NULL pointer for
client argument.
In one case this pointer was not checked for NULL value
before dereference.
This simply add missing NULL pointer check.

hw/drivers/i2s: Fix no client crash

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
hw/mcu/dialog/da1469x/src/da1469x_clock.c
hw/mcu/dialog/da1469x/src/da1469x_sleep.c
hw/mcu/dialog/da1469x/src/hal_system.c
hw/mcu/dialog/da1469x/syscfg.yml

System clock was always set to XTAL32M.
Now it can be also RC32M and PLL96
PLL96 can be turned on even if it is not used for system clock,
this is needed if USB is to be used.

hw/mcu/dialog: Add system clock choice

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh

If application was running on 96MHz PLL flash loader seems
to have problem flashing board.
This switches system clock to XTAL32 before flash loader code
is executed.

hw/bsp/dialog: Start flash loader with XTAL32M

---

hw/mcu/dialog/da1469x/src/arch/cortex_m33/da1469x_m33_sleep.S

SCB->CPACR value is loaded using r1 register as a base address, but
there was no proper value set there.

hw/mcu/dialog: Fix retaining SCB state in deep sleep

---

encoding/base64/src/base64.c
sys/shell/src/shell_nlip.c

Incoming NLIP frames were not being properly decoded.  This bug has two causes:
1. The trailing '\n' character was not being stripped before passing input to `nlip_process()`.  The base64 decode functions were recently made more strict such that they reject invalid input.  The old behavior was to stop at the first invalid character and return the partially decoded string.
The fix here is to trim the trailing '\n'.
2. The base64 code contained a buffer overrun bug.  An internal function expected a string but was passed an unterminated character array.  When the internal function called `strlen()` on its input, the result was undefined behavior.  Consequently, base64 decoding would fail with some optimization levels.
The fix is to change the intermediate function (`process_token()`) to …

Fix NLIP receives

---

util/scfg/src/scfg.c

When scfg was implemented, sys/config did not support unsigned integer
types.  Support has since been added to sys/config, but scfg still
rejects them.
This commit makes scfg not reject settings with unsigned integer types.

util/scfg: Support for unsigned integer types

---

hw/mcu/stm/stm32_common/src/stm32_periph.c

The stm32_periph.c file may not include os_cputime.h if certain
syscfg values are not set. This explicitly include os_cputime.h
if OS_CPUTIME_TIMER_NUM is >= 0.

hw/mcu/stm/stm32_common: Add include for os_cputime.h

---

net/oic/src/port/mynewt/adaptor.c

oc_connectivity_init() would succeed if at least one interface was successfully initialized.  This allowed interfaces to silently fail.
This commit changes oc_connectivity_init() so that it fails unless *all* interfaces successfully initialize.

net/oic: Fail init if any interface fails

---

hw/mcu/dialog/da1469x/src/hal_gpio.c

We need PDC entry to wakeup from deep sleep.

hw/mcu/dialog: Configure PDC for GPIO irq

---

hw/mcu/stm/stm32_common/include/stm32_common/stm32_hal.h
hw/mcu/stm/stm32_common/src/hal_uart.c
hw/mcu/stm/stm32_common/src/stm32_periph.c
hw/mcu/stm/stm32_common/syscfg.yml

Adds support for configuring UART3-UART7, increasing the maximum number of configurable UARTs on STM32 from 3 to 8.

Add support for all UARTS on STM32

---

hw/mcu/nordic/nrf52xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/nrf52_clock.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

This is needed to be able to run NRF52 devices without an external 32MHz crystal.
BLE will not work when set to HFINT, but everything else should.
The only restriction is that the LFCLK source cannot be LFSYNTH
In the rare case where MCU_HFCLK_SOURCE is set to HFINT and BLE is enabled, an assert(0) will be hit in nrf52_clock_hfxo_request/release

Add syscfg option to select HFCLK source for NRF52 devices

---

hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c
hw/mcu/nordic/nrf52xxx/src/hal_spi.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

Various devices in the NRF52 family have different number of SPI/TWI peripherals.
The NRF52810 only has TWI0 and SPI0 where the NRF52811 also has SPI1.
Unfortunately, NRF52810 and NRF52811 don't have the same IRQn names (and values) for TWI and SPI peripherals.
The peripheral/irq table is as follows:
```
SPI0    SPI1    TWI0    TWI1
NRF52810    IRQ4    N/A     IRQ3    N/A
NRF52811    IRQ4    IRQ3    IRQ3    N/A
NRF52832    IRQ3    IRQ4    IRQ3    IRQ4
NRF52840    IRQ3    IRQ4    IRQ3    IRQ4
```
This change updates the nrf52xxx syscfg.yml's peripheral restrictions as well as hal_spi.c and i2c_nrf52_twim.c
The IRQn names are as follows:
nrf52.h/nrf52840.h
```
SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0_IRQn=   3,  /*!< 3  SPIM0_SPIS0_TWIM0_TWIS0_SPI0_TWI0                                      */ …
```

Fix SPI/TWI support for NRF52810 and NRF52811

---

hw/drivers/crypto/include/crypto/aes_alt.h
hw/drivers/crypto/src/mbedtls_aes_alt.c

Let https://github.com/apache/mynewt-core/pull/2175 merge and then merge the top change.

mbedtls_aes_alt: add setkey for decyption, validate input, fix data type and return type

---

hw/usb/tinyusb/da146xx/include/tusb_hw.h
hw/usb/tinyusb/da146xx/pkg.yml
hw/usb/tinyusb/da146xx/src/da1469x.c
hw/usb/tinyusb/da146xx/syscfg.yml

This provides code for hardware initialization: GPIO and clock.
This may be merged after TinyUSB part is merged.
https://github.com/hathach/tinyusb/pull/427

tinyusb: Add hardware initialization for DA1469x

---

hw/mcu/stm/stm32_common/src/hal_uart.c

The uart irq handler for certain stm32 mcu's was not handling
the clearing of an rx overrun error. This code should handle it
properly.

hw/mcu/stm/stm32_common: Clear overrun error

---

hw/drivers/crypto/crypto_da1469x/src/crypto_da1469x.c
hw/mcu/dialog/da14699/include/mcu/mcu.h

The da1469x DMA should use a different address range to
access the flash based addresses. When the input buffer
is QSPI Flash based, perform the translation. RAM based buffers
do not need this translation.

da1469x: Use appropriate address range for the crypto input

---

hw/mcu/stm/stm32_common/src/stm32_driver_mod_i2c_v1.c

STM32F1 needs workarounds for silicon errors.
Workaround stolen from ST HAL I2C driver.

Fix I2C receive for STM32F1

---

hw/drivers/crypto/crypto_da1469x/src/crypto_da1469x.c
hw/drivers/flash/enc_flash/ef_da1469x/include/ef_da1469x/ef_da1469x.h
hw/drivers/flash/enc_flash/ef_da1469x/pkg.yml
hw/drivers/flash/enc_flash/ef_da1469x/src/hw_enc_flash.c
hw/mcu/dialog/da1469x/include/mcu/da1469x_otp.h

The crypto driver provides common code for encryption operations.
Use this instead of accessing the crypto hardware directly.

da1469x: Use the crypto driver for encrypted flash operations

---

hw/mcu/stm/stm32_common/src/hal_os_tick.c
hw/mcu/stm/stm32_common/syscfg.yml
hw/mcu/stm/stm32f1xx/include/mcu/cortex_m3.h
hw/mcu/stm/stm32f1xx/src/rtc_tick_stm32f1xx.c

Tickles sleep can be used when LSE oscillator is used and OS_TICKS_PER_SEC is set to power of 2.

Add tickles sleep for STM32F1 CPU

---

hw/bus/src/bus.c

We should check if APIs are called on proper objects - this is only
valid if "BUS_DEBUG_OS_DEV: 1".

hw/bus: Add missing debug checks

---

hw/mcu/dialog/da1469x/src/hal_gpio.c

Routine which adds PCC entry overwrites 'i' value so needs to be done
after interrupt struct is initialized, otherwise things will not work
as expected.

mcu/dialog: Fix gpio irq init with deep sleep enabled

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_sleep.h
hw/mcu/dialog/da1469x/src/arch/cortex_m33/da1469x_m33_sleep.S
hw/mcu/dialog/da1469x/src/da1469x_sleep.c
hw/mcu/dialog/da1469x/syscfg.yml

Adding configurability to da1469x_m33_sleep.S QSPI in deep sleep. MCU_DEEP_SLEEP_QSPIC_QUAD_DISABLE.
Adding retention for more IPRs.
Adding pre and post callbacks for dep_sleep
@andrzej-kaczmarek

da1469x_sleep: Adding deep sleep pre/post callbacks, and QSPI configurability in deep sleep

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
hw/mcu/dialog/da1469x/src/da1469x_clock.c

Dialog advises to use special startup procedure to avoid
rare hardware condition when PLL will not start.
PLL LDO is also switched off when PLL is not needed.

hw/mcu/dialog: Update PLL start-up procedure

---

kernel/os/src/os_dev.c

**Background:**
The flash loader application initializes the flash without
going through the os_dev APIs and by default OS_SCHEDULING
is set to 0. Hence no os initialization is done.
If the flash_loader needs to access other flash interfaces such as
encrypted flash, that is dependent on os features.
Turning OS_SCHEDULING can result in the hal_bsp_init being
invoked twice. Once through os_* and then from flash_loader.
Though this is should be avoided, in such scenario, it is seen
that the global device list gets incorrectly updated with entries
pointing to itself as next device, thus creating an infinite loop.
**Fix:**
If the device is already present in the global list,
calling os_dev_add() can potentially result in an incorrect
list. Fix this by checking for the device when the list
is …

kernel/os: os_dev_add check to see if device is already present

---

apps/rust_blinky/Cargo.toml
apps/rust_blinky/build.rs
apps/rust_blinky/cargo_build.sh
apps/rust_blinky/pkg.yml
apps/rust_blinky/src/bindings.rs
apps/rust_blinky/src/lib.rs
apps/rust_blinky/wrapper.h

This added the Rust blinky application as explained in https://mynewt.apache.org/latest/tutorials/other/rust.html
Then it extends it by using bindgen to generate Rust code from the actual C-header as used for the C code. Then use the generated code in the Rust application to make it compatible with all BSP.

apps/rust_blinky: Add blinky app using Rust language

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

These two variables need to be uint16_t when MCU_DMA_CHAN_MAX is > 8.
Currently the code is as follows, which results in not enough bit flags for DMA channel # 9 or higher:
```
#if (MCU_DMA_CHAN_MAX) > 8
static uint8_t g_da1469x_dma_acquired;
static uint8_t g_da1469x_dma_isr_set;
#else
static uint16_t g_da1469x_dma_acquired;
static uint16_t g_da1469x_dma_isr_set;
#endif
```

hw/mcu/dialog: Fix size of flag variables when MCU_DMA_CHAN_MAX > 8

---

hw/drivers/i2s/i2s_stm32f1/src/i2s_stm32f1.c
hw/drivers/i2s/i2s_stm32f4/src/i2s_stm32f4.c

This adds interrupt tracing code so SystemView can be
used for load analyzes.

hw/drivers/i2s: Add sysview interrupt tracing to STM drivers

---

hw/mcu/stm/stm32_common/src/hal_os_tick.c
hw/mcu/stm/stm32f1xx/src/rtc_tick_stm32f1xx.c

Reading RAM or FLASH from Debugger on STM32 MCUs in SLEEP (WFI)
returns wrong values.
If makes it almost impossible to use with SystemView when application
runs at high clock speed and spend a lot of time in SLEEP mode.
SystemView is often not able to correctly read header for RTT
virtually preventing tool to detect instrumentation.
This change replaces WFI with busy loop waiting for interrupts when
OS_SYSVIEW is defined.

stm32: Disable WFI when OS_SYSVIEW is defined

---

hw/mcu/dialog/da1469x/src/da1469x_clock.c

There was intentional preprocessor generated error that
was supposed to detect when register definition file is updated.
It turned out that there are some custom register files that already
has this definition present yet normal DA1469xAB.h file still does
not have it.
Preprocessor error is now removed to avid build errors.

hw/mcu/dialog: Remove preprocessor error

---

apps/crypto_test/src/main.c

Along with ticks, print in milliseconds as well.

crypto_test: get stats in milliseconds

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c
hw/mcu/dialog/da1469x/syscfg.yml

For hw/mcu/dialog/da1469x, adds a syscfg `MCU_DMA_IRQ_PRIO` to allow setting the interrupt priority of DMA_IRQn at system initialization time.

hw/mcu/dialog: Add syscfg to allow setting a custom DMA_IRQn priority.

---

kernel/os/include/os/os_mempool.h

[Originally posted at https://github.com/apache/mynewt-nimble/pull/848 . See discussion there for more info]
Use `OS_ALIGNMENT` as everywhere else in the code, instead of `OS_CFG_ALIGNMENT`.
Also adds CHERI-support, which has 128-bit pointers.
I am not sure where `OS_CFG_ALIGNMENT`/`OS_CFG_ALIGN_4` were supposed to be defined (maybe some mynewt definitions?), but we have `OS_ALIGNMENT` for this.

Rework `os_membuf_t` definition + add CHERI support

---

net/oic/include/oic/oc_gatt.h
net/oic/include/oic/port/mynewt/ble.h
net/oic/src/port/mynewt/ble_adaptor.c
net/oic/syscfg.yml

This PR enables an oc client to work with ble gatt transport adaptor in as a ble central (rather than a peripheral). This had never been done and therefore did not work. As a client and a central, we need to write to a the request characteristic and listen for notifications on the response characteristic. 
These changes add a new syscfg flag `OC_BLE_CENTRAL` to `net/oic/syscfg.yml` with a default value 0. Setting this value to 1 defines a function for receiving response characteristic notifications and enables characteristic write requests.

Allow oc gatt client as BLE central

---

hw/drivers/sensors/bmp388/include/bmp388/bmp388.h
hw/drivers/sensors/bmp388/src/bmp388.c
hw/drivers/sensors/bmp388/syscfg.yml

Added new driver code for BMP388 to limit the amount of i2c traffic needed to get sensor data 
The existing BMP388 driver read modes have a couple potential issues depending on the desired behavior/usage
First issue is that in BMP388_read_mode_poll() every time the sensor is read it requires re-configuring the device, which creates a significant amount of i2c traffic for each read
Second issue is that in bmp388_read_mode_fifo() the main portion of the logic sits in a for(;;) loop that take approximately 10 seconds before it will error out in some situations.  The fifo mode also can cause issues if there are multiple BMP388 sensors running in the same context.
This PR creates a third mode called hybrid for lack of a better term that reuses some of the logic of the other modes, but allows …

BMP388 Pressure/temperature sensor i2c communtication optimization

---

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
hw/drivers/ipc_nrf5340/syscfg.yml

This allows to configure GPIOs that should be controlled by Network
Core. For race-free execution GPIOs are configured from IPC subsystem
when Networking Core is force-off.

hw/ipc_nrf5340: Add support for passing GPIO control

---

hw/bsp/pinetime/syscfg.yml

Change the watchdog settings, as the new version of the
default bootloader for the PineTime also setup a watchdog with a 7
second interval. Without this change the processor will be reset a few
seconds after the application was started.

hw/bsp/pinetime: Setup 7 second watchdog

---

hw/drivers/i2s/include/i2s/i2s.h
hw/drivers/i2s/src/i2s.c
hw/drivers/i2s/syscfg.yml

It is easy to accidentally write past the sample buffer.
Such writes could lead to difficult to trace memory corruptions.
With this change most common errors will be detected early.
To have checking code working syscfg value I2S_BUFFER_GUARD
should specify how many bytes before and after actual data
is reserved and filled with pattern.

hw/drivers/i2s: Add buffer overwrite check

---

hw/battery/syscfg.yml

BATTERY_DRIVERS_MAX was used in battery.h but it was never
defined, this fixes this inconsistency.
Thanks @5frank for spotting this.

battery: Add missing syscfg definition

---

docs/os/modules/console/console.rst
docs/os/modules/fcb/fcb.rst
docs/os/modules/hal/hal.rst
docs/os/modules/hal/hal_flash/hal_flash.rst
docs/os/modules/logs/logs.rst
docs/os/modules/sensor_framework/sensor_api.rst
docs/os/modules/sensor_framework/sensor_create.rst
docs/os/modules/sensor_framework/sensor_driver.rst
docs/os/modules/sensor_framework/sensor_listener_api.rst
docs/os/modules/shell/shell.rst
docs/os/modules/split/split.rst
docs/os/modules/system_modules.rst
encoding/json/include/json/json.h
fs/fcb/include/fcb/fcb.h
fs/fcb2/include/fcb/fcb2.h
hw/sensor/include/sensor/sensor.h
kernel/os/include/os/os_callout.h
kernel/os/include/os/os_heap.h
kernel/os/include/os/os_mutex.h

This fixes some of the warning when generating the mynewt documentation. It fixes broken links, syntax warnings and doxygen warnings.

Documentation fixes

---

compiler/gdbmacros/flash_loader.gdb
hw/bsp/dialog_da1469x-dk-pro/bsp.yml

There were two problems with this gdb script that prevent
it usage on Windows:
1. echo command from cmd.exe don't have -n option
shell command that was creating foo.gdb script used echo which
did not used /usb/bin/echo.exe from msys, but Windows build in
echo that does not have -n option
2. /tmp folder is not valid for cmd.exe redirection
To fix this problems echo is not used, instead awk that is already
present is used to output whole line
foo.gdb is not created in /tmp folder (which would fail on Windows)
instead is created in current folder for a while. It was deleted
after source command so it's not that important to have it in /tmp
folder.
bsp.yml had load and debug overwrites for Windows, unfortunately
.cmd files were not created for this bsp.
Since newt can handle .sh files on …

da1469x load and debug fixes

---

sys/log/full/src/log_cbmem.c

The return code of succesfull log_cbmem_walk was 0, even when the loop
ended early. In case of an early loop break, we want to return the rc of
the walked function.
This is needed to make `newtmgr log show --all` work, as the rc is
passed to the client to indicate more data available.
The return codes of the log_walk functions seem a bit of a mess, as they both indicate an error state as rc of the walk_func. To bad C doesn't support multiple return values.

sys/log/cbmem: Fix return code for early break in log_cbmem_walk

---

apps/sensors_test/src/main.c
apps/slinky/src/main.c
apps/slinky_oic/src/main.c
apps/splitty/src/main.c
docs/os/modules/logs/logs.rst

The size passed to cbmem_init is in bytes. Therefore the datatype of
cbmem_buf needs to be one byte long.

apps: Fix cbmem sizes

---

sys/stats/stub/include/stats/stats.h

Macro STATS_GET don't make sense in stub (it do in full)

remove STATS_GET macro from stats/stub

---

apps/loraping/src/main.c

Timer is inited and never used and some BSP dont have timer 4.

remove timer 4 initialisation from loraping

---

compiler/gdbmacros/flash_loader.gdb

flash_loader.gdb generated script that was later sourced back
into gdb with file_sz variable computed in shell.
This script had extra backslash that was not really needed.
awk complained about this extra \

flash_loader: Fix awk script

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_pd.h
hw/mcu/dialog/da1469x/src/da1469x_pd.c
hw/mcu/dialog/da1469x/src/hal_gpio.c

da1469x_pd.c: Add function to get power domain reference counts.
hal_gpio.c: Restore Px_DATA_REG from retained values. Seeing issues/hangs when attempting to restore it from itself, when it is possibly not retained when PD_COM is down.

da1469x_pd: add function to get power domain reference counts

---

hw/battery/src/battery.c
hw/battery/src/battery_adc.c
hw/battery/src/battery_prop.c
hw/battery/src/battery_shell.c

GCC complains about a strncpy call when building using build_profile speed.
This warning indicates a possible string truncation. The only proper
solution I could find was to decrease the buf_size and explicitly set a
zero byte.
Error: In function 'battery_prop_get_name',
inlined from 'battery_find_property_by_name' at repos/apache-mynewt-core/hw/battery/src/battery.c:392:9:
repos/apache-mynewt-core/hw/battery/src/battery.c:379:5: error: 'strncpy' specified bound 20 equals destination size [-Werror=stringop-truncation]
379 |     strncpy(buf, driver_prop->bdp_name, buf_size);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

hw/battery: Fix strncpy warning

---

hw/mcu/stm/stm32f1xx/mcu_cli/pkg.yml
hw/mcu/stm/stm32f1xx/mcu_cli/src/mcu_cli.c
hw/mcu/stm/stm32f1xx/mcu_cli/syscfg.yml

Package adds shell command for display clocks and
peripheral clock.
```
compat> select mcu
mcu> info
015511 Clocks:
015511   SYSCLK: 72000000
015513     source PLL
015515   HSI: off
015516   HSE: on
015518   PLL: on
015519   LSI: on
015521   LSE: on
015523 Peripherals:
015524   AHB HCLK: 72000000
015527     SRAM   on
015529     FLITF  on
015531   APB1 PCLK1: 36000000
015533     TIM2   on
015535     TIM3   on
015537     USART2 on
015539     PWR    on
015541   APB2 PCLK2: 72000000
015544     AFIO   on
015546     IOA    on
015548     IOB    on
015549     IOC    on
```
```
mcu> info all
041774 Clocks:
041774   SYSCLK: 72000000
041776     source PLL
041778   HSI: off
041779   HSE: on
041781   PLL: on
041782   LSI: on
041784   LSE: on
041786 Peripherals:
041787   AHB HCLK: 72000000
041790 …
```

add MCU cli for STM32F1

---

hw/mcu/stm/stm32_common/src/hal_spi.c

SPI_4 maps to STM SPI5.
Alternate function for this block is not always GPIO_AF5_SPI5.
For some MCUs (STM32F411) it should be GPIO_AF6_SPI5.
So now one that is defined by STM HAL will be used.

stm32/hal_spi: Fix alternate function spec for SPI_4

---

hw/bsp/pinetime/syscfg.yml

Enable the I2C port 1 for the Pinetime. Maximum speed of 400 KHz is set since connected I2C slave devices are >= 400 KHz.

hw/bsp/pinetime: Setup I2C

---

hw/bsp/pinetime/pinetime_debug.sh
hw/bsp/pinetime/pinetime_download.sh
hw/scripts/common.sh
hw/scripts/openocd.sh

Here is a new bash funtion in _hw/scripts/common.sh_ to detect connected programmers. I've added detection by USB vendor:product IDs, but other methods could be implemented. At the moment I've tested with Segger's **jlink** nrf5x on-board, **cmsis-dap** on STM32 and **stlink-v2** and **stlink-v2.1**.
Detected programmer is put on **DETECTED_PROGRAMMER variable** so download or debug script for some board will be able to use the bash function. For example, scripts for pinetime BSP are using this feature.

Detect connected programmer to download and debug firmware

---

hw/drivers/sensors/bmp388/src/bmp388.c

Fix was provided by Bosch.
At high altitudes there is a potential for rollover in the compensate_pressure() function.  To prevent that, Bosch provided a fix with a divide by 10 in the affected code and then a multiply by 10 after to bring the final value back to the expected value.

This change adds protection against rollover at high altitudes.

---

hw/mcu/dialog/da1469x/src/da1469x_clock.c

RC32K was used to wait for XTAL32M to settle.
Unfortunately it's declared frequency range is 25kHz to 39kHz.
XTAL32M settling time was taken into account for CMAC wakeup
calculation but it can be very inaccurate when RC32K is used.
This can result in CMAC crashes due to assert when Cortex-M0
wakes up to late.
This switches to 256kHz clock (derived from RC32M) that is much
mode precise.

hw/mcu/dialog: Use 256kHz clock during XTAL32M settling

---

hw/mcu/dialog/da1469x/src/hal_system_start.c

This patch adds handling of both legacy values and updated values for the
IMAGE_TLV_AES_NONCE and IMAGE_TLV_SECRET_ID TLVs.  The reason for the change
is to avoid overlapping TLV usage with upstream mcuboot.

hw/mcu/dialog: Support updated TLV values for booting

---

hw/mcu/dialog/da1469x/src/arch/cortex_m33/da1469x_m33_sleep.S

QSPIC code changes r0 register which is set in the code before to
indicate that deep sleep did not happen. This means we will always
return non-zero which means "deep sleep *did* happen" in da1469x_sleep.
It likely is not not much of a problem except we will always take
longer path when exiting from da1469x_sleep.

hw/mcu/dialog: Fix return value from da1469x_m33_sleep

---

compiler/gdbmacros/cmac_core_dump.gdb

Core file from DA1469x platform contains embedded memory
dump from Cortex-M0 core.
cmac_core_dump.gdb adds command to extract cmac core to separate core
file that can be analyzed.
Crashes inside interrupt handler were not tested.

gdbmacros: Add script to extract cmac core

---

libc/baselibc/include/assert.h

Currently **static_assert** is only defined when
```__STDC_VERSION__ >= 201112L```.
Static asserts present in header files should
use static_assert to be able to build with C++.
For non C++ build it should map **_Static_assert**.
While _Static_assert is C11 feature it can be
present for older compilers.
This drops checking for compiler version,
if compiler does not support _Static_assert it
will fail anyway.
This resolves #2040

baselibc: Always define static_assert for C

---

hw/bsp/nucleo-f030r8/include/bsp/bsp.h
hw/bsp/nucleo-f072rb/include/bsp/bsp.h
hw/bsp/nucleo-f103rb/include/bsp/bsp.h
hw/bsp/nucleo-f303k8/include/bsp/bsp.h
hw/bsp/nucleo-f303re/include/bsp/bsp.h
hw/bsp/nucleo-f401re/include/bsp/bsp.h
hw/bsp/nucleo-f413zh/include/bsp/bsp.h
hw/bsp/nucleo-f439zi/include/bsp/bsp.h
hw/bsp/nucleo-f746zg/include/bsp/bsp.h
hw/bsp/nucleo-f767zi/include/bsp/bsp.h
hw/bsp/nucleo-l476rg/include/bsp/bsp.h

All nucleo 64/144 boards have button at PC13.
Some boards already had this definition.
Some boards had BTN_USER_1 instead.
Some did not have user button definition at all.
Now all have BUTTON_1 that is also present in other
BSPs.

nucleo: Add missing BUTTON_1 definitions

---

hw/bsp/dialog_da1469x-dk-pro/src/arch/cortex_m33/gcc_startup_da1469x.S
hw/mcu/dialog/da1469x/da1469x.ld
hw/mcu/dialog/da1469x/include/mcu/cortex_m33.h
hw/mcu/dialog/da1469x/src/arch/cortex_m33/da1469x_m33_sleep.S
hw/mcu/dialog/da1469x/src/hal_system_start.c
hw/mcu/dialog/da1469x/src/system_da1469x.c
hw/mcu/dialog/da1469x/syscfg.yml
hw/scripts/micro-trace-buffer.py
kernel/os/src/arch/cortex_m33/os_fault.c

This adds support for Micro Trace Buffer (MTB) which allows to store trace information of executed instructions in dedicated RAM area. Stored data can be then used to recreate exact program flow. GDB script is also provided to decode contents of MTB easily.
See commit messages for extra info on how to use this feature.

hw/mcu/dialog: Add support for Micro Trace Buffer (MTB)

---

hw/mcu/dialog/da1469x/src/hal_uart.c
hw/mcu/dialog/da1469x/syscfg.yml

When UART RX pin is shorted to ground and UART is enabled it enters
busy state.
In this state busy interrupt fires constantly it prevents non-interrupt code
to be executed and can lead to watchdog reboot.
In function hal_uart_config() pullup was added to RX pin to enable configuration
(which was not successful in busy state).
This counter measure worked fined when RX pin was floating and just happen to be
low for a while but internal pull-up resistor was enough to make is stable.
However when RX pin is shorted to ground internal pull-up will not solve the problem.
- now RX pin is not routed to UART during configuration to prevent busy state at that time.
- RX can be disconnected from UART once it enters busy state, pin is reconfigured for
GPIO with interrupt to detect end of short …

hw/mcu/dialog: Disconnect UART RX pin when grounded

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h
hw/mcu/dialog/da1469x/src/da1469x_clock.c

There was code to calibrate RCX oscillator.
Now similar code can measure RC32K and RC32M if needed.

hw/mcu/dialog: Add calibration of RC32K and RC32M

---

hw/drivers/sensors/bmp388/src/bmp388.c

Compiler detects this:
bmp388.c:3596:12: error: 'rc' may be used uninitialized in this function
Fixed by initializing variable to 0.

hw/drivers/bmp388: Fix compilation warning

---

hw/drivers/i2s/i2s_stm32f4/src/i2s_stm32f4.c

I2S number can very from MCU to MCU.
I2S2 and I2S3 are common but not many MCUs have 5 I2S blocks.
This adds proper preprocessor guards against non existing configurations.

hw/drivers/i2s: Fix build for MCUs that have fewer I2S

---

apps/bleprph_oic/pkg.yml
apps/bleprph_oic/syscfg.yml
apps/blesplit/pkg.yml
apps/blesplit/syscfg.yml
apps/bleuart/pkg.yml
apps/bleuart/syscfg.yml
apps/bsncent/pkg.yml
apps/bsncent/syscfg.yml
apps/bsnprph/pkg.yml
apps/bsnprph/syscfg.yml
apps/ocf_sample/pkg.yml
apps/ocf_sample/syscfg.yml
apps/sensors_test/pkg.yml
apps/sensors_test/syscfg.yml
apps/testbench/pkg.yml
apps/testbench/syscfg.yml

store/ram was deprecated
Now application are configured to use store/config and
BLE_STORE_CONFIG_PERSIST set to 0.

apps/ble: Use store/config instead of store/ram

---

hw/util/button/src/button.c
hw/util/button/syscfg.yml
net/ip/native_sockets/src/native_sock.c
net/ip/native_sockets/syscfg.yml

Button and native sockets had some time values that measured in ticks
but value used indicated that normal time values could be applied.
syscfg values were updated to be more natural for human the machine.

remove OS_TICKS_PER_SEC from syscfg when not needed

---

hw/drivers/uart/include/uart/uart.h

This adds thin wrapper to open UART device.
Generic os_dev_open has opaque pointer that in case of UART has
configuration but it's not clear what should be passed as argument
without looking to UART code.
With this change parameter check is enhanced as well as readability.

hw/drivers/uart: Add uart_open function

---

hw/mcu/dialog/da1469x/src/hal_gpio.c

When GPIO pin is configured as input with interrupt it seems
reasonable to be able to release this interrupt during
GPIO interrupt handler without need to go through threaded code.
To achieve this WKUP_CLEAR_PX() must be called with correct pin
number. If interrupt handler released currently handled GPIO
interrupt handler pin in hal_gpio_irqs is no longer valid.
Now local copy of pin number is used when WKUP_CLEAR_PX is called
to make sure releasing GPIO IRQ is safe.

hw/mcu/da1469x: Allow to release GPIO pin in ISR

---

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c

File 'mcu/nrf5340_hal.h' is application core specific and is not
used when file is build for network code.
IPC_NRF5340_NET_GPIO is defined in application build only
and is used to conditionally include offending file.

hw/ipc_nrf5340: Fix build for network core

---

net/lora/node/src/mac/LoRaMac.c

LoRaNode thread can access RxDone data before it's filled in if the submitting thread has a lower priority, typically not a good idea. 
Second commit addresses the rx_win1 and rx_win2 issues where we can be stuck waiting for a timeout on rx_win1 because
rx_win2 has already started (and prevented a timeout of rx_win1).

net/lora/node: RxDone event and rx_win1 timeout

---

sys/log/full/src/log_fcb.c

In scenarios where the interested record lies towards the end of a
large circular buffer, walking it from the beginning can take up
significant amount of time.
It is possible that the thread that walks the log is shared among
other user interfaces and until the bookmarks are built up, flash
based walks and lookups can make the system quite slow to respond.
Optimize this by beginning to walk from the flash area that is closer
to the latest one in use.
In the tests performed, the walk time was reduced by 2 orders of
magnitude (e.g 9000 ms to 50 ms).

log_fcb: optimize finding records towards the end of circular buffer

---

hw/mcu/dialog/da1469x/include/mcu/da1469x_dma.h

hw/mcu/dialog: Fix typo in da1469x_dma.h

---

hw/mcu/dialog/da1469x/src/hal_watchdog.c

RCX oscillator runs at 15kHz.  Watchdog initialization did not account
for both RCX and EXT 32kHz oscillators when calculating WDT init value.

hw/mcu/dialog: Fix watchdog init when using RCX

---

hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml
sys/flash_map/syscfg.yml

This solves the problem of sensor_creator usage along with SPI flash that is present in flash map.
If BSP uses SPI flash and sensor creator with SPI devices that are connected to the same
SPI bus as flash, not initializing chip select pin for those other devices may lead to wrong
reads from flash.
It happens when uninitialized yet GPIO is still perceived by sensor as active and sensor responds
to requests that should be answered by flash.
This adds sensor_dev_init() that has initialization code taken from sensor_dev_create().
Thai also changes flash_map initialization stage to accommodate for other initialization that
could be needed before flash_map can be initialized.

sensor creator init split

---

hw/mcu/dialog/da1469x/src/da1469x_clock.c
hw/mcu/dialog/da1469x/syscfg.yml

Code prior to this change fixed the reference count value used for RCX calibration to 100. This change allows it to be configured by the user as a value of 100 makes for a long calibration time (on the order of 6.67 msecs).

hw/mcu/da1469x: Allow RCX reference count calibration value to be configurable

---

hw/mcu/nordic/nrf52xxx/src/hal_system.c
hw/mcu/nordic/nrf52xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/nrf52_clock.c

hal_timer and hal_system_clock_start both enabled the HFXO directly. 
Now they use the nrf52_clock_hfxo_request, and where suitable also nrf52_clock_hfxo_release.

hw/mcu/nordic/nrf52xxx: Using hfxo_request and release. Addresses #2393.

---

hw/usb/tinyusb/cdc_console/src/cdc_console.c
sys/console/full/src/console.c
sys/console/full/src/console_priv.h

Add usb_cdc_console_is_init() to return the usb cdc console
initialization status. Without this, usb console log won't work.

Add function to check usb console init

---

hw/battery/src/battery.c

Fixed two bugs related to bounds checking. These caused problems when
searching for a non-existing property.

hw/battery: Fix bounds checking

---

crypto/tinycrypt/include/tinycrypt/utils.h
crypto/tinycrypt/src/cbc_mode.c
crypto/tinycrypt/src/cmac_mode.c
crypto/tinycrypt/src/ecc_dh.c
crypto/tinycrypt/src/ecc_dsa.c
crypto/tinycrypt/src/hmac.c
crypto/tinycrypt/src/hmac_prng.c

Tinycrypt has not been updated in `mynewt-core` since version `0.2.8`. It has since received numerous bug fixes(without a release), such as [Fix incorrect buffer size](https://github.com/intel/tinycrypt/commit/da923ca2293018e0ba7102d6650867aa6812b0e8) , [Fix HMAC-PRNG implementation](https://github.com/intel/tinycrypt/commit/6e0eb53fc8403988f97345e94081b0453f47231d). Would like these fixes, upto the latest commit to be merged into the core-repo.

crypto/tinycrypt: Update library to master

---

hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c

I2C implementation was prone to race condition when
transfer was finished due to reading/writing all requested data,
but STOP condition flag was not raised yet by I2C controller.
It lead to cases when STOP condition flag was stopping transfers
even thou this flag was valid for previous transmission.

fix da1469x i2c stop condition race condition

---

hw/drivers/i2s/i2s_da1469x/include/i2s_da1469x/i2s_da1469x.h
hw/drivers/i2s/i2s_da1469x/pkg.yml
hw/drivers/i2s/i2s_da1469x/src/i2s_da1469x.c

I2S driver implementation for DA1469X MCUs.
Only TX part for now (speaker).
Three data formats supported 16/16 16/32 and 32/32.

hw/drivers/i2s: Add I2S driver for DA1469x family

---

hw/drivers/uart/uart_da1469x/include/uart_da1469x/uart_da1469x.h
hw/drivers/uart/uart_da1469x/pkg.yml
hw/drivers/uart/uart_da1469x/src/uart_da1469x.c
hw/drivers/uart/uart_da1469x/syscfg.yml
hw/mcu/dialog/da1469x/pkg.yml
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/mcu/dialog/da1469x/syscfg.yml

Driver that shuts down UART when RX line goes down.
Uses de-bouncing to wait for RX line to be stable high again before
re-enabling UART.

Add da1469x uart driver

---

hw/drivers/mmc/src/mmc.c

Apparently the lowest clock rate acceptable by hal_spi_init is 125KHz, so if 100KHz is used hal_spi_init will always fail.

Fixed MMC starting frequency

---

hw/mcu/stm/stm32l0xx/stm32l073.ld

File stm32l073.ld should have been added when BSP for
nucleo-l073rz was committed by 'Add nucleo-l073rz BSP'
File is really a copy of stm32l072.ld.

hw/mcu/stm: Add missing ld file for nucleo-l073rz BSP

---

hw/mcu/dialog/da1469x/pkg.yml
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/mcu/dialog/da1469x/syscfg.yml

Introduction of dedicated UART driver broke build when user
decided to use HAL driver instead.
When HAL_UART was set in syscfg.yml da1469x_periph.c would not
build due to conditional compilation inconsistency.
This also changes HAL_UART syscfg to UART_HAL which is more
consistent with driver name.

hw/mcu/da1469x: Fix HAL UART creation

---

hw/bsp/frdm-k64f/frdm-k64_debug.sh
hw/bsp/frdm-k64f/frdm-k64_download.sh
hw/scripts/pyocd.sh

Move custom pyocd flashing/debugging scripts to a common hw/script that can be used by other KINETIS BSPs and update it to recent pyocd APIs.

[KINETIS] Turn pyocd into a reusable script

---

hw/charge-control/src/charge_control.c

An alternate event queue can specified for `charger-control` by setting `CHARGE_CONTROL_MGR_EVQ`, but this was resulting in an undeclared identifier compiler error. 
This PR fixes the error by declaring the queue specified by `CHARGE_CONTROL_MGR_EVQ` as `extern struct os_eventq`. 
Note: This fix uses the same approach already used by `hw/sensor` to resolve an externally defined queue.

charge-control: Fix to allow usage of an alternate event queue.

---

apps/crypto_test/src/main.c

* apps: crypto_test: add AES-256 vectors - Add AES-256 vectors from NIST and expand inplace and iovect to test AES-256.
* apps: crypto_test: fix warnings from syscfg - Enabling/disabling some of the crypto_test syscfgs resulted in warnings from non-used variables, etc. This commit fixes the issues so each individual syscfg can be isolatedly used.
Tested on frdm-k82f (fully functional), nucleo-f439 (fully functional), frdm-k64f (no AES-256 support, not sure if it's a driver or HW issue), nrf52840/pca10056 (no AES-256? no decryption!)

Update crypto_test for AES-256

---

hw/mcu/dialog/da1469x/src/da1469x_periph.c

Fixes a bug in new `da1469x_uart_create()` with  UART_HAL: 1. The OS device name was always being set as "uart0" instead of using function arg `const char *name`.

hw/mcu/da1469x: fix passing of uart name in da1469x_uart_create

---

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c
hw/mcu/dialog/da1469x/src/da1469x_prail.c

DCDC is more efficient then LDO to provide power rails but in case
when VBUS (charger) is present, it is actually more efficient from
battery point of view to disable DCDC (which is powered by battery)
and use LDO that is powered by VBUS.
This way charging current will go to battery and not to DCDC reducing charge time.
It will also prevent discharging battery when it was fully changed and not removed
from charger.

da1469x disable dcdc when vbus is present

---

hw/drivers/crypto/include/crypto/aes_alt.h
hw/drivers/crypto/src/mbedtls_aes_alt.c

* Export `mbedtls_aes_setkey_dec`
* Correctly handle encryption/decryption in ECB mode
* Add CBC alt implementation

hw: driver: crypto: Mbed TLS alt improvements

---

hw/drivers/hash/include/hash/sha256_alt.h
hw/drivers/hash/src/mbedtls_sha256_alt.c

Using the md interface in Mynewt when a HW hash driver is enabled fails because SHA-224 is calling `mbedtls_internal_sha256_process` directly. Since SHA-224 is not commonly used, add a placeholder to allow building.

hw: drivers: hash: fix Mbed TLS md interface usage

---

apps/rust_blinky/cargo_build.sh

This PR makes [cargo_build.sh](https://github.com/apache/mynewt-core/blob/master/apps/rust_blinky/cargo_build.sh) use a cargo build profile (debug or release) based on the mynewt build profile. Previously, the cargo debug profile was always used.

apps/rust_blinky: Support cargo release builds

---

apps/hash_test/src/main.c
hw/drivers/hash/hash_stm32/include/hash_context.h
hw/drivers/hash/hash_stm32/src/hash_stm32.c

apps: hash_test: add single byte multi-write test - Expand string stream test to also run on SHA-224 (when available). Add new single byte multi-write test, where a single "a" is written 257 (because odd numbers are good!) times, running on both SHA-224 and SHA-256 (where available).
hw: drivers: hash_stm32: fix stream support - The STM32 HASH HW is configured to work on a word (32-bit) write, and the only write that can be less than 4-bytes is the last write (_finish()). To be compatible with streams that are non word-boundary sized, a new pad (aka state) was added that caches writes that are less than 4 byte, so only words are ever written in an _update(), and _finish() flushes the remaining bytes that were less than 4-bytes.

Fix STM32 HASH stream support

---

hw/bus/src/bus.c

Inactivity timeout used for power management was not really using
time value.
- if timeout was greater then 0 it was ignored and device was disabled
at once instead of later.
- if timeout was 0 device should be disabled at once but it was scheduled
to be run 1 tick later according to os_callout_reset way
Now checking timeout condition is reversed that seems to be intended
behavior.

hw/bus: Fix inactivity timeout usage

---

hw/mcu/nordic/nrf5340_net/src/hal_system.c

Network core doesn't have secure peripherals.

hw/mcu: Fix nRF5340 netcore build with synthesize LF clock

---

hw/sensor/src/sensor.c

Added assert to check if stt is not NULL before dereferencing it

hw/sensor: fix possible null dereference in sensor_set_thresh()

---

hw/bsp/dialog_da1469x-dk-pro/src/arch/cortex_m33/gcc_startup_da1469x.S
hw/scripts/micro-trace-buffer.py
kernel/os/src/arch/cortex_m33/os_fault.c

- MTB registers are stored in RAM when crash happens so MTB can be used check what lead to crash
- MTB is also stopped in __assert_function() not only in default interrupt handler
- disassemble of non existing memory region does not stop script for continuing
- instruction preceding exception are displayed

MTB in core dump

---

hw/bsp/nordic_pca10095_net/boot-nrf5340_net.ld

IPC is not used in bootloader but linker were complaining about IPC
region being not present.

bsp/nordic_pca10095_net: Set empty IPC region for bootloader build

---

sys/console/full/src/console.c
sys/console/full/syscfg.yml
sys/console/minimal/src/console.c
sys/console/minimal/syscfg.yml

Currently when an NLIP command is finished processing, console echo is always turned back on.
This PR adds an optional syscfg, `CONSOLE_NLIP_RESTORE_ECHO`.
`CONSOLE_NLIP_RESTORE_ECHO: 0` (default setting) retains the existing console behavior, in which completion of an NLIP command will turn on console echo.
`CONSOLE_NLIP_RESTORE_ECHO: 1` will cause the echo on/off state to be restored to the state it was in before an NLIP command was processed.

sys/console: Add syscfg to allow restoring echo state after NLIP commands

---

hw/sensor/creator/src/sensor_creator.c

Some default sensor configurations have uninitialized member fields,
which later were used as value to set in [sensor_name]_config().
Now all values are 0 by default, and non-zero values are set.

sensor_creator: initialize sensor configs with zeros

---

crypto/mbedtls/include/mbedtls/config_mynewt.h
crypto/mbedtls/src/bignum.c
crypto/mbedtls/syscfg.yml

* crypto: mbedtls: allow EC customizations - Add options to implement EC point operations, ECDH and ECDSA with external libraries. This can be used to accelerate math in custom HW based implementations.
* crypto: mbedtls: allow MPI size customization - This syscfg can be used to lower the amount of RAM used by MPIs, when it is known that less than 1024 bytes are required, eg, EC operations (or small RSA).
* crypto: mbedtls: allow alt bignum implementation - Add options that allows overriding the bignum (aka MPI) implementation so that HW accelerators for math in modular fields can be used as alternative to SW based MPI calculation. PS: This is not a standard Mbed TLS option, so care must be taken when upgrading.
* crypto: mbedtls: default secp256r1 to enabled - secp224r1, which is not a …

Add more Mbed TLS alt implementations support
