apache/mynewt-core

hw/mcu/native/src/hal_gpio.c

just something simple so the user can see something when the run sim blink

added a simulated LED blink for blinky native

---

libs/json/include/json/json.h
libs/json/pkg.yml
libs/json/src/test/test_json.c
libs/json/src/test/test_json.h
libs/json/src/test/test_json_simple.c
libs/testutil/include/testutil/testutil.h

this is a simple test library for json. I wrote it while documenting the test library creating (still ongoing).

Mynewt-210

---

hw/mcu/native/src/hal_adc.c

redo this simulator to use open instead of fopen.

MYNEWT-275

---

libs/newtmgr/include/newtmgr/newtmgr.h
libs/newtmgr/src/newtmgr.c
libs/newtmgr/src/newtmgr_os.c

This command takes Date format as per RFC 3339 format
2016-03-02T22:44:00                  UTC time (implicit)
2016-03-02T22:44:00Z                 UTC time (explicit)
2016-03-02T22:44:00-08:00            PST timezone
2016-03-02T22:44:00.1                fractional seconds
2016-03-02T22:44:00.101+05:30        fractional seconds with timezone

Adding string date get and set command handler

---

hw/hal/include/hal/hal_pwm.h
hw/hal/include/hal/hal_pwm_int.h
hw/hal/src/hal_pwm.c
hw/mcu/native/src/hal_pwm.c

1) enable automatically
2) remove wave since its not useful to most

modified the hal_pwm API to support the comments from the code review

---

hw/hal/include/hal/hal_dac.h
hw/hal/include/hal/hal_dac_int.h
hw/hal/src/hal_dac.c

Also fixed code to better match coding standard

added a disable API for hal_dac

---

libs/baselibc/src/tinyprintf.c
libs/json/src/json_encode.c
libs/os/include/os/os_time.h
libs/os/src/os_time.c
sys/log/include/log/log.h
sys/log/src/log.c
sys/log/src/log_cbmem.c
sys/log/src/log_nmgr.c

- Adding/Changing fields(msg, ts, entries) to log entries
- Fixing json encode for 64 bit data types
- Adding os_time function to get uptime in microsenconds
- Changing json responses to contain multiple log entries
(Also addressing comments on github)
- Changing log_index to l_index and removing log_level from teh log
structure since it's not needed.

Log changes

---

hw/hal/include/hal/hal_spi.h
hw/hal/include/hal/hal_spi_int.h
hw/hal/src/hal_spi.c

I implemented a simple blocking hal SPI.   TODO, I want to implement a callback based SPI so we can transfer one byte and get a callback at interrupts when its complete.  
This would allow writing of a more sophisticated hal driver on top of the SPI.

this is a simple blocking SPI interface.

---

libs/json/src/test/test_json_simple.c

Here,  there is test related to badly format json and also test for empty array

Doing advance testing on the BoolArr. 

---

apps/bleuart/pkg.yml
apps/bleuart/src/main.c
libs/bleuart/include/bleuart/bleuart.h
libs/bleuart/pkg.yml
libs/bleuart/src/bleuart.c
net/nimble/host/src/host_hci.c

BLEuart app and string based bleary library which works with Nordic's nRF uart  app on iOS and Android.

BLEuart app and string based console library

---

apps/slinky/pkg.yml
apps/slinky/src/main.c

No Ticket - Syscfg Reboot log/counter changes

---

net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_l2cap_sig.c
net/nimble/host/test/src/ble_l2cap_test.c

Here is a set of fixes/minor cleaning and minor refactor which came up after testing against PTS.

L2CAP fixes for PTS testing

---

sys/console/full/include/console/prompt.h
sys/console/full/include/console/ticks.h
sys/console/full/src/cons_fmt.c
sys/console/full/src/ticks.c
sys/console/full/syscfg.yml
sys/console/stub/include/console/ticks.h
sys/shell/include/shell/shell_tick.h
sys/shell/src/shell.c
sys/shell/src/shell_tick.c

Clean commit of the shell/console ticks on/off. Also some cleanup of prompt command to include a straight on/off command and coding style conformation.

Console Ticks on/off

---

apps/bletiny/src/cmd.c

This patch introduces help commands to the bletiny app.
Right now interaction with the app is hard, because
it returns almost no information after executing commands.
To find out how to interact with the app one has to look
directly into the code.
With this patch user can invoke
help commands to list all possible parameters or commands
to pass to the app.
E.g.
b help - lists all toplevel commands like adv, conn, set, etc.
b adv help - lists all adv subcommands and parameters.

bletiny - Add help command and subcommands

---

apps/bletiny/src/main.c
net/nimble/host/src/ble_gap.c

One major and two minor patches which came up during PTS GAP testing

GAP under PTS testing

---

apps/bletiny/src/gatt_svr.c

Defined GATT db for testing purposes. Placed the definitions above
already defined services to ensure that the new ones will be used in
tests.

bletiny: add services and characteristics for PTS tests

---

apps/bletiny/src/cmd.c

This command allows to send service changed indications from console.
Currently this needs to be handled from application and is required
for PTS qualification.

bletiny: Add svcchg command

---

hw/drivers/sensors/lsm303dlhc/include/lsm303dlhc/lsm303dlhc.h
hw/drivers/sensors/lsm303dlhc/src/lsm303dlhc.c
hw/drivers/sensors/sim/include/sim/sim_mag.h
hw/drivers/sensors/sim/src/generic_mag.c
hw/sensor/include/sensor/mag.h
hw/sensor/src/sensor_shell.c

This pull requests adds magnetometer support to the sensor API. It also adds magnetometer data to the LSM303DLHC driver.

Add magnetometer support with LSM303DLHC test driver

---

net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_cmd.c
net/nimble/host/src/ble_sm_lgcy.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/src/ble_sm_sc.c
net/nimble/host/test/src/ble_sm_test_util.c

As discussed on mailing list.
+ some cleanups

Packed structures for SMP PDUs

---

hw/mcu/native/pkg.yml
kernel/os/include/os/os_task.h
kernel/os/src/os_task.c
kernel/os/test/src/callout_test.c
kernel/os/test/src/callout_test.h
kernel/os/test/src/eventq_test.c
kernel/os/test/src/eventq_test.h
kernel/os/test/src/testcases/event_test_poll_single_sr.c
kernel/os/test/src/testcases/event_test_poll_sr.c
kernel/os/test/src/testcases/event_test_poll_timeout_sr.c
kernel/os/test/src/testcases/event_test_src.c
kernel/os/test/src/testcases/os_callout_test.c
kernel/os/test/src/testcases/os_callout_test_speak.c
kernel/os/test/src/testcases/os_callout_test_stop.c
sys/flash_map/test/src/testcases/flash_map_test_case_1.c
sys/flash_map/test/src/testcases/flash_map_test_case_2.c

Add an assert checking that same prio is not used by two different
tasks.

MYNEWT-292; Don't allow two tasks to have the same priority

---

apps/blecent/src/main.c
apps/bleprph_oic/src/main.c
apps/blesplit/src/main.c
apps/bleuart/src/main.c
apps/ocf_sample/src/ocf_ble.c
net/nimble/host/src/ble_hs_id.c
net/nimble/host/src/ble_hs_misc.c
net/nimble/host/test/src/ble_gap_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_os_test.c
net/nimble/host/test/src/ble_sm_lgcy_test.c
net/nimble/host/test/src/ble_sm_sc_test.c

Some cleanup after recent changes for ble_addr and ble_uuid.

Nimble: some cleanup

---

net/oic/src/messaging/coap/observe.c

whether to send notify or not.

MYNEWT-652; net/oic - remove check of OC_PERIODIC when deciding

---

apps/bletiny/src/bletiny.h
apps/bletiny/src/cmd.c
apps/bletiny/src/main.c
net/nimble/host/include/host/ble_l2cap.h
net/nimble/host/src/ble_att.c
net/nimble/host/src/ble_att_priv.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_hs_conn.c
net/nimble/host/src/ble_hs_conn_priv.h
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_misc.c
net/nimble/host/src/ble_l2cap.c
net/nimble/host/src/ble_l2cap_coc.c
net/nimble/host/src/ble_l2cap_coc_priv.h
net/nimble/host/src/ble_l2cap_priv.h
net/nimble/host/src/ble_l2cap_sig.c
net/nimble/host/src/ble_l2cap_sig_cmd.c
net/nimble/host/src/ble_l2cap_sig_priv.h
net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/test/src/ble_hs_conn_test.c
net/nimble/host/test/src/ble_hs_test_util.c
net/nimble/host/test/src/ble_l2cap_test.c

Hi,
Here is the implementation of L2CAP LE CoC. Tested on UPF56 and with PTS testing.
Implementation pass all the PTS CoC test cases including the one when multichannel support is enabled.
What is missing:
* unit tests
* PTS instruction 
Sorry for big PR

L2CAP LE CoC implementation

---

hw/bsp/bbc_microbit/bsp.yml

microbit bsp: fix split linker script typo

---

hw/bsp/stm32f429discovery/boot-stm32f429discovery.ld
hw/bsp/stm32f429discovery/bsp.yml
hw/bsp/stm32f429discovery/f429.cfg
hw/bsp/stm32f429discovery/f429discovery.cfg
hw/bsp/stm32f429discovery/include/bsp/bsp.h
hw/bsp/stm32f429discovery/include/bsp/cmsis_nvic.h
hw/bsp/stm32f429discovery/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/stm32f429discovery/pkg.yml
hw/bsp/stm32f429discovery/src/arch/cortex_m4/startup_STM32F429x.s
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f429discovery/src/sbrk.c
hw/bsp/stm32f429discovery/src/system_stm32f4xx.c
hw/bsp/stm32f429discovery/stm32f429discovery.ld
hw/bsp/stm32f429discovery/stm32f429discovery_debug.cmd
hw/bsp/stm32f429discovery/stm32f429discovery_debug.sh
hw/bsp/stm32f429discovery/stm32f429discovery_download.cmd
hw/bsp/stm32f429discovery/stm32f429discovery_download.sh
hw/bsp/stm32f429discovery/syscfg.yml
hw/mcu/stm/stm32f4xx/stm32f429.ld

Add STM32F429 bsp
- Test STM32F429 bsp via
- blinky
- slinky
- timtest

Add STM32F429 bsp support

---

hw/scripts/common.sh
hw/scripts/jlink.sh
hw/scripts/openocd.sh

Updated against the latest develop, and tested it with git-bash as the shell of choice.

Fix ctrl c win

---

net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_lgcy.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/src/ble_sm_sc.c

I did preliminary testing and it seems to work.

Proposed fix for Mynewt 661

---

uncrustify.cfg

This adds a Mynewt style configuration for uncrustify: http://uncrustify.sourceforge.net/
Useful either for automated PR checking or reformatting an import/fork of external sources.

Add uncrustify style for mynewt

---

hw/bsp/bmd200/src/sbrk.c
hw/bsp/bmd300eval/src/sbrk.c
hw/bsp/nrf51-blenano/split-nrf51dk.ld
hw/bsp/nrf51dk-16kbram/split-nrf51dk-16kbram.ld
hw/bsp/nrf51dk-16kbram/src/sbrk.c
hw/bsp/nrf51dk/src/sbrk.c
hw/bsp/usbmkw41z/src/sbrk.c

from discussion https://github.com/apache/incubator-mynewt-core/pull/198/files

nrf51 bsp fixes 

---

net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/include/controller/ble_ll_ctrl.h
net/nimble/controller/include/controller/ble_ll_test.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_ctrl.c
net/nimble/controller/src/ble_ll_hci.c
net/nimble/controller/src/ble_ll_hci_ev.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/controller/src/ble_ll_xcvr.c
net/nimble/controller/syscfg.yml
net/nimble/controller/test/pkg.yml
net/nimble/controller/test/src/ble_ll_csa2_test.c
net/nimble/controller/test/src/ble_ll_test.c
net/nimble/controller/test/syscfg.yml
net/nimble/include/nimble/hci_common.h

This adds implementation of Channel Selection Algorithm #2 as specified in Core Specification 5.0 Vol 6 Part B 4.6.14.
Includes required HCI event, changes to supported features masks and unit tests based on sample data from Core Specification.

controller: Support for LE Channel Selection Algorithm #2

---

libc/baselibc/src/tinyprintf.c

From the printf(3) man page on my OS X:
`-'          A negative field width flag; the converted value is to
be left adjusted on the field boundary.  Except for n
conversions, the converted value is padded on the right
with blanks, rather than on the left with blanks or
zeros.  A - overrides a 0 if both are given.

MYNEWT-735 tinyprintf: negative field width spec.

---

sys/console/full/include/console/console.h
sys/console/full/src/cons_fmt.c
sys/console/minimal/include/console/console.h
sys/console/stub/include/console/console.h

The *printf family of functions do this. It is useful for aligning text.

MYNEWT-734 console_printf() return # printed chrs.

---

net/nimble/transport/uart/src/ble_hci_uart.c

The UART transport assumes outgoing ACL data packets consist of a single
mbuf. If the chain contains multiple buffers, the later part of the
outgoing packet consists of all zeros.

MYNEWT-736 NimBLE - UART xport can't send multibuf

---

net/nimble/transport/socket/include/socket/ble_hci_socket.h
net/nimble/transport/socket/pkg.yml
net/nimble/transport/socket/src/ble_hci_socket.c
net/nimble/transport/socket/syscfg.yml

net/nimble; add HCI transport which has Linux bluetooth socket,

---

hw/mcu/stm/stm32f4xx/src/hal_flash.c

stm32f4xx, erasing flash should wait for complete

stm32f4xx, erasing flash should wait for complete

---

apps/bletiny/src/cmd.c
apps/bletiny/src/main.c
net/nimble/host/include/host/ble_gap.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/include/nimble/hci_common.h

Bletiny got commands for testing.
b phy read conn=1
b phy set conn=1 tx_phys_mask=1 rx_phys_mask=5 phy_opts=1
b phy set_def tx_phys_mask=7 rx_phys_mask=7

Host: Support for read/set/set_default LE PHY

---

hw/bsp/ble400/ble400.cfg
hw/bsp/ble400/ble400_debug.cmd
hw/bsp/ble400/ble400_debug.sh
hw/bsp/ble400/ble400_download.cmd
hw/bsp/ble400/ble400_download.sh
hw/bsp/ble400/ble400_no_boot.ld
hw/bsp/ble400/boot-nrf51xxac.ld
hw/bsp/ble400/bsp.yml
hw/bsp/ble400/include/bsp/boards.h
hw/bsp/ble400/include/bsp/bsp.h
hw/bsp/ble400/include/bsp/cmsis_nvic.h
hw/bsp/ble400/nrf51xxac.ld
hw/bsp/ble400/pkg.yml
hw/bsp/ble400/split-ble400.ld
hw/bsp/ble400/src/arch/cortex_m0/gcc_startup_nrf51.s
hw/bsp/ble400/src/arch/cortex_m0/gcc_startup_nrf51_split.s
hw/bsp/ble400/src/hal_bsp.c
hw/bsp/ble400/src/sbrk.c
hw/bsp/ble400/syscfg.yml

This PR adds support for the Waveshare BLE-400 using the Core51822 module.
http://www.waveshare.com/wiki/BLE400
http://www.waveshare.com/wiki/Core51822

Initial BLE400 BSP

---

net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/host/src/ble_hs_dbg.c
net/nimble/host/src/ble_hs_hci_evt.c

Fix number of completed packet events in both controller and host.

MYNEWT-738: Fix parameter array errors

---

hw/mcu/microchip/pic32mz2048efg100/include/mcu/mcu.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_gpio.c

This has been tested on a Wi-Fire board.

hw: mcu: pic32mz2048efg100: Implement hal_gpio driver

---

hw/drivers/nimble/native/src/ble_phy.c
net/nimble/controller/src/ble_ll.c

one of them is quick fix, I'll send email to mailing list with a bit more detailed description of an issue.

Fixes for controller native unit tests

---

hw/bsp/pic32mz2048_wi-fire/include/bsp/bsp.h

hw: hsp: pic32mz2048_wi-fire: Define LED pins

---

apps/sensors_test/pkg.yml
apps/sensors_test/src/main.c
apps/sensors_test/syscfg.yml
hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/nrf52dk/src/hal_bsp.c
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/drivers/sensors/bme280/include/bme280/bme280.h
hw/drivers/sensors/bme280/pkg.yml
hw/drivers/sensors/bme280/src/bme280.c
hw/drivers/sensors/bme280/src/bme280_priv.h
hw/drivers/sensors/bme280/src/bme280_shell.c
hw/drivers/sensors/bme280/syscfg.yml
hw/drivers/sensors/bno055/include/bno055/bno055.h
hw/drivers/sensors/bno055/src/bno055.c
hw/sensor/include/sensor/humidity.h
hw/sensor/include/sensor/pressure.h
hw/sensor/include/sensor/temperature.h
hw/sensor/src/sensor_oic.c
hw/sensor/src/sensor_shell.c
hw/sensor/syscfg.yml

Add SPI driver for BME280 along with pressure, temperature and humidity support in SensorAPI.

MYNEWT-748 SensorAPI: Add BME280 support to mynewt along with pressure, temperature and humidity support

---

sys/console/full/include/console/console.h
sys/console/full/src/console.c
sys/console/minimal/src/console.c
sys/shell/include/shell/shell.h
sys/shell/src/shell.c

These patches were meant to be sent along with #256, but that PR was merged earlier.

Shell fixes from review #256

---

hw/mcu/microchip/pic32mz2048efg100/src/hal_system.c

hw: mcu: pic32mz2048efg100: Implement hal_system_reset

---

mgmt/imgmgr/include/imgmgr/imgmgr.h
mgmt/imgmgr/src/imgmgr.c
sys/flash_map/include/flash_map/flash_map.h
sys/flash_map/src/flash_map.c

closes https://issues.apache.org/jira/browse/MYNEWT-747
Im guessing this needs code review. I just stripped what looks like what was needed for erase command and put it in a new command.

imgmgr: add erase command, remove erase from upload command

---

mgmt/imgmgr/src/imgmgr_coredump.c

This change is discussed in https://issues.apache.org/jira/browse/MYNEWT-664

MYNEWT-664 add length to coredownload rsp.

---

hw/bsp/stm32f7discovery/boot-stm32f7discovery.ld
hw/bsp/stm32f7discovery/bsp.yml
hw/bsp/stm32f7discovery/include/bsp/bsp.h
hw/bsp/stm32f7discovery/include/bsp/cmsis_nvic.h
hw/bsp/stm32f7discovery/include/bsp/stm32f7xx_hal_conf.h
hw/bsp/stm32f7discovery/pkg.yml
hw/bsp/stm32f7discovery/src/arch/cortex_m7/startup_stm32f746xx.s
hw/bsp/stm32f7discovery/src/arch/cortex_m7/startup_stm32f767xx.s
hw/bsp/stm32f7discovery/src/hal_bsp.c
hw/bsp/stm32f7discovery/src/sbrk.c
hw/bsp/stm32f7discovery/src/system_stm32f7xx.c
hw/bsp/stm32f7discovery/stm32f7discovery.cfg
hw/bsp/stm32f7discovery/stm32f7discovery.ld
hw/bsp/stm32f7discovery/stm32f7discovery_debug.sh
hw/bsp/stm32f7discovery/stm32f7discovery_download.sh
hw/bsp/stm32f7discovery/syscfg.yml
hw/mcu/stm/stm32f7xx/stm32f746.ld

See http://www.st.com/en/evaluation-tools/32f746gdiscovery.html
LED blink and serial console (using VCP) tested OK.

BSP for STM32F7-Discovery board

---

hw/bsp/pic32mz2048_wi-fire/include/bsp/bsp.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_uart.c

hw: mcu: pic32mz2048efg100: Reduce code duplication in hal_uart

---

net/nimble/host/src/ble_hs_hci_evt.c

This code change fixes our incorrect interpretation of the BLE
specification regarding parameter arrays when parsing
advertising reports.

MYNEWT-738: Fix parameter arrays

---

net/oic/src/messaging/coap/coap.c

This change is briefly described in https://issues.apache.org/jira/browse/MYNEWT-775.

MYNEWT-775 Crash; unaligned accesses: CoAP parsing

---

net/lora/node/src/mac/LoRaMac.c
net/lora/node/src/utilities.c

The main changes here were to make sure that code was using
msecs and/or ticks in the appropriate places. Made some
gratuitous format changes as well.

No jira ticket: additional timing changes

---

hw/drivers/sensors/bno055/src/bno055_shell.c

For "r" command throw error on no type.

MYNEWT-781 BNO055 Shell: throw error on no type

---

mgmt/imgmgr/src/imgmgr_state.c

This change is described in: https://issues.apache.org/jira/browse/MYNEWT-752.

MYNEWT-752 Allow confirm of tentative slot.

---

boot/boot_serial/src/boot_serial.c

This issue is described in: https://issues.apache.org/jira/browse/MYNEWT-787

MYNEWT-787 serial boot loader - newtmgr buffer overruns

---

README.md
hw/bsp/vbluno51/boot-nrf51xxac.ld
hw/bsp/vbluno51/bsp.yml
hw/bsp/vbluno51/include/bsp/boards.h
hw/bsp/vbluno51/include/bsp/bsp.h
hw/bsp/vbluno51/include/bsp/cmsis_nvic.h
hw/bsp/vbluno51/nrf51xxac.ld
hw/bsp/vbluno51/pkg.yml
hw/bsp/vbluno51/split-vbluno51.ld
hw/bsp/vbluno51/src/arch/cortex_m0/gcc_startup_nrf51.s
hw/bsp/vbluno51/src/arch/cortex_m0/gcc_startup_nrf51_split.s
hw/bsp/vbluno51/src/hal_bsp.c
hw/bsp/vbluno51/src/sbrk.c
hw/bsp/vbluno51/syscfg.yml
hw/bsp/vbluno51/vbluno51_debug.cmd
hw/bsp/vbluno51/vbluno51_debug.sh
hw/bsp/vbluno51/vbluno51_download.cmd
hw/bsp/vbluno51/vbluno51_download.sh
hw/bsp/vbluno51/vbluno51_no_boot.ld

VBLUno51 board from VNG (Nordic nRF51822 SoC based)
+ Abstract
nRF51822
Bluetooth Low Energy
DAPLink interface
UNO pinout
4 power
+ Wiki: https://vngiotlab.github.io/vbluno/
Signed-off-by: iotvietmember <robotden@gmail.com>

Add support for VBLUno51 board

---

apps/blecent/src/main.c
apps/bleprph/src/main.c
apps/bleprph_oic/src/main.c
apps/blesplit/src/main.c
apps/bletiny/src/main.c
apps/bleuart/src/main.c
net/nimble/host/include/host/ble_hs.h
net/nimble/host/include/host/ble_store.h
net/nimble/host/src/ble_sm.c
net/nimble/host/src/ble_sm_priv.h
net/nimble/host/src/ble_store.c
net/nimble/host/src/ble_store_util.c
net/nimble/host/store/ram/src/ble_store_ram.c
net/nimble/host/test/src/ble_sm_test.c
net/nimble/host/test/src/ble_sm_test_util.c
net/nimble/host/test/src/ble_store_test.c

This pull request addresses the issue identified in MYNEWT-751 (https://issues.apache.org/jira/browse/MYNEWT-751).
This PR incorporates changes from another PR: 277 (https://github.com/apache/incubator-mynewt-core/pull/277).  Therefore, this PR should only be merged after 277.

BLE Host - Policy for SM key overflow

---

hw/drivers/nimble/native/src/ble_phy.c
hw/drivers/nimble/nrf51/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/syscfg.yml

Bt5 ctrl fixes

---

apps/bletiny/src/bletiny.h
apps/bletiny/src/cmd.c
apps/bletiny/src/main.c
net/nimble/controller/syscfg.yml
net/nimble/host/include/host/ble_gap.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/include/nimble/hci_common.h
net/nimble/syscfg.yml

This pull request contains host part of extended advertising feature.
Note: This is experimental API.

Bt5 extended advertising - host part

---

hw/bsp/pic32mz2048_wi-fire/include/bsp/bsp.h
hw/bsp/pic32mz2048_wi-fire/src/hal_bsp.c
hw/bsp/pic32mz2048_wi-fire/syscfg.yml
hw/hal/include/hal/hal_i2c.h
hw/mcu/microchip/pic32mz2048efg100/include/mcu/mips_hal.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_i2c.c

This pull request implements a driver for the I2C peripheral.
It has been tested using a MPU6050 and reading the product ID of this device using a wi-fire.

Wi-Fire: Add I2C driver 

---

apps/bletiny/src/main.c
net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/include/controller/ble_ll_sched.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/include/nimble/ble.h

nimble: Couple of fixes and improvements to bluetooth 5

---

net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/include/controller/ble_ll_hci.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_hci.c
net/nimble/controller/src/ble_ll_conn_priv.h
net/nimble/controller/src/ble_ll_ctrl.c
net/nimble/controller/src/ble_ll_hci_ev.c
net/nimble/controller/src/ble_ll_supp_cmd.c
net/nimble/controller/syscfg.yml
net/nimble/host/include/host/ble_hs_hci.h
net/nimble/host/src/ble_gap.c
net/nimble/host/src/ble_gap_priv.h
net/nimble/host/src/ble_hs_conn_priv.h
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_hs_hci_cmd.c
net/nimble/host/src/ble_hs_hci_evt.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/host/src/ble_hs_startup.c
net/nimble/include/nimble/hci_common.h

This introduces multiple improvements in the way we handle local and remote features in both host and controller.

Nimble: improvements on controller/peer features handling

---

net/nimble/controller/src/ble_ll_conn_hci.c

This fixed build error on nrf51 when optmized is on

nimble/controller: Improve validation on extended connect 

---

net/ip/native_sockets/src/native_sock.c

native_sockets; now that sockets are nonblocking, partial transmits

---

hw/sensor/src/sensor_oic.c
hw/sensor/syscfg.yml
net/oic/include/oic/oc_api.h
net/oic/include/oic/oc_ri.h
net/oic/src/api/oc_ri.c
net/oic/src/api/oc_server_api.c

- Also changing sensor oic support to use new api

MYNEWT-803 OIC add api for setting poll rate to ms

---

hw/bsp/ruuvi_tag_revb2/pkg.yml
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/bsp/ruuvi_tag_revb2/syscfg.yml
hw/drivers/sensors/bme280/src/bme280.c
hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/pkg.yml
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/src/lis2dh12_priv.h
hw/drivers/sensors/lis2dh12/syscfg.yml
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor_oic.c
hw/sensor/syscfg.yml
net/oic/include/oic/oc_api.h
net/oic/include/oic/oc_ri.h
net/oic/src/api/oc_ri.c
net/oic/src/api/oc_server_api.c

- Adding basic SPI driver for LIS2DH12 to work with the Ruuvitag
- Changing the frequency for SPI to 4Mhz.
- Change Ruuvi sample rate for LIS2DH12

MYNEWT-789 Add RuuviTag polling LIS2DH12 3-axis accel SPI driver

---

net/nimble/controller/src/ble_ll_ctrl.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/src/ble_ll_sched.c
net/nimble/host/services/ans/src/ble_svc_ans.c
net/nimble/host/src/ble_att_svr.c
net/nimble/host/src/ble_hs_adv.c

These are proposals for fixes for some issues found with clang-check. They may not be necessary. Comments are welcome.

[RFC] Fixes for possible issues found with clang-check

---

apps/sensors_test/syscfg.yml
hw/bsp/nrf52-thingy/pkg.yml
hw/bsp/nrf52-thingy/src/hal_bsp.c
hw/bsp/nrf52-thingy/syscfg.yml
hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/src/lis2dh12_priv.h

MYNEWT-808 Adding support for I2C LIS2DH12 driver

---

sys/console/full/src/console.c

The previous fix (#408, MYNEWT-811) introduced a regression in handling CR/LF characters.
When CR/LF was used, the LF character was added to the buffer and handled by the shell resulting in "Unrecognized command" error.
Additionally, this patch also fixes these issues in console/minimal.

sys/console: fix console compatibility

---

.rat-excludes
compiler/arm-none-eabi-m7/syscfg.yml
hw/bsp/sensorhub/sensorhub_debug.cmd
hw/bsp/sensorhub/sensorhub_download.cmd
hw/mcu/native/src/native_uart_cfg_priv.h
kernel/sim/src/sim_priv.h
libc/baselibc/syscfg.yml
net/ip/native_sockets/include/native_sockets/native_sock.h

Fix missing APL 2.0 license headers and updated RAT exceptions.

License check fixes

---

net/nimble/host/pts/pts-gap.txt
net/nimble/host/pts/pts-gatt.txt
net/nimble/host/pts/pts-l2cap.txt
net/nimble/host/pts/pts-sm.txt
net/nimble/host/src/ble_sm_lgcy.c
net/nimble/host/src/ble_sm_sc.c

Rerun GAP, GATT, L2CAP, SM test cases. Most tests are green.
We should look into the following test cases because I couldn't get them to pass with current instructions:
TC_BROB_BCST_BV_03_C
TC_SEC_AUT_BV_14_C
GATT/SR/GAC/BV-01-C
GATT/SR/GAW/BV-08-C

MYNEWT-659 Rerun PTS on Bluetooth5 branch (regression testing)

---

hw/drivers/nimble/nrf52/src/ble_phy.c
net/nimble/controller/include/controller/ble_ll_conn.h
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_conn_priv.h
net/nimble/controller/src/ble_ll_scan.c
net/nimble/controller/src/ble_ll_sched.c

this improves handling of aux_connect_rsp pdus and fixes some issues found when trying to make this work properly

nimble: improve handling AUX_CONNECT_RSP

---

kernel/os/src/arch/pic32/os_arch_pic32.c

A couple of FPU related lines crept outside the #ifs.

PIC32-FPU: fix compile for non-fpu hardware

---

hw/bsp/nrf52-thingy/include/bsp/bsp.h

Please reference https://nordicsemiconductor.github.io/Nordic-Thingy52-FW/documentation/pca20020_8h_source.html

bsp: fix nrf52 thingy pins

---

hw/drivers/nimble/nrf51/src/ble_phy.c

This is the same as 2d34c653a but for nRF51 which I forgot to change
there...

[MYNEWT-819] nimble/phy: Fix resolving address on nRF51

---

hw/mcu/microchip/pic32mx470f512h/src/hal_reset_cause.c

This is identical to the code I wrote for the pic32mz2048efg100.

hw: mcu: pic32mx470f512h: Implement hal_reset_cause and system reset

---

net/nimble/controller/src/ble_ll_conn.c

According to Bluetooth specificatoin 5.0 Vol 2. Part E 7.8.12, in LE
Create Connection Command:
"The Host shall not set Peer_Address_Type to either 0x02 or 0x03
if both the Host and the Controller support the LE Set Privacy Mode
command."
With this patch, when peer_address_type in LE Create Connection command
is set to 0x00 or 0x01 it is possible to connect to remote device
which is in controller resolving list and advertise with rpa
With this patch it is not possible to connect to remote device which is
in the controller resolving list in privacy mode network and advertise
with its identity address.

nimble/controller: Fix for privacy mode

---

apps/bletest/src/bletest_hci.c
apps/bletest/src/main.c

bletest was not building with the changes to the nimble stack. Get it building.

nimble/bletest: fix bletest build

---

hw/mcu/native/src/hal_hw_id.c
hw/mcu/native/src/hal_uart.c

This was still locking up with long cut'n'paste.

native/hal_uart; TX once for every RX in poller

---

hw/mcu/nordic/nrf51xxx/src/hal_flash.c
hw/mcu/nordic/nrf51xxx/src/hal_i2c.c
hw/mcu/nordic/nrf51xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/hal_flash.c
hw/mcu/nordic/nrf52xxx/src/hal_i2c.c
hw/mcu/nordic/nrf52xxx/src/hal_timer.c

These commits address a number of the issues that the coverity scan found.

Coverity fixes

---

hw/mcu/nordic/nrf52xxx/src/hal_uart.c

Signed-off-by: Tony Qu <tnyqu6@gmail.com>

Added baud rates 1200, 2400, 4800 to nrf52xxx

---

hw/mcu/microchip/pic32mx470f512h/src/hal_i2c.c
hw/mcu/microchip/pic32mz2048efg100/src/hal_i2c.c

Now waits while the ACKEN bit is high.

pic32 i2c receive now waits for end of ack

---

net/nimble/host/mesh/src/prov.c

Without this fix there is an issue when doing PB-ADV provisioning with PTS.
(MESH/NODE/PROV/UDP/BV-01-C)
Node was keep retransmitting Public Key which is ACKed by PTS and this leads
to transaction timeout as PTS does not send confirm probably because it
keep receiving PK from us.

nimble/mesh: Clear link TX when ACK arrived on it

---

net/nimble/controller/src/ble_ll_scan.c

With duplicates filtering enabled, we will filter out scan response
from advertiser if we already sent advertising report for the same
device. However, Core specification (Vol 6, Part B, section 4.4.3.5)
states:
"For each non-duplicate advertising or scan response PDU from an
advertiser, the Link Layer shall send an advertising report to the
Host."
This patch fixes this by tracking advertising reports and scan
responses separately for duplicates filtering.

nimble/ll: Fix duplicates filtering in scanner

---

mgmt/imgmgr/src/imgmgr.c

This adds support for the new image header format (done by @mkiiskila).

Works with new image format.

---

hw/drivers/sensors/mpu6050/include/mpu6050/mpu6050.h
hw/drivers/sensors/mpu6050/src/mpu6050.c
hw/drivers/sensors/mpu6050/src/mpu6050_priv.h
hw/sensor/creator/src/sensor_creator.c

Added interrupt support along with getters and setters for config values.

MPU6050: added interrupt support

---

repository.yml

0-latest points to latest release (any major version).
1-latest points to latest 1.X release.

Update repository to include 1.2 release

---

net/ip/native_sockets/src/native_sock.c
net/nimble/transport/socket/src/ble_hci_socket.c

These are two unrelated changes to native_sockets.

Native socket fixes

---

test/testutil/src/case.c

If a test case was reported with a message (e.g., an assertion failure),
the message gets duplicated for all subsequent test cases.  For
example:
```
[pass] ble_os_test_suite/ble_os_disc_test_case
[pass] ble_os_test_suite/ble_gap_direct_connect_test_case
[pass] ble_os_test_suite/ble_gap_terminate_test_case
[FAIL] ble_hs_pvcy_test_suite_irk/ble_hs_pvcy_test_case_restore_irks |net/nimble/host/test/src/ble_hs_pvcy_test.c:34| failed assertion: rc == 0
[pass] ble_sm_gen_test_suite/ble_sm_test_case_f4
|net/nimble/host/test/src/ble_hs_pvcy_test.c:34| failed assertion: rc == 0
[pass] ble_sm_gen_test_suite/ble_sm_test_case_f5
|net/nimble/host/test/src/ble_hs_pvcy_test.c:34| failed assertion: rc == 0
[pass] ble_sm_gen_test_suite/ble_sm_test_case_f6
|net/nimble/host/test/src/ble_hs_pvcy_test.c:34| …
```

testutil - Clear message after failure reported

---

hw/sensor/src/sensor.c

- While converting to macros, the thresholds were mixed up for the
watermark algo. Fixing it.

sensor notif: fix watermark algo

---

apps/lora_app_shell/src/las_cmd.c
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

Fixes for Class C unconfirmed transmission handling.

Class c tx

---

hw/drivers/nimble/nrf52/src/ble_phy.c

We fail to reply AUX_ADV_IND with a AUX_CONNECT_REQ if auxiliary packet
was received on LE Coded S8 phy. This is because time required to
process this packet is rought the same as when we need to enable radio
before transmission so we simply miss the slot and set the timer0 to
fire in the past.
The solution is to setup timer0 before processing the packet so radio
can be enabled on time and in case we don't need to tx anything we'll
just disable the timer and nothing will be transmitted.

nimble/phy: Change TX scheduling in RX-TX transition

---

apps/sensors_test/src/main.c
hw/drivers/sensors/bmp280/include/bmp280/bmp280.h
hw/drivers/sensors/bmp280/pkg.yml
hw/drivers/sensors/bmp280/src/bme280_priv.h
hw/drivers/sensors/bmp280/src/bmp280.c
hw/drivers/sensors/bmp280/src/bmp280_priv.h
hw/drivers/sensors/bmp280/src/bmp280_shell.c
hw/drivers/sensors/bmp280/syscfg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

- BMP280 Sensor driver
- BMP280 Sensor specific shell
- Sensor framework support

MYNEWT-840 bmp280 driver and shell and sensor framework support

---

net/nimble/controller/src/ble_ll_adv.c
net/nimble/include/nimble/ble.h

see commit message for details

nimble/ll: Fix scheduling of extended advertising events

---

net/nimble/controller/include/controller/ble_ll.h
net/nimble/controller/include/controller/ble_ll_scan.h
net/nimble/controller/src/ble_ll.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/host/src/ble_gap.c

This is set of patches done just before and on UPF58. mostly related to extended scanner and extended connection creation.

nimble/controller: Multiple fixes out of IOP testing

---

apps/lora_app_shell/src/las_cmd.c
net/lora/node/include/node/lora.h
net/lora/node/include/node/lora_band.h
net/lora/node/include/node/lora_priv.h
net/lora/node/src/lora_app.c
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c
net/lora/node/syscfg.yml

Please read the individual commit messages for more information about the changes. The main change was to remove setting the data rate in the port.

LoRa Datarate changes

---

hw/drivers/lp5523/include/lp5523/lp5523.h
hw/drivers/lp5523/pkg.yml
hw/drivers/lp5523/src/lp5523.c
hw/drivers/lp5523/src/lp5523_shell.c
hw/drivers/lp5523/syscfg.yml

I tried to stick to the data sheet nomenclature, looking back, I'm not sure that was the best way to go as it isn't very consistent, any thoughts?

LP5523: LED Driver

---

kernel/os/src/os_sem.c

Semaphores were using lockcnt & flags fields as if they were mutexes.
Removed that dependency so semaphores can be signaled from another task.
Signed-off-by: Jitesh Shah <jitesh@liveathos.com>

No lock accounting for semaphores

---

net/nimble/host/mesh/src/cfg.c

These are fixes to various test cases that were previously failing with the PTS.
Based on: https://github.com/zephyrproject-rtos/zephyr/pull/4729

mesh: Various fixes found during PTS testing

---

apps/iptest/src/main.c

Change iptest light resource to match bleprph_oic

---

net/nimble/host/mesh/src/adv.c
net/nimble/host/mesh/src/adv.h
net/nimble/host/mesh/src/beacon.c
net/nimble/host/mesh/src/cfg.c
net/nimble/host/mesh/src/net.c
net/nimble/host/mesh/src/net.h
net/nimble/host/mesh/src/proxy.c
net/nimble/host/mesh/src/transport.c
net/nimble/host/mesh/src/transport.h

Ported from: https://github.com/zephyrproject-rtos/zephyr/pull/4681

mesh: Preparation for Friend support

---

net/nimble/controller/include/controller/ble_ll_adv.h
net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_hci.c
net/nimble/host/src/ble_gap.c
net/nimble/include/nimble/ble.h
net/nimble/include/nimble/hci_common.h

Those are some cleanups preparing for support multi advertising.

Some GAP code cleanups 

---

net/oic/pkg.yml
net/oic/src/api/oc_priv.h
net/oic/src/api/oc_rep.c
net/oic/src/api/oc_ri.c
net/oic/src/port/mynewt/adaptor.c

Should've made this change earlier...

allow OIC resource registration at sysinit() time

---

apps/bletiny/src/main.c
apps/btshell/src/main.c
net/nimble/host/src/ble_l2cap.c
net/nimble/host/src/ble_l2cap_coc.c
net/nimble/host/test/src/ble_gatts_read_test.c

This PR fixes the two issues reported in https://issues.apache.org/jira/browse/MYNEWT-869.

MYNEWT-869 net/nimble/host unittest failures

---

docs/doxygen.xml
docs/mynewt_doc/modules/config/config.rst
sys/config/include/config/config.h

docs; Writeup about sys/config.

sys/config; doxygen formatted comments.

---

sys/console/full/src/uart_console.c

console_queue_char() may be called from interrupt context
and waiting for uart to drain the buffer may cause the console to
freeze. In these situations we should drop the character if
the buffer is full.
This is an easy solution to this problem, but we should redesign
console to not do this kind of processing in interrupt context.

sys/console: Fix console freeze

---

net/mqtt/eclipse/pkg.yml

Fix net/mqtt/eclipse pkg.name

---

LICENSE

Fix license issues

---

repository.yml

Update for 1.3.0 release

---

net/nimble/controller/src/ble_ll_adv.c
net/nimble/controller/src/ble_ll_conn.c
net/nimble/controller/src/ble_ll_scan.c
net/nimble/host/src/ble_att.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_l2cap.c
net/nimble/host/src/ble_sm.c

few unrelated fixes, see commit messages for details

nimble: few fixes

---

net/lora/node/src/mac/LoRaMac.c

net/lora: Fix compiler error for 868 band.

MYNEWT-878

---

kernel/os/src/os_sched.c

This should revert the previous commit for MYNEWT-879

Revert changes for mynewt-879

---

compiler/arm-none-eabi-m3/compiler.yml
compiler/arm-none-eabi-m3/pkg.yml
compiler/arm-none-eabi-m3/syscfg.yml
kernel/os/include/os/arch/cortex_m3/os/os_arch.h
kernel/os/src/arch/cortex_m3/m3/HAL_CM3.s
kernel/os/src/arch/cortex_m3/m3/SVC_Table.s
kernel/os/src/arch/cortex_m3/os_arch_arm.c
kernel/os/src/arch/cortex_m3/os_fault.c

This allows MCUBoot built for STM32L152C-Discovery to boot to image, so it's probably complete.

Add Cortex-M3 support

---

sys/console/full/src/console.c

64k of input len should be enough...

sys/console: Fix for input len >255

---

hw/drivers/nimble/nrf52/src/ble_phy.c

This fixes regression from PR #755 + minor cleanup

nimble/phy: Fix broken encryption on nRF52/nRF52840

---

hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/src/ble_phy.c

nimble/phy: Fix build

---

net/nimble/controller/src/ble_ll_dtm.c

DTM HCI commands operate on RF channels instead of channel indexes.

nimble/controller: Fix DTM test commands channel settings

---

docs/doxygen.xml

docs: add nimble mesh to the doxygen search path

---

net/nimble/host/mesh/src/adv.c
net/nimble/host/src/ble_hs_hci.c
net/nimble/host/src/ble_hs_hci_priv.h
net/nimble/host/src/ble_hs_startup.c

In this PR nimble reads HCI version and base on this use proper minimal advertising interval for Mesh

nimble/mesh: Improve advertising interval

---

hw/drivers/nimble/nrf52/src/ble_phy.c

This fixes #796.
See commit message for details.

nimble/phy: Fix for late RX-TX transition on nRF52

---

apps/btshell/src/main.c

Let's use static buffers for mempools instead of allocating them from
heap so we will know that they won't fit in RAM during build - no need
to wait for an assert during startup.

apps/btshell: Use static buffers for mempools

---

hw/mcu/nordic/nrf52xxx/src/hal_uart.c

The previous nrf52 code only allowed for one uart port as the nrf52 only had one
uart. The nrf52840 has two uarts so the code has been modified to allow both
to be used.

mcu/nrf52xx: Modify hal_uart so that UARTE1 can be used.

---

apps/btshell/src/cmd.c

Optional 'extra_data_len' parameter for both advertise-set-adv-data and
advertise-set-scan-rsp will append specified number of bytes to adv or
scanrsp data respectively.
Appended data are not valid advertising data. Instead, there is counter
encoded as BCD on every 2 bytes, so we have sth like this:
00:00:00:02:00:04:00:06:00:08:00:10:00:12:00:14:...:16:48:16:50
This allows to easily check whether data are continuous and properly
fragmented in the air which is especially useful for testing extended
advertising.

apps/btshell: Allow to append some extra data to adv/scanrsp data

---

net/nimble/host/services/gap/include/services/gap/ble_svc_gap.h
net/nimble/host/services/gap/src/ble_svc_gap.c
net/nimble/host/services/gap/syscfg.yml

Few fixes to make GAP service more compliant with the spec.

nimble: GAP service fixes

---

hw/drivers/sensors/bma253/src/bma253.c

Updated BMA253 w/ notification and set config function.

BMA253 set config

---

apps/blecent/pkg.yml
apps/blecent/src/main.c
apps/blesplit/pkg.yml
apps/blesplit/src/main.c

Someone should check my understanding. And not sure what if anything to do with bsncent but otherwise closes #827

blecent and blesplit remove set g_dev_addr

---

hw/bsp/dwm1001-dev/boot-nrf52xxaa.ld
hw/bsp/dwm1001-dev/bsp.yml
hw/bsp/dwm1001-dev/dwm1001-dev_debug.cmd
hw/bsp/dwm1001-dev/dwm1001-dev_debug.sh
hw/bsp/dwm1001-dev/dwm1001-dev_download.cmd
hw/bsp/dwm1001-dev/dwm1001-dev_download.sh
hw/bsp/dwm1001-dev/dwm1001-dev_no_boot.ld
hw/bsp/dwm1001-dev/include/bsp/boards.h
hw/bsp/dwm1001-dev/include/bsp/bsp.h
hw/bsp/dwm1001-dev/include/bsp/cmsis_nvic.h
hw/bsp/dwm1001-dev/nrf52xxaa.ld
hw/bsp/dwm1001-dev/pkg.yml
hw/bsp/dwm1001-dev/split-dwm1001-dev.ld
hw/bsp/dwm1001-dev/src/arch/cortex_m4/gcc_startup_nrf52.s
hw/bsp/dwm1001-dev/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/dwm1001-dev/src/hal_bsp.c
hw/bsp/dwm1001-dev/src/sbrk.c
hw/bsp/dwm1001-dev/syscfg.yml

Board is based on the DWM1001 module (ie: NRF52832 + DW1000)
https://www.decawave.com/products/dwm1001-dev

hw/bsp: DWM1001-DEV board

---

hw/bsp/puckjs/boot-nrf52xxaa.ld
hw/bsp/puckjs/bsp.yml
hw/bsp/puckjs/include/bsp/boards.h
hw/bsp/puckjs/include/bsp/bsp.h
hw/bsp/puckjs/include/bsp/cmsis_nvic.h
hw/bsp/puckjs/nrf52xxaa.ld
hw/bsp/puckjs/pkg.yml
hw/bsp/puckjs/puckjs_debug.cmd
hw/bsp/puckjs/puckjs_debug.sh
hw/bsp/puckjs/puckjs_download.cmd
hw/bsp/puckjs/puckjs_download.sh
hw/bsp/puckjs/puckjs_no_boot.ld
hw/bsp/puckjs/split_puckjs.ld
hw/bsp/puckjs/src/arch/cortex_m4/gcc_startup_nrf52.s
hw/bsp/puckjs/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/puckjs/src/hal_bsp.c
hw/bsp/puckjs/src/sbrk.c
hw/bsp/puckjs/syscfg.yml

We dont have an nrf52 with XTAL_32768_SYNTH so figured Id do it up right and PR it.
Fun clean little button/led/ir/nfc xmit design.
Check out https://www.puck-js.com and https://www.adafruit.com/product/3372

bsp: puckjs

---

hw/drivers/nimble/nrf52/src/ble_phy.c

If we are late when scheduling RX, receiver is enabled anyway since we
may just want to scan for "anything". However, current code only enables
receiver but does not configure it so the results seem unpredictable.
This patch fixes this by ensuring that radio is properly configured for
RX in both cases.

nimble/phy: Fix receiver configuration on late RX

---

sys/console/README.md

Update README to document minimal console

---

kernel/os/include/os/os_task.h
kernel/os/src/os.c
net/nimble/controller/src/ble_ll.c
net/nimble/host/mesh/src/adv.c
net/nimble/host/mesh/src/shell.c

This PR has been done after testing of  #882

kernel/os: Make sure correct stack aligment 

---

util/easing/include/easing/easing.h
util/easing/pkg.yml
util/easing/src/easing.c

This PR adds an easing library. 
This library provides the most [common easing functions usually available](http://easings.net/).

Adding int/float easing library

---

hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c

hw/mcu/nordic: Fixes in hal_gpio

---

hw/drivers/sensors/bma253/include/bma253/bma253.h
hw/drivers/sensors/bma253/src/bma253.c
hw/sensor/creator/src/sensor_creator.c

- Make driver API changes
- Add config for changing modes
- This fixes #891

sensors:bma253: Add config for stream/poll read

---

hw/drivers/nimble/nrf51/src/ble_hw.c
hw/drivers/nimble/nrf51/src/ble_phy.c
hw/drivers/nimble/nrf52/src/ble_hw.c

Few leftovers after transition to nrfx.

nimble/phy: Fix includes

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

- set_cfg function function was missing

lis2dw12: Add set_config function

---

hw/bsp/apollo2_evb/src/system_apollo2.c
hw/mcu/stm/stm32_common/src/stm32_driver_mod_spi.c
hw/mcu/stm/stm32f1xx/include/mcu/stm32f1_bsp.h

I encountered a few build errors when trying to build blinky for all BSPs.  These are some small changes that fix the errors.

Misc BSP fixes

---

apps/lora_app_shell/src/las_cmd.c
net/lora/node/include/node/lora_priv.h
net/lora/node/src/lora_node.c

Needed some better debugging tools so added a command (las_ln_log)
to dump the lora node log.

net/lora Add command to dump lora node log in lora_app_shell

---

hw/hal/include/hal/hal_timer.h

inttypes and os/queue was included twice

hal_timer: removed double include

---

hw/bsp/stm32f3discovery/stm32f3discovery.ld

Fix slot0 size in f3disco to avoid writing after end

---

hw/mcu/stm/stm32f3xx/src/ext/Drivers/STM32F3xx_HAL_Driver/Inc/stm32f3xx_ll_tim.h
kernel/os/include/os/os_fault.h
libc/baselibc/include/stdio.h
libc/baselibc/include/stdlib.h

Ran into issues compiling a C++ source code with
`arm-none-eabi-c++ (15:6.3.1+svn253039-1+b1) 6.3.1 20170620`

Some fixes for C++ compatibility.

---

hw/mcu/stm/stm32f1xx/src/hal_gpio.c
hw/mcu/stm/stm32f3xx/src/hal_gpio.c
hw/mcu/stm/stm32f4xx/src/hal_gpio.c
hw/mcu/stm/stm32f7xx/src/hal_gpio.c
hw/mcu/stm/stm32l1xx/src/hal_gpio.c

Until you ask me to stop, I'll keep submitting fixes for typos as I find them.

fix spelling

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c

Added mapping of int2 to int1.
User configurable.

LIS2DW12: Interrupt Line Remapping

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c
hw/drivers/sensors/lis2dw12/src/lis2dw12_priv.h
hw/drivers/sensors/lis2dw12/src/lis2dw12_shell.c
hw/sensor/creator/src/sensor_creator.c
hw/sensor/include/sensor/sensor.h

Reduces register reads when doing a stream read.
Add configuration of CTRL3 register.
Adds notify event for FREEFALL.

WIP: Improvements to LIS2DW12 driver

---

net/ip/mn_socket/include/mn_socket/mn_socket.h
net/ip/mn_socket/src/mn_socket_aconv.c
net/ip/mn_socket/test/src/mn_sock_test.c
net/ip/mn_socket/test/src/testcases/inet6_pton_test.c
util/parse/include/parse/parse.h
util/parse/pkg.yml
util/parse/src/parse.c

* Allow base to be specified for byte streams.
* Parsing function for IPv6 network string.

util/parse - Additional parsing functions.

---

net/lora/node/include/node/lora.h
net/lora/node/include/node/lora_priv.h
net/lora/node/src/lora_node.c
net/lora/node/src/mac/LoRaMac.c

Make function querying whether we've joined lora network public.

lora/node; average rssi/snr from received frames.

---

hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/nrf52840pdk/syscfg.yml

Fix for: https://github.com/apache/mynewt-core/issues/1043

bsp/nrf52840pdk: replace bitbang by native uart for UART1

---

sys/console/full/src/console.c
sys/console/full/syscfg.yml

Use up and down arrows to browse history.
Duplicate lines are dropped.

sys/console: Add console history functionality

---

sys/log/full/src/log_nmgr.c

With v3 we can now have CBOR (and binary data, but let's skip this for now...) stream as log entry and this should be properly transmitted via nmgr. This makes necessary changes to do this by sending `msg` field as valid CBOR stream from log entry, though `newtmgr` probably needs some updates to read it properly.

sys/log: Updates to handle CBOR entries via nmgr

---

apps/pwm_test/src/main.c
hw/bsp/ada_feather_nrf52/src/hal_bsp.c
hw/bsp/arduino_primo_nrf52/src/hal_bsp.c
hw/bsp/bmd300eval/src/hal_bsp.c
hw/bsp/dwm1001-dev/src/hal_bsp.c
hw/bsp/nina-b1/src/hal_bsp.c
hw/bsp/nrf52840pdk/src/hal_bsp.c
hw/bsp/nrf52dk/src/hal_bsp.c
hw/bsp/puckjs/src/hal_bsp.c
hw/bsp/rb-blend2/src/hal_bsp.c
hw/bsp/rb-nano2/src/hal_bsp.c
hw/bsp/ruuvi_tag_revb2/src/hal_bsp.c
hw/bsp/telee02/src/hal_bsp.c
hw/bsp/vbluno52/src/hal_bsp.c
hw/drivers/pwm/include/pwm/pwm.h
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c
hw/drivers/pwm/soft_pwm/src/soft_pwm.c
hw/drivers/pwm/soft_pwm/syscfg.yml
hw/drivers/pwm/src/pwm.c

This PR addresses issues described on https://github.com/apache/mynewt-core/issues/955

Refactoring PWM API Interface;

---

hw/util/button/include/button/button.h
hw/util/button/src/button.c
hw/util/button/syscfg.yml

Allow to specify event queue for internal processing. And eventq (per button if requested) for the callback processing

hw/util/button: allow to specify eventq

---

hw/drivers/sensors/lis2dw12/include/lis2dw12/lis2dw12.h
hw/drivers/sensors/lis2dw12/src/lis2dw12.c

ST's docs are pretty bad on the self test features. 
Basically, you need to do the difference between the two self test modes.
This should be right. Will double check with ST, but as I recall from the work I did a few years ago on a similar part, this is right. Also, now it passes for a part that we have observed to be good.

fix self test

---

hw/util/blinker/include/blinker/blink.h
hw/util/blinker/pkg.yml
hw/util/blinker/src/blink.c
hw/util/blinker/syscfg.yml

Provide an implementation of a blinker/beeper, only need to provide an on/off method (gpio, pwm, ...).
Make it easy to provide a simple user feedback

hw/util: blinker/beeper implementation

---

sys/console/full/src/uart_console.c

Original fix was merged into wrong branch.

console_fix: fix builds (#1131)

---

.rat-excludes
apps/blemesh_light/src/light_model.c
apps/blemesh_light/src/light_model.h
hw/mcu/nordic/nrf51xxx/include/nrfx_config.h
hw/mcu/nordic/nrf52xxx/include/nrfx52840_config.h
hw/mcu/nordic/nrf52xxx/include/nrfx52_config.h
hw/mcu/nordic/nrf52xxx/include/nrfx_config.h
hw/util/button/include/button/button.h
version.yml

Add missing license headers and update RAT excludes.

License check

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

Also, return some error code from sensor_read() in case of
failure.

lis2dw12; don't wait for for interrupt forever.

---

crypto/mbedtls/include/mbedtls/config.h
hw/drivers/lp5523/include/lp5523/lp5523.h
hw/drivers/lp5523/src/lp5523.c
hw/drivers/lp5523/src/lp5523_shell.c
hw/drivers/lp5523/syscfg.yml

Add some more APIs
Add concept of an led_itf, removing sensor_itf as it is not relevant
Add some more config

Lp5523 improvements

---

boot/boot_serial/syscfg.yml
sys/shell/src/shell_os.c
sys/shell/syscfg.yml

Optionally set nvreg to enter boot_serial in bootloader.

sys/shell; CLI command to reset device.

---

kernel/os/include/os/os_time.h
sys/defs/include/defs/error.h
test/testutil/include/testutil/testutil.h
util/mem/include/mem/mem.h
util/mem/src/mem.c

* Add some SYS_E[...] error codes.
* testutil: Fix TEST_SUITE_DECL() definition
* Add definition for OS_STIME_MAX
* util/mem: mem_pullup_obj() utility function.

Some miscellaneous additions

---

sys/shell/syscfg.yml

This increases RAM usage by 120 bytes (10 * 12).

sys/shell: Increase dflt max compat cmds (10->20)

---

hw/bsp/nucleo-f401re/src/hal_bsp.c
hw/bsp/nucleo-f413zh/src/hal_bsp.c
hw/bsp/olimex_stm32-e407_devboard/src/hal_bsp.c
hw/bsp/stm32f429discovery/src/hal_bsp.c
hw/bsp/stm32f4discovery/src/hal_bsp.c
hw/mcu/stm/stm32f4xx/src/hal_flash.c

This should fix a build issue with older gcc versions.

[STM32F4] Fix build after latest flash changes

---

hw/drivers/sensors/lis2ds12/src/lis2ds12.c

lis2ds12: lis2ds12_set_freefall bit mask fix

---

hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c
hw/sensor/test/src/testcases/sensor_test_case_poll_err.c

each sensor had a list of "error listeners." Each listener was associated with one or more sensor data types via a bitmap.  When a read error occurred, the sensor manager would notify each error listener whose bitmap shared at least one set bit with the bitmap indicating the type of data being read.
The idea was that the application could attach different behaviors to read errors, depending on the type of data that the sensor failed to read.  However, this idea was misguided, because when a driver's read callback reports failure, the sensor manager doesn't know the specific type of data that was being read when the error occurred.  So, all the sensor manager can tell the application is that there was an error communicating with a particular sensor.
Each sensor has only a single error …

hw/sensor: Limit a sensor to one error callback

---

hw/charge-control/include/charge-control/charge_control.h
hw/drivers/bq27z561/include/bq27z561/bq27z561.h
hw/drivers/bq27z561/src/bq27z561.c
hw/drivers/chg_ctrl/adp5061/src/adp5061.c

- Fix bq27z561 and add lock for adp5061

Add lock to charge control and adp5061 and bq27z561 fix

---

hw/battery/src/battery.c

The battery code was directly comparing os_time values without
using the macros intended for comparing two os_time values. There
is a feature change with this commit. The change is to the code
that sets the poll rate for a battery. The new code simply sets
the callout to fire off immediately if the battery poll rate is
changed. Decided that this is just simpler and there is no need
to check when the battery was last polled and only poll immediately
if the difference between now and the last time it was polled is
greater than the new poll rate. This code also did not check all
the batteries being polled so it could possibly miss a polling
interval if there are multiple battery devices being polled.

hw/battery: Fix incorrect os_time comparisons

---

hw/drivers/lora/include/lora/utilities.h
hw/drivers/lora/pkg.yml
hw/drivers/lora/src/utilities.c
hw/drivers/lora/sx1272/src/sx1272.c
hw/drivers/lora/sx1276/pkg.yml
hw/drivers/lora/sx1276/src/sx1276.c
hw/drivers/lora/syscfg.yml
net/lora/node/syscfg.yml

This pkg should contain configuration which is common for the drivers.
It also contains some utility functions which previoulsy where used from
/net/lora/node pkg.
This patch removes dependecy from lora drivers to lora/node

lora: Add lora common pkg

---

kernel/os/src/os_mempool.c

os_mempool poison code is generic but also quite slow. Since we always
use word-sized pattern and memblock address and size should be aligned,
we can make this code much faster. Extra checks are added to ensure
functions are called with properly aligned buffers.
On nRF52840 os_memblock_get() from msys1 pool with default block size
the difference is 133us vs. 30us.

kernel/os: Optimize os_mempool poison

---

kernel/os/src/os.c
kernel/os/syscfg.yml
test/crash_test/src/crash_cli.c
test/crash_test/src/crash_test.c

...which tries to dump system state before HAL watchdog fires.

 kernel/os; add hal watchdog monitor

---

hw/drivers/bq27z561/src/bq27z561.c

- Remove assert in code and just return return codes

drivers/bq27z561: remove assert in driver

---

hw/mcu/nordic/nrf52xxx/src/hal_i2c.c

This is a fix for situations where a slave device is left holding the SDA line low, which effectively prevents the master from regaining control of the bus. This can occur if an I2C transaction fails in the middle of reading data from some slave devices.
Note: The fix is inserted between TWI disable/enabled because TWI must be disabled in order for the SCL and SDA pins to be driven using GPIO functionality.

Add hal_i2c_clear_bus to I2C timeout recovery

---

hw/bsp/arduino_primo_nrf52/pkg.yml
hw/bsp/arduino_primo_nrf52/src/hal_bsp.c
hw/bsp/arduino_primo_nrf52/syscfg.yml
hw/bsp/bmd300eval/pkg.yml
hw/bsp/bmd300eval/src/hal_bsp.c
hw/bsp/bmd300eval/syscfg.yml
hw/bsp/dwm1001-dev/pkg.yml
hw/bsp/dwm1001-dev/src/hal_bsp.c
hw/bsp/dwm1001-dev/syscfg.yml
hw/bsp/nina-b1/pkg.yml
hw/bsp/nina-b1/src/hal_bsp.c
hw/bsp/nina-b1/syscfg.yml
hw/bsp/nrf52dk/pkg.yml
hw/bsp/puckjs/pkg.yml
hw/bsp/puckjs/src/hal_bsp.c
hw/bsp/puckjs/syscfg.yml
hw/bsp/rb-blend2/pkg.yml
hw/bsp/rb-blend2/src/hal_bsp.c
hw/bsp/rb-blend2/syscfg.yml
hw/bsp/rb-nano2/pkg.yml
hw/bsp/rb-nano2/src/hal_bsp.c
hw/bsp/rb-nano2/syscfg.yml
hw/bsp/telee02/pkg.yml
hw/bsp/telee02/src/hal_bsp.c
hw/bsp/telee02/syscfg.yml
hw/bsp/vbluno52/pkg.yml
hw/bsp/vbluno52/src/hal_bsp.c
hw/bsp/vbluno52/syscfg.yml
hw/mcu/nordic/nrf52xxx-compat/include/nrfx_config.h

We need to convert all existing BSP-s to new package so compat package can be removed just after release and we can forget about it.

Update all nRF52xxx BSP-s to use new nrf52xxx MCU package

---

hw/bsp/reel_board/boot-nrf52840aa.ld
hw/bsp/reel_board/bsp.yml
hw/bsp/reel_board/include/bsp/bsp.h
hw/bsp/reel_board/nrf52840aa.ld
hw/bsp/reel_board/pkg.yml
hw/bsp/reel_board/reel_board_debug.cmd
hw/bsp/reel_board/reel_board_debug.sh
hw/bsp/reel_board/reel_board_download.cmd
hw/bsp/reel_board/reel_board_download.sh
hw/bsp/reel_board/reel_board_no_boot.ld
hw/bsp/reel_board/split-reel_board.ld
hw/bsp/reel_board/src/arch/cortex_m4/gcc_startup_nrf52840.s
hw/bsp/reel_board/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/reel_board/src/hal_bsp.c
hw/bsp/reel_board/src/sbrk.c
hw/bsp/reel_board/syscfg.yml

This is an evaluation board with nRF52840.
https://www.phytec.eu/product-eu/internet-of-things/reelboard/

hw/bsp: Add BSP for reel board

---

.travis.yml

Add RAT reporting to build matrix
@michal-narajowski This will need rebase after mynewt-travis-ci changes are merged.

Travis testing - RAT report

---

hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/src/lis2dh12_priv.h
hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c
hw/drivers/sensors/lis2dh12/syscfg.yml

LIS2DH12 accelerometer driver. Finishing up work done previously by @kasjer and @andrzej-kaczmarek. These changes do not affect functionality of juul_platform master. To test full functionality, see juul_platform PR #329, branch lis2dh12_bringup.

Lis2dh12 driver

---

net/ip/include/arch/sys_arch.h
net/ip/include/ip/os_queue.h
net/ip/lwip_base/include/lwip/stats.h
net/ip/lwip_base/src/core/init.c
net/ip/lwip_base/src/core/stats.c
net/ip/src/os_queue.c

LwIP mbox api additions 

---

mgmt/newtmgr/src/newtmgr.c

Fix by removing ability to handle multiple incoming requests in a single message, as that is
not being used.

newtmgr; crashes with invalid nh_len.

---

hw/battery/src/battery.c

Adding an option to stop battery polling by setting polling rate to 0

adding battery polling rate 0 to stop polling

---

sys/stats/full/src/stats.c

Some modules may want to register stats before sysinit, e.g. some BSP
can create os_dev in hal_bsp_init and corresponding driver will try to
register stats on device init which means before sysinit is called.
To make this possible, stats code was modified a bit so it will
automatically initialize itself on 1st register call in case it was not
yet initialized via sysinit. This is possible since it does not have any
extra dependencies.
To avoid using some new global variables which hold initialization state
we can just check stat for number of registered stats - it will be
non-zero after initialization since "stat" is always registered.

sys/stats: Allow stats to be registered before sysinit

---

sys/log/full/src/log.c
sys/log/full/src/log_shell.c

...and also some useful additions to CLI.

sys/log: Add pretty printing for CBOR log entries

---

hw/bsp/hifive1/src/hal_bsp.c
hw/mcu/sifive/fe310/src/hal_spi.c

- SPI frequency is now specified in kHz (was in Hz)
- Bus driver support added

hifive1 spi update

---

apps/flash_loader/README.md
apps/flash_loader/REAME.md
apps/flash_loader/include/flash_loader/flash_loader.h
apps/flash_loader/pkg.yml
apps/flash_loader/src/fl.c
apps/flash_loader/syscfg.yml
compiler/gdbmacros/flash_loader.gdb

flash_loader; app and gdb macros to facilite populating external flash

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

This works with no changes from the previous patch on my freshly shipped hardware. Resubmitting. Closes #1171

lis2dw12: fix self test to match an5038 rev2

---

hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lis2dh12/src/lis2dh12_priv.h

This adds self-test procedure.
It also fixes multi-byte write over I2C that was not incrementing register address.

lis2dh12 add self test procedure

---

hw/mcu/nordic/nrf51xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx-compat/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c

Make hal_gpio_irq_release() pass 'pin' to hal_gpio_irq_disable()

---

hw/drivers/sensors/lis2dw12/src/lis2dw12.c

- Format adjusted to match mynewt style.
- Self works correctly when FIFO is enabled before self test starts.

lis2dw12 improve self test

---

test/spiflash_stress_test/pkg.yml
test/spiflash_stress_test/src/spiflash_stress_test.c
test/spiflash_stress_test/syscfg.yml

This is package for testing multi task access to spiflash (or any flash).
It is not very sophisticated it creates 3 tasks that try to write to same flash area (different location though) and later read what was written.

spiflash stress test

---

.rat-excludes
compiler/arm-none-eabi-m33/compiler.yml
compiler/arm-none-eabi-m33/pkg.yml
compiler/arm-none-eabi-m33/syscfg.yml
kernel/os/include/os/arch/cortex_m33/os/os_arch.h
kernel/os/src/arch/cortex_m33/m33/HAL_CM33.s
kernel/os/src/arch/cortex_m33/m33/SVC_Table.s
kernel/os/src/arch/cortex_m33/os_arch_arm.c
kernel/os/src/arch/cortex_m33/os_fault.c

kernel; first pass at kernel support files for Cortex-M33.

compiler; add package for Cortex-M33 compilation

---

apps/trng_test/pkg.yml
apps/trng_test/src/main.c
apps/trng_test/syscfg.yml
hw/bsp/frdm-k64f/pkg.yml
hw/bsp/frdm-k64f/src/hal_bsp.c
hw/drivers/trng/pkg.yml
hw/drivers/trng/trng_k64f/include/trng_k64f/trng_k64f.h
hw/drivers/trng/trng_k64f/pkg.yml
hw/drivers/trng/trng_k64f/src/trng_k64f.c
hw/drivers/trng/trng_k64f/syscfg.yml
hw/drivers/trng/trng_nrf52/pkg.yml
hw/drivers/trng/trng_stm32/pkg.yml
hw/mcu/nxp/MK64F12/syscfg.yml

Improvements to trng_test app and driver for K64F.

[TRNG] Add K64F driver

---

hw/drivers/sensors/lps33thw/src/lps33thw.c

- Coding style fixes
- Build warning due to unused variable fixed

hw/drivers/lps33thw: small fixes

---

hw/mcu/nxp/src/ext/sdk-2.0-frdm-k64f_b160321/devices/MK64F12/drivers/fsl_common.h
kernel/os/include/os/util.h

kernel/os: Add helper to calculate array size

---

kernel/os/include/os/os_eventq.h
kernel/os/src/os_eventq.c
kernel/os/syscfg.yml

events pulled from event queue.

os; add a way to collect data about how much time is spent handling

---

sys/fault/fault_cli/src/fault_cli.c
sys/fault/include/fault/fault.h
sys/fault/src/fault.c
sys/fault/src/fault_conf.c

This PR implements a few small fixes to the `sys/fault` package.  Please see commit messages for a description of the fixes.

sys/fault: A few minor fixes

---

hw/bus/drivers/spi_hal/src/spi_hal.c

SPI read was using hal_spi_tx_val() which sends on byte at a time
waiting for data to be transmitted.
Now hal_spi_txrx() is used that can be faster for hardware with
FIFO support.

hw/bus: Improve SPI read performance

---

kernel/os/src/os_mempool.c

This fixes a memory corruption bug.  When a mempool was initialized with 0 elements, its 0-length buffer would still be written to.  The bad write occurred when setting the last element's `next` pointer to NULL here:
```
/* Last one in the list should be NULL */
SLIST_NEXT(block_ptr, mb_next) = NULL;
```
The fix is to only perform this final write if there is at least one element in the pool.

kernel/os: Fix mem corruption on 0-entry mempool

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

Revert change that used END_START shortcut and EVENTS_STARTED
interrupt for SPIM interface. The reason behind reverting back
to the previous method is if interrupts are disabled/delayed too
long it is possible to transmit unexpected bytes on the SPI
interface. This method adds latency but insures a valid transfer.
See issue #1667.
NOTE: the reason this was not a simply revert of the git commit which added the shortcut is that there were other changes in that commit that should be in the code.

hw/mcu/nordic/nrf52xxx: Do not use END_START shortcut for SPIM

---

sys/config/src/config_store.c

@mkiiskila I am trying to understand this. Can you please confirm that this can be indeed done and would not cause any issues.

sys/config: commit for all fcbs together only once

---

apps/pwm_test/pkg.yml
apps/pwm_test/src/main.c
apps/pwm_test/src/pwm_shell.c
apps/pwm_test/src/pwm_shell.h
hw/drivers/pwm/pwm_nrf52/src/pwm_nrf52.c
util/easing/src/easing.c

This PR brings pwm_shell and couple of fixes to pwm_nrf52

app/pwm_test improvements and pwm_nrf52 fixes

---

hw/drivers/rtt/include/rtt/SEGGER_RTT.h
hw/drivers/rtt/include/rtt/SEGGER_RTT_Conf.h
hw/drivers/rtt/src/SEGGER_RTT.c
hw/drivers/rtt/src/SEGGER_RTT_printf.c
sys/sysview/vendor/include/sysview/vendor/Global.h
sys/sysview/vendor/include/sysview/vendor/SEGGER.h
sys/sysview/vendor/include/sysview/vendor/SEGGER_SYSVIEW.h
sys/sysview/vendor/include/sysview/vendor/SEGGER_SYSVIEW_Conf.h
sys/sysview/vendor/include/sysview/vendor/SEGGER_SYSVIEW_ConfDefaults.h
sys/sysview/vendor/src/SEGGER_SYSVIEW.c
sys/sysview/vendor/src/SEGGER_SYSVIEW_Int.h

Also enable SystemView on Cortex-M33

Update external code from SEGGER (RTT and SystemView)

---

.rat-excludes
hw/bsp/nucleo-f030r8/bsp.yml
hw/bsp/nucleo-f030r8/syscfg.yml
hw/bsp/nucleo-f072rb/README.md
hw/bsp/nucleo-f072rb/bsp.yml
hw/bsp/nucleo-f072rb/include/bsp/bsp.h
hw/bsp/nucleo-f072rb/include/bsp/stm32f0xx_hal_conf.h
hw/bsp/nucleo-f072rb/nucleo-f072rb.ld
hw/bsp/nucleo-f072rb/nucleo-f072rb_debug.cmd
hw/bsp/nucleo-f072rb/nucleo-f072rb_debug.sh
hw/bsp/nucleo-f072rb/nucleo-f072rb_download.cmd
hw/bsp/nucleo-f072rb/nucleo-f072rb_download.sh
hw/bsp/nucleo-f072rb/pkg.yml
hw/bsp/nucleo-f072rb/src/arch/cortex_m0/startup_stm32f072xb.s
hw/bsp/nucleo-f072rb/src/hal_bsp.c
hw/bsp/nucleo-f072rb/src/system_stm32f0xx.c
hw/bsp/nucleo-f072rb/syscfg.yml
hw/mcu/stm/stm32_common/src/hal_nvreg.c
hw/mcu/stm/stm32_common/src/hal_spi.c
hw/mcu/stm/stm32_common/src/hal_uart.c
hw/mcu/stm/stm32f0xx/include/mcu/stm32_hal.h
hw/mcu/stm/stm32f0xx/include/mcu/stm32f0xx_mynewt_hal.h
hw/mcu/stm/stm32f0xx/stm32f0xx.ld
hw/mcu/stm/stm32f0xx/syscfg.yml

Nucleo-F072RB

---

hw/drivers/sensors/lps33hw/include/lps33hw/lps33hw.h
hw/drivers/sensors/lps33hw/src/lps33hw.c
hw/drivers/sensors/lps33thw/include/lps33thw/lps33thw.h
hw/drivers/sensors/lps33thw/src/lps33thw.c
hw/sensor/include/sensor/sensor.h
hw/sensor/src/sensor.c

- Add optional API for doing sensor_reset()
- Use the API for LPS33HW and LPS33THW

hw/sensors: Add API for doing sensor_reset()

---

sys/console/full/include/console/console.h
sys/console/full/pkg.yml
sys/console/full/src/ble_monitor_console.c
sys/console/full/src/console.c
sys/console/full/src/rtt_console.c
sys/console/full/src/uart_console.c
sys/console/minimal/include/console/console.h
sys/console/minimal/src/console.c
sys/console/minimal/src/rtt_console.c
sys/console/minimal/src/uart_console.c
sys/console/stub/include/console/console.h
sys/log/stub/include/log/log.h

- Silence non-nlip console output
- Ignore non-nlip console input

sys/console: silence non-nlip console output and ignore non-nlip console input

---

net/oic/include/oic/oc_api.h
net/oic/src/messaging/coap/observe.c

This allows for per-observer type actions/filtering.

net/oic; call get routine for notifications individually for every observer. 

---

hw/drivers/crypto/src/crypto.c

This removes dependency on buffers being a multiple of AES_BLOCK_LEN for CTR.

[CRYPTO] Allow CTR to work with any block size

---

hw/drivers/led/lp5523/src/lp5523.c
mgmt/imgmgr/include/imgmgr/imgmgr.h
mgmt/imgmgr/src/imgmgr.c

Added `start` `stop` and `complete` callbacks for imgmgr

added image upload callbacks to imgmgr

---

hw/drivers/led/lp5523/src/lp5523.c

I was seeing an issue with the 2-byte instruction read and write. Single byte transfers fixed the issue.

drivers/lp5523: change multi byte instruction read write to single

---

mgmt/imgmgr/include/imgmgr/imgmgr.h
mgmt/imgmgr/src/imgmgr.c
mgmt/imgmgr/src/imgmgr_state.c

Added check for NULL imgmgr_dfu_callbacks_fn pointer
Added/renamed imgmgr callouts

imgrmgr: dfu callback fixes

---

time/timepersist/src/time_persist_config.c

Stored time could be considerably off, if system spent extended period of time under. Also this makes the behaviour more similar to setup where NVREG is used as the storage mechanism; losing power means losing time.

timepersist; don't restore time from config if coming out of POR.

---

hw/drivers/flash/spiflash/src/spiflash.c

Time calculation did work correctly on non-1MHz cpu timer.

spiflash: Fix timeout calculation

---

hw/bsp/hifive1/bsp.yml
hw/bsp/hifive1/hifive1_debug.cmd
hw/bsp/hifive1/hifive1_download.cmd

Windows load/debug scripts were missing.

hifive1: Add Windows load/debug scripts

---

sys/shell/src/shell.c

If there are multiple matches but there is some common
part that could be appended without printing all possibilities
just append common part first.
This allows to quickly use tab for completion of similar commands
without polluting shell.

sys/shell: Tab completion works more like bash

---

.rat-excludes
hw/bsp/nucleo-f103rb/boot-nucleo_f103rb.ld
hw/bsp/nucleo-f103rb/bsp.yml
hw/bsp/nucleo-f103rb/include/bsp/bsp.h
hw/bsp/nucleo-f103rb/include/bsp/stm32f1xx_hal_conf.h
hw/bsp/nucleo-f103rb/nucleo_f103rb.ld
hw/bsp/nucleo-f103rb/nucleo_f103rb_debug.cmd
hw/bsp/nucleo-f103rb/nucleo_f103rb_debug.sh
hw/bsp/nucleo-f103rb/nucleo_f103rb_download.cmd
hw/bsp/nucleo-f103rb/nucleo_f103rb_download.sh
hw/bsp/nucleo-f103rb/pkg.yml
hw/bsp/nucleo-f103rb/src/arch/cortex_m3/startup_stm32f103xb.s
hw/bsp/nucleo-f103rb/src/hal_bsp.c
hw/bsp/nucleo-f103rb/src/system_stm32f1xx.c
hw/bsp/nucleo-f103rb/syscfg.yml

Put together from olimex-p103 and bluepill

Add nucleo-f103rb bsp

---

kernel/os/include/os/os_mutex.h

os_mutex: Fix os_mutex_get_level return type

---

hw/hal/include/hal/hal_system.h
hw/mcu/nordic/nrf52xxx/src/hal_reset_cause.c
sys/reboot/include/reboot/log_reboot.h

Obtaining more information on reasons why it is resetting. Adding wake up from system off.

Additional Wake Up / Reset Reason

---

hw/drivers/sensors/lis2dh12/include/lis2dh12/lis2dh12.h
hw/drivers/sensors/lis2dh12/src/lis2dh12.c

Adding ability to check individual axis to see which one is broken.

LIS2DW12 Self Test

---

hw/drivers/adc/gpadc_da1469x/include/gpadc_da1469x/gpadc_da1469x.h
hw/drivers/adc/gpadc_da1469x/src/gpadc_da1469x.c

gpadc_da1469x; add knob to run through ADC calibration sequence

---

hw/mcu/nordic/nrf52xxx/src/hal_system.c
hw/mcu/nordic/nrf52xxx/syscfg.yml
kernel/os/src/arch/cortex_m4/os_fault.c

- It should get called before asm("bkpt") gets called

Add MCU_PRE_BKPT_CB() syscfg

---

apps/sensors_test/src/main.c
hw/drivers/sensors/kxtj3/include/kxtj3/kxtj3.h
hw/drivers/sensors/kxtj3/pkg.yml
hw/drivers/sensors/kxtj3/src/kxtj3.c
hw/drivers/sensors/kxtj3/src/kxtj3_priv.h
hw/drivers/sensors/kxtj3/src/kxtj3_shell.c
hw/drivers/sensors/kxtj3/syscfg.yml
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Driver supports following sensor functionality:
- sensor data poll
- sensor config: resolution, grange, odr
Driver tested on nordic_pca10040 with sensor test app
and kxtj3 shell app.

Add KXTJ3 sensor driver

---

hw/bsp/black_vet6/bsp.yml
hw/bsp/black_vet6/include/bsp/bsp.h
hw/bsp/black_vet6/src/hal_bsp.c
hw/bsp/black_vet6/syscfg.yml

- Reduced NFFS size to avoid assert in config fcb
- Added USART2 and USART3

black vet6 bsp update

---

hw/drivers/sensors/kxtj3/include/kxtj3/kxtj3.h
hw/drivers/sensors/kxtj3/src/kxtj3.c
hw/drivers/sensors/kxtj3/src/kxtj3_priv.h
hw/drivers/sensors/kxtj3/src/kxtj3_shell.c
hw/drivers/sensors/kxtj3/syscfg.yml
hw/sensor/creator/src/sensor_creator.c

- Add KXTJ3 wake-up support
- Add interrupt support
Wake-up tested on nordic_pca10040 with sensor test app
and kxtj3 shell app.

Add KXTJ3 sensor wake-up support

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh

...completely at the end of download.

da1469x-dk-pro; 'mon reset' does not appear to reset the MCU

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

This commit moves the initialization of the SCK gpio to hal_config_spi_master.
This initialization was done in hal_spi_init_master previously. The reason
for moving this is the data mode in the structure does not get set prior to
calling the init function. This could cause the GPIO to be configured in
an incorrect manner. Note that the nordic specification makes specific mention
regarding how SPI GPIO should be configured prior to enabling the SPI master.
In this case, SCK should be an output with state set same as CONFIG.CPOL

hw/mcu/nordic: Initialize SCK for SPI in config API

---

hw/drivers/sensors/bma253/src/bma253.c

- Fix build with BUS_DRIVER_PRESENT:1

bma253: Fix build with BUS_DRIVER_PRESENT:1

---

hw/mcu/dialog/da1469x/src/hal_gpio.c

hw/mcu/dialog: Fix pin latch registers usage

---

hw/drivers/uart/uart_bitbang/src/uart_bitbang.c

uart_bitbang; allow configuration without RX.

---

hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Allow sensor to be placed at non I2C_0 interface.

sensors: mpu6050 add flexibility

---

hw/bsp/nucleo-l476rg/include/bsp/bsp.h
hw/bsp/nucleo-l476rg/src/hal_bsp.c
hw/bsp/nucleo-l476rg/syscfg.yml
hw/mcu/stm/stm32l4xx/syscfg.yml

Change adds one UART and two I2C interfaces.

nucleo l476 peripherals

---

hw/mcu/nordic/nrf52xxx/include/mcu/nrf52_hal.h
hw/mcu/nordic/nrf52xxx/include/nrfx52810_config.h
hw/mcu/nordic/nrf52xxx/include/nrfx52811_config.h
hw/mcu/nordic/nrf52xxx/include/nrfx_config.h
hw/mcu/nordic/nrf52xxx/pkg.yml
hw/mcu/nordic/nrf52xxx/src/hal_flash.c
hw/mcu/nordic/nrf52xxx/src/hal_gpio.c
hw/mcu/nordic/nrf52xxx/src/hal_i2c.c
hw/mcu/nordic/nrf52xxx/src/system_nrf52.c
hw/mcu/nordic/nrf52xxx/syscfg.yml
hw/mcu/nordic/pkg.yml

Updated TWI definitions to use new struct.
Added various NRF52811 specific defines (and sometimes NRF52810!)

Trying to add NRF52811 support

---

hw/bus/drivers/spi_hal/src/spi_hal.c
hw/drivers/sensors/adxl345/include/adxl345/adxl345.h
hw/drivers/sensors/adxl345/src/adxl345.c
hw/drivers/sensors/bme280/include/bme280/bme280.h
hw/drivers/sensors/mpu6050/include/mpu6050/mpu6050.h
hw/drivers/sensors/mpu6050/src/mpu6050.c
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Couple of small build issues in sensors and bus drivers.
- Build issues fixed in bus driver for dialog.
- Build issues fixed for bme280 and adxl345
- Bus driver support added to mpu6050 and adxl345
- Sensor creator for bus driver for mpu6050 and adxl345

sensors and bus drivers

---

hw/drivers/sensors/bma253/src/bma253.c

- Fix build issue with bma253 and also change the name of the notification config to be default

hw/bma253: fix build

---

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger_shell.c

Register read and write commands were not available in compat shell.
Help from compat was not in sync with new style commands.
Compat shell was unconditionally used, now it can be turned off.
Now compat and new style shell commands use same table of commands
and risk of having different commands is removed.

da1469x_charger: Update compat cli

---

hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bma253/src/bma253_shell.c
hw/drivers/sensors/bma253/syscfg.yml

-  Fix I2C build and add notification stats
- Also fix device shell name

bma253: Fix I2C build and add notification stats

---

hw/drivers/sensors/bma253/src/bma253.c

- Use FIFO mode for streaming
- Fix timeout on reading FIFOs
- Remove the FIFO read outer loop since bma253_read_and_handle_fifo_data() already dumps the FIFO

sensors/bma253: Use FIFO mode for streaming

---

sys/log/full/src/log_nmgr.c
sys/log/full/syscfg.yml

Adding syscfg to configure log watermark update after every log read. @ccollins476ad

log: configurability for log read watermark update

---

hw/drivers/sensors/lps33hw/src/lps33hw.c

Updated variable name as it changed in the previous PR from lps to lps33hw.

LPS33HW Stale Variable

---

hw/drivers/sensors/bmp388/include/bmp388/bmp388.h
hw/drivers/sensors/bmp388/src/bmp388.c
hw/drivers/sensors/bmp388/src/bmp388_priv.h
hw/drivers/sensors/bmp388/src/bmp388_shell.c
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

Fix driver for BMP388 sensor

---

hw/bsp/dialog_da1469x-dk-pro/da1469x_serial.py
hw/bsp/dialog_da1469x-dk-pro/otp_tool.py
hw/mcu/dialog/da14699/include/mcu/mcu.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_otp.h
hw/mcu/dialog/da1469x/src/da1469x_otp.c
hw/mcu/dialog/da1469x/src/system_da1469x.c

Rebased this to the current master in use

OTP drivers and scripts

---

hw/hal/include/hal/hal_system.h
hw/hal/src/hal_common.c
sys/reboot/include/reboot/log_reboot.h
sys/reboot/src/log_reboot.c

Also fix an issue where reboot count was advancing twice for
some reboots.

[REBOOT REASON] Add a new entry for DFU RESET

---

hw/mcu/dialog/da1469x/src/da1469x_trimv.c

Latest version of OTP driver uses offset instead of address as a
location of OTP word to read. Current version of trim values driver was
not updated for this so it does not quite read values properly...

hw/mcu/dialog: Fix reading trim values from OTP

---

hw/bsp/dialog_da1469x-dk-pro/dialog_da1469x-dk-pro_download.sh
hw/bsp/dialog_da1469x-dk-pro/otp_tool.py
hw/mcu/dialog/da14699/include/mcu/mcu.h
hw/mcu/dialog/da1469x/include/mcu/da1469x_otp.h
hw/mcu/dialog/da1469x/src/da1469x_otp.c
hw/mcu/dialog/da1469x/src/hal_system_start.c

This patch fixes some minor issues with the OTP provisioning script
and also finishes the secure boot process by leveraging recently added
mcuboot features.

Fixup OTP provisioning script and secure boot process

---

apps/lora_app_shell/pkg.yml
apps/lora_app_shell/src/las_cmd.c
net/lora/node/src/lora_cli.c

Patch from mynewt@hackdaworld.org.

Fix build error when lora CLI syscfgs were disabled.

---

sys/shell/src/shell.c

When module is selected with 'select' command commands
from other modules can't be executed.
They can be execute when no module is selected or correct module is
selected.
To execute tasks command from compat module those lines would work:
```
shell> comapt tasks
compat> tasks
```
but once other module is selected tasks can't be executed without
leaving btshell module.
With this change commands from other modules can executed if
module name is prefixed with **/**
```
btshell> /compat tasks
```
Auto completion also works with **/**

sys/shell: Add full command path handling

---

hw/bsp/hifive1/hifive1.ld
hw/bsp/hifive1/include/bsp/bsp.h

Other bsp's already have sections for uninitialized data.
Now hifive1 will also have it.

hw/bsp/hifive1: Add bss non zero section

---

hw/mcu/nordic/nrf52xxx/src/hal_spi.c

nrf52xxx/hal_spi.c, change to use MCU_TARGET instead of old MCU_NRF52832

---

sys/console/full/src/console.c

It cab be useful to preserver console history in RAM when
code is begin debugged and application is intentionally
rebooted i.e. mon reset.
History memory is put in bssnz section and magic value is
stored to detect RAM preservation.
History will be preserved on some platforms where during
reboot history data is not overwritten by bootloader data.
Tested to work on hifive1 board with custom reset handler,
and dialog da14699 board.

sys/console: Allow history to be preserved during reset

---

sys/console/full/src/console.c

There were reports that latest console changes affect
existing eco-system that depends on CR and LF characters
to be handled even if console is instructed to ignore
non-nlip traffic.
This change allow simple test that device is alive by
pressing Enter on keyboard.
Original code also echo back some other random non
printable characters but this is not restored.

sys/console: Restore old style CR LF handling for nlip

---

kernel/os/src/os.c

Previous check causes idle task to skip sanity check if wake up occured
at the same tick when sanity should happen. This should not be a problem
because iticks will be 0 and sanity check will be performed after wakeup
on next tick. The only side effect should be wake up on 2 consecutive
ticks. However...
It is (unlikely but) possible that (at least) one tick occurs between
check and entering critical section. If this happens on a tick where
sanity check is skipped, time to next sanity is calculated as a negative
value instead of 0 so depending on time to next sched/callout we may not
wake up for sanity and tickle watchdog on time.

kernel/os: Fix sanity interval handling

---

kernel/os/include/os/os_task.h
kernel/os/src/os_task.c

This allows to get info about specified task.

kernel/os: Add os_task_info_get function

---

sys/console/full/history_log/pkg.yml
sys/console/full/history_log/src/history_log.c
sys/console/full/history_log/syscfg.yml
sys/console/full/history_ram/pkg.yml
sys/console/full/history_ram/src/history_ram.c
sys/console/full/history_ram/syscfg.yml
sys/console/full/include/console/history.h
sys/console/full/pkg.yml
sys/console/full/src/console.c
sys/console/full/syscfg.yml

Console history now can be kept in log as well as in ram.

console history persistence

---

hw/bsp/nucleo-f411re/boot-nucleo-f411re.ld
hw/bsp/nucleo-f411re/bsp.yml
hw/bsp/nucleo-f411re/include/bsp/bsp.h
hw/bsp/nucleo-f411re/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/nucleo-f411re/nucleo-f411re.ld
hw/bsp/nucleo-f411re/nucleo-f411re_debug.cmd
hw/bsp/nucleo-f411re/nucleo-f411re_debug.sh
hw/bsp/nucleo-f411re/nucleo-f411re_download.cmd
hw/bsp/nucleo-f411re/nucleo-f411re_download.sh
hw/bsp/nucleo-f411re/pkg.yml
hw/bsp/nucleo-f411re/src/arch/cortex_m4/startup_STM32F411.s
hw/bsp/nucleo-f411re/src/hal_bsp.c
hw/bsp/nucleo-f411re/syscfg.yml
hw/mcu/stm/stm32f4xx/include/mcu/cmsis_nvic.h
hw/mcu/stm/stm32f4xx/stm32f411.ld
hw/mcu/stm/stm32f4xx/syscfg.yml

This adds:
- support for STM32F411RE MCU
- Nucleo-F411RE board

Add Nucleo-F411RE

---

net/oic/src/api/oc_client_api.c

If there was an error during cbor processing the code in dispatch_coap_request() would set an incorrect payload length of 0xffff since the return code of -1 was being interpreted as a length instead of an error. The new code checks for error from oc_rep_finalize(), and if there is an error, frees the appropriate buffers and clears and transactions (if any).

net/oic: Handle cbor error in dispatch_coap_request()

---

uncrustify.cfg

This brings the uncrustify config closer to matching the current style employed in Mynewt.

Fix more uncrustify issues

---

hw/drivers/flash/enc_flash/ef_da1469x/src/hw_enc_flash.c

Support encryption, decryption operation for block lengths != ENC_FLASH_BLK (16)

da1469x: support blocks that are not ENC_FLASH_BLK multiples.

---

compiler/gdbmacros/callout.gdb

- Usage "mn_callout_print &g_callout_list"

gdbmacros: Add callout traversing script

---

hw/bsp/stm32f411discovery/boot-stm32f411discovery.ld
hw/bsp/stm32f411discovery/bsp.yml
hw/bsp/stm32f411discovery/include/bsp/bsp.h
hw/bsp/stm32f411discovery/include/bsp/stm32f4xx_hal_conf.h
hw/bsp/stm32f411discovery/pkg.yml
hw/bsp/stm32f411discovery/src/arch/cortex_m4/startup_STM32F411.s
hw/bsp/stm32f411discovery/src/hal_bsp.c
hw/bsp/stm32f411discovery/stm32f411discovery.ld
hw/bsp/stm32f411discovery/stm32f411discovery_debug.cmd
hw/bsp/stm32f411discovery/stm32f411discovery_debug.sh
hw/bsp/stm32f411discovery/stm32f411discovery_download.cmd
hw/bsp/stm32f411discovery/stm32f411discovery_download.sh
hw/bsp/stm32f411discovery/syscfg.yml

This PR adds support for stm32f411discovery AKA STM32F411E-DISC0

Adding  bsp/stm32f411discovery 

---

encoding/base62/include/base62/base62.h
encoding/base62/pkg.yml
encoding/base62/selftest/pkg.yml
encoding/base62/selftest/src/encoding_test.c
encoding/base62/selftest/src/testcases/base62_encoding.c
encoding/base62/selftest/src/testcases/base62_errors.c
encoding/base62/selftest/src/testcases/base62_invalid_args.c
encoding/base62/src/base62.c

Base62 encoding code and unit tests.

Add base62 encoder/decoder

---

docs/os/modules/console/console.rst

Added example of event queue handling for full console.

Add full console example to console documentation

---

sys/console/full/history_ram/src/history_ram.c

Feature present in log based console history is now implemented
to ram base history handler.

sys/console: Add auto search to ram based history

---

hw/drivers/display/cfb/include/display/cfb.h
hw/drivers/display/cfb/src/cfb.c
hw/drivers/display/cfb/src/cfb_fonts.c
hw/drivers/display/include/display/display.h
hw/drivers/display/ssd1673/src/ssd1673.c
hw/drivers/display/ssd1673/src/ssd1673_regs.h

This code is under Apache-2 license but was not developed for
Apache Software Foundation.

Fix license headers in hw/drivers/display

---

hw/bsp/dialog_da1469x-dk-pro/cfg/device.cfg
hw/bsp/dialog_da1469x-dk-pro/cfg/ft4232h.cfg
hw/bsp/dialog_da1469x-dk-pro/da1469x_serial.py
hw/bsp/dialog_da1469x-dk-pro/otp_tool.py
hw/bsp/dialog_da1469x-dk-pro/reset.sh
hw/bsp/dialog_da1469x-dk-pro/reset_ocd.sh

This PR brings in enhancement updates to the OTP and Serial Loading Tools.

dialog_da1469x: enhance otp and serial loader tools.

---

hw/drivers/i2s/README.md
hw/drivers/i2s/i2s_stm32f4/include/i2s_stm32f4/i2s_stm32f4.h
hw/drivers/i2s/i2s_stm32f4/include/i2s_stm32f4/stm32_pin_cfg.h
hw/drivers/i2s/i2s_stm32f4/pkg.yml
hw/drivers/i2s/i2s_stm32f4/src/i2s_stm32f4.c
hw/drivers/i2s/i2s_stm32f4/syscfg.yml
hw/drivers/i2s/include/i2s/i2s.h
hw/drivers/i2s/include/i2s/i2s_driver.h
hw/drivers/i2s/pkg.yml
hw/drivers/i2s/src/i2s.c

This PR adds I2S driver for STM32F4 MCU.
First 2 commits are part of #2267.

Add I2S driver for stm32f4

---

hw/mcu/nordic/pkg.yml

Modified copies of those are no longer present in tree.

hw/mcu/nordic: Remove old entries for ignored files

---

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c

This PR addresses an issue with setting up the channel gain and makes the ADC calibrate(if calibrate is active) on every sample right after a configuration.

adc/nrf52_adc: Driver improvements and fixes: calibration and gain 

---

hw/drivers/temp/include/temp/temp.h
hw/drivers/temp/pkg.yml
hw/drivers/temp/src/temp.c
hw/drivers/temp/temp_nrf52/include/temp_nrf52/temp_nrf52.h
hw/drivers/temp/temp_nrf52/pkg.yml
hw/drivers/temp/temp_nrf52/src/temp_nrf52.c
hw/mcu/nordic/nrf52xxx/pkg.yml
hw/mcu/nordic/nrf52xxx/src/nrf52_periph.c
hw/mcu/nordic/nrf52xxx/syscfg.yml

This adds a generic temperature driver interface, a driver for nRF52 temperature sensor and the initialization code for the nRF52 MCU.

Temperature sensor nRF52

---

hw/drivers/crypto/crypto_da1469x/include/crypto_da1469x/crypto_da1469x.h
hw/drivers/crypto/crypto_da1469x/pkg.yml
hw/drivers/crypto/crypto_da1469x/src/crypto_da1469x.c
hw/drivers/crypto/crypto_da1469x/syscfg.yml
hw/mcu/dialog/da1469x/pkg.yml
hw/mcu/dialog/da1469x/src/da1469x_periph.c
hw/mcu/dialog/da1469x/syscfg.yml

This is untested because I don't have HW! Best way to test is to run `apps/crypto_test` and check no errors are detected.
/cc @nkaje @agross-korg

da1469x: add initial crypto driver

---

net/ip/native_sockets/src/native_sock.c

Some miscellaneous fixes for the `net/ip/native_sock` package.

Native sock fixes

---

net/oic/src/port/mynewt/tcp4_adaptor.c

This is a fix that I meant to include in the previous PR (https://github.com/apache/mynewt-core/pull/2300).  Sorry for the confusion!
Prior to commit:
When a managed TCP connection had no pending transmits, the code would
enqueue another "tx" event.  As a result, the "tx" event would always be
executing or enqueued!
Fix:
If a connection has no pending transmits, move on to the next
connection.  Do not enqueue a "tx" event.

oic tcp4_adaptor: Don't loop if nothing to tx

---

hw/mcu/dialog/da1469x/src/hal_i2c.c

Currently hal_i2c acquires PD_COM on init and does not release it. This
means it will be always powered, even in deep sleep.
With this patch, PD_COM is only acquired by hal_i2c_enable and then can
be released by hal_i2c_disable. Also clock and I2C itself is enabled
and disabled on request which should allow to disable PD_COM in deep
sleep assuming other users can also release this power domain properly.
There are not many registers to configure on init so the process of
enabling I2C is still pretty quick.
New behavior should be especially useful if used via bus driver. Once
"BUS_PM: 1" is set, bus driver will automatically enable when needed and
disable when not used anymore.

hw/mcu/dialog: Add better power control to hal_i2c

---

mgmt/oicmgr/syscfg.yml

oicmgr: fix typo in syscfg.yml

---

apps/crypto_test/src/main.c

The concurrency test output is garbled and difficult
to read when the lines don't get printed completely.
Avoid this by using a mutex.
Before:
=== Concurrency [8 tasks] ===
task0 [0 fails / 256 ok] done
task1 [0 fails / 2t5t6t totkt] done
ask2 [0 fails / 256 ok] done
ask3 [0 afaaaials / 256 ok] done
sk4 [0 fails / 256 sosks] done
k5 [0 fails / 256 ok] done
k6 [0 fakils / 256 ok] done
7 [0 fails / 256 ok] done
After:
=== Concurrency [8 tasks] ===
task0 [0 fails / 256 ok] done
task1 [0 fails / 256 ok] done
task2 [0 fails / 256 ok] done
task3 [0 fails / 256 ok] done
task4 [0 fails / 256 ok] done
task5 [0 fails / 256 ok] done
task6 [0 fails / 256 ok] done
task7 [0 fails / 256 ok] done

crypto_test: add a mutex to serialize prints

---

apps/slinky/src/led.c
apps/slinky/src/led.h
apps/slinky/src/main.c
apps/slinky/syscfg.yml

1. apps/slinky: use led when available
2. slinky: enable console history

Slinky: use LEDs when available

---

hw/mcu/dialog/da1469x/src/hal_uart.c

This ensures PD_COM is acquired only when UART is configured (i.e.
opened) and released when closed.

hw/mcu/dialog: Fix pd_com handling in hal_uart

---

hw/bsp/dialog_da1469x-dk-pro/otp_tool.py

Use a default baudrate of 500000. Update all the APIs
to pass in an option to use a different baudrate if desired.

otp_tool: Use a default baudrate.

---

hw/sensor/include/sensor/current.h
hw/sensor/include/sensor/sensor.h
hw/sensor/include/sensor/voltage.h
hw/sensor/src/sensor_shell.c

current.h and voltage.h are used in INA219 and INA226 and there were not added yet.
Sensors shell also has support for current and voltage.

sensors: Add current and voltage support

---

hw/hal/include/hal/hal_system.h
hw/mcu/dialog/da1469x/src/hal_system.c
sys/reboot/include/reboot/log_reboot.h
sys/reboot/src/log_reboot.c
sys/reboot/syscfg.yml

Adding all checks for reboot reasons per da1469x ds.

hw/mcu/dialog: Add all reset reason checks

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

Fixes a few issues that were causing unreliable DMA operation when using channels
higher than 0 and 1.
1. In MCU_DMA_GET_MUX, shift the mux config bitfields by `cidx * 2` instead of `cidx * 4`. 
DMA_REQ_MUX_REG consists of 4 bitfields of 4 bits each, where each field applies to a channel pair:
```
For cidx=2, shift by cidx*2=4 to read DMA23_SEL at bits 7:4
For cidx=4, shift by cidx*2=8 to read DMA45_SEL at bits 11:8
For cidx=6, shift by cidx*2=12 to read DMA67_SEL at bits 15:12
```
2. In `da1469x_dma_acquire_single()` and `da1469x_dma_release_channel()`, exclude channels 8 and higher from using DMA_REQ_MUX_REG, since the register only applies to channels 0-7.

mcu/dialog: Fix a few bugs in da1469x_dma.c

---

hw/drivers/i2s/i2s_nrf52/src/i2s_nrf52.c

I2S setup was no done for 24 bits samples, all calculations were
for 16 and 8 bits samples only.
Ratio value for 48000Hz sample rate was incorrect and would result
in an assert in nrfx code.

hw/drivers/i2s: Add support for 24 bits samples for NRF52

---

hw/battery/src/battery.c
hw/battery/syscfg.yml

allow more then one battery

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

DMA controller resides in PD_SYS domain so we cannot turn off that
domain if any DMA channes is acquired. That basically means on 1st
acquired DMA channel we need to also acquire PD which we can release
after last DMA channel is released. Note that acquiring PD_SYS means
M33 cannot be powered down in deep sleep.

hw/mcu/dialog: Acquire PD_SYS for DMA

---

hw/drivers/crypto/crypto_da1469x/src/crypto_da1469x.c
hw/mcu/dialog/da1469x/src/da1469x_dma.c

Modify the crypto driver to acquire/release the
DMA channel being used. As the acquire/release
modifies a global variable and DMA_REQ_MUX_REG, which
are shared resources, these accesses need to be done
in a critical section.
The marcros MCU_DMA_SET_MUX/MCU_DMA_GET_MUX are reworked
to generate the pattern  for the pair of channels as documented
in the datasheet.
Configure DMA_REQ_MUX_REG within a critical section to avoid
race conditions. Use common macros provided by the DMA
driver to make changes to this register. It is to be noted that this
lock usage can be quite heavy when the any given DMA channel needs to be
accessed for long periods of time and this should be addressed.

da1469x: Fix DMA Multiplexer register access

---

hw/mcu/nordic/nrf52xxx/src/hal_qspi.c

Without a hff_erase implementation for HAL flash functions, the HAL flash layer will default to sector erase for all
erase functions, regardless of length.
This PR implements hff_erase, and will issue a chip erase or 64KB block erase where possible based on the address and length of area to be erased.
On the nRF52840 DK (PCA10056) using the provided MX25R6435F QSPI flash, I measured a 4K sector erase of about 84 mS.  With this patch, a 64KB block erase averages about 1164 mS.  This saves about 176 mS per 64K erase.

64KB block and chip erase for Nordic nrf52 QSPI

---

hw/mcu/stm/stm32_common/syscfg.yml

Missing SPI definitions on STM32 common drivers. See issue #2385

WIP: SPI_4 and SPI_5 definitions

---

hw/mcu/dialog/cmac/src/cmac_isr.c
hw/mcu/dialog/cmac/src/cmac_sleep.c

hw/mcu/cmac: Dispatch RF calibration req

---

hw/mcu/stm/stm32_common/src/stm32_driver_mod_i2c_v1.c

Sometime glitche on SDA SCL lines cause I2c to enter
busy state that never end.
All calls to read or write will fail later because of BUSY flag.
Datasheet recommens software reset in that case.
Workaround applied to transmit only, it could be on receive
but that should do.

Add busy I2C state recovery on STMF1/F4/L1

---

hw/mcu/dialog/da1469x/src/da1469x_clock.c

There was extarn for SystemCoreClock but variable was not defined
like on others MCUs.
This adds variable and sets it according to current system clock
selection.

hw/mcu/dialog: Add SystemCoreClock variable

---

hw/mcu/dialog/da1469x/src/hal_uart.c

If RX pin is set to negative value UART can be used with TX functionality only.
Useful for logging only UART

hw/mcu/dialog: Allow TX only UART

---

kernel/os/src/arch/cortex_m33/os_fault.c

allow extra time for corefile to be created in NMI handler

---

hw/mcu/microchip/pic32mx470f512h/include/mcu/pic32.h
hw/mcu/microchip/pic32mx470f512h/src/hal_system.c
hw/mcu/microchip/pic32mz2048efg100/include/mcu/pic32.h
hw/mcu/microchip/pic32mz2048efg100/src/hal_system.c
kernel/os/include/os/arch/pic32/os/os_arch.h
kernel/os/src/arch/pic32/os_arch_pic32.c

pic32 was neglected for some time it would not build for some trivial reasons.

fix pic32 build issues

---

hw/bsp/nucleo-l073rz/boot-nucleo-l073rz.ld
hw/bsp/nucleo-l073rz/bsp.yml
hw/bsp/nucleo-l073rz/include/bsp/bsp.h
hw/bsp/nucleo-l073rz/include/bsp/stm32l0xx_hal_conf.h
hw/bsp/nucleo-l073rz/nucleo-l073rz.ld
hw/bsp/nucleo-l073rz/nucleo-l073rz_debug.sh
hw/bsp/nucleo-l073rz/nucleo-l073rz_download.sh
hw/bsp/nucleo-l073rz/pkg.yml
hw/bsp/nucleo-l073rz/src/arch/cortex_m0/startup_stm32l073xx.s
hw/bsp/nucleo-l073rz/src/hal_bsp.c
hw/bsp/nucleo-l073rz/syscfg.yml

This PR adds BSP for one of the nucleo boards.

Add nucleo-l073rz BSP

---

hw/drivers/sensors/ina226/include/ina226/ina226.h
hw/drivers/sensors/ina226/pkg.yml
hw/drivers/sensors/ina226/src/ina226.c
hw/drivers/sensors/ina226/src/ina226_shell.c
hw/drivers/sensors/ina226/syscfg.yml

I forget add licence on all file

Licence is missing to INA226 files

---

apps/hash_test/src/main.c
hw/drivers/hash/hash_kinetis/src/hash_kinetis.c

* apps: hash_test: add small varlen inputs test - Add a new test that hashes multiple small variable length strings into a digest, where each string is smaller than SHA-256 block length.
* hw: drivers: hash_kinetis: fix small buffer hashing - Hashing a message with multiple blocks of length<=64 (SHA-256 block length) was broken due to proper usage of the mmCAU padding. This commit fixes the handling of the pad data.

Fix Kinetis HASH driver with small length buffers

---

hw/drivers/sensors/bma253/src/bma253.c
hw/drivers/sensors/bma2xx/src/bma2xx.c
hw/drivers/sensors/bme680/src/bme680.c
hw/drivers/sensors/bmp388/src/bmp388.c
hw/drivers/sensors/bno055/src/bno055_shell.c
hw/drivers/sensors/icp101xx/src/icp101xx.c
hw/drivers/sensors/lis2dh12/src/lis2dh12.c
hw/drivers/sensors/lsm6dso/src/lsm6dso.c
hw/drivers/sensors/tcs34725/src/tcs34725.c
hw/drivers/sensors/tsl2561/src/tsl2561.c
hw/drivers/sensors/tsl2561/src/tsl2561_shell.c

Fixes for Coverity issues

---

apps/pwm_test/src/pwm_shell.c
hw/drivers/sensors/bno055/src/bno055_shell.c
hw/sensor/src/sensor_oic.c

strtok is not thread safe.
Fixes #2510

Replace strtok with strtok_r

---

net/osdp/pkg.yml

Update pkg.yml with a better description.

net/osdp: update pkg.yml with a better description

---

hw/mcu/nxp/kinetis/src/hal_qspi.c

Update the QSPI flash driver so it can work correctly with two flashes connected to the two QSPI channels. This is currenctly limited to using two QSPI flashes of the same type.

hw: mcu: kinetis: Fix dual flash QSPI support

---

hw/usb/tinyusb/std_descriptors/src/std_descriptors.c

TinyUSB project updated HID callbacks function with
additional interface parameter.
This updated standard descriptors handling code to
use new prototypes provided by TinyUSB.

tinyusb: Update HID callbacks signatures

---

hw/drivers/flash/spiflash/chips/syscfg.yml
hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c

hw/drivers/flash/spiflash: add JEDEC_MFC_XTX and XT25F32B chip

---

sys/console/full/src/console.c
sys/console/full/src/console_priv.h
sys/console/full/syscfg.yml
sys/console/full/tcp_console/pkg.yml
sys/console/full/tcp_console/src/tcp_console.c
sys/console/full/tcp_console/syscfg.yml

This adds TCP console implementation.

sys/console: Add TCP console

---

hw/mcu/sifive/fe310/include/mcu/fe310_hal.h
hw/mcu/sifive/fe310/src/hal_spi.c

Fix typo and duplicated function prototype.

mcu/fe310: Fix typo

---

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c

Software reset does not clear IPC registers.
This can result in strange scenarios where
IPC registers set before software reset are
used as if some fresh communication happened.
This will lead to hard fault virtually preventing
OTA when reset is induced by software instead of
reset pin.
1. Now code does not handle pending interrupts that are
visible in INTPEND but they were not enabled hence callback
is NULL.
2. During ipc_nrf5340_init() also clear RECEIVE_CNF so no
spurious event is tried to be handled.

hw/ipc_nrf5340: Improve reset behavior

---

hw/mcu/nordic/nrf5340/src/hal_system.c
hw/mcu/nordic/nrf5340/syscfg.yml
hw/mcu/nordic/nrf5340_net/src/hal_system.c
hw/mcu/nordic/nrf5340_net/syscfg.yml

https://infocenter.nordicsemi.com/index.jsp?topic=%2Fps_nrf5340%2Fnvmc.html

nrf53/hal: icache config enable reg is in netcore

---

hw/drivers/flash/spiflash/chips/syscfg.yml
hw/drivers/flash/spiflash/src/spiflash.c

hw/drivers/flash/spiflash: add XM25QH32B chip

---

hw/drivers/ram/spiram/include/spiram/spiram.h
hw/drivers/ram/spiram/pkg.yml
hw/drivers/ram/spiram/src/spiram.c
hw/drivers/ram/spiram/syscfg.yml

This adds driver for SPI RAMs.

hw/drivers/spiram: Add SPI RAM driver

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

Function da1469x_dma_write_peripheral() sets up source register to be
used by DMA transfer (Memory->Peripheral) and starts DMA.
If source address is located in QSPI flash it can still be used if
address is not from cached region 0x1600000-0x18000000.
This updates source address to be from uncached region if QSPI cached
area was used.

da1469x: Allow DMA reads from QSPI

---

hw/drivers/uart/max3107/include/max3107/max3107.h
hw/drivers/uart/max3107/pkg.yml
hw/drivers/uart/max3107/src/max3107.c
hw/drivers/uart/max3107/src/max3107_priv.h
hw/drivers/uart/max3107/syscfg.yml

This adds driver for max3107 (SPI to UART device).

hw/drivers/uart: Add MAX3107 driver

---

kernel/os/src/arch/pic32/os_arch_pic32.c

Tick timer interrupt handler assumed it was execute before
next tick interrupt should be fired.
In case when interrupt was handled late (due to other interrupts
or just blocked interrupt for some time) next computed tick time
was already in the past and system time stopped for a very long time.
Now COMPARE register when set is compared to current COUNT register
and if it is in the past next tick time is computed until interrupt
is schedule to be ahead of COUNT register.
Also os_time_advance() takes into account what is the difference of
COUNT and COMPARE registers and in case of late interrupt, g_os_time
can advance more then one tick at a time.

pic32: Fix tick timer handling

---

net/osdp/src/osdp.c
net/osdp/src/osdp_common.c
net/osdp/src/osdp_cp.c
net/osdp/src/osdp_pd.c
net/osdp/src/osdp_sc.c

net/osdp: support additional osdp baud rates

---

net/osdp/src/osdp.c
net/osdp/src/osdp_common.c
net/osdp/src/osdp_cp.c
net/osdp/src/osdp_pd.c
net/osdp/src/osdp_sc.c

net/osdp: ignore reply incoming from another PD

---

.travis.yml

Related to https://github.com/JuulLabs-OSS/mynewt-travis-ci/pull/92

travis.yml: Install gcc via homebrew addon

---

apps/timtest/src/main.c

Timer configuration frequencies were changed without fixing the comments.

apps: timtest: fix frequency in comments

---

hw/mcu/nxp/kinetis/src/hal_qspi.c

Lock the OS when calling `QSPI_SoftwareReset`; this API sets bits that result in a QSPI HW reset, loops for a while, and manually resets the same bits. If a context switch happens while those bits are set, and the next task reads the QSPI flash through the AHB mapping, this read results in zeroes being returned instead of the expected data.
Also removed a non-required busy wait after the HW reset.

mcu: kinetis: fix QSPI HW reset race

---

hw/mcu/nordic/nrf5340/src/hal_system_start.c

To prevent information leak from ARM TrusZone secure to non-secure code,
on-secure RAM (whole as of now) is cleared before switching to non-secure mode.

mcu/nrf5340: Clear RAM before switching to non-secure

---

hw/mcu/nordic/nrf5340/net_core_image/syscfg.yml

Commit follows target name change in nimble repository.
PR that needs to be merged first: https://github.com/apache/mynewt-nimble/pull/1095

mcu/nrf5340: Update blehci target name

---

hw/bsp/nordic_pca10059/boot-nrf52840aa.ld
hw/bsp/nordic_pca10059/bsp.yml
hw/bsp/nordic_pca10059/include/bsp/bsp.h
hw/bsp/nordic_pca10059/nordic_pca10059_debug.sh
hw/bsp/nordic_pca10059/nordic_pca10059_download.sh
hw/bsp/nordic_pca10059/nordic_pca10059_no_boot.ld
hw/bsp/nordic_pca10059/nrf52840aa.ld
hw/bsp/nordic_pca10059/pkg.yml
hw/bsp/nordic_pca10059/split-nordic_pca10059.ld
hw/bsp/nordic_pca10059/src/arch/cortex_m4/gcc_startup_nrf52840.s
hw/bsp/nordic_pca10059/src/arch/cortex_m4/gcc_startup_nrf52_split.s
hw/bsp/nordic_pca10059/src/hal_bsp.c
hw/bsp/nordic_pca10059/syscfg.yml

BSP is mostly copy of pca10056 with buttons and LEDs
definitions.
UART is turned off by default

hw/bsp: Add BSP for nRF52840 Dongle pca10059

---

hw/mcu/stm/stm32_common/src/stm32_periph.c

Added support for additional SPI initializations.

stm32_periph: Add additional SPIs

---

hw/mcu/dialog/da1469x/src/hal_uart.c

1. Set TX threshold for FIFO at 1/4 full so we can start pushing bytes
before it's completely empty.
2. Delay tx_done callback until last byte left THR.

hw/mcu/da1469x: Improve UART TX isr handling

---

hw/scripts/common.sh

Not sure what this gets used for but I had already started to patch it before I realised it wasn't my problem and perhaps the code is useful for others.

OSX support for detect_programmer

---

hw/drivers/sensors/lsm6dsl/include/lsm6dsl/lsm6dsl.h
hw/drivers/sensors/lsm6dsl/pkg.yml
hw/drivers/sensors/lsm6dsl/src/lsm6dsl.c
hw/drivers/sensors/lsm6dsl/src/lsm6dsl_priv.h
hw/drivers/sensors/lsm6dsl/src/lsm6dsl_shell.c
hw/drivers/sensors/lsm6dsl/syscfg.yml
hw/sensor/creator/pkg.yml
hw/sensor/creator/src/sensor_creator.c
hw/sensor/creator/syscfg.yml

This PR:
- adds driver for LSM6DSL
- adds LSM6DSL to sensors creator

Add support for LSM6DSL

---

hw/mcu/dialog/cmac/src/cmac_timer.c

Need to use proper comparator.

hw/mcu/cmac: Fix calculating time-to-next timer

---

hw/drivers/uart/uart_da1469x/src/uart_da1469x.c
hw/mcu/dialog/da1469x/src/hal_uart.c

Now 2MHz can be used for all UARTs.
For UART_1(UART2) UART2(UART3) two additional baudrates
are added 3MHz and 6MHz.
For those to work PLL96 must be selected as system clock source (syscfg MCU_SYSCLK_SOURCE: 1).
Code updates both hal_uart and uart_da1469x

hw/mcu/dialog: Increase UART maximum baudrate

---

hw/mcu/dialog/da1469x/src/hal_gpio.c

While hardware can be setup to detect only rising or falling
edge it is possible to add HAL_GPIO_TRIG_BOTH support
handled by software.
This re-arms edge of interrupt in GPIO ISR to detect next change.

hw/mcu/da1469x: Add support for both edges GPIO interrupt trigger

---

hw/bsp/apollo3_evb/syscfg.yml

mynewt-core changes to accomodate the recent ble hci rework.
nimBLE Apollo3 PR can be found here
https://github.com/apache/mynewt-nimble/pull/1199

Apollo3 BLE Definition updates for HCI Rework

---

hw/drivers/rtc/ds1307/include/ds1307/ds1307.h
hw/drivers/rtc/ds1307/pkg.yml
hw/drivers/rtc/ds1307/src/ds1307.c
hw/drivers/rtc/ds1307/src/ds1307_shell.c
hw/drivers/rtc/ds1307/syscfg.yml
hw/drivers/rtc/ds3231/include/ds3231/ds3231.h
hw/drivers/rtc/ds3231/pkg.yml
hw/drivers/rtc/ds3231/src/ds3231.c
hw/drivers/rtc/ds3231/src/ds3231_shell.c
hw/drivers/rtc/ds3231/syscfg.yml

Not relay sure if may be usefully to other but I share this.
Two RTC module with same functiones that can keep wall clock

Two I2C RTC modules

---

sys/log/full/src/log_shell.c

This commit adds the ability to clear a log, a group of logs or
all logs using the 'log' shell command. The option -c was added
for this purpose. The syntax is similar to the log dump syntax.
Examples:
1) Clear all logs
log -c
2) Clear a specific log
log -c <logname>
3) Clear a group of logs
log -c <partialname*>
NOTE: you cannot use the -c option with an index

sys/log: Add clearing log to log command

---

sys/shell/src/shell_os.c

Command prints reset cause when called.

sys/shell: Add "/compat reset_cause" command

---

apps/iptest/src/main.c

net_test_socket could be created twice leading to memory leak now whenever 'socket' command is executed it closes previous socket first.
bind/listen/connect check if socket is created first and print message if it is not.

apps/iptest: Make app more user friendly

---

sys/console/full/tcp_console/src/tcp_console.c

tcp_console_flush was being called from main task
via tx_flush_event and from tcpip task that called tcp_console_writable.
It this happened at the same time tcp_console_out_buf could be double freed.
Now flushing happens only from tcpip task and tcp_console_out_buf is handed over to tcpip thread in critical section to prevent race.

tcp_console: Fix race condition

---

hw/mcu/microchip/pic32mz/include/mcu/pic32.h
hw/mcu/microchip/pic32mz/src/system_pic32.c

Add D-cache flushing functions if L1 CACHE is present.

mcu/pic32mz: Add d-cache flushing functions

---

compiler/riscv-none-embed/compiler.yml
compiler/riscv64/compiler.yml

Arm-based compilers have speed profile now also riscv will have it.

compiler/riscv: Add speed profile

---

.github/test_build_blinky.sh
.github/workflows/build_blinky.yml
.github/workflows/build_targets.yml

Use matrix to execute builds on all suppored OSes.

ci: Run tests on Windows and Mac

---

.github/workflows/build_blinky.yml
.github/workflows/build_targets.yml

We want all jobs to be completed even if some failed.

ci: Don't use fail-fast strategy

---

.github/workflows/build_blinky.yml
.github/workflows/build_targets.yml
.github/workflows/newt_test_all.yml

Makes test names a bit more userfriendly.

ci: Improve reported test names

---

README.md

Switch from Travis to GH Actions badges.

README: Update CI status badges

---

hw/bus/drivers/spi_apollo3/src/spi_apollo3.c

Bus driver now supports duplex mode.
This adds required function for duplex write/read.

bus/spi_apollo3: Add duplex for SPI

---

hw/scripts/download.sh

Space was missing in several if conditions between " and ]

hw/scripts: Fix downloader script syntax

---

hw/mcu/nordic/nrf52xxx/src/system_nrf52.c

Disabling approtect by writing 0x5A to UICR is valid for newer chips only.
Writing 0x5A to approtect for older revisions results in enabling protection.
This applies auto debugger enable feature for revisions that support this.

mcu/nrf52: Limit auto enable debugger to new chips

---

hw/bus/drivers/spi_stm32/src/spi_stm32.c
hw/bus/src/bus.c

Now bus driver functionality can be used with mcuboot.
When OS_SCHEDULING is NOT set node locking always
succeeds

hw/bus: Support for non scheduling build

---

apps/lvgl/demo/src/main.c

Benchmark was running only onc scene in a loop.
Now whole benchmark is executed.

lvgl/demo: Run all tests in benchmark

---

hw/mcu/dialog/da1469x/src/da1469x_dma.c

Added critical section inside of da1469x_dma_acquire_periph()

hw/mcu/dialog: added critical section to dma acquire peripheral

---

encoding/base64/src/base64.c
hw/mcu/native/src/hal_timer.c
hw/mcu/nordic/nrf51xxx/src/hal_timer.c
hw/mcu/nordic/nrf52xxx/src/hal_timer.c
hw/mcu/nordic/nrf5340/src/hal_timer.c
hw/mcu/nordic/nrf5340_net/src/hal_timer.c
hw/mcu/nordic/nrf91xx/src/hal_timer.c
hw/mcu/nxp/kinetis/src/hal_timer.c
hw/mcu/stm/stm32_common/src/hal_timer.c

TBH I'm not sure on how to fix base64 warning so it is only silenced...

ARM GCC 13 compilation fixes

---

hw/mcu/dialog/da1469x/scripts/dialog_da1469x-download_jlink.sh

Need to break on mynewt_main instead of main.

hw/mcu/dialog: Fix download script

---

hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c

It was possible to have custom value for MCK setup and ratio, but if it was set ACLK was no started.
Now custom ration and mck setup can be set and ACLK still be started if requested

hw/drivers/i2s: Allow custom mck config

---

.github/test_build_apps.sh
.github/workflows/build_all_apps.yml
apps/bsncent/syscfg.yml

Make sure samples are building with degfault BSP
(currently nordic_pca10056).

ci: Build application samples

---

util/stream/include/stream/stream.h
util/stream/pkg.yml
util/stream/src/stream.c

This API provides interface to streams it should replace util/streamer.

util/stream: Add streaming API

---

.style_ignored_dirs

LittleFS is not in core repository any more

Remove LittleFS sources from ignored style check

---

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
hw/drivers/flash/spiflash/src/spiflash.c
hw/drivers/flash/spiflash/syscfg.yml

This adds simple stats that can be use to evaluate spiflash usage.

spiflash: Add stats

---

kernel/os/include/os/os_sem.h

Adds missing documentation for functions and structures. 

kernel/os_sem: Update doxygen comments in the header file

---

kernel/os/include/os/os_eventq.h

Adds missing documentation for functions and structures. 
Adds missing functions parameters names.

kernel/os_eventq: Update doxygen comments in the header file

---

kernel/os/include/os/os_sched.h
kernel/os/src/os_sched.c

Adds missing documentation for functions and removes it from the source file.
Adds missing parameter names to functions prototypes.

kernel/os_sched: Update doxygen comments in the header file

---

test/flash_test/src/flash_test.c

So far flash read displayed data in hexadecimal format only. Now additional ascii values are shown for printable characters, which is common practice
Old format:
```
compat> flash 0 read 0x1d110100 0x20
Read 0x1d110100 + 32
0x1d110100: 0x09 0x0f 0x00 0x6c 0x6f 0x67 0x2d 0x73
0x1d110108: 0x74 0x6f 0x72 0x61 0x67 0x65 0x20 0xff
```
New format:
```
compat> flash 0 read 0x1d110100 0x20
Read 0x1d110100 + 32
0x1d110100: 0x09 0x0f 0x00 0x6c 0x6f 0x67 0x2d 0x73  ...log-s
0x1d110108: 0x74 0x6f 0x72 0x61 0x67 0x65 0x20 0xff  torage .
```

flash_test: Show printable characters along when read

---

kernel/os/include/os/os_time.h

Amends/adds the documentation for macros, functions and structures. 

kernel/os_time: Update doxygen comments in the header file

---

.github/check_doxygen.py
.github/workflows/check_compliance.yml
.rat-excludes
Doxyfile

This pull request adds a new check to the CI pipeline to ensure documentation integrity.
The script verifies if the Doxygen output contains any warnings.

ci: Add `Doxygen Check` job to the compliance workflow

---

hw/bsp/nordic_pca10059/readme.md

Readme is updated with syscfg.yml that shows configuration of blehci.

hw/bsp: pca10059 update readme.md

---

uncrustify.cfg

Changes Uncrustify configuration to align with the guidelines outlined in `CODING_STANDARDS.md`

uncrustify: Update configuration

---

libc/nano/pkg.yml

This enables printf floating point.

libc: Add newlib-nano printf float support

---

.github/project_build_all_apps.yml
.github/project_build_cc_target.yml
.github/project_newt_test_all.yml
.github/workflows/build_all_apps.yml
.github/workflows/build_cc_target.yml
.github/workflows/newt_test_all.yml

This should speed up CI a bit.

ci: Only download required repositories

---

hw/mcu/atmel/samd21xx/ext/pkg.yml

This is in preparation for Mynewt 1.13.0 release.

hw/mcu/samd21xx: Update repo version to 1.13.0

---

apps/bsncent/pkg.yml
apps/bsnprph/pkg.yml
apps/coremark/pkg.yml
apps/flash_loader/README.md
apps/lora_app_shell/pkg.yml
apps/pwm_test/pkg.yml
docs/os/modules/hal/hal_creation.rst
docs/os/modules/hal/hal_flash/hal_flash_int.rst
docs/os/modules/hal/hal_in_libraries.rst
hw/bsp/apollo2_evb/pkg.yml
hw/bsp/apollo3_evb/pkg.yml
hw/bsp/calliope_mini/pkg.yml
hw/drivers/adc/adc_apollo3/pkg.yml
hw/drivers/adc/adc_nrf51/pkg.yml
hw/drivers/adc/adc_nrf52/pkg.yml
hw/drivers/pwm/pkg.yml
hw/drivers/pwm/pwm_nrf52/pkg.yml
hw/drivers/pwm/pwm_stm32/pkg.yml
hw/drivers/pwm/soft_pwm/pkg.yml
hw/drivers/temp/pkg.yml
hw/drivers/temp/temp_nrf52/pkg.yml
hw/mcu/ambiq/apollo2/pkg.yml
hw/mcu/ambiq/apollo3/pkg.yml
hw/mcu/ambiq/pkg.yml

There were few incubator leftovers around the tree.

Remove incubator leftovers

---

.github/workflows/check_compliance.yml
uncrustify.cfg

Also park GHA image to specific ubuntu version (24.04).

ci: Update uncrustify configuration to 0.78

---

.github/workflows/check_compliance.yml
Doxyfile

It looks like newer version of Doxygen has issues if no output is generated. Specify to generate HTML output in tmp folder.

ci: Fix doxygen setup

---

sys/log/full/src/log_fcb.c

- Reboot was crash on rotate because the `l_arg` which points to the `fcb_log` was actually getting set to the `fcb`, thereby causing a crash. This fixes it.

sys/reboot_log: Fix crash on rotate

---

sys/log/full/src/log_console.c

This simplified module coloring scheme ensures that all modules receive a color, and that the colors remain the same after reboots. It also differentiates between system- vs. per-user modules.
Notes:
- I chose color inversion (ANSI `7;`) instead of explicit background color specification so that it can be agnostic to the typical white-on-black vs. black-on-white terminal text preference (granted that in each case, the normal colors have been configured in the terminal app to be well visible).
- From the module colors, I excluded black & white for the above reason, and red as the color used for serious modlog levels.

sys/log: Simplify module coloring scheme

---

hw/mcu/stm/stm32_common/src/hal_spi.c

hal_spi_init_hw function is needed by spi_hal driver

hal/spi: Add missing hal_spi_init_hw function

---

hw/bus/drivers/spi_hal/src/spi_hal.c

Other drivers already allow CS pin to be -1
if user does not need CS to be used automatically.

hw/bus/spi_hal: Make cs pin optional

---

.github/workflows/check_workflows.yml

This checks if PRs are using up-to-date workflows.

ci: Add workflows up-to-date check

---

.github/workflows/check_compliance.yml

If skip-style-check label is present print information about skipping the workflow.

ci: Add information about skipping style check

---

hw/scripts/openocd.sh

Added support for selecting a specific debug probe using USB serial number via environment variables.
Script creates new .cfg file where serial number is stored, and appends it to the CFG variable that include all .cfg files. Once done the file is deleted.
In case an error appears the .cfg file with S/N is not deleted and user can check whether wrong number didnt cause the error.
This is useful when multiple boards are connected and openocd cannot choose which one is target.
Supported variables:
- **STLINK_SN** for ST-Link
- **JLINK_SN** for J-Link
Example:
`STLINK_SN=0666FF495157808667171335 newt load nucleo-f767zi-blinky`

hw/scripts: Add adapter selection for opencod

---

.github/workflows/build_cc_target.yml

Validates if things build with GCC 14.

ci: Add GCC 14 to build matrix

---

hw/mcu/microchip/pic32mz/src/hal_spi.c

hal_spi structure had pins pointer that held
pin configuration. This assumed that pointer
was from constant memory and would not change
during code execution.
When bus driver spi_hal is used it passes this data from stack that will result in random pin configuration.
Now pins are stored inside hal_spi structure making it safe for hal and bus driver usage.

hw/mcu/pic32: Fix SPI for spi_hal
