hw/drivers/mmc/src/mmc.c
SD specification section "6.4.1 Power Up"
requires 74 clocks with high CS.
Code was sending 592 clocks (it was sending 74 bytes).
Now code sends 10 bytes (80 cycles).
=> mmc: Decrease mmc/sd initialization time

hw/drivers/flash/at45db/src/at45db.c, hw/drivers/flash/spiflash/src/spiflash.c, hw/drivers/led/tlc5971/src/tlc5971.c, hw/drivers/mmc/src/mmc.c, hw/mcu/dialog/da1469x/src/hal_spi.c, hw/mcu/nordic/nrf51xxx/src/hal_spi.c, hw/mcu/nordic/nrf52xxx/src/hal_spi.c, hw/mcu/nordic/nrf5340/src/hal_spi.c, hw/mcu/nordic/nrf5340_net/src/hal_spi.c, hw/mcu/nordic/nrf91xx/src/hal_spi.c
hal_spi_enable/disable errors were handled, but not everywhere. This
unifies handling manner.
=> hw: handle hal_spi_enable/disable errors

.rat-excludes, hw/mcu/nxp/kinetis/MK8xF/src/fsl_ftfx_controller.c, hw/mcu/nxp/kinetis/MK8xF/syscfg.yml, hw/mcu/nxp/kinetis/src/hal_flash.c, hw/mcu/nxp/kinetis/src/hal_os_tick.c, hw/mcu/nxp/pkg.yml
hw: mcu: kinetis: remove custom systick - Remove custom systick implementation and allow Kinetis MCUs to use the existing `SysTick_Handler` implementation already available for Cortex-M4 MCUs.
hw: mcu: kinetis: k8x: fix flash write alignment - Flash in Kinetis devices has either 4 or 8 byte write alignment, depending on the specific model. For K8x this is 4 bytes so fix the current syscfg.
hw: mcu: kinetis: uninterrupted flash programming - Disable interrupts while executing the flash commands; this avoids hardfaults due to interrupts executing code when FCCOBx registers are being written. This is only protecting `FTFx_CMD_Program` which is the function that is called from the Kinetis HAL's flash_write; other flash programming routines might also need similar protection. I've not seen any …
=> Fixes to Kinetis/K8x port

hw/bus/drivers/spi_da1469x/include/bus/drivers/spi_da1469x.h, hw/bus/drivers/spi_da1469x/pkg.yml, hw/bus/drivers/spi_da1469x/src/spi_da1469x.c, hw/bus/drivers/spi_da1469x/syscfg.yml, hw/mcu/dialog/da1469x/pkg.yml, hw/mcu/dialog/da1469x/src/da1469x_periph.c
This adds SPI bus driver that utilizes DMA
MCU da1469x_periph_create_spi() now creates new SPI bus(es) using new driver.
=> add da1469x SPI bus driver

hw/mcu/dialog/da1469x/include/mcu/da1469x_dma.h, hw/mcu/dialog/da1469x/src/da1469x_dma.c
For peripherals that are used with DMA it's quite common
to change memory address used, leave peripheral address
intact since same register is usually used for subsequent
transmissions, then set transmission size and start DMA.
This adds two convenience function for starting read and write
to peripherals when common configuration part is already done.
=> da1469x: Add peripheral DMA read and write

kernel/os/src/arch/cortex_m0/os_fault.c, kernel/os/src/arch/cortex_m3/os_fault.c, kernel/os/src/arch/cortex_m33/os_fault.c, kernel/os/src/arch/cortex_m4/os_fault.c, kernel/os/src/arch/cortex_m7/os_fault.c, kernel/os/src/arch/rv32imac/os_fault.c, libc/baselibc/src/sprintf.c, libc/baselibc/src/vsprintf.c
unistd.h is included in several files that seems not to need
it for anything.
=> Remove unistd.h from files that don't need it

sys/log/full/include/log/log.h, sys/log/full/pkg.yml, sys/log/full/src/log.c, sys/log/full/src/log_shell.c
- Added function to get last log index
- Dumping log from shell with partial log name match
```shell
log my*
```
- Limit number of logs shown using index
```shell
log 1000 mylog
```
- List streaming logs
```shell
log -l
218506 console (stream)
218506 mylog
```
=> sys log shell improvements

.travis.yml
Update the Travis environment to use Bionic (18.04) instead of Xenial (16.04) due to issues installing gcc-multilib.
=> travis: try running on Bionic

hw/mcu/nxp/kinetis/src/hal_qspi.c
This fixes an issue where an erase command with sizes larger or equal than a block erase (32K or 64K) could delete the whole block even when it was not aligned. A block erase command is accepted for any address inside the block, but if a flash area is not aligned to this block size, it will result in erasing data which are not part of the expected requested range. With this change the alignment must be valid when doing block erases.
=> hw: kinetis: Only allow aligned block erases

hw/hal/src/hal_flash.c
When a flash erase failed the error was ignored. This doesn't usually happen in the internal flash but can happen on external flash due to bus related issues, etc. Add a proper check and return an error that can be used for verification.
=> hw: hal: flash: Add proper check for erase

apps/fs_test/pkg.yml, apps/fs_test/src/littlefs.c, apps/fs_test/src/main.c, apps/fs_test/src/nffs.c, apps/fs_test/syscfg.yml
The fs_test app exercises all defined `fs/fs` interfaces, and is useful when adding new filesystems' support or debugging filesystem issues.
=> apps: fs_test: Add filesystem testing application

hw/bsp/dialog_cmac/syscfg.yml
If msys block size is less than 308, all PDUs with max length will be
fragmented into chain. This is not only inefficient in terms of block
usage but also costs some time when allocating and copying RX PDUs
and as a result we may be late on some transitions. This is especially
troublesome when scanning chains spaced at min offset (T_mafs) since
we are quite often too late to schedule next aux scan and thus it's
unlikely we can scan complete chain.
=> hw/bsp/dialog: Bump default msys block size for CMAC

hw/bsp/black_vet6/src/hal_bsp.c, hw/bsp/black_vet6/syscfg.yml
Some of the ETH pins were set up to port G.
There are not Port G pins on MCU on this board.
But there are pins from port B that can be used.
IRQ was hard coded to PA3 while ETH code allows
for this pin to be undefined, so now default
value is -1.
PHY address were hardcoded now they can be changed
in syscfg.
=> bsp/black_vet6: Fix ETH configuration

hw/mcu/nordic/nrf5340/syscfg.yml
- Pins should be checked for -1 for invalidity
=> mcu/nrf5340: Pins should be checked for -1 for invalidity

hw/mcu/nordic/nrf5340/src/hal_gpio.c
- hal gpio irq should use GPIOTE0 but GPIOTE1 was getting used
=> mcu/nrf5340: HAL gpio irq should use GPIOTE0

hw/bus/src/bus.c, hw/bus/syscfg.yml
Automatic mode for bus required calling function **bus_dev_set_pm()**.
Now it's possible to enable automatic mode using syscfg values.
When automatic mode is chosen, bus is not enabled till it is used.
Before even if **bus_dev_set_pm()** was called to set automatic mode,
bus that was enabled during initialization stayed enabled and would
be automatically disabled after first use.
=> Bus driver power management improvments 

docs/os/modules/extcmd/extcmd.rst
The `post_build_cmds` step was renamed to `post_link_cmds` with https://github.com/apache/mynewt-newt/commit/39005b80a6a034244061898c1b610dd7e4e34a36
Fix extcmd documentation appropriately.
=> doc: Fix post_link_cmds newt extcmd documentation

hw/bsp/nordic_pca10095/src/hal_bsp.c, hw/bsp/nordic_pca10095/syscfg.yml, hw/mcu/nordic/nrf5340/include/mcu/nrf5340_hal.h, hw/mcu/nordic/nrf5340/src/hal_qspi.c, hw/mcu/nordic/nrf5340/src/hal_system.c, hw/mcu/nordic/nrf5340/src/system_nrf5340.c, hw/mcu/nordic/nrf5340/syscfg.yml
This PR adds:
- hal for QSPI
- QSPI flasd device in pca10095 bsp
bsp.yml is not yet modified to have this flash used for any purpose.
It is possible to move slot 1 to this external flash.
Encryption is not implemented yet.
=> Add QSPI for NRF5340

hw/mcu/nordic/nrf5340_net/src/system_nrf5340_net.c
This is required for enabling debugging support.
=> mcu/nrf5340_net: Add support for APPROTECT setup

hw/mcu/dialog/da14699/include/mcu/mcu.h, hw/usb/tinyusb/da146xx/src/da1469x.c
=> hw/mcu/da14699: Use defines for USB pins

net/ip/lwip_mn/src/lwip_socket.c
Socket like api function lwip_recvfrom did not called
lwip_recved which is needed to update TCP window.
Without this change socket is able to receive only
TCP_WND bytes which is by default 4380.
Now tcp_recved() is called inside lwip_recvfrom() much
like in other implementations.
It would be slightly better to call it when mbuf is freed
but that is not possible easily right now.
=> net/ip: Update receive windows in lwip_recvfrom

hw/mcu/nordic/nrf5340_net/src/hal_flash.c
Function nrf5340_net_flash_sector_info was returning wrong
address for all sectors. It was not using hf_base_addr for
calculation and network core flash does not starts from 0
but from 0x1000000. It prevents mcuboot from correctly
identify slot size.
This just takes into account base address of netcore flash.
=> mcu/nrf5340: Fix flash sector info

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/mcu/nordic/nrf5340/syscfg.yml, hw/mcu/nordic/nrf5340_net/syscfg.yml
ipc driver was depending on `BSP_NRF5340` (which is specific to
nordic_pca100095) to determine which core was code built for.
Custom bsp would need to introduce same name to use IPC driver.
Now MCUs define own constants that could be used.
=> mcu/nrf5340: Add MCU_APP_CORE/MCU_NET_CORE syscfg values

hw/mcu/nordic/nrf5340/src/hal_flash.c, hw/mcu/nordic/nrf5340_net/src/hal_flash.c
Flash erase was settings wrong value to CONFIG register so
erase procedure never started on both cores.
Now nrf5340_[net_]flash_erase_sector() is not sharing code with
write any more.
Additionally nrf5340_[net_]flash_erase() was added to that can
speed up erase a little bit.
=> mcu/nrf5340: Fix flash erase

hw/mcu/nxp/kinetis/src/hal_gpio.c
This PR fixes `hal_gpio_init_out`, which is not setting the initial value to the configured pin. 
There has also been removed a `port_pin_config_t` instance, since the only port configuration needed in this case is the multiplexer.
=> kinetis/hal_gpio.c: Fix hal_gpio_init_out

hw/drivers/trng/trng_nrf52/src/trng_nrf52.c, hw/mcu/nordic/nrf5340_net/pkg.yml, hw/mcu/nordic/nrf5340_net/src/nrf5340_net_periph.c
- Add nrfx header to trng_nrf52.c
=> mcu/nrf5340: Add trng to netcore. Use existing trng_nrf52 driver

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/drivers/ipc_nrf5340/syscfg.yml
This allows to send data over IPC in fragments. Previously data size
was limited to IPC buffer size. In extreme case IPC buffer can now have
size of 2, although this may result in excessive number of interrupts.
=> hw/ipc_nrf5340: Allow sending data in fragments

hw/mcu/nordic/nrf52xxx/src/hal_system.c, hw/mcu/nordic/nrf52xxx/syscfg.yml, hw/mcu/nordic/nrf5340/pkg.yml, hw/mcu/nordic/nrf5340/src/hal_system.c, hw/mcu/nordic/nrf5340/src/nrf5340_periph.c, hw/mcu/nordic/nrf5340/syscfg.yml
- nrf5340: Add support for enabling instruction/data cache in hal_system_init() based on syscfg and add dependencies for BUS_DRIVER
- nrf52xxx: Enable instruction code cache in hal_system_init() based on syscfg
=> nrf5340/nrf52xxx: Add support for enabling instruction/data cache in hal_system_init() and add dependencies for BUS DRIVER

sys/flash_map/pkg.yml, sys/flash_map/src/flash_map.c, sys/flash_map/syscfg.yml
A flash map configuration may be stored in the manufacturing meta region, and be used instead of the one build time generated from bsp.yml. This is currently hard-coded in the flash map code. For users who don't use a mmr, this adds somewhere between 500 and 1000 bytes of code who serves no purpose. This PR adds a syscfg to allow enabling/disabling the use of the MMR in the flash map thus making the mfg dependency optional.
PS: I am adding `FLASH_MAP_SUPPORT_MFG` unset, which breaks backwards compatibility, but on the assumption that most users **don't use** an MMR.
=> flash_map: make mfg support optional

hw/mcu/stm/stm32_common/src/hal_uart.c
Function hal_uart_blocking_tx() had incorrect condition
checking if UART is open, this prevented non-blocking writes.
Condition:
if (!u || u->u_open)
was obviously wrong and is now changed to
if (!u || !u->u_open)
=> stm32/hal_uart: Fix blocking write

hw/mcu/dialog/cmac/include/mcu/cmac_timer.h, hw/mcu/dialog/cmac/src/cmac_timer.c, hw/mcu/dialog/cmac/src/hal_os_tick.c, hw/mcu/dialog/cmac/src/hal_timer.c
os_cputime runs at 32768Hz but it uses LLT internally which runs at
1MHz. This means both timers will wrap around at different time. This
means after one of timers wraps around (os_cputime wraps earlier),
calculations that use values converted between both timers will fail.
To fix this we "manually" extend LLT value to 64-bit internally so it
takes zillion of years before it wraps around. Also conversions from
os_cputime (a.k.a. HAL) value to LLT value take os_cputime value wrap
around into account and return proper 64-bit LLT value.
=> hw/mcu/cmac: Fix os_cputime and LLT wrap around handling

hw/bsp/nordic_pca10095_net/bsp.yml, hw/bsp/nordic_pca10095_net/src/hal_bsp.c, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/mcu/nordic/nrf5340/net_core_image/pkg.yml, hw/mcu/nordic/nrf5340/net_core_image/scripts/build_net_core.sh, hw/mcu/nordic/nrf5340/net_core_image/syscfg.yml, hw/mcu/nordic/nrf5340/nrf5340.ld, hw/mcu/nordic/nrf5340/pkg.yml, hw/mcu/nordic/nrf5340/syscfg.yml, hw/mcu/nordic/nrf5340_net/include/mcu/nrf5340_net_hal.h, hw/mcu/nordic/nrf5340_net/src/hal_vflash.c
This adds a way to have single image used to upgrade code on both cores.
Combine build advantages:
- easy upgrade deployment
- possible upgrade off application side only
- synchronization of code between net and app side
- **newtmgr** just works
- **mcuboot** works (but could be changed to embrace this approach batter)
- similar pattern of combine build is already present for Dialog network core (made possible by @andrzej-kaczmarek, scripting know-how part borrowed from his cmac)
For this to work **mcuboot** on **network** core have to be build with
```yml
BOOTUTIL_OVERWRITE_ONLY: 1
```
In the **application** core target
```yml
NRF5340_EMBED_NET_CORE: 1
```
=> nrf5340 combine app/net build

hw/mcu/nordic/nrf5340/src/system_nrf5340.c, hw/mcu/nordic/nrf5340/syscfg.yml
MCU starts with HFCLK divder set to 2, meaning APP core
runs at 64MHz.
Now divider can be set to 1 in syscfg allowing to run
MCU at 128MHz.
=> mcu/nrf5340: Allow changing HFCLK divider

hw/drivers/i2s/i2s_da1469x/include/i2s_da1469x/i2s_da1469x.h, hw/drivers/i2s/i2s_nrf52/include/i2s_nrf52/i2s_nrf52.h, hw/drivers/i2s/i2s_stm32f1/include/i2s_stm32f1/i2s_stm32f1.h, hw/drivers/i2s/i2s_stm32f4/include/i2s_stm32f4/i2s_stm32f4.h, hw/drivers/i2s/include/i2s/i2s.h, hw/drivers/i2s/include/i2s/i2s_driver.h
Most I2S related headers were missing extern "C" block
for correct c++ build.
=> i2s: Add extern "C" for c++ build

hw/mcu/stm/stm32f0xx/stm32f0xx.ld, hw/mcu/stm/stm32f1xx/stm32f103.ld, hw/mcu/stm/stm32f3xx/stm32f303.ld, hw/mcu/stm/stm32f4xx/stm32f401.ld, hw/mcu/stm/stm32f4xx/stm32f407.ld, hw/mcu/stm/stm32f4xx/stm32f411.ld, hw/mcu/stm/stm32f4xx/stm32f413.ld, hw/mcu/stm/stm32f4xx/stm32f427.ld, hw/mcu/stm/stm32f4xx/stm32f429.ld, hw/mcu/stm/stm32f4xx/stm32f439.ld, hw/mcu/stm/stm32f7xx/stm32f746.ld, hw/mcu/stm/stm32f7xx/stm32f767.ld, hw/mcu/stm/stm32l0xx/stm32l072.ld, hw/mcu/stm/stm32l0xx/stm32l073.ld, hw/mcu/stm/stm32l1xx/stm32l152.ld, hw/mcu/stm/stm32l4xx/stm32l476.ld, hw/mcu/stm/stm32wbxx/stm32wb55.ld
content of .init_array* sections is meant to be executed only
once during system start.
For no apparent reason those arrays were put in data section.
This results in wast of RAM when C++ code is built.
Sections are now moved to .text.
=> mcu/stm32: Move .init_array sections to flash

hw/bsp/nucleo-f303k8/src/arch/cortex_m4/startup_stm32f303x8.s, hw/bsp/stm32f429discovery/src/arch/cortex_m4/startup_STM32F429x.s, hw/mcu/sifive/fe310/src/arch/rv32imac/start.s, libc/baselibc/src/start.c, libc/baselibc/syscfg.yml
Code required to execute global object constructors was usually not called.
hifive1 and two other stm32 boards had calls to __libc_init_array while all
the others did not.
Now **__libc_init_array()** is executed for all cases in **_start()**
baselibc version of this function is provided so tool chain's one does not need to be.
=> baselibc cpp global constructors

kernel/os/include/os/os_trace_api.h
Initializing non-const char pointer with constant string literal
is an error in c++ according to g++ compiler.
`error: ISO C++ forbids converting a string constant to 'char*' [-Werror=write-strings]
`
This assignment even for c build is not useful since
_asprintf_ assigns new value (possible NULL) to **desc** anyway.
This change just drops meaningless initialization that makes g++ unhappy.
=> sysview: Fix build for c++

encoding/base64/src/hex.c, encoding/json/src/json_decode.c, hw/drivers/uart/uart_hal/src/uart_hal.c, net/ip/mn_socket/src/mn_socket_aconv.c, net/oic/src/api/oc_uuid.c, sys/console/full/history_log/src/history_log.c, sys/log/full/src/log_shell.c, time/datetime/src/datetime.c
Although ctype.h functions/macros like isalpha, isdigit etc.
take int argument as input behaviour is undefined if value
passed to those are not from unsigned char + EOF.
If the implementation choose to use simple macro that accesses
table indexed by argument and it was negative as it can be
when char is cast to int (as was the case in some places)
result would be unpredictable.
In most cases argument to ctype define functions was correctly
cast to unsigned (json/lwip and many other places).
This updates places that could be prone to this problem with
cast to (unsigned char).
For baselibc implementation it does not make difference but
if some other libc was chosen it could lead to potential
problems (warnings at build time or unpredictable behavior).
Problem was observed when gcc provided …
=> ctype: Fix undefined behavior in ctype.h usage

hw/drivers/i2s/include/i2s/i2s.h
_Alignas is c only keyword.
C++ has alignas keyword.
stdalign.h header should define alignas so it
could be used in both.
To be able to use i2s.h in c++, macro is provided when not present.
placement of alignas() is also moved before static which seems to
be a problem for g++.
=> i2s: Fix c/c++ _Alignas usage

compiler/riscv-none-embed/compiler.yml, compiler/riscv-none-embed/pkg.yml, compiler/riscv64/compiler.yml
- This adds alternative compiler definition for riscv
- riscv64 compiler definition was missing c++ tool specification
=> riscv toolchain changes

hw/mcu/nordic/nrf51xxx/nrf51.ld, hw/mcu/nordic/nrf52xxx/nrf52.ld, hw/mcu/nordic/nrf52xxx/nrf52_ram_resident.ld, hw/mcu/nordic/nrf5340/nrf5340.ld, hw/mcu/nordic/nrf5340/nrf5340_ram_resident.ld, hw/mcu/nordic/nrf5340_net/nrf5340_net.ld, hw/mcu/nordic/nrf5340_net/nrf5340_net_ram_resident.ld, hw/mcu/nordic/nrf91xx/nrf91.ld, hw/mcu/nordic/nrf91xx/nrf91_ram_resident.ld
content of .init_array* sections is meant to be executed only
once during system start.
For no apparent reason those arrays were put in data section.
This would results in wast of RAM for C++ code built if it was
not for the fact that KEEP keyword was missing so such sections
would not result in final build (RAM nor FLASH) because by
compiler design  content of those section is not referenced
explicitly and relays on linker using them without apparent
reference.
Sections are now moved to .text and used KEEP keyword to make
sure constructors will be executed.
=> mcu/nrf5x: Move .init_array sections to flash

fs/littlefs/pkg.yml, fs/littlefs/syscfg.yml
Add syscfg options that enable building the v1 metadata format migration to v2, and read-only support (for smaller build sizes).
=> fs: littlefs: add migrate/readonly build options

hw/mcu/nordic/nrf5340/syscfg.yml, hw/mcu/nordic/nrf5340_net/syscfg.yml
MCU_TARGET syscfg value is commonly used in NRF5x based targets.
NRF5340 already has MCU_APP_CORE and MCU_NET_CORE but for
applications that can be built for all kinds of MCUs, it
seems that common MCU_TARGET variable is cleaner solution to have.
=> mcu/nrf5340: Add MCU_TARGET

kernel/os/include/os/os.h
Symbols min and max are standard template functions.
When os.h is included from C++ code macros provided
by this header break build.
mynewt is written in C hence removing min/max definitions
just from C++ build will not break any existing code.
=> kernel/os: Remove min/max macros for C++

hw/drivers/i2s/i2s_nrfx/include/i2s_nrfx/i2s_nrfx.h, hw/drivers/i2s/i2s_nrfx/pkg.yml, hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c, hw/mcu/nordic/nrf5340/include/nrfx_config.h
This is based on NRF52 but incorporates changes needed
to handle NRF5340 MCU.
Name of driver implies that it used Nordic provided NRFX code.
This driver can be used in NRF52 MCUs as well.
**Driver is still missing support for ACLK**
=> hw/drivers/i2s: Add I2S driver for NRF5x families

hw/battery/src/battery_adc.c, hw/drivers/adc/gpadc_da1469x/src/gpadc_da1469x.c, hw/drivers/adc/sdadc_da1469x/src/sdadc_da1469x.c
This patch fixes an unchecked return value when invoking the adc_chan_config
call.  This issue was found as part of a static analysis tool.  Fixed all
instances using this API that were not checking return value.
=> hw: battery: Check return code from adc_chan_config

hw/mcu/stm/stm32_common/src/hal_spi.c
Functions hal_spi_enable() and hal_spi_disable() did not do
anything useful.
Now like many other implementations (NRF, DA1469x) those functions
actually enable and disable SPI.
Without this change SPI peripheral could be enabled by
ST HAL functions like HAL_SPI_Transmit_Receive() but
if that was the case chip select would be asserted before
SPI peripheral was enabled.
In some cases it could lead to clock PIN going to inactive state
after chip select was active.
With this change SPI pins are in correct state before CS is activated during transmission.
=> stm32/hal_spi: Enable SPI in hal_spi_enable

hw/sensor/creator/src/sensor_creator.c, hw/sensor/creator/syscfg.yml
LIS2DW12 has support for bus driver.
Now it can be used with sensor_creator.
=> sensor_creator: Add LIS2DW12 configuration for bus drivers

hw/drivers/i2s/i2s_stm32f4/include/i2s_stm32f4/i2s_stm32f4.h, hw/drivers/i2s/i2s_stm32f4/src/i2s_stm32f4.c
Add possibility to redirect MSCK to pin so it can be
used by slave device.
=> hw/drivers/i2s: Add routing of MSCK pin for STMF4

hw/mcu/dialog/da1469x/da1469x.ld, hw/mcu/dialog/da1469x/da1469x_ram_resident.ld
content of .init_array* sections is meant to be executed only
once during system start.
For no apparent reason those arrays were put in data section.
This would results in wast of RAM for C++ code built if it was
not for the fact that KEEP keyword was missing so such sections
would not result in final build (RAM nor FLASH) because by
compiler design  content of those section is not referenced
explicitly and relays on linker using them without apparent
reference.
Sections are now moved to .text and used KEEP keyword to make
sure constructors will be executed.
=> mcu/da1469x: Move .init_array sections to flash

hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c, hw/mcu/dialog/da1469x/src/hal_i2c.c
For register I2C_CON_REG datasheet description of
bit I2C_MASTER_MODE:
This bit controls whether the controller master is enabled.
0= master disabled
1= master enabled
Software should ensure that if this bit is written with
'1' then bit 6 (SLAVE_DISABLE) should also be written with a '1'.
It's not clear what will happened otherwise, so far it seemed to
work without this but to be on the safe side.
=> da1469x/i2c: Correct CON_REG settings

hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c, hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c, hw/bus/drivers/i2c_nrf91_twim/src/i2c_nrf91_twim.c, hw/bus/drivers/spi_da1469x/src/spi_da1469x.c, hw/bus/drivers/spi_stm32/src/spi_stm32.c, hw/bus/src/bus.c
In several places return value of **stats_init_and_reg**() is ignored.
When stub implementation is used this evaluates to just 0 then
there are statements like:
0;
which are reported in following way
Error: In file included from repos/apache-mynewt-core/hw/bus/include/bus/bus_driver.h:26,
from repos/apache-mynewt-core/hw/bus/src/bus.c:25:
repos/apache-mynewt-core/hw/bus/src/bus.c: In function 'bus_dev_init_func':
repos/apache-mynewt-core/sys/stats/stub/include/stats/stats.h:75:33: error: statement with no effect [-Werror=unused-value]
75 | #define stats_init_and_reg(...) 0
|                                 ^
repos/apache-mynewt-core/hw/bus/src/bus.c:250:5: note: in expansion of macro 'stats_init_and_reg'
250 |     stats_init_and_reg(STATS_HDR(bdev->stats),
Now return value from …
=> sys/stats: Fix build warnings when stats are stubbed

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger_shell.c, hw/drivers/chg_ctrl/da1469x_charger/syscfg.yml
Battery temperature values from CHARGER_TEMPSET_PARAM_REG
could be incorrectly decoded in shell command `charger dump decode`
when NTC value was different then datasheet recommended 15k ohm.
Now real pull-up resistor value is taken into account when values
are displayed.
Value of the resistor can be set in syscfg file.
=> drivers/da1469x_charger: Enable custom value for NTC

net/osdp/include/osdp/osdp.h, net/osdp/include/osdp/osdp_common.h, net/osdp/src/osdp_common.c, net/osdp/src/osdp_pd.c, net/osdp/syscfg.yml
- Raise a timeout flag if the peripheral device does not hear from the control panel for said time interval
=> net/osdp: add a polling timeout for non-secure session

kernel/os/src/arch/pic32/asm/ctx.S
At some point task_t was modified and keeps stack
bottom instead of stack top.
t_stacktop -> t_stackbottom
For PIC32 FPU context is stored at the very top of stack
(CPU context is stored at current SP).
Context switch code was not updated and still was
using same storage from task_t that was changed.
Lack of update resulted in writes to random places.
This change computes stack top to restore functionality.
=> pic32: Fix context switch

apps/coremark/pkg.yml
Application package referenced "@mcuboot/boot/bootutil"
which was not used.
=> apps/coremark: Remove bootutil dependency

hw/sensor/creator/src/sensor_creator.c, hw/sensor/creator/syscfg.yml
LIS2DW12 could be used with SPI and I2C when bus driver was used.
SPI configuration was missing for non-bus driver usage.
This also restores default I2C interface number 0 for LIS2DW12.
=> sensor_creator: Add non-bus driver SPI config for LIS2DW12

kernel/os/include/os/os_trace_api.h
This PR voids case the unused parameters in `os_trace_api`.
=> kernel/os/include/os/os_trace_api: avoid unused parameter warning

hw/sensor/creator/src/sensor_creator.c
This fixes obvious copy/paster error in chip select
pin syscfg name.
=> sensor_creator: Fix typo in LIS2DW12 spi configuration

sys/log/stub/include/log/log.h
Similar to #2604 this PR voids casts unused parameters, useful when only including `os/*` and not wanting to disable the warning for all compilation units (I'm using Werror in my build).
=> sys/log/stub: avoid unused parameter warning

hw/mcu/nxp/kinetis/include/hal_lpuart_nxp.h, hw/mcu/nxp/kinetis/src/hal_lpuart.c
Refactor LPUart driver to only allocated RAM proportional to the number of enabled Uarts; each UART uses about 230 bytes for its state, so having a single UART enabled should provide a significant reduction in RAM usage.
The driver's flash usage was also reduced, by about 20% when a single UART is being used.
=> nxp: kinetis: decrease LPUART RAM usage

kernel/os/src/arch/pic32/startup/crt0.S
xc32 compiler version 3.xx starts to complain
about constant value range
Error: repos/apache-mynewt-core/kernel/os/src/arch/pic32/startup/crt0.S: Assembler messages:
repos/apache-mynewt-core/kernel/os/src/arch/pic32/startup/crt0.S:314: Error: operand 3 out of range `addiu $10,$0,0xFFFFFFFC'
previous compiler did not complain
This changes 32bit unsigned interpretation of -4 (0xFFFFFFFC)
to just -4, so 2.5 and 3.x versions are happy.
-4 can be found in SDK provided crt0.S files.
=> pic32: Fix crt0.S build error

crypto/mbedtls/include/mbedtls/config_mynewt.h, crypto/mbedtls/pkg.yml
This changes one instance of `#include ""` to `#include <>` to allow
build with xc32-gcc compiler. This is really a issue in the xc32 compiler not
**mbedtls** but it can be fixed by changing `""`  to `<>`.
Other change is to remove include `"os/mynewt.h"` and use `<syscfg/syscfg.h>`
this time is due to symbol found in PIC32MZ... headers that conflicts with some
local symbol used by **mbedtls**.
Including big part of **mynewt** core header files is not really needed to build **mbedtls**
when just having **MYNEWT_VAL** macro expansion is enough.
=> mbedtls xc32 build fixes

hw/mcu/nordic/nrf5340/pkg.yml, hw/mcu/nordic/nrf5340/syscfg.yml
- As per Errata 26, CTRL-AP: APPROTECT.DISABLE and
SECUREAPPROTECT.DISABLE registers are not functional
- So we need to conditionally disable its usage
- Adding a syscfg so we can rely on UICR config instead of CTRLAP
-  Remove MCU_NET_CORE restriction from APP CORE, does not matter anymore since MCUs are different
Note: Somehow this fix is not required on the netcore side. Hence, only making this fix on the app core side.
** BEFORE **
A `HardFault` would happen at `57             NRF_CTRLAP_S->APPROTECT.DISABLE = NRF_UICR_S->APPROTECT;` in `repos/apache-mynewt-core/hw/mcu/nordic/src/ext/nrfx/mdk/system_nrf5340_application.c` which would be seen in the bootloader.
** AFTER **
No `HardFault`
=> nrf5340: Conditional Rev A errata 26 fix

hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c, hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c, hw/bus/drivers/i2c_nrf91_twim/src/i2c_nrf91_twim.c
Current code return error code when read was called
with BUS_F_NOSTOP flag set.
It seems better to just assert at line where the user can
see why this not working instead of returning error code
where user will have to figure out why I2C lines are dead.
This kind of problem is not something that can be fixed
in runtime by just repeating read it will always fail
until the code is modified not to use such flag.
This change should alert the user that this kind of desired
behavior will not work on this platform.
=> bus/i2c_nrf5x: Assert on not supported usage

hw/mcu/nordic/nrf52xxx/src/nrf52_periph.c
`bus_spi_hal_dev_create` needs struct `bus_spi_hal_dev` when using bus driver.
=> hw/mcu/nordic: use correct struct type for spi2 and spi3 bus in nrf52 periph

test/flash_test/src/flash_test.c
flash_test output looked like this:
```
compat> flash_speed 0 0x8000000 range
Speed test, hal_flash_read(0, 0x8000000, X)
004310   1 299288
006436   2 280513
008562   4 298043
010688   8 278327
012814  16 245812
014940  24 220095
```
It was not so clear what this output means without
checking source code.
Now header is added to range version and kB/s is
also printed like this:
```
compat> flash_speed 0 0x8000000 range
041813 Speed test, hal_flash_read(0, 0x8000000, X)
041819  X  reads/s  kB/s
043823   1  303089   295
045949   2  283850   554
048075   4  301816  1178
050201   8  281617  2200
052327  16  248369  3880
054453  24  222145  5206
```
=> flash_test: Make test output more readable

hw/drivers/i2s/src/i2s.c
When device is not configured correctly i2s_start for
I2S output device may fail.
i2s_start() returning I2S_ERR_NO_BUFFER is rather expected
while other errors may indicate some serious configuration
problem.
With this change failing i2s_start will stop user code form
openning device since it will probably not work anyway.
=> i2s: Assure open fails in case of driver error

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
Calling ipc_nrf5340_recv on channel which is already enabled is always
an application error which leads to confusing behaviour (or crashes).
If application want to change receive handler for specified channel it
shall first unregister old one by passing NULL pointer.
=> hw/ipc_nrf5340: Assert on ipc_nrf5340_recv if channel is already in use

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/drivers/ipc_nrf5340/syscfg.yml
Due to the way MYNEWT_VAL is defined (always within ()) some preprocesor
magic is required when passing comma separated values.
Heavily Inspired by #2628 but using preprocessor magic to initialise the original vector instead.
Tested with 0, 1, and multiple pins redirected to networking core.
=> hw/ipc_nrf5340: Fix enabling multiple GPIOs passed to network core 

hw/mcu/nordic/nrf5340_net/src/hal_spi.c
This applies when using bus driver and SPIM0 for the networking core, and SPIM0 is initialised from hal_spi_init_hw. 
During ```hal_spi_init``` it called ```hal_spi_enable``` which returs an error because the txrx_cb isn't set.
This change makes hal_spi_init similar on networking core to application core where no extra disabling or enabling occurs. 
Without this change the bus device isn't properly initialised and causes a segfault as soon as you try to use the spi.
=> hw/mcu/nrf5340_net: Remove enable/disable from hal_spi_init

hw/hal/src/hal_flash.c, hw/hal/syscfg.yml
So far flash ids needed to start from 0 to some number.
It was not possible to have only some numbers.
If BSP specified flash areas that belonged to 3 devices.
Device ID would be 0,1,2.
If bootloader (or some application configuration) was not
to touch some of the devices hal_bsp_flash_dev() function
would just return NULL to end flash device enumeration.
If bsp.yml contained flash areas belonging to 3 flash devices,
application (bootloader) could have access to 0, or 0,1 or 0,1,2
devices. It could not access only 0 and 2.
This change introduces HAL_FLASH_MAX_DEVICE_COUNT that when specified
allows to not have driver present for some of the flash devices.
Default value (0) keeps old behavior.
=> hal/flash: Relax flash id number restriction

hw/bsp/nordic_pca10095/src/hal_bsp.c, hw/bsp/nordic_pca10095/syscfg.yml, hw/bsp/nordic_pca10095_net/src/hal_bsp.c, hw/bsp/nordic_pca10095_net/syscfg.yml
So far crash dumps had whole RAM image stored in flash.
If flash area assigned to coredumps were to small, end
of RAM was not dumped (including interrupt stack).
This adds possibility to skip dumping unused heap space.
This can reduce size of core dumps.
=> hw/bsp/nordic_pca10095: Add reduced size crash dumps

hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c
After read or write that ended with error (address nack)
interrupts are blocked and stop condition is generated
that will rise EVENTS_STOP later on.
Read or write finishes with this event active.
On next write or read interrupt were enabled before EVENTS_STOP
was cleared resulting in interrupt handling that would signal
semaphore.
In some cases that may lead to data corruption when code reuses buffer
while I2C transaction is ongoing.
This changes clears old events before enabling interrupts.
=> nrf5340/i2c: Fix STOP event handling

test/flash_test/src/flash_test.c
flash command now can display flash areas like this
```
compat> flash area
000852 AreaID FlashId     Offset     Size
000853      0       0 0x00000000 0x008000
000854      1       0 0x0000c000 0x076000
000855      2       0 0x00082000 0x076000
000856      3       0 0x000f8000 0x004000
000857     16       0 0x00008000 0x004000
000858     17       0 0x000fc000 0x004000
000859     18       2 0x01028000 0x011000
```
=> flash_test: Add flash area list

hw/bus/drivers/spi_hal/src/spi_hal.c, hw/bus/include/bus/bus_driver.h, hw/bus/src/bus.c
Change extends bus driver operations to allow faster transfer.
New driver function **write_read** allow for faster transaction implementation.
Existing function **bus_node_write_read_transact()** was using **write** that **read**.
It turns out that for short transfers (1 or 2 bytes written) several bytes read it is worth
to implement custom function that writes and read.
This code also adds first implementation of such function for spi_hal driver that can
benefit around 50% time reduction on single transfer.
=> Improve bus write read transactions

libc/baselibc/include/stdlib.h
repos/apache-mynewt-core/libc/baselibc/src/jrand48.c:8:29: error: argument 1 of type
‘short unsigned int[3]’ with mismatched bound [-Werror=array-parameter=]
8 | long jrand48(unsigned short xsubi[3])
|              ~~~~~~~~~~~~~~~^~~~~~~~
In file included from repos/apache-mynewt-core/libc/baselibc/src/jrand48.c:5:
repos/apache-mynewt-core/libc/baselibc/include/stdlib.h:66:23: note: previously declared
as ‘short unsigned int *’
66 | __extern long jrand48(unsigned short *);
|                       ^~~~~~~~~~~~~~~~
=> baselibc: Fix build with -Werror=array-parameter enabled

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/drivers/ipc_nrf5340/syscfg.yml
The outcome of #2629 used a bitmask to set which GPIOs the application core handed over to the networking core. 
This made for neat code but complicated the syscfg handling. 
This PR undoes #2629, the bitmask change, and uses preprocessor magic to accomplish the same with a simple comma separated syscfg value for specifying pins.  
Feedback welcome again, and this time I'll hang out for consensus before merging.
=> hw/ipc_nrf5340: (Re-)Fix enabling GPIO passing to network core

hw/mcu/nordic/nrf5340/net_core_image/scripts/build_net_core.sh
Presently, the netcore image bundled with the app core uses a default `timestamp` flag for `create-image` step. This PR uses two additional syscfgs `APPLICATION_VERSION` and `APPLICATION_SIGNING_KEYS` that can be set to pass user defined flags to this call. If these syscfgs are not provided, script will use the default `timestamp` flag without keys.
=> hw/mcu/nordic/nrf5340: User defined image create flags for combined image

sys/console/full/src/rtt_console.c
Move console_rx_restart within CONSOLE_INPUT guards to compile correctly with CONSOLE_INPUT turned off
=> sys/console/rtt_console: Fix CONSOLE_INPUT guards in RTT console

sys/console/minimal/src/console.c
Compile `console_out` for UART console only. RTT console has it's own implementation of `console_out` which conflicts if RTT_CONSOLE is used with console/minimal
=> sys/console/minimal: Fix RTT console compiler error for minimal console

sys/console/full/src/console.c
When echo is off history auto search should not output anything.
This allows to have **newtmgr** upload working while code
is build with history auto search support.
=> sys/console: Stop history auto search when echo is off

hw/bus/drivers/spi_hal/src/spi_hal.c
Function bus_spi_write_read() was calling hal_spi_txrx()
with NULL for txbuf for transactions involving more then 16 bytes.
NULL pointer is not valid for this function.
When code was build with SPI_HAL_USE_NOBLOCK enabled, zeroed receive buffer
was already used as argument for transmit buffer.
Same approach is now used when SPI_HAL_USE_NOBLOCK is not set.
=> hw/bus/spi_hal: Fix bus_spi_write_read

kernel/os/src/arch/pic32/os_arch_pic32.c
Bit **EXL** of **Status** register was not set in initial context.
When task was scheduled for the first time and some interrupt
fired during initial context switch task would stack in never
ending end of interrupt loop.
Here is sequence that was broken due to missing **EXL** bit set,
(at this point interrupts are disabled due to DI instruction
and additionally EXL bit when set).
```asm
lw     k0, CTX_EPC(sp)
mtc0   k0, _CP0_EPC      # here is correct value set to EPC register
lw     k0, CTX_STATUS(sp)
mtc0   k0, _CP0_STATUS   # at this point interrupt IE is 0 and EXL should be 1
```
In normal case when this happen interrupts are still disabled for **EXL** bit
but for initial context switch they are not, it there is pending interrupt
register **EPC** gets changed to address around this …
=> pic32: Fix context initialization

hw/bsp/ada_feather_nrf52/syscfg.yml, hw/bsp/bbc_microbit/syscfg.yml, hw/bsp/bmd200/syscfg.yml, hw/bsp/calliope_mini/syscfg.yml, hw/bsp/puckjs/syscfg.yml
Some BSPs still have deprecated BLL_LL_MASTER_SCA
and BLE_LL_OUR_SCA when they should have BLE_LL_SCA.
This replaces deprecated values with BLE_LL_SCA.
=> hw/bsp: Use BLE_LL_SCA where needed

kernel/os/src/os_sem.c
Context switch is performed in low priority interrupt.
If higher priority interrupt code releases semaphore
BEFORE g_current_task is updated in context switch,
os_sem_release() function can see that task
that entered os_sem_pend() and initiated context switch
is still running and there is no need to switch tasks.
As a result task is marked as ready.
Then high priority interrupt ends and context switch is
finished leaving lower priority task running.
When this happens and current task is idle it may take
a while till reschedule is done again leaving task that
should be running in ready state.
To prevent this, condition to reschedule is now changed
so that if current task is same as task that should be woken
context switch is also initiated just in case switching
already started and …
=> kernel/os: Fix semaphore release hazard

hw/usb/tinyusb/std_descriptors/src/std_descriptors.c
Check whether string descriptor would fit in static buffer
used for unicode string was wrong by one byte this would
lead to random data corruption.
Now check (that cuts descriptor is corrected).
Additional assert is also added since user should now
that syscfg provided string descriptor will not be
transmitted out.
When mynewt adopts usual way to remove assert in release
build check that cuts over-sized string can still work.
=> tinyusb: Fix memory corruption for USB descriptors

hw/usb/tinyusb/nrf53/include/tusb_hw.h, hw/usb/tinyusb/nrf53/pkg.yml, hw/usb/tinyusb/nrf53/src/nrf53.c
This provides code for hardware initialization.
Part of this initialization is present in tinyusb bsps which
are not used by mynewt since it has own bsps.
This part is distinct from NRF52 since some hardware registers
were changed.
=> tinyusb: Add hardware initialization for NRF5340

hw/mcu/dialog/da1469x/src/da1469x_clock.c
XTAL32M_DXTAL_SYSPLL_ENABLE bit have to be set to lock PLL.
Without this bit PLL may not lock or it may start with
some strange frequency (apparently).
=> hw/mcu/da1469x: Fix PLL enable procedure

hw/usb/tinyusb/pkg.yml
STM32F7 has very similar USB block to STM32F4 and STM32L4.
This enable synopsy package that initializes interrupts
that are needed when building USB project on STM32F7 boards.
=> tinyusb: Enable USB for STM32F7

repository.yml
MCUboot was moved to mcu-tools org, and now uses "main" instead of "master" branch.
=> Update MCUboot repo and branch

hw/drivers/trng/trng_kinetis/src/trng_kinetis.c, hw/drivers/trng/trng_kinetis/syscfg.yml
* trng: kinetis: Use statically allocated stack
Change TRNG poller task to use a statically allocated stack; allocating this way uses the same mechanism as other Mynewt standard tasks, and avoids the requirement of a heap.
* trng: kinetis: update TRNG to be interrupt driven
When TRNG HW (not RNGA) is present, it can be used in an interrupt driven manner, where interrupts are generated for data available or on errors. With this commit the poller task is updated so it only runs when woken by an interrupt instead of polling constantly to fill in the cache. This fixes issues with task starvation, since the poller task is very high priority and the TRNG is very slow in the standard configuration.
A new syscfg was added to allow faster generation of entropy by changing the value of …
=> Updates to the kinetis TRNG driver

hw/bsp/frdm-k82f/include/bsp/bsp.h
Use standard LED_n nomenclature from color name based.
=> hw: bsp: frdm-k82f: update LED definitions

apps/sensors_test/src/main.c
Application defined 2 tasks to blink 1 led.
It also provided default pin (15) for led if
BSP did not provide LED_BLINK_PIN definition.
Amount of RAM used for tasks and stacks prevents
this application to run on MCUs with 20KB of RAM.
This:
- replaces tasks with callout reducing RAM used.
- removes local hard coded definition of LED,
so pin 15 may be used for something else.
=> apps/sensors_test: Remove blinking tasks

hw/bsp/nucleo-l073rz/src/hal_bsp.c, hw/drivers/pwm/pwm_stm32/src/pwm_stm32.c
This updates STM32 PWM usability:
- fixes return value from` stm32_pwm_set_frequency()` (**pwm_test** application assert failure)
- fixes build for **STM32F0** with PWM driver
- adds **PWM** peripherals configuration to **nucleo-l073rz** board
=> stm32 PWM fixes

hw/drivers/pwm/pwm_stm32/src/pwm_stm32.c
Advanced timer PWMs require the MOE bit in the TIMX_BDTR register to be set to enable output.
Enabling the compare preload function (CCxP in the TIMx_CCER register) is not supported in code for non-advanced timers. It should be explicitly disabled for advanced timers.
=> pwm/stm32_pwm: Fix PWM using advanced timers

hw/mcu/stm/stm32l0xx/include/mcu/mcu.h
STM32L0 mcu.h had its own version of MCU_GPIO_PORTx macros.
All others ST MCUs use common definition from stm32_common/mcu.h
This common definition file als provides more macros that are
required for alternate pin function handling.
This change removes STM32L0 copy of pin macros and includes common
definitions that all others MCUs use.
=> stm32l0: Use common pin macros

apps/pwm_test/src/pwm_shell.c
STM32 PWM driver encodes alternate pin function
at higher bits of pin definition.
Definition of pins with alternate function > 0 are 16 bits long,
where bits 12:15 specify function.
pwm_shell assumed that 8 bits is enough for pin number, but it will
not work for most ST cases.
This changes local variable type to accommodate ST encoding of pins
with alternate function.
=> apps/pwm_test: Fix pin handling for STM32

apps/rust_blinky/cargo_build.sh
This PR makes `cargo_build.sh` map the mynewt `cortex_m33` architecture to the cargo target `thumbv8m.main-none-eabih(f)`.
=> rust_blinky: support building for cortex m33

hw/usb/tinyusb/std_descriptors/src/std_descriptors.c
std_descriptors.c is using assert() but it did not explicitly
include assert.h. It was included by console.h but not in
stubbed implementation.
repos/apache-mynewt-core/hw/usb/tinyusb/std_descriptors/src/std_descriptors.c:278:9: error: implicit declaration of function 'assert' [-Werror=implicit-function-declaration]
Now assert.h is explicitly included regardless of which version of console
is used.
=> tinyusb: Fix build with stub console

hw/mcu/dialog/da1469x/src/hal_gpio.c
When entering sleep state of GPIO was latched regardless
whether COM would go to sleep or not.
If COM is not going to sleep register content will not be
lost and there is not need to save/restore it during MCU sleep.
Now latching GPIO is done only when last reference to COM
power domain will be released and COM domain is going to sleep.
=> hw/mcu/dialog: Latch GPIO only if COM is going to sleep

hw/bsp/dialog_da1469x-dk-pro/da1469x_serial.py
This patch increases the maximum supported size of ram loaded binaries using the
serial loading protocol.
Images < 64k in size use the original load method.  Any binary exceeding 64k but less than 128k needs to use the extended load sequence.
=> da1469x: Increase size of loadable binaries in development mode

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c, hw/mcu/dialog/da1469x/include/mcu/da1469x_vbus.h, hw/mcu/dialog/da1469x/src/da1469x_periph.c, hw/mcu/dialog/da1469x/src/da1469x_vbus.c, hw/usb/tinyusb/da146xx/include/tusb_hw.h, hw/usb/tinyusb/da146xx/src/da1469x.c, hw/usb/tinyusb/da146xx/syscfg.yml
VBUS changes were handled locally by charger code.
USB code also needs to know about such events.
Now common VBUS code handles interrupt and inform
charger and/or USB module about such events
This requires: https://github.com/hathach/tinyusb/pull/1094 to be merged first for **auto** and **ignore** modes (selected by **DA1469X_USB_VBUS_HANDLING** syscfg).
Older TinyUSB can be used only with **custom** mode as there may be missing function in TinyUSB driver.
=> Update da1469x vbus

hw/mcu/dialog/da1469x/src/da1469x_sleep.c
When PLL is enabled but not selected as system clock (just for USB)
switching to XTAL32M was missing even though XTAL32M was running.
This error was introduced when PLL was added as system clock source.
This change restores switching to XTAL32M clock when PLL is enabled
but not selected as system clock when system wakes from sleep.
=> hw/mcu/dialog: Fix setting up clock source with PLL enabled

.travis.yml
This is required for updated install script to work properly.
=> travis.yml: Bump Go to 1.16

hw/mcu/dialog/cmac/include/mcu/cmac_timer.h, hw/mcu/dialog/cmac/src/hal_timer.c
This is regression after c9f72793d712365e6bdc0b5a3386f6e3caebee11.
LLT value stored for given HAL value needs to correspond precisely to
HAL value converted to LLT, otherwise conversion from HAL to LLL will
not be accurate and calculated times e.g. for scheduling may be off by
up to 1 tick.
=> hw/mcu/cmac: Fix hal_timer_read

hw/mcu/nordic/nrf5340_net/pkg.yml
`nrf5340_net_vflash_init` is currently using a struct (`ipc_shared`) defined in `ipc_nrf5340/ipc_nrf5340_priv.h`.
When building, there will be an error due to the fact that the `ipc_nrf5340` package is not a dependency so the header cannot be found.
=> mcu/nrf5340_net: Add ipc_nrf5340 dependency for nrf5340_net_vflash_init

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
When application did not have embedded image net core startup
time was pretty small and ipc driver did not wait for other
core to finish.
It worked correct as long as there was no application side
IPC communication initiated before IPC on the net core finished
its initialization.
If some IPC communication was started before IPC was initialized
interrupt that should be visible on net core side was cleared.
That could happen if application was configured to be client of
network core flash. In that case IPC communication was very
fast resulting in reboot loop due to watchdog.
With this change application side always waits till network core
finishes IPC configuration.
=> hw/ipc_nrf5340: Always wait for net core to start

apps/splitty/pkg.yml, mgmt/smp/pkg.yml, mgmt/smp/smp_os/pkg.yml, sys/reboot/syscfg.yml
sys/reboot defined value LOG_SOFT_RESET that it never used.
mgmt/smp and mgmt/smp/smp_os used this value to include sys/reboot
which did not do anything due to catch 22.
This change removes LOG_SOFT_RESET from mynewt-core it will be added
to package in mcumgr that uses it.
this should be merged prior to https://github.com/apache/mynewt-mcumgr/pull/156 to avoid double definition
=> sys/reboot: Move LOG_SOFT_RESET to mcumgr

hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c, hw/mcu/nordic/nrf5340/src/hal_spi.c, hw/mcu/nordic/nrf5340_net/src/hal_spi.c
Add checks to confirm that the buffer points to a location in RAM given that easyDMA can only access RAM locations
=> mcu/nrf5340: Add RAM location check to calls using easyDMA

hw/bsp/black_vet6/include/bsp/bsp.h
This adds commonly used LED_1, LED_2, BUTTON_1, BUTTON_2
=> bsp/black_vet6: Update bsp pin definitions

libc/baselibc/src/memcmp.c
Optimized version was used for M3/M4/M7, now it also applies to M33.
=> libc: Use optimized memcmp() for Cortex-M33

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340_priv.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
So far reset of net core that was not initiated by
app core was silently ignored.
It could lead to synchronization loose of IPC or
higher layers.
Now net core restart notification can be propagated
to app core and that information can be used or
simply logged.
=> hw/ipc_nrf5340: Add network core crash notification

hw/bsp/nordic_pca10095_net/boot-nrf5340_net.ld, hw/bsp/nordic_pca10095_net/nrf5340_net.ld, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c, hw/drivers/ipc_nrf5340/syscfg.yml, hw/mcu/nordic/nrf5340/nrf5340.ld, hw/mcu/nordic/nrf5340_net/nrf5340_net.ld, hw/mcu/nordic/nrf5340_net/src/hal_vflash.c
IPC and virtual flash configuration was changed to be TrustZone non-secure friendly.
Those modification broke compatibility with existing net core bootloader.
This restores compatibility with old bootloader.
To enable old bootloader compatibility app core application have to be compiled with
`IPC_NRF5340_PRE_TRUSTZONE_NETCORE_BOOT: 1`
=> Fix nrf534 ipc with old boot

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
Assign the device pointer before un-configuring ADC instance. This prevents `global_adc_dev` from being NULL inside `channel_unconf()` via `init_instance_unconf()`
=> hw/drivers/adc_nrf52: Prevent NULL pointer access

test/crash_test/pkg.yml
There were two sections pkg.deps.CRASH_TEST_MGMT:
in such case only second section is used by newt tool.
cborattr/cborattr.h was included but cborattr package was
not specified.
=> mgmt: Fix package dependency

hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/src/tinyusb.c
Function tinyusb_start creates task.
For running TinyUSB stack in bootloader task creation is
not needed.
Now tinyusb stack can be run without scheduling in DFU mode.
=> tinyusb: Allow tinyusb task without scheduling

hw/usb/tinyusb/dfu/src/dfu.c, hw/usb/tinyusb/dfu/syscfg.yml
When mcuboot have BOOT_PREBOOT set it executes boot_preboot() function.
dfu package provides this function boot_preboot() that checks selected GPIO
to see if DFU mode should be activated.
=> tinyusb/dfu: Add boot_preboot for DFU in bootloader

hw/usb/tinyusb/da146xx/include/tusb_hw.h
With introduction of hcibridge configuration it is possible
to have BLE HCI controller over USB on DA1469x.
This adds default endpoint values needed by BTH driver.
=> tinyusb: Add BT HCI config values for DA1469x

hw/mcu/dialog/cmac/pkg.yml, hw/mcu/dialog/cmac/src/arch/cortex_m0_cmac/os_arch_arm.c
Having include ../../../../../../apache-mynewt-core... in
os_arch_arm.c breaks build on Windows.
Adding include path to package seems to fix the problem.
```sh
Executing scripts/create_cmac_bin.sh
Target successfully built: targets/dialog_cmac
Executing scripts/build_libcmac.sh
Building target @apache-mynewt-nimble/targets/dialog_cmac
Error: CreateFile h\:\work\mynewt\repos\apache-mynewt-core\kernel\os\src\os_priv.h: The filename, directory name, or volume label syntax is incorrect.
```
=> hw/mcu: Fix cmac build on Windows

hw/usb/tinyusb/std_descriptors/src/std_descriptors.c
TinyUSB project changed HID_PROTOCOL_NONE to HID_ITF_PROTOCOL_NONE.
This updated standard descriptors handling code to
use new definition.
=> tinyusb: Update HID descriptor

kernel/os/include/os/arch/pic32/os/cp0defs.h
Some of CPU0 register definition had incorrect selector in cp0defs.h
This file was taken from xc32 compiler but xc32 v2.5 and v3.01 also
have those number mismatched.
Correct values are taken from Microchip document:
"PIC32 Family Reference Manual" DS60001192B.
=> pic32: Fix CPU0 register definitions

hw/scripts/stlink.sh
stlink: Allow STM32_Programmer_CLI for flashing
ST provides command line tool for flashing devices as a part of STM32CubeIDE.
In some cases this tool works better than currently used st-flash tool.
st-flash sometimes has problem detecting flash memory:
```
Error: Downloading bin/targets/nucleo-f411re-blinky/app/apps/blinky/blinky.img to 0x8020000
st-flash 1.7.0-11-ge662da0
2021-12-16T14:25:02 INFO common.c: stm32f411re: 128 KiB SRAM, 0 KiB flash in at least 16 KiB pages.
Unknown memory region
```
For same hardware setup ST provided tool has no problem (openocd also works fine but requires script selection).
When user sets environment variable `STLINK_USE_STM32_PROGRAMMER_CLI=1`,
**STM32_Programmer_CLI** will be used instead of st-flash tool.
=> stlink: Allow STM32_Programmer_CLI for flashing

hw/bsp/dialog_da1469x-dk-pro/include/bsp/bsp.h, hw/bsp/dialog_da1469x-dk-pro/syscfg.yml
DK-PRO has two connectors for in MIKROBUS standard.
Change adds symbolic definition for both connectors.
This PR also adds DK PRO revision selectors that can be used to
choose correct board revision so Arduino and MIKROBUS pin
constants are correct.
=> dialog_da1469x-dk-pro: MIKROBUS and ARDUINO pin constants

hw/mcu/stm/stm32_common/pkg.yml
When OS_TICKS_USE_RTC is 1 hal_os_tick.c includes datetime/datetime.h
but appropriate package was not added now it is added when required.
=> stm32: Add missing package when RTC is used for systick

hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/std_descriptors/syscfg.yml
mynewt has default implementation of DFU over USB.
This implementation exposes SLOT0 or SLOT1.
Existing syscfg value USBD_DFU==1 includes DFU interface descriptor
and enabled TinyUSB stack part of implementation.
User had to provide own DFU application code or use hw/tinyusb/dfu
package.
New USBD_DFU_STD does inclusion of the package so it can
be easly turned on and off in targets.
=> tinyusb: Add syscfg to include dfu standard package

kernel/os/src/arch/pic32/stubs/pic32_init_cache.S
There was no big issue in cache initialization code but there were
few things that were not correct:
- __pic32_scache_xxxx variables were just eating ram for no reason
- __pic32_icache_xxxx and __pic32_dcache were put in .sdata section that
is cleared just after those variables are initialized, (they were not
used for anything later so it did not matter much but for debugging
it was not so good)
- initialization code tried to use __pic32_init_cache_program_base_addr and
__pic32_init_cache_data_base_addr symbols in following way:
.set noreorder
4:      la a0,__pic32_init_cache_program_base_addr
bne a0,zero,0f
/* Use a default if the symbol is not defined */
li a0,0x9D000000 // <----!!! This is delay slot, instruction is executed anyway due to noreorder directive
but since cache …
=> pic32: Fix cache discrepancies

kernel/os/include/os/arch/pic32/os/os_arch.h
Code was checking STATUS register EXL bit to check if CPU is in ISR.
This is true when CPU starts handling interrupt, but normal code
generated by xc32-gcc turns off this bit in ISR code before
user code is executed.
void __attribute__((interrupt(IPL3AUTO), vector(_TIMER_2_VECTOR))) timer2_isr(void)
{
9d008198:	415de800 	rdpgpr	sp,sp
9d00819c:	401b7000 	mfc0	k1,c0_epc
9d0081a0:	401a6002 	mfc0	k0,c0_srsctl
9d0081a4:	27bdfed0 	addiu	sp,sp,-304
9d0081a8:	afbb012c 	sw	k1,300(sp)
9d0081ac:	401b6000 	mfc0	k1,c0_status  // k1 has STATUS with EXL bit set
9d0081b0:	afba0124 	sw	k0,292(sp)
9d0081b4:	afbb0128 	sw	k1,296(sp)
9d0081b8:	7c1b7844 	ins	k1,zero,0x1,0xf   // k1 has now only IE preserved (which is 1 since code is in ISR), EXL is cleared
9d0081bc:	377b0c00 	ori	k1,k1,0xc00       // k1 IPL is …
=> kernel/os: Fix os_arch_in_isr for pic32

hw/drivers/sensors/lis2dw12/src/lis2dw12_shell.c, hw/drivers/sensors/lis2dw12/syscfg.yml
Shell functionality was limited to non bus driver build due
to sensor_itf usage.
Now shell opens existing device (default "lis2dw12_0") that
is used for communication.
Shell interface configuration for accelerometer is now marked as defunc,
and new LIS2DW_SHELL_DEV_NAME is added to point out to existing
device.
=> sensors: LIS2DW12 allow shell usage with bus driver

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
This allows application core to reset Network core and re-sync IPC
state.
=> hw/ipc_nrf5340: Add support for reseting Network Core

hw/drivers/ipc_nrf5340/syscfg.yml
Increase default on Application core to 5 to cover "default" BLE
usecase: 2x for HCI, 2x for Virtual Flash and 1x for Keep Alive.
Increase default on Network core to 16 (max) since on that core only
"struct ipc_channel" is kept in RAM (rest is on Application core) and
true number of channels is read from AppCore IPC config in runtime.
=> hw/ipc_nrf5340: Adjust default number of enabled channels

hw/bsp/ublox_bmd_345/boot-nrf52840aa.ld, hw/bsp/ublox_bmd_345/bsp.yml, hw/bsp/ublox_bmd_345/debug.sh, hw/bsp/ublox_bmd_345/download.sh, hw/bsp/ublox_bmd_345/include/bsp/bsp.h, hw/bsp/ublox_bmd_345/nrf52840aa.ld, hw/bsp/ublox_bmd_345/pkg.yml, hw/bsp/ublox_bmd_345/split-ublox_bmd_345.ld, hw/bsp/ublox_bmd_345/src/arch/cortex_m4/gcc_startup_nrf52840.s, hw/bsp/ublox_bmd_345/src/arch/cortex_m4/gcc_startup_nrf52_split.s, hw/bsp/ublox_bmd_345/src/hal_bsp.c, hw/bsp/ublox_bmd_345/syscfg.yml, hw/bsp/ublox_bmd_345/ublox_bmd_345_no_boot.ld
Board is similar to PCA10056 in design.
Buttons, LEDs and pin headers are same.
Notable difference is DC/DC can't be used and
is disabled in BSP.
There is Skyworks RFX2411 Amplifier on board.
BSP enables bypass mode for this amplifier
till driver is added.
No other changes from PCA10056.
=> bsp: Add Ublox BMD-345

apps/blesplit/pkg.yml
Dependency to nimble/transport/ram changed to nimble/transport
This change is needed for https://github.com/apache/mynewt-nimble/pull/1101
travis uses this target
=> apps/blesplit: Remove transport ram dependency

hw/usb/tinyusb/pic32mz/include/tusb_hw.h, hw/usb/tinyusb/pic32mz/pkg.yml, hw/usb/tinyusb/pic32mz/src/pic32mz.c
This provides code for USB hardware initialization
including interrupt and ID pin force to device mode.
=> tinyusb: Add hardware initialization for PIC32MZ

hw/bsp/ublox_bmd_345/pkg.yml, hw/bsp/ublox_bmd_345/src/hal_bsp.c, hw/bsp/ublox_bmd_345/syscfg.yml
SKY66112 driver can be used to drive RFX2411 so lets use it instead of
hardcoded PA/LNA bypass code.
=> ublox-bmd-345: Enable PA/LNA by default

kernel/os/include/os/os_cputime.h, kernel/os/src/os.c
We'll need 31250 Hz/tps for upcoming changes to Dialog CMAC code.
=> kernel/os: Add support for 31250 Hz for os_cputime and os_tick

hw/mcu/dialog/da1469x/src/hal_system_start.c, hw/mcu/nordic/nrf51xxx/src/hal_system_start.c, hw/mcu/nordic/nrf52xxx/src/hal_system_start.c, hw/mcu/nordic/nrf5340/src/hal_system_start.c, hw/mcu/nordic/nrf5340_net/src/hal_system_start.c, hw/mcu/nordic/nrf91xx/src/hal_system_start.c
Two changes to the code: clear ICPR register (to clear any pending interrupts) and also leave global interrupts enabled when calling hal_system_start. The idea behind this change is that the cortex-M has global interrupts enabled on reset and that this should be the state when the system is restarted.
For now, I only modified the code in the hw/mcu/dialog directory to have a discussion regarding this change in case folks object. I am not sure why there is a both a hal_system_start and hal_system_restart function but given there were two I decided to change restart only. It appears that mcuboot for mynewt calls hal_system_start and it should probably call hal_system_restart or we should abandon hal_system_restart and have hal_system_start clear ICER and ICPR and leave primask with …
=> hal: Modify hal_system_restart

hw/usb/tinyusb/dfu/pkg.yml, hw/usb/tinyusb/dfu/src/dfu.c, hw/usb/tinyusb/dfu/syscfg.yml
To prevent bricking device image is confirm in software
after bootloader swap.
Decision when to confirm new software is left to the application.
This allows to add simple timer that will confirm new image
after it was executing for some time (60 s default).
Then user does not need to write own decision-making way if
simply running new image is enough.
Two syscfg values are added:
- USBD_DFU_AUTO_CONFIRM
- USBD_DFU_AUTO_CONFIRM_TIME
=> dfu: Add auto confirm with timeout

hw/bsp/ublox_bmd_345/syscfg.yml
This is required to comply with FCC and CE-RED.
=> ublox-bmd-345: Limit max TX power when PA/LNA is enabled

hw/mcu/dialog/da1469x/syscfg.yml
MCU_GPIO_RETAINABLE_NUM default value 4 is optimized to reduce
RAM usage.
Unfortunately it leads very difficult problems.
If BSP tries to configure more GPIO then system asserts at run time.
It is even harder if this happens in flash_loader.
This changes MCU_GPIO_RETAINABLE_NUM to 32 by default
=> mcu/da1469x: Increase retained GPIO number

hw/bus/drivers/i2c_common/include/bus/drivers/i2c_common.h, hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c, hw/bus/drivers/i2c_hal/src/i2c_hal.c, hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c, hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c, test/i2c_scan/src/i2c_scan.c
This introduces additional i2c bus driver function to probe bus for
specific address.
nrf5x, da1469x and hal drivers were updated to allow this functionality.
i2c_scan package can now be used with bus driver.
=> i2c scan for bus driver usage

hw/usb/tinyusb/std_descriptors/include/tusb_config.h, hw/usb/tinyusb/std_descriptors/syscfg.yml
TinyUSB provides logs that can be enabled in tusb_config.h
This provides syscfg value that can enable those logs when needed.
When logs are enabled due to printf usage USBD_STASK_SIZE need to be increased,
and maybe some other tasks stacks that call TinyUSB functions.
It is also recommended having UART baudrate set to 1000000 or higher.
Recommended additional settings for logs:
CONSOLE_UART: 1
CONSOLE_UART_BAUD: 1000000
CONSOLE_UART_TX_BUF_SIZE: 512
=> tinyusb: Add TinyUSB loging

hw/mcu/dialog/da1469x/src/hal_uart.c
If TX FIFO is not empty (and maybe other conditions) during programming
new baudare UART can endup in BUSY state that will never end.
This adds reset of UART prior to configuring it in similar way as is
already done in uart_da1469x.c
=> hw/mcu/dialog: Reset UART before reconfiguration

hw/mcu/dialog/da1469x/src/da1469x_otp.c, hw/mcu/dialog/da1469x/src/hal_system.c
Different timing settings shall be used in OTP configuration if system
clock is set to 96MHz to ensure proper operation.
=> hw/mcu/dialog: Fix OTP settings when using 96MHz clock

apps/coremark/syscfg.yml
When **HARDFLOAT** is 1 (usually done in compiler.yml) coremark application
uses floating point for calculations and prints.
**baselibc** version of `printf` does not support `%f` if **FLOAT_USER** is not enabled.
It results in missing information about iterations and total time
```
2K performance run parameters for coremark.
CoreMark Size    : 666
Total ticks      : 1520
Total time (secs):
Iterations/Sec   :
Iterations       : 1000
Compiler version : GCC10.3.1 20210621 (release)
Compiler flags   :
Memory location  : STACK
seedcrc          : 0xe9f5
```
To fix this **FLOAT_USER** is set to 1 in syscfg.yml when **HARDFLOAT** is 1.
=> apps/coremark: Fix output when HARDFLOAT is on

hw/mcu/microchip/pic32mz/syscfg.yml, hw/usb/tinyusb/pkg.yml
When hw/usb/tinyusb package is included for pic32mz based build,
it will automatically pull pic32mz glue package that will
setup interrupt.
This is done same way as for other MCUs
=> tinyusb: Setup pic32mz USB interrupt automatically

hw/bsp/black_vet6/syscfg.yml, hw/usb/tinyusb/stm32_fsdev/src/stm32_fsdev.c, hw/usb/tinyusb/synopsys/src/synopsys.c
For black_vet6 USB_DP_HAS_EXTERNAL_PULL_UP is set to 1 to reflect hardware design.
Without this USB host may not noticed that device rebooted and re-enumeration is required
For ST based hardware (both synopsys or stm32_fsdev) external pullup handling was working in
mynewt OS but when USB was built into bootloader GPIO handling of D+ was to fast because
os_time_delay() did not work.
For bootloader case os_cpu_time_delay is used.
=> TinyUSB and external pull up on D+

hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32wb55/include/tusb_hw.h, hw/usb/tinyusb/stm32_fsdev/stm32wb55/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32wb55/src/stm32_fsdev.c, hw/usb/tinyusb/stm32_fsdev/stm32wb55/syscfg.yml
TinyUSB uses same driver for STM32WB55 as for STM32F1 but there
are differences in interrupts and power settings that call
for separate package.
=> tinyusb: Add hardware initialization for stm32wb55

hw/drivers/flash/spiflash/chips/syscfg.yml, hw/drivers/flash/spiflash/include/spiflash/spiflash.h, hw/drivers/flash/spiflash/src/spiflash.c
Similar to #2582 , this adds support for the P25Q32H SPI NOR flash chip found in some P8(b) smartwatch variants. 
Datasheet: https://www.puyasemi.com/uploadfiles/2018/08/201808071524332433.pdf , see p. 70 for IDs.
=> hw/drivers/flash/spiflash: add P25Q32H chip

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
This allows to read directly from an IPC flat buffer instead of reading
to a buffer.
=> hw/drivers/nrf53_ipc: Add API to retrieve pointer to data buffer

kernel/os/include/os/os_mempool.h, kernel/os/src/os_mempool.c
Function can be useful if mempool is to be shared by packages
=> mempool: Add function to get mempool by name

hw/sensor/creator/src/sensor_creator.c
If BMP280 is connected to SPI with bus driver build
syscfg value for bus name was mismatched in source and yml.
=> sensor_creator: Fix BMP2800 SPI configuration

hw/mcu/dialog/da1469x/src/hal_i2c.c
hal_i2c_init function used to configure I2C hardware completely.
Power improvements changed this behavior, but those changes
were mostly for bus driver functionality where power management
is handled batter.
This brings back enabling hardware in hal_i2c_init in case
some application (sensors_test) uses I2C with hal functions
only and does not care about power management.
=> da1469x/i2c: Enable I2C controller on init

sys/console/full/history_log/pkg.yml, sys/console/full/history_log/src/history_log.c, sys/console/full/history_ram/src/history_ram.c, sys/console/full/include/console/history.h, sys/console/full/src/console.c
history_handle_t type was used to store pointer or result.
Code assumed that pointer will always be positive and error code
would be SYS_xxx so they would be negative.
For PIC32 RAM addresses start from 0x80000000 sot they were always
negative.
This removes double meaning of history_handle_t and some functions return
error codes separately from found history entries.
There is no change in history handling logic just arguments and return values reworked.
=> console: Fix internals console history

hw/mcu/dialog/da1469x/src/da1469x_periph.c
Watchdog is automatically enabled at start.
To enable build without watchdog it must be
manually frozen before it will fire since
idle task will not feed it when WATCHODG_INTERVAL==0.
=> hw/mcu/da1469x: Allow no-watchdog build

hw/usb/tinyusb/src/tinyusb.c
When TinyUSB was enabled in bootloader (for DFU) and Watchdog was
enabled device resets all the time because TinyUSB loop did not feed
watchdog.
Now for bootloader build watchdog is handled when tinyusb takes over.
=> tinyusb: Tickle watchdog in bootloader

fs/fcb2/selftest/src/fcb_test.c, fs/fcb2/selftest/src/fcb_test.h, fs/fcb2/selftest/src/testcases/fcb_test_append_fill.c, fs/fcb2/selftest/src/testcases/fcb_test_append_fill_small.c, fs/fcb2/src/fcb_getnext.c
When FCB was full and there was less free space that could be used < 6.
fcb2_init incorrectly returned error FCB2_ERR_CRC instead of FCB2_OK
It could lead to FCB being wiped if fcb2_init_flash_area() was used for fcb initialization.
Fixes #2756
=> fcb2 initialization fix

hw/drivers/sensors/lis2dh12/src/lis2dh12.c
Fix for a compile error that happens when `LIS2DH12_LIS2DK10_COMPAT: 0` due to an undefined label.
=> Fix compile error introduced by adding support for lis2dk10

hw/drivers/semihosting/src/mbed_semihost_api.c
Arguments were not set properly.
=> hw/drivers/semihosting: Fix typo in semihost_rename

crypto/mbedtls/pkg.yml
Debug build compiled with gcc 10.x (arm and riscv) produces
warning:
repos/apache-mynewt-core/crypto/mbedtls/src/hmac_drbg.c:134:11: error: 'ret' may be used uninitialized in this function [-Werror=maybe-uninitialized]
134 |     return( ret );
This warning is incorrect and now is suppressed.
=> MbedTLS: Suppress gcc 10 warning

apps/pwm_test/src/main.c
Code assumed that NUCLEO_F767ZI, NUCLEO_F303RE or NUCLEO_F303K8
are defined for respective board while it's not.
Preprocessor condition changed to reflect currently present definitions.
=> apps/pwm_test: Fix configuration for nucleo boards

hw/mcu/nordic/nrf5340/startup/syscfg.yml, hw/mcu/nordic/nrf5340_net/startup/syscfg.yml
H4 over IPC requires a bit more stack.
=> hw/mcu/nordic: Bump main stack for nRF53

hw/bsp/hifive1/include/bsp/bsp.h
bsp.h use uint8_t without including stdint.h.
For most cases it will work since bsp.h is likely to be
included later then some other headers.
If it is first include file compilation will fail:
Error: In file included from repos/apache-mynewt-core/apps/slinky/src/led.c:22:
repos/apache-mynewt-core/hw/bsp/hifive1/include/bsp/bsp.h:121:8: error: unknown type name 'uint8_t'
extern uint8_t _ram_start;
Now required header is explicitly included.
=> bsp/hifive1: Add missing include

repository.yml
Mcuboot 1.8 and newer have issues in test framework affecting
'newt test all'
=> Make Mynewt 1.10 release depend on mcuboot 1.7.2

hw/usb/tinyusb/cdc_console/syscfg.yml, hw/usb/tinyusb/dfu/syscfg.yml, hw/usb/tinyusb/std_descriptors/include/tusb_config.h, hw/usb/tinyusb/std_descriptors/syscfg.yml
USB function in TinyUSB stack is enabled by one of the following
definitions: CFG_TUD_CDC, CFG_TUD_HID, CFG_TUD_MSC, CFG_TUD_MIDI,
CFG_TUD_MSC, CFG_TUD_VENDOR, CFG_TUD_USBTMC, CFG_TUD_DFU_RT, CFG_TUD_DFU,
USBD_BTH need to be set to non-zero value.
So far some of those could be set in syscfg (definition were provided
in std_descriptors package). Following syscfg values were there:
USBD_HID, USBD_CDC, USBD_MSC, USBD_DFU, UDBD_BTH.
In order to enable standard functionality two things had to be set.
For example to have USB console one had to include hw/usb/tinyusb/cdc_console
(this could be done by settings CONSOLE_USB: 1) and separate settings in
target or application was needed USBD_CDC: 1.
For BT one had to set BLE_TRANSPORT_HS: usb and USBD_BTH: 1.
Now that any package can overwrite …
=> tinyusb: USB function enable rework

crypto/mbedtls/include/mbedtls/gcm.h, crypto/mbedtls/src/gcm.c
This set of changes adds back in a couple of GCM functions that we had been using but which were recently dropped during the mbedtls update.
Specifically these are the mbedtls_gcm_setkey_noalloc() and mbedtls_gcm_update_add() APIs.
=> Mbedtls GCM refresh

hw/usb/tinyusb/std_descriptors/include/tusb_config.h, hw/usb/tinyusb/std_descriptors/syscfg.yml
So far CDC RX/TX fifo size was matching endpoint size.
Now it is possible to specify those in syscfg.yml.
This can improve console logging.
Default FIFO sizes remain unchanged.
=> tinyusb/cdc: Add fifo size configuration option

hw/usb/tinyusb/stm32_fsdev/stm32wb55/include/tusb_hw.h
CFG_TUSB_MCU should be set to OPT_MCU_STM32WB.
OPT_TUSB_STM32SB55 was originally proposed in TinyUSB pull request
but it was changed to version without 55
=> tinyusb/stm32wb55: Fix MCU type

kernel/os/src/os_mempool.c
When OS_MEMPOOL_CHECK was set to 1, code tried to
verify that block is not already in free list.
If during iteration over free list, memory block
was taken from the pool (from interrupt or higher
priority task) and already filled with data
mb_next could point to anything resulting in
MPU or hard fault exception.
Now critical section is added to prevent list
modification during check.
=> mempool: Fix check for duplicate free

hw/bsp/p-nucleo-wb55-usbdongle/src/hal_bsp.c
When BUTTON_1_AS_STM32_DFU is set (that should be used only in bootloaer)
hal_bsp redirect execution to STM32 DFU bootloader to allow writing
bootloader or application.
Function boot_preboot was defined always even if functionality was not enabled.
This prevented alternative boot_preboot() functionality that can be provided
by other package.
Now hal_bsp.c only provides boot_preboot() when BUTTON_1_AS_STM32_DFU is set.
=> bsp/p-nucleo-wb55-dongle: Update BUTTON_1 in bootloader

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
With this inclusion it is possible to use pin
defined in bsp.h (i.e. BUTTON_1) as pin for enabling
MSC FAT View in bootloader.
=> tinyusb: include bsp.h in FAT View

hw/bsp/dialog_da14695-dk-usb/src/hal_bsp.c, hw/bsp/dialog_da1469x-dk-pro/src/hal_bsp.c, hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h, hw/mcu/dialog/da1469x/src/hal_flash.c, hw/mcu/dialog/da1469x/syscfg.yml
This patch adds in auto-detection and configuration of Gigadevice and Macronix
flash devices based on the manufacturer and device ID.  The intent in this is to
allow for a single binary to work on devices with different flash.
Normally, the flash is initialized by the ROM bootloader on the device.  However, if the image being loaded is RAM_RESIDENT, that header will not exist and the ROM bootloader will not provision the device to have a working flash configuration.
=> da1469x: hal_flash: Autodetect and configure flash

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
The Nimble IPC messages are written in 2 parts: the cmd byte and the rest.
It is unneccesary to already interrupt the other core for the first byte,
since it will be interrupted by the 2nd write already.
(a 2nd patch to Nimble will use this new function)
=> nrf5340: avoid have 2 interrupts for each IPC message

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
Huge file size handling from syscfg had typo and incorrect condition
resulting in huge file always taking most of the free spece.
Now huge file size can have size specified by the user.
=> tinyusb/msc_fat_view: Fix huge file specification

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
HUGE_FILE_SIZE could be re-defined due to missing else
=> tinyusb/msc_fat_view: Fix missing else in pre-processor

hw/mcu/nordic/nrf5340/nrf5340.ld, hw/mcu/nordic/nrf5340/nrf5340_ram_resident.ld
Comment about erratas 33, 34 was valid only for first drop of NRF52832.
For NRF5340 erratas with those numbers exists but are not applicable here.
=> nrf5340: Remove misleading comment

kernel/os/include/os/os_mempool.h
OS_MEMPOOL_SIZE returned incorrect memory size for mpool buffer when
OS_MEMPOOL_GUARD was enabled.
OS_MEMPOOL_GUARD requires extra space between memory blocks and
OS_MEMPOOL_SIZE (and OS_MEMPOOL_BYTES) returned values that did not
include this extra space.
During os_mempool_init_internal() memory outside expected buffer
was clobbered.
=> mempool: Fix OS_MEMPOOL_SIZE when OS_MEMPOOL_GUARD is on

hw/drivers/sensors/lsm6dsl/include/lsm6dsl/lsm6dsl.h, hw/drivers/sensors/lsm6dsl/src/lsm6dsl.c, hw/drivers/sensors/lsm6dsl/src/lsm6dsl_priv.h, hw/drivers/sensors/lsm6dsl/src/lsm6dsl_shell.c, hw/sensor/include/sensor/sensor.h
Adding absolute and relative tilt functionality.
Extending lsm6dsl_shell dump to include bankA and bankB registers.
Fixed LSM6DSL_SHUB_REG_ACCESS_MASK bit mask.
=> sensors/lsm6dsl: add tilt function

hw/drivers/sensors/bmp388/include/bmp388/bmp388.h, hw/drivers/sensors/bmp388/pkg.yml, hw/drivers/sensors/bmp388/src/bmp388.c
Allow sensors/bmp388 driver to accept the bmp390 chip ID. 
The Bosch BMP390 an updated pressure sensor which is compatible with the older BMP388. The only difference from a driver perspective is the chip ID, where the BMP390 chip ID is 0x60 and BMP388 is 0x50.
=> sensors/bmp388: Add compatibility for bmp390

hw/mcu/nordic/nrf5340/startup/src/arch/cortex_m33/gcc_startup_nrf5340.s, hw/mcu/nordic/nrf5340_net/startup/src/arch/cortex_m33/gcc_startup_nrf5340_net.s
Main stack is now filled with pattern at startup for
better control of stack usage.
=> mcu/nrf5340: Fill main stack with pattern

hw/bsp/dialog_da1469x-dk-pro/include/bsp/bsp.h
Need to include syscfg.h since it uses MYNEWT_VAL_CHOICE().
=> hw/bsp/dialog: Add missing #include

hw/mcu/ambiq/apollo3/src/hal_flash.c, hw/mcu/ambiq/apollo3/syscfg.yml
Ambiq's internal flash writing functionality does not allow for direct flash to flash memory transfers. This change handles situations like that by transferring to an intermediary ram buffer.
=> Ambiq Apollo3: Utilize ram buffer to handle flash to flash memory writes

hw/mcu/nordic/nrf52xxx/src/system_nrf52.c
Newest hardware revisions of NRF52840, NRF52810 (and others) now have
access port protection enabled by default.
To enable debugger use after reset nrf52_handle_approtect() should be
called during startup.
SystemInit from NRF SDK now has and uses code to handle APROTECT, this
change do the same for mynewt.
=> mcu/nrf52: Handle APROTECT

hw/mcu/nordic/nrf5340/src/hal_system_start.c
RAM_SIZE was always taken from bps.h.
With trust zone in place it may be that the bootloader
had limited RAM assigned in linker scripts.
This may happen when MCU_BOOT_MEASURED_STARTUP is used.
This change clears only RAM that bootloader used.
If nothing special was done to linker scripts RAM size
will be the same as it used to be.
=> mcu/nrf5340: Trust zone RAM clean update

net/ip/native_sockets/src/native_sock.c
Werror=stringop-overflow= seems to be now enabled by default on GCC 11.
repos/apache-mynewt-core/net/ip/native_sockets/src/native_sock.c: In
function ‘native_sock_mn_addr_to_addr’:
repos/apache-mynewt-core/net/ip/native_sockets/src/native_sock.c:199:9:
error: ‘strncat’ specified bound 108 equals destination size
[-Werror=stringop-overflow=]
199 |         strncat(sun->sun_path, msun->msun_path,
sizeof sun->sun_path);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> net/ip/native_socks: Fix build on with -Werror=stringop-overflow

hw/drivers/flash/spiflash/src/spiflash.c, hw/drivers/flash/spiflash/syscfg.yml
This PR introduces three new **optional** configuration parameters: `SPIFLASH_IGNORE_MANUFACTURER`, `SPIFLASH_IGNORE_MEMORY_TYPE`, and `SPIFLASH_IGNORE_MEMORY_CAPACITY`. (Default: `0`).
These parameters selectively disable the whitelist checks of the SPI Flash JEDEC IDs.
I am currently [porting the InfiniTime OS](https://github.com/InfiniTimeOrg/InfiniTime/pull/1050) (written for the [PineTime smartwatch](https://www.pine64.org/pinetime/)) to a popular Chinese smartwatch series called "P8". `mynewt-core` is used for the bootloader.
These P8 watches come in a whole zoo of variants, each being compatible with the firmware but containing sometimes a bit different chips due to the silicon shortage and general chip availability on the global market. This is usually no problem to handle. …
=> hw/drivers/flash/spiflash: Add option to ignore JEDEC ID

hw/bsp/hifive1/hifive1.ld, hw/mcu/sifive/fe310/src/hal_flash.c
This eliminates following warning:
/tmp/ccfBOXIv.s: Assembler messages:
/tmp/ccfBOXIv.s:6: Warning: setting incorrect section attributes for .data.fe310_flash_transmit
/tmp/ccfBOXIv.s:41: Warning: setting incorrect section attributes for .data.fe310_flash_fifo_put
/tmp/ccfBOXIv.s:89: Warning: setting incorrect section attributes for .data.fe310_flash_fifo_write
/tmp/ccfBOXIv.s:145: Warning: setting incorrect section attributes for .data.fe310_flash_wait_till_ready
/tmp/ccfBOXIv.s:194: Warning: setting incorrect section attributes for .data.fe310_flash_write_enable
/tmp/ccfBOXIv.s:232: Warning: setting incorrect section attributes for .data.fe310_flash_write_page
/tmp/ccfBOXIv.s:419: Warning: setting incorrect section attributes for .data.fe310_flash_erase_sector
.data.XXXX section gets …
=> riscv: Fix build warning

hw/usb/tinyusb/cdc/include/cdc/cdc.h, hw/usb/tinyusb/cdc/pkg.yml, hw/usb/tinyusb/cdc/src/cdc.c, hw/usb/tinyusb/cdc_console/pkg.yml, hw/usb/tinyusb/cdc_console/src/cdc_console.c, hw/usb/tinyusb/cdc_console/syscfg.yml, hw/usb/tinyusb/std_descriptors/include/tusb_config.h, hw/usb/tinyusb/std_descriptors/src/std_descriptors.c, hw/usb/tinyusb/std_descriptors/syscfg.yml
This adds way to have several CDC interfaces (COM ports or /dev/ttyACMx devices) on one USB devices.
This will allow to have USB console with other serial based interface like HCI over serial connection.
cdc package is added that routes TinyUSB CDC devices callbacks to multiply interface implementations.
Some USB string descriptor handling is also updated so string indices for interfaces and DFU slot are no longer hardcode.
This also adds standard descriptor for CDC HCI that can be used by future nimble transport.
=> tinyusb: Allow for several CDC interfaces

hw/mcu/stm/stm32f4xx/src/system_stm32f4xx.c, hw/mcu/stm/stm32f7xx/src/system_stm32f7xx.c
SystemInit disabled few bits in CR register before every clock was
configured. This allows to configure PLL.
If PLLI2S was enabled before this function was called (could happen
if I2S was enabled in bootloader) PLL source could not be changed.
ST HAL function HAL_RCC_OscConfig() expect this bit to be cleared.
Following code from HAL will not update PLLSRC bit if PLLI2S in enabled
during call to this function.
/* Configure the main PLL clock source, multiplication and division factors. */
WRITE_REG(RCC->PLLCFGR, (RCC_OscInitStruct->PLL.PLLSource                                            | \
RCC_OscInitStruct->PLL.PLLM                                                 | \
(RCC_OscInitStruct->PLL.PLLN << RCC_PLLCFGR_PLLN_Pos)             | \
(((RCC_OscInitStruct->PLL.PLLP >> 1U) - 1U) << …
=> stm32f4/f7 Fix PLL configuration

hw/bsp/hifive1/hifive1.ld
Startup script has only one loop that copies initialized data and
code that should execute from RAM.
It implies that variables in .data .ram_text .srodata .sdata and such
has same layout in flash and in RAM.
Those data are packed by default in flash so output sections
(.data .srodata .sdata) if they start with something that requires
alignment change may end up with wrong data being copied to
statically initialized data.
One way to prevent such case is to copy each output section in separate
loop. But it is also possibly to add output section attribute ALIGN_WITH_INPUT
and then linker will fill necessary space in flash image.
=> riscv: Fix initialized data

apps/coremark/syscfg.yml
Default value 200 for COREMARK_ITERATIONS is not good enough for most BSP/MCUs.
Making default value 0 makes coremark pre-compute number of iterations needed for 10-20s of benchmark time.
this change will make most (maybe all) BSP work out of the box.
=> coremark: Compute number of iteration automatically by default

hw/bsp/ublox_bmd_345/pkg.yml
This was recently renamed from plna to fem.
=> hw/bsp: Update Sky66112 package path for uBlox BMD345

hw/mcu/microchip/pic32mz/src/hal_flash.c
This fixes:
- unaligned address writes that are not needed (FCB uses unaligned writes).
- writes that are not multiply of 4 are now allowed
- flash read uses uncached segment to avoid wrong data read after writes (CRC failure in FCB usage)
=> pic32 flash access fixes

hw/mcu/nordic/include/nrfx_glue.h
Some nrfx functionality uses NRFX_STATIC_ASSERT and NRFX_ATOMIC_xxxx functions.
Those were not provided in mynewt even though they are present in Nordic nrfx_glue.h template.
Now mote nrfx can be use if needed.
=> nrfx_glue: Support atomic and static assert

sys/log/full/src/log.c
GCC 12 reports following error:
Compiling repos/apache-mynewt-core/sys/log/full/src/log_level.c Error: repos/apache-mynewt-core/sys/log/full/src/log.c: In function
'log_walk_body_section':
repos/apache-mynewt-core/sys/log/full/src/log.c:923:24: error: storing
the address of local variable 'lwba' in '*log_offset.lo_arg'
[-Werror=dangling-pointer=]
923 |     log_offset->lo_arg = &lwba;
|     ~~~~~~~~~~~~~~~~~~~^~~~~~~
repos/apache-mynewt-core/sys/log/full/src/log.c:917:30: note: 'lwba'
declared here
917 |     struct log_walk_body_arg lwba = {
|                              ^~~~
repos/apache-mynewt-core/sys/log/full/src/log.c:917:30: note:
'log_offset' declared here
=> sys/log: Fix dangling pointer

hw/mcu/stm/stm32f4xx/src/clock_stm32f4xx.c
Prefetch is not available only on Revision A.
Prefetch was enabled only for Revision Z.
Now revisions 1,2,4,Y also can have prefetch enabled.
=> stm32f4: Enable prefetch for F405/F407/415/417

hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c, hw/mcu/nordic/nrf5340/include/nrfx_config.h
NRF5340 has dedicated audio clock that allows for more precise audio frequencies then 32MHz oscillator only.
NRF5340 also supports 32 bits sample slots.
This add support ACLK.
For this to work NRFX_CLOCK_ENABLED must be enabled to allows usage of clock related nrfx api.
=> i2s_nrfx: Add Audio clock support

kernel/os/src/arch/pic32/asm/ctx.S, kernel/os/src/arch/pic32/os_arch_pic32.c
All interrupts used same register set and that made interrupt code take more time since more registers needed to be save.
Commit 808115b9530b059ff9b6a12fc5b988f87e540710 enabled interrupts at some point during context switch and while interrupts were enabled isr code for interrupt or exception that would be handled (Coprocessor Unusable exception) would use k0 and k1 without storing it first. This leads to difficult to find hard faults.
One way to fix it would be to not enable interrupts during context switch but this change just assigns SRS to interrupts and exception so k0 and k1 will not get clobbered during context switch.
For pic32mx just not enable interrupt during context switch since they don't have enough SRS.
=> pic32: Assign shadow register sets to interrupts

libc/baselibc/pkg.yml, libc/baselibc/src/mynewt.c, libc/baselibc/syscfg.yml
baselibc has option to lock the heap so malloc/free/calloc can be called from multi-threaded application.
This adds implementation of this using os_mutex.
When BASELIBC_THREAD_SAFE_HEAP_ALLOCATION is set to 1 baselibc has package initialization functions that puts locking functionality in place.
For now to preserve compatibility this functionality is not enabled by default leaving heap allocation
not thread unsafe.
=> baselibc: Add option to have thread-safe heap

hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340.h, hw/drivers/ipc_nrf5340/include/ipc_nrf5340/ipc_nrf5340_priv.h, hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
This adds structure required for HCI IPC transport to shared memory. Since HCI IPC transport implements generic flow control for HCI over IPC, we can remove "old" flow control code.
=> hw/ipc_nrf5340: Add support for HCI IPC transport

apps/iptest/syscfg.yml, net/ip/lwip_mn/lwipopts/syscfg.yml
LwIP in default configuration specified by lwipopts.h uses malloc/calloc/free for
some allocations.
- To make sure that malloc is thread safe restriction is applied in syscfg for lwipopts package
- apps/iptest has this value set in syscfg
=> iptest thread safe malloc

libc/baselibc/pkg.yml
When optimization is above O1 compilers recognizes sequences:
p = malloc(n);
memset(p, 0, n);
and turns them into calloc calls.
Unfortunately this sequence is actually in baselibc implementation of calloc so compiler just optimizes this sequence and calls calloc recursively or jumps to the beginning resulting in infinite loops.
To break this circle baselibc is build with option -fno-builtin-malloc
=> baselibc: Prevent calloc recursion

hw/bsp/ublox_bmd_345/syscfg.yml
Some configuratio were renamed from _LL_ to _FEM_.
=> ublox-bmd-345: Update syscfg to not use defunct configs

kernel/os/include/os/os_task.h
t_obj points to semaphore or mutex while task is waiting now t_obj is field in union along with t_mutex and t_sem it just makes debugging easier since IDE can show mutex or semaphore without need to case in GDB console
=> kernel/os: Add t_mutex and t_sem fields

hw/mcu/stm/stm32f7xx/src/clock_stm32f7xx.c, hw/mcu/stm/stm32f7xx/stm32f746.ld, hw/mcu/stm/stm32f7xx/stm32f767.ld, hw/mcu/stm/stm32f7xx/syscfg.yml
- Some inapplicable leftover from STM32F4 removed
- Added DCache enabler
- vector table moved to DTCM due to apparent NVIC problem with cached SRAM1
=> stm32f7 dcache

hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h, hw/mcu/dialog/da1469x/src/hal_flash.c
This set of patches fixes an issue with Gigadevice flash when issuing rdid reads.  The second patch adds an export of the RDID information so that it can be used by other application code.  This is especially useful if special actions need to be taken based on the detected flash identification.
=> Flash autoconfigure updates

hw/mcu/dialog/da1469x/src/hal_watchdog.c, hw/mcu/dialog/da1469x/syscfg.yml
This patch adds a facility to control whether or not the Dialog watchdog is disabled when the hal_watchdog_init function is being called.  There are some use cases where the watchdog needs to remain running from a previous application or bootloader.
=> da1469x: Add option to not disable watchdog on init

hw/mcu/nordic/nrf5340/syscfg.yml
Does not really make sense to have it disabled by default since we are running from flash.
=> hw/mcu/nrf5340: Enable cache by default

hw/mcu/nordic/nrf5340/pkg.yml, hw/mcu/nordic/nrf5340/src/hal_system_start.c, hw/mcu/nordic/nrf5340/src/nrf5340_periph.c, hw/mcu/nordic/nrf5340/tfm/include/tfm/tfm.h, hw/mcu/nordic/nrf5340/tfm/pkg.yml, hw/mcu/nordic/nrf5340/tfm/src/tfm.c, hw/mcu/nordic/nrf5340/tfm/syscfg.yml
New package will contain secure functions.
Those functions will allow access to secure only peripherals.
To start MCU assignment to GPIO function tfm_gpio_pin_mcu_select
allows to redirect PIN to net core.
tfm_uicr_otp_read() allows to read UICR->OTP from non-secure code.
When tfm package build with bootloader or secure application
functions are treated as every other function.
When tfm is build with non-secure application function bodies
are not present in the build and are expected to be linked with
library that provides secure gateways.
tfm can be also build into bootloader in this case it's the
bootloader that provides secure functions.
ELF that provides implementation of secure functions must be
build with TFM_EXPORT_NSC: 1 syscfg value.
Signed-off-by: Jerzy Kasenberg …
=> mcu/nrf5340: Add secure functions package

sys/console/full/src/console.c
When console has colors (for now only for software cursor) color or other text attributes can be changed from the default when device reboots.
Now escape sequnce to restore default text attributes is added to first time initialization of console.
=> sys/console: Reset text attributes on init

hw/mcu/nordic/nrf5340/src/hal_system.c
This is allowed only from secure code (either application running in secure mode, or bootloader).
=> mcu/nrf5340: Enable cache only from secure code

hw/mcu/stm/stm32_common/src/hal_spi.c
if STM32_HAL_SPI_RESOLVE() fails code jumps to err: where retval is uninitialized.
```c
uint16_t hal_spi_tx_val(int spi_num, uint16_t val) {
...
uint16_t retval;
...
STM32_HAL_SPI_RESOLVE(spi_num, spi);
...
err:
return retval;
}
```
=> stm32/spi: Fix uninitialized return value

hw/mcu/stm/stm32_common/src/hal_spi.c
This fixes the problem firmware update on STM32 devices with external flash that is enabled
in bootloader (most likely when second slot is in external flash as is configured for black_vet6,
but could happen also when both slots are in normal flash and spiflash is enabled in bootloader
for other reason).
spi->handle.Instance initiated to constant value (register address) It was done in hal_spi_config() so value was set every time this function was called which is not the main reason it is moved now to hal_spi_init().
Main reason is that in spiflash code call to hal_spi_disable() is made before first call to hal_spi_config() it can result in writes to addresses around 0 which most likely be internal flash address. It can result in exception if MPU is present and configured to block writes …
=> stm32/spi: Init Instance in hal_spi_init

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
New directory entries with long file name were not handled correctly and could lead to stack corruption.
Now file names up to 78 characters are handled.
And longer file names should not result in device
misbehavior.
=> tinyusb: Fix long file name handling

hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c
If I2S was configured in input mode only sample_count that is used to calculate input buffer size passed to nrfx_i2s_start was incorrect (0) and nrfx would assert.
For I2S configured in input direction only buffer size is taken from buffer capacity and can be updated later by driver after DMA finishes.
=> hw/drivers/i2s: Fix i2s_nrfx for microphone configuration

fs/fcb2/src/fcb_getprev.c
on reaching oldest item the mutex does not get unlocked due directly returning
=> fs/fcb2: fix missing unlock of mutex in getprev

kernel/os/include/os/os_sched.h, kernel/os/src/os_sched.c
This change add possibility to lock task scheduling temporarily.
Pair of functions os_sched_suspend/os_sched_resume is added to allow task switching to be suspended while interrupts are still enabled.
This change is needed specially when Trust Zone MCU runs unsecure code
and then it calls secure functions while interrupts are enabled.
In some cases interrupt can activate context switch.
Context switch will not work correctly when current task is executing secure code
with separate (but only one) main secure stack.
=> os/kernel: Add scheduler locking functionality

net/lora/node/src/mac/LoRaMac.c
`lora_mac_process_radio_rx_timeout` is called from `lora_mac_process_rx_win2_timeout` which is triggered when RX2/join2 window starts. The problem here is that there still can be unfinished rx1 window downlink transmission (delay between rx1 and rx2 window start is fixed to 1sec and the message air time can be longer).
In that case, we don't want to put radio to sleep - that would cancel the receive and the message would be dropped
=> loramac: fix broken rx1 interval

hw/mcu/nordic/nrf5340/src/hal_system.c, hw/mcu/nordic/nrf5340_net/src/hal_system.c
We need to request hfxo via API to make sure ref is held all the time, otherwise any other request/release will stop hfxo and thus break lfsynth.
=> hw/mcu/nrf53: Request hfxo for lfsynth via api

.github/workflows/build_blinky.yml, .github/workflows/build_targets.yml
ASF policy requires to use exact sha instead of tags for actions that are not certified by Github or ASF.
=> Use exact commit sha for GH Actions that are not certified

.github/workflows/build_targets.yml
Don't fail on first error but try to build all targets. Also, make build less spammy, we care about errors only anyway.
=> github: Improve test targets build

.github/workflows/build_targets.yml
We need to build from bash instead of windows shell.
=> ci: Fix targets build on Windows

libc/baselibc/src/memset.c
Code is slightly more efficient then one generated by default. It is replaced however because when "speed" profile is selected default loop
while (n--) {
*q++ = c;
}
is recognized as candidate for memset and recursive call to same function is generated like that:
void *memset(void *dst, int c, size_t n)
{
204022ee:	1141                	addi	sp,sp,-16
204022f0:	c422                	sw	s0,8(sp)
204022f2:	c606                	sw	ra,12(sp)
204022f4:	842a                	mv	s0,a0
#else
while (n--) {
204022f6:	c601                	beqz	a2,204022fe <memset+0x10>
*q++ = c;
204022f8:	0ff5f593          	zext.b	a1,a1
204022fc:	3fcd                	jal	204022ee <memset>  !!!!!!!!!!! recursive call
}
#endif
=> libc/baselibc: Add specialized memset for RISCV

hw/mcu/stm/stm32_common/syscfg.yml
TIMER_3, TIMER_4 and TIMER_5 were referenced at code stm32_periph.c yet there were not definitions for them.
This just adds missing definitions.
=> stm32: Update syscfg for timers

.github/project.yml
External repositiries needed by some BSP are not added to project.yml used for CI.
=> Add stm32u5 stm32h7 repository to project.yml for CI

hw/mcu/sifive/fe310/src/sys_clock.c
This does not change anything special it just exports SystemCoreClock that matches name commonly used in ARM builds.
Old cpu_freq value was local declaration so there is no risk of breaking anything.
Since there is no common way defined by mynewt for application to get system clock frequency fe310 adopts convention used by ARM code.
=> mcu/fe310: Export SystemCoreClock variable

uncrustify.cfg
Use sp_word_brace_init_lst instead of sp_word_brace
=> uncrustify: Don't use deprecated config

README.md
Updated readme with the  deleted apps : 
Below is the list of commits that removed the respected apps : 
Commit &nbsp;&nbsp; | Apps Removed
1c1df506cef5678d3118f55288cb4cd437fbd478 | blecent, bleprph, blehci, btshell 
540ee189c90d66b86af52aae3d0d9cc31021281b | boot                                           
3469f91bba3b5ccb42f7011bab38aba676b9df07 | test
33cdc60bc6e78e786c879c0b5dd59a5d80369ee8 | blinky
=> README: Remove deleted apps from Sample Applications

hw/mcu/stm/stm32h7xx/src/hal_timer_freq.c
Function was using incorrect constants for divider. For STM32H7 APB clock has separate divider from HCLK which is the case for other STM32 MCUs.
As a result timer based on APB1 where incorrectly setup and run at different frequency that expected.
=> stm32h7: Fix APB1 divider conversion function

hw/bus/drivers/spi_hal/src/spi_hal.c, hw/bus/drivers/spi_stm32/src/spi_stm32.c, hw/bus/include/bus/bus.h, hw/bus/include/bus/bus_driver.h, hw/bus/src/bus.c
Duplex of SPI was not covered in bus drivers.
This adds bus_node_duplex_write_read() function that
can be used with SPI drivers that support duplex mode.
For simplicity both buffers provided to function have same length.
=> hw/bus: Add duplex_write_read function to bus_dev_ops

hw/mcu/nordic/nrf5340/src/hal_spi.c
16 and 32 MHz are only valid for SPI4 not SPI3
=> mcu/nrf5340: Fix spi frequency selection

hw/bus/drivers/spi_apollo3/src/spi_apollo3.c
bus_spi_node seems to keep SPI frequency in kHz while hal_spi_settings keeps it in Hz.
This just converts frequency to Hz before calling hal_spi_config.
=> bus/spi_apollo3: Fix SPI frequency setting

.github/workflows/build_blinky.yml, .github/workflows/build_targets.yml, .github/workflows/newt_test_all.yml
This should make it easier for upgrading dependencies in newt.
=> ci: Use latest go for building newt

hw/usb/tinyusb/std_descriptors/src/std_descriptors.c, hw/usb/tinyusb/std_descriptors/syscfg.yml
Device descriptor was set to composite only when CDC was used. Now user can specify class/subclass/protocol for device descriptor in syscfg.
If USBD_COMPOSITE_DEVICE is selected class/subclass/protocol are set according to composit device specification.
This allow to have BTH with MSC and CDC at the same time.
=> tinyusb: Device descriptor configuration update

uncrustify.cfg
Should be sp_word_brace_init_lst.
=> uncrustify: Fix typo in configuration

sys/console/syscfg.yml
Until now CONSOLE_IMPLEMENTATION had no default value, which was causing build errors when implementation package wasn't specified.
=> sys/console: Add default CONSOLE_IMPLEMENTATION value

hw/mcu/dialog/da1469x/src/hal_spi.c
It is possible to setup 16/8/4 and 2.28 MHz SPI clock. However for 16/8/4 MHZ clock was set only if baudrate had exactly correct value in other cases clock would defalt to slowest 2.28 Mhz.
With this change clock is selected to have highest value that not exceeds requested baudrate.
With this change it is easier to set baudare that is specific to device that is connected to SPI.
For example if SPI device supports up to 10 MHZ user could just pass this value in syscfg.yml and this could possibly be used for different MCUs that have different capabilities without needed to have separate clock values for different MCU. This strategy of rounding down is already used in ST MCUs and hifive1.
=> hw/mcu/dialog: hal_spi update clock selection

kernel/os/src/os_sched.c
When os_sched_sleep() was called from task that previously disabled scheduler (using os_sched_suspend()) current task was put in sleep queue and continue to execute while not being marked as ready.
If task called os_sched_sleep() again g_os_sleep_list and g_os_run_list get mixed resulting in idle task being active all the time.
Now os_sched_sleep() does not modify task list when scheduling is locked. It means that os_delay() will not not put task to sleep and will exit immediately.
=> os/kernel: Fix os_sched_sleep when task switch is locked

hw/bus/drivers/spi_common/include/bus/drivers/spi_common.h
With LCD over SPI it is possible to have clocks
around 100MHz while due to type chosen for freq
SPI was limited to around 64MHz.
Now type is extend to 32 bits to allow greater speeds.
=> hw/bus: Extend SPI handle speed over 64MHz

hw/mcu/microchip/pic32mz/include/mcu/mips_hal.h, hw/mcu/microchip/pic32mz/src/hal_spi.c, hw/mcu/microchip/pic32mz/src/pic32mz_periph.c
This is simple refactor of hal_spi so it can be used with spi_hal bus driver.
When bus driver bus/drivers/spi_hal is added to the target pic32mz_periph_create() function creates proper devices
so applications using bus driver interface can be built.
=> pic32 use spi_hal bus driver for SPI

hw/bus/drivers/spi_hal/src/spi_hal.c
bus_spi_duplex_write_read (unlike all other read/write functions) was always using hal_spi_txrx_noblock().
Now when SPI_HAL_USE_NOBLOCK is not set it calls hal_spi_txrx() as the rest of API functions.
=> hw/bus/spi_hal: Fix duplex write/read

hw/bus/drivers/spi_stm32/src/spi_stm32.c
When SPI_MASTER_KEEP_IO_STATE_ENABLE flag is not set for STM32H7, SPI SCK line can change state when SPI is re-configured. This change in SCK line can lead to broken SPI transmission.
Even when this will be set there is still issue in ST driver that can prevent correct transmission
https://github.com/STMicroelectronics/stm32h7xx_hal_driver/issues/35
=> bus/spi_stm32: Fix SCK glitch for STM32H7

hw/mcu/nordic/nrf5340/tfm/include/tfm/tfm.h, hw/mcu/nordic/nrf5340/tfm/pkg.yml, hw/mcu/nordic/nrf5340/tfm/src/tfm.c
This adds tfm_uicr_protect_device function that allows to read and write status of device protection.
=> mcu/nrf5340/tfm: Add function to disable debugger

hw/mcu/stm/stm32h7xx/pkg.yml
So far commit message instructed how to add ST repositories to project.yml
Now repository specification is stored in package for out of the box usage.
=> stm32h7: Add repository reference to mcu package

hw/usb/tinyusb/msc_fat_view/include/msc_fat_view/msc_fat_view.h, hw/usb/tinyusb/msc_fat_view/pkg.yml, hw/usb/tinyusb/msc_fat_view/src/coredump_files.c, hw/usb/tinyusb/msc_fat_view/src/coredump_files.h, hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c, hw/usb/tinyusb/msc_fat_view/syscfg.yml
With this PR existing core dump(s) can be extracted for further analyze from device using PC file system.
=> Add core dumps to MSC FAT view

.style_ignored_dirs
STM32 based BSP contain hal config header that is
formatted by ST.
This change adds those headers to style checker ignore list
=> stm32: Update style_ignored_dirs

hw/mcu/nordic/nrf5340/tfm/include/tfm/tfm.h, hw/mcu/nordic/nrf5340/tfm/pkg.yml, hw/mcu/nordic/nrf5340/tfm/src/tfm.c, hw/mcu/nordic/nrf5340/tfm/syscfg.yml
New NSC function tfm_uicr_otp_write() stores data in OTP
=> mcu/nrf5340/tfm: Add OTP write function

.github/project.yml
stm32u5 and stm32h7 repositories are not referenced in sdk packages and don't need to be specified in project.yml
Versions form project.yml were no longer used anyway so this should reduce github action burden on downloading 4 repositories that are not being used.
=> github: Remove stm32u5/h7 repositories from project.yml

hw/mcu/stm/stm32_common/src/hal_flash.c
ST HAL for those two MCUs have function HAL_FLASH_Program that has one of the arguments different then other HALs. Write to flash result in hard fault or some random data being written.
This change create special case for those two MCUs.
=> stm32: Fix flash write for STM32U5 and STM32H7

hw/bsp/nucleo-u575zi-q/boot-nucleo-u575zi-q.ld, hw/bsp/nucleo-u575zi-q/bsp.yml, hw/bsp/nucleo-u575zi-q/nucleo-u575zi-q.ld
Flash layout (in bsp.yml) was copied form STM32F7. It has huge space for scratch/reboot log/nffs
because of sector sizes on STM32F7.
STM32U5 has sector size 8kB so flash areas are
updated to better match hardware capabilities.
=> hw/bsp/nucleo-u575-q: Update flash layout

hw/bus/drivers/spi_stm32/src/spi_stm32.c, hw/bus/drivers/spi_stm32/stm32u5xx/include/spidmacfg.h, hw/bus/drivers/spi_stm32/stm32u5xx/pkg.yml, hw/bus/drivers/spi_stm32/stm32u5xx/src/spidmacfg.c, hw/bus/drivers/spi_stm32/stm32u5xx/syscfg.yml
This adds DMA configuration for STM32U5.
Minor change was needed to spi_stm32.c to accommodate for register and changes in U5 devices.
=> bus/spi_stm32: Update SPI driver for STM32U5

hw/drivers/ipc_cmac/diag/pkg.yml, hw/drivers/ipc_cmac/diag/src/cmac_diag.c, hw/drivers/ipc_cmac/include/ipc_cmac/diag.h, hw/drivers/ipc_cmac/include/ipc_cmac/mbox.h, hw/drivers/ipc_cmac/include/ipc_cmac/rand.h, hw/drivers/ipc_cmac/include/ipc_cmac/shm.h, hw/drivers/ipc_cmac/include/ipc_cmac/shm_hs.h, hw/drivers/ipc_cmac/include/ipc_cmac/shm_ll.h, hw/drivers/ipc_cmac/pkg.yml, hw/drivers/ipc_cmac/scripts/build_libcmac.sh, hw/drivers/ipc_cmac/scripts/create_cmac_bin.sh, hw/drivers/ipc_cmac/src/mbox.c, hw/drivers/ipc_cmac/src/rand.c, hw/drivers/ipc_cmac/src/shm_hs.c, hw/drivers/ipc_cmac/src/shm_ll.c, hw/drivers/ipc_cmac/syscfg.yml, hw/mcu/dialog/cmac/cmac.ld, hw/mcu/dialog/cmac/src/arch/cortex_m0_cmac/os_arch_arm.c, hw/mcu/dialog/cmac/src/arch/cortex_m0_cmac/os_fault.c, hw/mcu/dialog/cmac/src/cmac_isr.c, hw/mcu/dialog/cmac/src/cmac_sleep.c, hw/mcu/dialog/cmac/src/cmac_timer.c, hw/mcu/dialog/cmac/src/system_cmac.c, hw/mcu/dialog/da1469x/da1469x.ld
This adds ipc_cmac driver which is basically cmac_driver moved from nimble repo and with some extra changes to make configuration easier.
The structure of image header for CMAC image is modified to allow host detect configuration of CMAC image. This means there's no need to sync configuration on M33 and CMAC targets manually, it's enough to configure CMAC image and M33 will detect configuration in runtime.
=> hw/drivers: Add ipc_cmac driver

hw/drivers/adc/adc_nrf52/src/adc_nrf52.c
buffer size passed to nrf_adc_set_buffer() was sometimes used
as if it was in bytes and sometimes as if it was in 16 bits words.
Now it always mean buffer size in bytes.
=>  hw/drivers/adc_nrf52: Fix non-blocking read

hw/bsp/nucleo-u575zi-q/src/hal_bsp.c, hw/bsp/p-nucleo-wb55-usbdongle/src/hal_bsp.c, hw/bsp/p-nucleo-wb55/src/hal_bsp.c
STM32U5 and STM32WB don't ethernet peripheral in any version so extra includes are removed now.
=> hw/bsp: stm32u5/stm32wb: remove reference to ETH

hw/mcu/stm/stm32_common/pkg.yml, hw/mcu/stm/stm32f4xx/pkg.yml
Package adc_stm32f4 was included for all STM32 devices when ADC_x was enabled.
adc_stm32f4 will only build for STM32F4 devices so dependency is moved to appropriate package
=> mcu/stm32: Fix ADC dependencies

hw/drivers/sensors/lps33thw/pkg.yml, hw/drivers/sensors/lps33thw/src/lps33thw.c, hw/drivers/sensors/lps33thw/syscfg.yml
Adds a syscfg, `LPS33THW_STATS`, to make use of statistics in the driver optional. The syscfg defaults to 1 (no modification to existing behavior). Some people will not care to use statistics for memory reasons.
I also want to note, the way statistics are currently implemented in the driver prevents it from being used with more than 1 sensor at a time, because `lps33thw_init` will attempt to register the statistics again the second time it is called. This will result in a sysinit panic:
```
/* Initialise the stats entry */
rc = stats_init(STATS_HDR(g_lps33thwstats),
STATS_SIZE_INIT_PARMS(g_lps33thwstats, STATS_SIZE_32),
STATS_NAME_INIT_PARMS(lps33thw_stat_section));
SYSINIT_PANIC_ASSERT(rc == 0);
/* Register the entry with the stats registry */
rc = stats_register(dev->od_name, …
```
=> lps33thw: add syscfg to make statistics optional

hw/usb/tinyusb/cdc_console/src/cdc_console.c
In the current implementation of the UART and CDC consoles, there can be a discrepency in the order of the Linefeed and Carriage Return print order. For consistency, we change this to always be "\r\n" for both variants of the implementation. This is useful in automated echo tests for verifying payloads.
=> Be consistent in console write order for '\n' and '\r'

hw/drivers/display/lvgl/indev/trackball/src/trackball.c
hal_gpio_irq_init does not enable GPIO interrupt for most of the platforms. After initializing irq interrupt must be explicitly enabled.
=> lvgl/trackball: Fix trackball for some MCUs

hw/usb/tinyusb/std_descriptors/include/tusb_config.h
TinyUSB build with mcuboot allows to have DFU or MSC for firmware update. In such case there is no mynewt scheduling and USB task takes over CPU.
However for custom builds (without mcuboot) mynewt can run normal os scheduling while having BOOT_LOADER set to 1 for linking into boot area.
Now std_descriptors tusb_config.h checks for OS_SCHEDULING instead of BOOT_LOADER to decided if TinyUSB should run in mynewt os mode or bare metal one.
=> tinyusb: Fix CFG_TUSB_OS for custom bootlader builds

hw/mcu/microchip/pic32mz/src/pic32mz_periph.c
When BUS_DRIVER_PRESENT was not set include files were correctly excluded but some SPI related structure that are valid only in bus driver build were declared.
Now spiX_cfg is only defined when BUS_DRIVER_PRESENT is present.
=> mcu/pic32: Fix build when bus driver is not present

hw/bus/pkg.yml, hw/bus/syscfg.yml, hw/mcu/dialog/da1469x/pkg.yml, hw/mcu/dialog/da1469x/syscfg.yml, mgmt/smp/smp_os/syscfg.yml
This allows the target to rearrange package initialization order via syscfg override
=> Use syscfg setting for sysinit stage numbers

hw/mcu/nordic/nrf52xxx/include/nrfx52810_config.h, hw/mcu/nordic/nrf52xxx/include/nrfx52811_config.h, hw/mcu/nordic/nrf52xxx/include/nrfx52840_config.h, hw/mcu/nordic/nrf52xxx/include/nrfx52_config.h
- GPIOTE
- PPI
- TIMER 2, 3
Tested if builds:
- pca10056
- pca10040
Please review @kasjer, thank you ! ; )
=> Enable by default some NRFX API for NRF52

targets/coverity/btshell_nrf52840_coverity/nrf52.ld, targets/coverity/btshell_nrf52840_coverity/nrf52840aa.ld, targets/coverity/btshell_nrf52840_coverity/pkg.yml, targets/coverity/btshell_nrf52840_coverity/syscfg.yml, targets/coverity/btshell_nrf52840_coverity/target.yml, targets/coverity/btshell_nrf52840_coverity2/pkg.yml, targets/coverity/btshell_nrf52840_coverity2/syscfg.yml, targets/coverity/btshell_nrf52840_coverity2/target.yml
Those targets are not meant for normal use but only to build as much code as possible. They use custom linker script to workaround flash overflow on images.
=> Add targets useful for static code analysis

sys/flash_map/src/flash_map.c
Omitting the null check can cause null pointer dereference.
=> sys/flash_map: Check return values of hal_bsp_flash_dev() for null

hw/bus/drivers/spi_da1469x/src/spi_da1469x.c
Changes allow for 16-bit DMA transfers for spi. Note that the current hal and other configuration code do not allow the spi to be configured for 16 bits. However, if this is configured outside the provided API this code will allow for the proper size transfer.
I do think that we should add 16-bit spi transfers to the HAL (for all hal spi) but this is a larger undertaking and I think this change would be independent (and the same) without doing that which is why I am putting in this PR without adding 16-bit spi for HAL
=> hw/bus/drivers/spi_da1469x: Allow for 16-bit SPI transfers

hw/drivers/display/lcd_itf/itf_8080/src/itf_8080.c, hw/drivers/display/lcd_itf/itf_8080/syscfg.yml, hw/drivers/display/lcd_itf/pkg.yml, hw/drivers/display/lcd_itf/syscfg.yml
This adds support for 16 bit data bus for LCD.
Default implementation uses hal_gpio to send data.
=> lvgl: Add support for 16 bit 8080 MIPI DSI

hw/mcu/dialog/cmac/include/mcu/mcu.h, hw/mcu/dialog/cmac/src/system_cmac.c
This adds chip variant dedection early during startup. Previously this was done during RF initialization, but since CHIP_ID1 register resides in PD_SYS it could happen that domain was powered down already due to M33 going to sleep.
Reading on boot is safe since M33 starts CMAC and then waits for shm to initialize so PD_SYS is always available at CMAC startup.
=> hw/mcu/cmac: Add chip variant detection on startup

hw/drivers/ipc_nrf5340/src/ipc_nrf5340.c
Symptoms
Network core peripherals or CPU behave erratically after Force-OFF release.
Conditions
Network core is in System ON IDLE state when it is entering Force-OFF or the device enters System OFF mode.
Consequences
Network core peripherals and CPU are not reset. CPU does not restart from the reset vector, and peripherals can behave erratically.
This adds code suggested by Nordic Errata 161 when network core reset is released.
=> hw/ipc_nrf5340: Apply Errata 161 workaround

hw/bsp/hifive1/hifive1_debug.sh, hw/scripts/common.sh, hw/scripts/jlink.sh, hw/scripts/openocd.sh, hw/scripts/pyocd.sh, hw/scripts/stlink.sh, hw/scripts/stm32_programmer.sh
This adds gdb detection so if gdb-multiarch is installed and arm-none-eabi or some of the riscv versions are not available gdb-multiarch will be used.
=> hw/scripts: Add fallback to gdb-multiarch

hw/mcu/stm/stm32_common/src/hal_flash.c, hw/mcu/stm/stm32u5xx/syscfg.yml
STM32U5 devices require quad writes (128 bits).
64 bits writes result in error so write size is extended.
=> mcu/stm32u5: Fix flash write

hw/mcu/nordic/nrf52xxx/src/hal_spi.c
SPI clock settings allowed only specific number of values to be set. Requesting value not in predefined set resulted in SPI not being configured.
Other MCUs' HALs, when SPI frequency is specified try to set frequency that does not exceed requested one.
This approach allows to have common frequency value that applies to device that is connected to SPI for wider range of MCUs. For example MMC requires SPI to be in range of 100-400kHz during startup and MMC code have frequency set to 125kHz just because this value is supported by NRF52.
With this change NRF5x SPI frequency is set to value that does not exeed requested one. It should not affect existing code that must have exact value set to work at all.
Now it will be possible to specify 200kHz and HAL will setup value 125kHz it this is what …
=> mcu/nrf5x: Relax SPI baudrate restrictions

hw/mcu/nordic/nrf5340/src/hal_spi.c
SPI clock settings allowed only specific number of values to be set. Requesting value not in predefined set resulted in SPI not being configured.
Other MCUs' HALs, when SPI frequency is specified try to set frequency that does not exceed requested one.
This approach allows to have common frequency value that applies to device that is connected to SPI for wider range of MCUs.
With this change NRF5340 SPI frequency is set to value that does not exceed requested one. It should not affect existing code that must have exact value set to work at all.
=> mcu/nrf5340: Relax SPI baudrate restrictions

hw/drivers/mmc/include/mmc/mmc.h, hw/drivers/mmc/src/mmc.c
This PR:
- fixes CMD18 multiple block read where read control token and CRC were handled correctly only if single block was read
- adds code that switches to higher speed after initialization (was marked as TODO:)
=> hw/drivers/mmc: Fix Multiple Block Read CMD18

hw/mcu/stm/stm32_common/src/hal_flash.c, hw/mcu/stm/stm32h7xx/syscfg.yml
Flash min write size was incorrectly set to 1 while for most H7 MCUs it has to be 32 bytes.
HAL_FLASH_Program uses different arguments then the reset of MCU with non-linear flash sectors.
Write now respects minimum write size.
STM32H7 hal requires eraseInit.Banks field to be set.
=> mcu/stm32h7: Fix flash write/erase

fs/fcb/include/fcb/fcb.h, hw/drivers/flash/enc_flash/selftest/src/testcases/enc_flash_fcb.c
Component: Flash Circular Buffer
Change the type of sector_cnt and scratch_cnt from a uint8_t to a uint16_t, allowing for counts > 255.
=> Increase size of some `struct fcb` members

hw/bsp/black_vet6/src/hal_bsp.c, hw/bsp/hifive1/src/hal_bsp.c, hw/bsp/nucleo-h723zg/src/hal_bsp.c, hw/bsp/nucleo-l073rz/src/hal_bsp.c, hw/bsp/nucleo-u575zi-q/src/hal_bsp.c, hw/bsp/olimex-pic32-emz64/src/hal_bsp.c, hw/bsp/olimex-pic32-hmz144/src/hal_bsp.c, hw/bsp/pinetime/src/hal_bsp.c, hw/drivers/flash/spiflash/src/spiflash.c, hw/drivers/flash/spiflash/syscfg.yml
SPI mode for hardcoded to HAL_SPI_MODE3, most SPI flashes also support HAL_SPI_MODE0.
Now user can specify which mode to use.
=> hw/drivers/flash/spiflash: Make SPI mode configurable

libc/baselibc/include/stdlib.h, sys/config/src/config.c
CONF_FLOAT was defined as a type but not implemented. This change adds CONF_FLOAT.
=> sys/config: Add CONF_FLOAT

hw/mcu/dialog/da1469x/src/da1469x_prail.c
The code to enable DC/DC on CMAC was not updated to new transport and IPC driver.
=> hw/mcu/dialog: Fix DC/DC for CMAC

hw/mcu/nordic/nrf5340/src/system_nrf5340.c, hw/mcu/nordic/nrf5340_net/src/system_nrf5340_net.c, hw/mcu/nordic/nrf91xx/include/nrfx9160_config.h, hw/mcu/nordic/nrf91xx/src/nrf91_clock.c, hw/mcu/nordic/pkg.yml
This is latest nrfx 2.X version.
=> mcu/nrf5x: Update nrfx to version 2.11

.github/workflows/check_compliance.yml
RAT 0.16 will have support for SPDX but snapshots links are not permanent so for time being use 0.15.
=> ci: Use RAT 0.15 for compliance check

hw/mcu/stm/stm32_common/src/hal_spi.c
It seems that HAL_SPI_ERROR_FRE was defined is some previous versions of HAL for STMF1.
Now it's gone but register bit is still there and there is not Errata stating that bit should not be touched.
SPI block is shared among all STM products and all of them have this UDR bit that is mapped to HAL_SPI_ERROR_FRE in ST HAL.
Without this change HAL SPI will not build for STM32F1 devices.
=> stm32f1/spi: Add definition missing from HAL

sys/config/src/config.c
The check in conf_value_from_str for CONF_FLOAT is incorrect. FLT_MIN is not the smallest negative float; it is the smallest positive float. Removing the check for min/max value as it is not needed in this case.
=> sys/config: fix CONF_FLOAT

hw/bsp/pinetime/include/bsp/bsp.h
uint8_t was used without stdint.h being included.
=> bsp/pinetime: Add missing include file

hw/mcu/nordic/include/nrfx_glue.h, libc/baselibc/include/assert.h
While trying to build with arm-none-eabi-gcc version 12.3.1 and setting LIBC: nano, the compiler did not recognise static_assert.
=> Fix build error with arm gcc 12.3.1

hw/drivers/display/lcd_itf/include/lcd_itf.h, hw/drivers/display/lcd_itf/itf_8080/src/itf_8080.c, hw/drivers/display/lcd_itf/itf_lcd_da1469x/pkg.yml, hw/drivers/display/lcd_itf/itf_lcd_da1469x/src/itf_lcd_da1469x.c, hw/drivers/display/lcd_itf/itf_lcd_da1469x/syscfg.yml, hw/drivers/display/lcd_itf/itf_spi/src/itf_spi.c, hw/drivers/display/lvgl/default/lv_conf.h, hw/drivers/display/lvgl/src/mynewt_lvgl.c, hw/drivers/display/lvgl/syscfg.yml, hw/drivers/display/lvgl/tft/gc9a01/src/gc9a01.c, hw/drivers/display/lvgl/tft/ili9341/src/ili9341.c, hw/drivers/display/lvgl/tft/ili9486/src/ili9486.c, hw/drivers/display/lvgl/tft/st7735s/src/st7735s.c, hw/drivers/display/lvgl/tft/st7789/src/st7789.c
This adds several syscfg values that tweak LVGL build.
LV_DISP_DRAW_BUF_LINES (default 10) specifies buffer size in lines.
Increasing this number can reduce drawing time but uses more memory.
LV_DISP_DOUBLE_BUFFER - when set, allows display driver to draw
pixel asynchronously (with DMA). Currently no driver utilizes this.
LV_DISP_X_ALIGN/LV_DISP_Y_ALIGN - can specify minimum pixel alignment
required by display driver. Currently only DA1469X LCD driver requires
LV_DISP_X_ALIGN to be 1. Increasing this number forces LVGL to draw more
pixels that library needs.
LV_MEM_SIZE allows to reduce (or increase) memory used internally by LVGL.
Default value is 48kB but can now be change in syscfg.
LV_MEM_CUSTOM allows to use libc malloc/free/realloc instead of version
provided by LVGL.
Signed-off-by: …
=> lvgl: Display driver optimizations

hw/usb/tinyusb/cdc/pkg.yml, hw/usb/tinyusb/cdc_console/pkg.yml, hw/usb/tinyusb/da146xx/pkg.yml, hw/usb/tinyusb/dfu/pkg.yml, hw/usb/tinyusb/nrf53/pkg.yml, hw/usb/tinyusb/nrf5x/pkg.yml, hw/usb/tinyusb/pic32mz/pkg.yml, hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/stm32_fsdev/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32l0/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32wb55/pkg.yml, hw/usb/tinyusb/synopsys/pkg.yml, hw/usb/tinyusb/tinyusb_sdk/pkg.yml
With this change there is no need to add TinyUSB to project.yml
alternative to #3056
=> tinyusb: Add TinyUSB sdk package with repository

sys/log/full/src/log.c, sys/log/full/src/log_shell.c, sys/log/full/syscfg.yml
Adds a syscfg `LOG_SEQUENTIAL_IDX`. When enabled the global log index won't be incremented when adding logs of `LOG_TYPE_STREAM` which are not persisted (e.g. console logs). 
The global index is only useful for persisted logs, and if it is incremented for non-persisted logs there will be jumps in the log indexes of the persisted logs. This makes detection of missing logs a challenging task. By incrementing the global index only for persisted logs, it becomes sequentially increasing, which makes detection of missing/dropped logs trivial for upstream consumers of the logs.
This PR also adds a syscfg `LOG_SHELL_SHOW_INDEX` to enable displaying the log index in the 'log' shell command output.
=> sys/log: Add option to make the global log index increment sequentially

hw/drivers/display/lcd_itf/syscfg.yml, hw/drivers/display/lvgl/tft/gc9a01/src/gc9a01.c, hw/drivers/display/lvgl/tft/ili9341/src/ili9341.c, hw/drivers/display/lvgl/tft/ili9486/src/ili9486.c, hw/drivers/display/lvgl/tft/st7735s/src/st7735s.c, hw/drivers/display/lvgl/tft/st7789/src/st7789.c
This adds way to define active level of backlight pin that will be used during driver initialization.
=> lvgl: Add backlight pin active level

crypto/mbedtls/include/.gitignore
mbedtls is now build as external repo so this is no longer needed.
=> crypto/mbedtls: Remove not needed .gitignore

.github/workflows/check_compliance.yml
SPDX support is only available in unreleased RAT snapshot so for now use latest snapshots.
=> ci: Use latest RAT snapshots

hw/drivers/display/lcd_itf/include/lcd_itf.h, hw/drivers/display/lcd_itf/itf_8080/src/itf_8080.c, hw/drivers/display/lcd_itf/itf_lcd_da1469x/src/itf_lcd_da1469x.c, hw/drivers/display/lcd_itf/itf_spi/src/itf_spi.c
Function lcd_itf_write_color_data() had pixel pointer constant and in case of SPI when LV_COLOR_16_SWAP was set to 0 additional buffer in RAM was allocated for swapped bytes.
LVGL however does not touch memory after it passes it to interface so it is safe to swap bytes (if needed) in place.
Setting LV_COLOR_16_SWAP to 1 eliminates need for data swap but then LVGL internally uses some extra bit manipulation.
=> lvgl/itf: Swap colors in place

hw/drivers/display/lvgl/default/lv_conf.h, hw/drivers/display/lvgl/syscfg.yml
LVGL has support for logs.
This change allows to enable logs from mynewt syscfg.
- LV_USE_LOG - enables logs
- LV_LOG_LEVEL - allows to choose logging level
- LV_LOG_PRINTF - redirects logs to use printf (default for now,
can be change latter to use mynewt logging)
=> lvgl: Add logging settings to syscfg

kernel/os/src/os_dev.c
Function os_dev_init() is called in two places
First possibility is when device is created in
os_dev_create() AND g_os_started is not 0
This apply to devices that are created after main
function is called (including package defined syscfg functions).
Other place that calls os_dev_init is os_dev_initialize_all() This function calls all os_dev_init() functions for requested stage. When os_dev_initalize_all() is called only devices added by bsp (often delegated to mcu) are created. Keep in mind that since g_os_started is not set yet condition is not checked.
When mcuboot starts with sysinit() enabled it calls os_dev_initalize_all() twice then executes sysinit(). Any device created in sysinit() will not be initialized since g_os_started is not set.
This change stores device init stage number …
=> kernel/os: Update device initialization condition

.github/project.yml, .github/test_build_blinky.sh, .github/workflows/build_blinky.yml, .github/workflows/build_targets.yml, .github/workflows/newt_test_all.yml
This uses standard folder tree to build tests (where core is in
repos folder, and not as a top project folder).
=> ci: Build tests under standard project folder tree

.github/targets_linux/nordic_pca10028_boot/README, .github/targets_linux/nordic_pca10028_boot/pkg.yml, .github/targets_linux/nordic_pca10028_boot/syscfg.yml, .github/targets_linux/nordic_pca10028_boot/target.yml
It was accidentally moved to NimBLE CI.
=> ci: Restore bootloader target for nRF51

hw/bsp/nucleo-u575zi-q/src/hal_bsp.c
Registers names for I2C were incorrect resulting in build error when I2C was enabled.
=> hw/bsp/nucleo-u575zi-q: Fix I2C register names

hw/mcu/nordic/nrf51xxx/syscfg.yml, hw/mcu/nordic/nrf52xxx/syscfg.yml, hw/mcu/nordic/nrf5340/syscfg.yml, hw/mcu/nordic/nrf5340_net/syscfg.yml, hw/mcu/nordic/nrf91xx/syscfg.yml
This is typically specified by BSP and omitting to do so is an error.
=> mcu/nordic: Require LF clock source to be specified

.github/workflows/build_cc_target.yml
This will help make sure we build correctly with more GCC version.
=> ci: Add workflow for testing various GCC versions

hw/mcu/microchip/pic32mz/p32mz_app.ld
kseg1_program_mem and kseg0_program_mem point to same physical memory.
kseg1 is not cached while kseg0 is cached.
cache init was placed in cached segment which cold lead to crashes during restart.
=> hw/mcu/pic32: Put cache init code in non-cached space

hw/usb/tinyusb/cdc_console/pkg.yml, hw/usb/tinyusb/cdc_console/syscfg.yml
hw/usb/tinyusb: Fix sysinit levels so that tinyusb gets initialized
before console uses it
- Changing cdc_console sysinit to 502 adding a new syscfg
`CONSOLE_USB_CDC_SYSINIT_STAGE` for CDC USB console
and use that instead
- Also add restrictions so that usbd is never inited after
cdc_console
=> hw/usb/tinyusb: usb cdc console and tinyusb library sysinit before console uses it

hw/usb/tinyusb/dfu/src/dfu.c
Part of the code and data was included only if
USBD_DFU_RESET_AFTER_DOWNLOAD was set.
While package init function used those functions and data regardless of syscfg value.
package init function is not called from sysinit when USBD_DFU_RESET_AFTER_DOWNLOAD is not set but code inside is still there.
Now all code is there and if functionality is not used package init function will not be called from sysinit.
=> tinyusb/dfu: Fix build when auto confirm is off

hw/mcu/stm/stm32_common/src/hal_os_tick.c
This fixes RTC based hal_os_tick.
- Fixed build for STM32U5
- Fixed crash at midnight caused by assert due to negative time increment
=> stm32 rtc fixes

hw/mcu/stm/stm32h7xx/src/clock_stm32h7xx.c
This remove function call to HAL_PWREx_EnableOverDrive() that is only available in F4 and F7 and not H7.
=> hw/mcu/stm32h7: Remove STM32F4/7 specific code

libc/nano/src/start.c
When move from main to mynewt_main was made,
start.c for newlib-nano was omitted.
Now builds with nano libc also expect mynewt_main
=> libc/nano: Switch to mynewt_main in start.c

kernel/os/include/os/os_fault.h, kernel/os/src/arch/cortex_m33/os_fault.c, kernel/os/syscfg.yml
Added a MYNEWT_VAL named OS_DEFAULT_IRQ_CB which, when enabled, will call a user-defined callback as the first function called in os_default_irq(). This will allow users to define custom functionality when a default irq occurs.
=> kernel/os: Add default irq callback

hw/mcu/nordic/nrf52xxx/include/nrfx52810_config.h, hw/mcu/nordic/nrf52xxx/include/nrfx52811_config.h, hw/mcu/nordic/nrf52xxx/syscfg.yml
They don't have timer 3 or instruction cache
Tested on a Seeed Xiao nRF52840 board (which worked fine) and a custom nRF52811 board (which is getting there.  It's no longer having timer or instruction cache issues at least!)
=> mcu/nordic: Disable features not on nRF52810 & 11

hw/mcu/stm/stm32_common/src/hal_i2c.c, hw/mcu/stm/stm32f0xx/include/mcu/stm32f0xx_mynewt_hal.h, hw/mcu/stm/stm32f3xx/include/mcu/stm32f3xx_mynewt_hal.h, hw/mcu/stm/stm32f7xx/include/mcu/stm32f7xx_mynewt_hal.h, hw/mcu/stm/stm32h7xx/include/mcu/stm32h7xx_mynewt_hal.h, hw/mcu/stm/stm32l0xx/include/mcu/stm32l0xx_mynewt_hal.h, hw/mcu/stm/stm32l4xx/include/mcu/stm32l4xx_mynewt_hal.h, hw/mcu/stm/stm32u5xx/include/mcu/stm32u5xx_mynewt_hal.h, hw/mcu/stm/stm32wbxx/include/mcu/stm32wbxx_mynewt_hal.h
STM32 F1,F4,L1 do have ClockSpeed filed in I2C initialization API, so it easy to specify requested clock speed for I2C. For all other devices ST HAL does not provide such field and expect that TIMINGR register value is precomputed. This value is specified in each BSP and is likely incorrect for some of them.
This change introduces hic_speed to MCUs that has timing register and function that computes timing register base on requested speed and system clock.
If timing register is specified in settings it is still being used to to configure I2C. If timing register setting is 0 hic_speed is used.
=> mcu/stm32: Calculate I2C timing register

hw/usb/tinyusb/tinyusb_sdk/pkg.yml
TinyUSB is not a part of mynewt-core and may occasionally has code that produces unsued-varialble warning that is escalated in mynewt to error.
This disable warning that may cause builds to fail.
=> tinyusb: Disable unused variable warning

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
Condition to populate disk presented over USB checked if last SCSI command was TEST_UNIT_READY.
This only worked if TEST_UNIT_READY was send twice one after the other. It seems to work on Linux but for Windows it did not happen very often.
Now disk data is populated (init_disk_data()) on first TEST_UNIT_READY request when medium state is set to MEDIUM_REALOAD.
=> tinyusb/msc_fat_view: Fix directory population condition

libc/baselibc/include/stdio.h, libc/baselibc/src/mynewt.c
This tries to fix error:
Linking review/bin/targets/nordic_pca10056-auracast_usb/app/@apache-mynewt-nimble/apps/auracast_usb/auracast_usb.elf Error: Arm GNU Toolchain arm-none-eabi/13.2 Rel1/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/ld.exe: Arm GNU Toolchain arm-none-eabi/13.2 Rel1/bin/../lib/gcc/arm-none- eabi/13.2.1/thumb/v7e-m/nofp\libg.a(libc_a-fflush.o): in function `fflush': fflush.c:(.text.fflush+0x0): multiple definition of `fflush'; review/bin/targets/nordic_pca10056-auracast_usb/app/@apache-mynewt-core/libc/baselibc/@apache-mynewt-core_libc_baselibc.a(mynewt.o):review/repos/apache-mynewt-core/libc/baselibc/src/mynewt.c:54: first defined here
fflush is not used anywhere in the code but for some reason gcc 12 and 13 complains about duplicate. When baselibc …
=> baselibc: Fix fflush duplicate error

hw/mcu/nordic/nrf51xxx/src/hal_spi.c, hw/mcu/nordic/nrf52xxx/src/hal_spi.c, hw/mcu/nordic/nrf5340/src/hal_spi.c, hw/mcu/nordic/nrf5340_net/src/hal_spi.c, hw/mcu/nordic/nrf91xx/src/hal_spi.c
When a non-blocking SPI transfer has finished, our `spi->spi_xfr_flag` and the hardware interrupt flag are now reset before the `spi->txrx_cb_func` is run.  This allows the callback to start a new SPI transfer.
I've tested the nRF52 changes and they're fine.  I'm making the bold assumption that the other nRFs work the same.
=> mcu/nordic: Set flags before running SPI callback

hw/drivers/sensors/lis2dh12/syscfg.yml
Statement was not effective, it is `restrictions` not `restriction`
=> hw/drivers: fix LIS2DH12_SHELL_DEV_NAME syscfg restrictions

hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/shell/pkg.yml, hw/usb/tinyusb/shell/src/tinyusb_cli.c, hw/usb/tinyusb/syscfg.yml
So far TinyUSB stack was starting during system init stage. Now it is possible for the application to start it at later time by manually call `tinyusb_start()` function.
Additionally shell commands are added to test functionality:
```
/usb start
/usb stop
```
=> tinyusb: Make automatic start of USB optional

hw/drivers/mmc/include/mmc/mmc.h, hw/drivers/mmc/src/mmc.c, hw/drivers/mmc/syscfg.yml
Bus driver support is needed for nrf53 but it
can be used with any MCU that has SPI driver
support (in contrast to just SPI HAL)
=> drivers/mmc: Add support for bus driver

.github/workflows/build_cc_target.yml
This will test code with latest version of ARM GCC.
=> ci: Add GCC 13.2 to compilers test build workflow

sys/console/full/history_ram/src/history_ram.c
Console history was meant to be stored in section pointed by bssnz_t This section is usually defined in bsp.h that was not included. Section was put in normal ram and console history was not able to persist across reboots as was the intentions.
Now bsp.h is included and console history can be accessed after reboot if bsp defines section that is not cleared during startup.
=> console: Fix console history placement

hw/mcu/nordic/nrf51xxx/src/hal_watchdog.c, hw/mcu/nordic/nrf52xxx/src/hal_watchdog.c, hw/mcu/nordic/nrf5340/src/hal_watchdog.c, hw/mcu/nordic/nrf5340_net/src/hal_watchdog.c, hw/mcu/nordic/nrf91xx/src/hal_watchdog.c
Watchdog interrupt priority was set to minimal value. It seems that when Watchdog interrupt is triggered there is no much that can be done and the system reboot is imminent, so there is not point in doing anything else while watchdog interrupt handler can indicate problem.
If some other interrupt had problem that resulted in busy loop watchdog interrupt would never fire due to lowest priority set.
This increases watchdog interrupt priority to maximum for Nordic MCU's.
=> mcu/nrf: Increase watchdog interrupt priority

.github/workflows/check_compliance.yml
RAT 0.16.1 was released so we no longer need to use snapshots for SPDX support.
=> ci: Use latest RAT release

hw/cmsis-core/pkg.yml
=> hw/cmsis-core: Update CMSIS to 5.4.0 release

util/crc/include/crc/adler32.h, util/crc/include/crc/crc32.h, util/crc/src/adler32.c, util/crc/src/crc32.c
This adds two simple implementations of standard CRC32 and Adler32 algorithms that can be used on block of data and in streams where result from previous call can be used as inptu to continue computation.
No prepcomputed table are used for now.
=> util/crc: Add crc32 and Adler32 algorithms

hw/usb/tinyusb/msc_fat_view/pkg.yml, hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
For now msc_fat_view provided several FAT root entries that could be enabled in syscfg.
There is function to add new root dir entries msc_fat_view_add_dir_entry(), however even if user added custom entry it would not show up since all entries were refreshed when during test_unit_ready by call to init_disk_data that silently dropped non standard entries and created root from scratch.
Now root population is divided in to two functions. init_disk_data() that provides standard enties is called when packaged is initiated and update_disk_data() is called when actual sectors for host are generated and this function includes user provided entries.
With this change core dump entries have to be initiated after msc_fat_view_pkg_init and any time before tinyusb_start
=> tinyusb/msc_fat_view: Fix custom entries support

sys/log/modlog/include/modlog/modlog.h, sys/log/modlog/src/modlog.c
This adds MODLOG_HEXDUMP macros which allow to write specified number of bytes' values in a string format into the log modules.
=> sys/log/modlog: Add modlog hexdump

boot/startup/include/mynewt_config.ld.h, boot/startup/mynewt_cortex_m0.ld, boot/startup/mynewt_cortex_m33.ld, boot/startup/mynewt_cortex_m4.ld, boot/startup/mynewt_cortex_m7.ld, boot/startup/pkg.yml, boot/startup/scripts/generate_linker_script.sh, boot/startup/src/arch/cortex_m0/cortex_m0_startup.s, boot/startup/src/arch/cortex_m33/cortex_m33_startup.s, boot/startup/src/arch/cortex_m4/cortex_m4_startup.s, boot/startup/src/arch/cortex_m7/cortex_m7_startup.s, boot/startup/src/interrupts.c, boot/startup/syscfg.yml
This is step to make common linker script for mynewt.
So far linker scripts were split in two parts one that usually was in MCU with all the rules for sections.
Second linker script defined memory regions (RAM/FLASH). There were separate memory region scripts
for bootloader.
This change:
- get rids of mcu/bsp linker scripts that differ from MCU to MCU
- makes flash area size consistent with flash size in linker script
- elf files contain stub image header (if needed) that makes it possible to write to flash by IDE without creating actual image
- Vector table is by startup code and does not need to be done by NVIC_Relocate that depends on NVIC_NUM_VECTORS
=> Add common startup for cortex mcu's

boot/startup/src/arch/cortex_m33/cortex_m33_startup.s, boot/startup/src/arch/cortex_m4/cortex_m4_startup.s, boot/startup/src/arch/cortex_m7/cortex_m7_startup.s
Wrong condition was used for bss clearing loop and for .data copying loop.
First 4 bytes of each region was not copied/zeroed.
Now condition is >= instead of >
=> boot/startup: Fix .bss and .data initialization

hw/bus/drivers/spi_stm32/pkg.yml, hw/bus/drivers/spi_stm32/stm32g0xx/include/spidmacfg.h, hw/bus/drivers/spi_stm32/stm32g0xx/pkg.yml, hw/bus/drivers/spi_stm32/stm32g0xx/src/spidmacfg.c, hw/bus/drivers/spi_stm32/stm32g0xx/syscfg.yml
Bus driver for STM32 requires DMA configuration that went missing when STM32G0 support was added
=> hw/bus/spi_stm32: Add DMA configuration for STM32G0

repository.yml
There is no point in using MCUboot from main branch even on core master. Core releases are depending on latest stable at point of release so we move 'backward' anyway. It is better to test on with what will likely be used for release.
=> Depend on latest MCUboot stable release on master branch

hw/scripts/download.sh
There was typo in script error message.
=> hw/scripts: Fix typo downloader script

hw/scripts/download.sh
This improves user experience when seting up project.
=> hw/scripts: Verify if programmer tool exist before flashing

boot/split/src/split.c, boot/split/syscfg.yml
When there is no config store defined there is little need to have config support in boot/split.
When config is NOT present even if boot/split is present final code size can be significantly reduced that is important when bootloader has functionality to confirm images:
```
newt size nucleo-g491re-boot
Size of Application Image: app
BOOT   SLOT0     RAM
66       0     490 *fill*
79       0      38 @apache-mynewt-core_boot_split.a
586       0       0 @apache-mynewt-core_boot_startup.a
1172       0       4 @apache-mynewt-core_crypto_mbedtls.a
132       0       0 @apache-mynewt-core_hw_bsp_nucleo-g491re.a
398       0       0 @apache-mynewt-core_hw_drivers_uart_uart_hal.a
672       0      13 @apache-mynewt-core_hw_hal.a
3074       0     160 @apache-mynewt-core_hw_mcu_stm_stm32_common.a
4090 …
```
=> boot/split: Make config support optional

hw/mcu/nordic/nrf51xxx/src/hal_system.c
When XTAL_32768/XTAL_RC/XTAL_32768_SYNTH were deprecated and MCU_LFCLK_SOURCE was chosen to be used instead, code that actually enabled clocks still depended on syscfg values that were never set.
This only changes preprocessor conditions to use MCU_LFCLK_SEOURCE.
=> mcu/nrf51: Fix low frequency clock selection

hw/mcu/microchip/pic32mz/pkg.yml
Dependency to hal_uart was only added when one or more UART_x was enabled. pic32mz_periph.c uses normal if statement to exclude unused UART's so package dependency is needed event though no UART is used.
=> mcu/pic32mz: Fix build when no UART is enabled

hw/mcu/microchip/pic32mz/p32mz_boot.ld
By mistake sdata2 section was put in kseg0_program_mem. It should be left alone with no redirection to region xc32 linker will put it in correct place.
memset_func put in this place resulted in crash during boot since mbedtls was was updated.
=> mcu/pic32: Fix memset_func placement

hw/mcu/microchip/pic32mz/p32mz_app.ld, hw/mcu/microchip/pic32mz/p32mz_boot.ld, hw/mcu/microchip/pic32mz/src/hal_gpio.c, hw/mcu/microchip/pic32mz/src/pic32mz_periph.c
- I2C_4 was incorrectly initialized
- added missing hal_gpio_deinit() function
- added support for link_tables.ld.h
- fix of .sdata2 section placement
=> Few small pic32 fixes

hw/usb/tinyusb/src/tinyusb.c
usbd_stack could be placed at memory with wrong alignment. For pic32 with FPU enabled that results in exceptions when code tries to store/restore FPU registers.
Now OS_TASK_STACK_DEFINE is used that forces correct alignment.
=> tinusb: Fix usbd_stack memory alignment

hw/mcu/microchip/pic32mz/p32mz_app.ld, hw/mcu/microchip/pic32mz/pkg.yml, kernel/os/src/arch/pic32/startup/crt0.S
This adds image_header section to elf so it can be flashed with IDE
This also adds minimal boot code that allows to have self sufficient elf.
=> pic32 no bootloader fixes

sys/log/full/src/log.c
- Log index was incrementing twice on a reboot, once when the log entry gets prepared to append and once when the log is registered. This fixes it by not-incrementing when the log gets registered.
=> sys/log: Fix log index after reboot

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c, hw/usb/tinyusb/msc_fat_view/syscfg.yml
Generated README.TXT file contains line
App version: 1.2.1.2
This line is generated from image version from SLOT0. This line uses fprintf and can increase code size if printf-like functions were not otherwise used.
Now syscfg value MSC_FAT_VIEW_DEFAULT_README_VERSION can disable line with version possibly reducing code size.
Additionally default application name used in README.TXT is taken from APP_NAME syscfg value generated by newt tool.
=> tinyusb/msc_fat_view: Make application version optional in readme

crypto/mbedtls/pkg.yml
New tagged version has changes needed for pic32 builds.
=> crypto/mbedtls: Upgrade to v2.28.8

hw/bsp/nordic_pca10056/syscfg.yml
Set GPIO_AS_PIN_RESET to 1 in syscfg.
=> bsp/pca10056: Support reset button by default

hw/scripts/jlink.sh, hw/scripts/pyocd.sh, hw/scripts/stlink.sh, hw/scripts/stm32_programmer.sh
- debug scripts for Windows does not requires `cmd start` normal mingw/msys work just fine so separate execution paths are now removed for jlink st-util and openocd
- stm32_programmer.sh now have functionality to start `ST-LINK_gdbserver` so it can be used for debugging when STLINK debugger is present and other open source software is not up to date yet.
=> Update debug scripts for windows

compiler/sim/compiler.yml, crypto/mbedtls/pkg.yml, encoding/json/src/json_encode.c, fs/nffs/selftest/src/nffs_test_debug.c, hw/mcu/native/src/hal_uart.c, kernel/os/include/os/os_mempool.h, kernel/os/selftest/src/mbuf_test.c, kernel/os/selftest/src/mbuf_test.h, kernel/os/selftest/src/testcases/ob_mbuf_test_adj.c, kernel/os/selftest/src/testcases/ob_mbuf_test_pullup.c, kernel/os/selftest/src/testcases/os_mbuf_test_extend.c, kernel/os/selftest/src/testcases/os_mbuf_test_pack_chains.c, kernel/os/src/arch/sim/os_arch.c, kernel/os/src/arch/sim/os_arch_stack_frame.s, kernel/os/src/os_callout.c, kernel/os/src/os_eventq.c, kernel/os/src/os_mbuf.c, kernel/os/src/os_mempool.c, kernel/os/src/os_mutex.c, kernel/os/src/os_sem.c, kernel/sim/include/sim/sim.h, libc/baselibc/pkg.yml, libc/baselibc/src/sprintf.c, libc/baselibc/src/tinyprintf.c, libc/baselibc/src/vsprintf.c, net/oic/src/messaging/coap/coap.c, sys/config/src/config.c, sys/log/full/src/log_cbmem.c, sys/log/full/src/log_console.c
This also requires changes from repositories apache-mynewt-nimble, apache-mynewt-mcumgr and mcuboot, which I commited.
=> Add native target 64-bit support

.github/test_build_bootloader.sh
After the merge of https://github.com/apache/mynewt-newt/commit/a798fcc687dd81857de7bb92e77711c9a74f0692
newt passes to the linker the same .a files as before, but in different order and it causes linker error. It means that previously this test was passing just by accident.
It does not make sense to build bootloader for native target anyway, so this test will simply be skipped.
=> ci: Add native to ignored BSPs in bootloader build test

boot/startup/src/interrupts.c
When generating isr vector table INT_VECTOR_UNUSED ignored its argument and used 0 instead.
Now this macro may be used to store some values in vector table (needed for STM32F1 where table ends
with some magic value).
=> boot/startup: Fix unused vector macro

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
This add support for single slot build.
BSP can have just one flash area slot
in this case only bootlaoder can have support
for updating application.
=> tinyusb/msc_fat_view: Add single slot support

sys/flash_map/src/flash_map.c
When bootloader alone can write new image to device (no swap needed) there is no need to define fake
flash area anymore.
This allows build when there is no definition for secondary swap image flash area.
=> sys/flash_map: Allow build with 1 flash image area

hw/bsp/nucleo-f767zi/pkg.yml, hw/bsp/nucleo-h723zg/pkg.yml
Two boards have MCU with double precision FPU.
This simply enables double precision instruction generation for those two boards.
=> hw/bsp: Enable double precision for STM32F767 and STM32H723

repository.yml
0.0.1 version was used for historical reasons and is no longer necessary. It was also causing issue with newt info command. When commit with release tag happens to be the HEAD commit of master branch, newt info would print version 0.0.1 instead of release version from tag.
=> repository.yml: Remove 0.0.1 version

hw/mcu/stm/stm32g4xx/src/system_stm32g4xx.c
system_stm32g4xx.c was including mcu/cmsis_nvic.h
while it should include stm32g4xx_hal_conf.h
This is required if external oscillator frequency
(defined in stm32g4xx_hal_conf.h) is not 24MHz
=> hw/mcu/stm32g4: Include hal config

hw/mcu/stm/stm32h7xx/include/mcu/stm32_hal.h
STM32_HAL_FLASH_CLEAR_ERRORS was copied from from F7 stm32h7 does not have OPERR field in CCR register so it is now removed.
=> mcu/stm32h7xx: Fix STM32_HAL_FLASH_CLEAR_ERRORS macro

hw/usb/tinyusb/dfu/syscfg.yml, hw/usb/tinyusb/msc_fat_view/syscfg.yml, sys/log/common/syscfg.yml, sys/log/full/src/log.c, sys/log/full/src/log_console.c, sys/log/full/syscfg.yml
This adds alternative way of printing mod log logs.
This change requires https://github.com/apache/mynewt-newt/pull/551
New syscfg values that can be use to configure console printing
```yml
LOG_CONSOLE_PRETTY: 1
LOG_CONSOLE_PRETTY_WITH_COLORS: 1
LOG_CONSOLE_PRETTY_WITH_TIMESTAMP: 0
```
Old way of showing mod log logs:
New way:
=> console log pretty

sys/config/src/config.c, sys/config/syscfg.yml
Adding CONF_FLOAT support could increase code size significantly if floating point are not used otherwise.
This makes support optional (enabled by default when HARDFLOAT is present).
=> sys/config: Make floating point support optional

libc/baselibc/src/tinyprintf.c
When commint "Add va_list pointer compiling error workaround" was introduced path for FLOAT_USER was not updated as all other places that use va.
It result in va and va_to_pass used if formating string contains %f and other like "%f %s %s"
This can result in wrong argument selection.
=> libc/baselibc: Fix floating point argument access

util/coremark/repo/include/core_portme.h
Coremark uses float numbers for printing only.
Now default value HAS_FLOAT used FLOAT_USER that tells tinyprintf to have support for %f instead of checking if MCU has FPU.
=> coremark: User FLOAT_USER instead of HARDFLOAT

hw/bsp/nucleo-h723zg/src/hal_bsp.c, hw/mcu/stm/stm32_common/src/hal_flash.c, hw/mcu/stm/stm32h7xx/src/hal_flash.c
STM32H7 actually has liner flash with sectors of 128kB. There is no need for stm32_flash_sectors table in BSP.
Additionally non-linear version that was used so far would not compile for some H7 chips that have different FLASH CR register and where FLASH_VOLATEG_RANGE_3 is not defined.
Liner sector variant was chosen when FLASH_PAGE_SIZE was defined. While H7 and H5 don't have this definition they do have FLASH_SECTOR_SIZE and when this definition is present FLASH_IS_LINEAR is also set to 1
=> hw/mcu/stm32h7: Use linear sector flash driver

hw/bsp/arduino_primo_nrf52/bsp.yml, hw/bsp/arduino_zero/bsp.yml, hw/bsp/ble400/bsp.yml, hw/bsp/bluepill/bsp.yml, hw/bsp/bmd200/bsp.yml, hw/bsp/calliope_mini/bsp.yml, hw/bsp/dialog_cmac/bsp.yml, hw/bsp/dialog_da14695-dk-usb/bsp.yml, hw/bsp/dialog_da1469x-dk-pro/bsp.yml, hw/bsp/dwm1001-dev/bsp.yml, hw/bsp/embarc_emsk/bsp.yml, hw/bsp/fanstel-ev-bt840/bsp.yml, hw/bsp/native-armv7/bsp.yml, hw/bsp/native-mips/bsp.yml, hw/bsp/native/bsp.yml, hw/bsp/nordic_pca10095/bsp.yml, hw/bsp/nordic_pca10095_net/bsp.yml, hw/bsp/nrf51-arduino_101/bsp.yml, hw/bsp/nrf51-blenano/bsp.yml, hw/bsp/nucleo-l073rz/bsp.yml, hw/bsp/pinetime/bsp.yml, hw/bsp/puckjs/bsp.yml, hw/bsp/reel_board/bsp.yml, hw/bsp/telee02/bsp.yml, hw/bsp/usbmkw41z/bsp.yml, hw/bsp/vbluno51/bsp.yml, hw/bsp/vbluno52/bsp.yml
Adds BSP information required for building site documentation, e.g. name, maker, url.
=> hw/bsp: add missing metadata for multiple BSPs

sys/config/src/config.c
When CONFIG_FLOAT_SUPPORT was added ony conf_value_from_str() was changed, not also conf_str_from_value() has conditional compilation code.
=> sys/config: Fix floating point support

.github/check_license.py, .github/workflows/check_compliance.yml, .rat-excludes, LICENSE
The workflow ensures that each entry in 'rat-excludes' and 'LICENSE' files refers to actual (existing) file in the repository.
=> ci: Add checks for RAT exclusions and LICENSE file

docs/os/core_os/callout/callout.rst
Removes deprecated part of API from the documentation entry.
=> docs/os/core_os/callout: Update docs

boot/split/syscfg.yml
For certain configurations SPLIT_CONFIG_SUPPORT was double defined and second definition was constant because syscfg.defs section was used instead of syscfg.vals.
So when CONFIG_xxx was set to 1 for NFFS/LITTLEFS/CFB/FCB2 SPLIT_CONFIG_SUPPORT could not be disabled
=> boot/split: Fix SPLIT_CONFIG_SUPPORT initialization

sys/config/include/config/config.h, sys/config/src/config.c, sys/config/src/config_cli.c
While every config entry could specify export function there was no easy way to call those functions.
Then only way to export config was to use shell command config dump
Now new function conf_export takes allows to export configuration and conf_dump_running just uses it so functionality is preserved.
=> sys/config: Add conf_export function

hw/usb/tinyusb/msc_fat_view/include/msc_fat_view/msc_fat_view.h, hw/usb/tinyusb/msc_fat_view/pkg.yml, hw/usb/tinyusb/msc_fat_view/src/entry_huge_file.c, hw/usb/tinyusb/msc_fat_view/src/entry_mynewt_htm.c, hw/usb/tinyusb/msc_fat_view/src/entry_readme.c, hw/usb/tinyusb/msc_fat_view/src/entry_slot0.c, hw/usb/tinyusb/msc_fat_view/src/entry_slot0_hex.c, hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c
This change extract several FAT root entries definitions to separate files so it's easier to see how to make custom entries.
This feature utilized newt tool features:
- link time tables (used for root dir entries)
- pkg.whole_archive switch that forces to search whole archive
- pkg.source_files (now package files are selected separately)
=> tinyusb/msc_fat_view: Use link_tables for root entries

hw/mcu/dialog/da1469x/src/hal_i2c.c
Adds 1MHz i2c speed to the i2c hal. The 1MHz speed requires high speed mode on the chip. In order for this to work it appears that the RESTART_EN bit has to be set in the control register or a tx abort condition occurs (bit 8 in tx abort source reg).
I tried to find some decent documentation on enabling high-speed mode for the da1469x. I also looked at some SDK versions that I had and I did not see that this bit was being set. When I tried simply setting the speed to 1MHz I was seeing this abort condition and read the chip doc and it appears that the RESTART_EN bit needs to be set for high-speed mode to work. Tested it with a da1469x equivalent chip and another chip that works with 1MHz i2c and things seem ok.
=> hw/mcu/dialog: Add 1MHz high-speed mode to hal i2c

hw/mcu/stm/stm32l0xx/src/hal_reset_cause.c
Often when device is powered up Reset pin is also activated. This cause power on never to be reported in favor of reset pin. Now Power On has highest priority.
Independent watchdog that is actually used in mynewt was not reported at all as reset reason. Only Windowed watchdog would be reported but is not used in mynwet-core.
This adds flag check so Watchdog reset can be detected.
=> stm32/hal_reset: Fix reported reset reason

hw/mcu/stm/stm32_common/src/hal_watchdog.c
All STM32 devices use LSI for watchdog functionality. LSI frequency varies between MCUs and it's approximation is define by LSI_VALUE in stm32xxx_hal_conf.h.
Code was assuming 32768 which is ok for devices that have LSI rate at 30kHz.
Some device has 37kHz others 40kHz it those cases calculated time could be too much off resulting in reset by watchdog.
Now code uses LSI_VALUE adding 10% to avoid cases when LSI runs faster then nominal.
=> stm32/hal_watchdog: Fix timeout calculations

hw/mcu/stm/stm32_common/src/hal_os_tick.c
STM32H7 HAL has __HAL_RCC_RTC_CLK_ENABLE macro for turning on RTC clock.
Some other MCUs also have this and for historical reasons have __HAL_RCC_RTCAPB_CLK_ENABLE that is an alias. Other only have __HAL_RCC_RTCAPB_CLK_ENABLE.
This uses __HAL_RCC_RTC_CLK_ENABLE() if defined to enable RTC clock in RCC.
=> stm32/hal: Fix STM32H7 with RTC as system tick

hw/mcu/stm/stm32l0xx/src/clock_stm32l0xx.c
Voltage scaling setting was done with PWR peripheral clock turned off which does not change anything.
=> mcu/stm32l0: Fix voltage scaling configuration

sys/config/src/config_fcb.c
If there are a lot of config variables, a watchdog can be triggered by the multiple `conf_fcb_var_read`s.
=> sys/config: Add watchdog tickle before each conf_fcb_var_read

hw/drivers/pwm/pwm_da1469x/src/pwm_da1469x.c
Read the current timer state (timer control reg) and preserve its running state when setting frequency. The only bits that should be set in the control register are the bits to enable the timer in the proper mode and enable the clock.
The rational behind this change is that some users may want to be able to change the frequency "on the fly" without having to diable pwm, change frequency and then re-enable pwm. I do realize that with this chip if you change frequency the duty cycle changes so changing frequency on the fly also changes the duty cycle but this was always the case.
Note that this should not change the previous functionality (other than adding some extra code to read the control register and mask out the SYS_CLK_EN bit. This change could have been done using a syscfg value to …
=> pwm/pwm_da1469x: Preserve timer state on frequency change.

hw/scripts/download.sh
When using Windows, check_downloader should look for JLink.exe instead of JLinkExe.
=> hw/scripts: set JLink executable based on operating system

boot/startup/mynewt_cortex_m0.ld, boot/startup/mynewt_cortex_m3.ld, boot/startup/mynewt_cortex_m33.ld, boot/startup/mynewt_cortex_m4.ld, boot/startup/mynewt_cortex_m7.ld
Filter .text* was before .text_ram* resulting in code intended for ram to be placed in normal flash.
Now .text.* is used for flash destination
=> boot/startup: Fix linker script filter for code in RAM

hw/mcu/stm/stm32f1xx/src/rtc_tick_stm32f1xx.c
When RTC (STM32F1 specific only) was used as os tick source. If OS requested longer tickles time RTC alarm was set to some time in the future.
After WFI finished RTC periodic tick interrupt was not enabled. If then some task took more time and periodically checked time, time would never advance due to RTC tick interrupt being disabled.
Time would advance only in idle task.
Now normal tick is working all the time unless there is nothing to do and after WFI finishes tick is enabled again.
=> stm32f1/rtc_tick: Fix tick interrupt generation

util/coremark/src/coremark_shell.c
This simply tickle watchdog before and after running coremark to prevent accidental reboot during command execution if watchdog was enabled.
=> apps/coremark: Tickle watchdog in coremark shell command

hw/mcu/stm/stm32_common/src/hal_nvreg.c
Writing to backup registers requires enabling BPK_CLK. For read it does not seem to be needed.
=> mcu/stm32: Fix hal_nvreg_write for STM32F1

hw/drivers/i2s/include/i2s/i2s_stream.h, hw/drivers/i2s/src/i2s_stream.c, util/stream/include/stream/stream.h, util/stream/src/stream.c
This extends in_stream and out_stream to provide pumping
functions
Additionally stream_pump() function is added to allow easy
pumping data between streams.
=> util/stream: Add pumping functions

hw/mcu/stm/stm32_common/src/hal_timer.c, hw/mcu/stm/stm32_common/syscfg.yml
Code allows to disable hal timer after it was running for some time (number over overflows) and it was not used for anything.
This can reduce power consumption without sacrificing usability. This can be useful for cputimer that is required but not used extensively.
=> stm32/hal_timer: Improve timer power consumption

hw/mcu/stm/stm32f1xx/src/rtc_tick_stm32f1xx.c
When tick was provided by RTC instead of SysTick (default) and MCUboot used SysTick during boot, SysTick was never turned off and was running in application code.
This resulted in two interrupts advancing mynewt OS tick so clock was running too fast.
Now os_tick_init() from RTC code disables SysTick that could be started in bootloader
=> hw/mcu/stm32f1: Disable SysTick when RTC is selected as tick source

hw/bus/drivers/spi_stm32/src/spi_stm32.c
While there were already some stats added to the driver they were never used.
Additionally STM32G0 configuration is fixed, there was errors for alternate function
mapping and clock used for SPI1
=> STM32 SPI drive stats

.github/check_style.py, uncrustify.awk
Uncrustify removes leading spaces from STATS.
This simple awk scrip is executed after uncrustify inserts spaces when expected
=> stylecheck: Add uncrastify exception for STATS

hw/usb/tinyusb/msc_fat_view/syscfg.yml
When update handler for writing images to flash
was moved to separate file pkg.yml was changed
to have update_handler.c included conditionally
but syscfg definition was not commited
This fixes the problem and updates can be
used again
=> tinyusb/msc_fat_view: Fix update handler

kernel/os/include/os/os_mbuf.h, kernel/os/src/os_mbuf.c
Adds missing documentation for macros and structures.
Updates existing documentation entries for clarity and completeness.
Ensures consistency in function parameter names.
=>  kernel/os_mbuf: Update doxygen comments in the header file 

hw/usb/tinyusb/cdc_console/syscfg.yml
`syscfg.defs:` section was added twice and now text is rearranged
=> tinyusb/cdc_console: Fix syscfg.yml doubled section

.github/check_style.py
nimble repository uses same check_style.py but calls it from different location resulting in missing
uncrasitfy.awk script
This explicitly sets path to awk script so it is found always regardless of how check_style.py was executd
=> ci: check_style: Fix awk filter for nimble

kernel/os/include/os/os_mutex.h
Adds missing documentation for macros and structures.
=>  kernel/os_mutex: Update doxygen comments in the header file

hw/mcu/stm/stm32_common/src/hal_flash.c
Code could corrupt stack when writing to flash that requires write of size greater then 1.
memset function used for filling buffer so writes have correct number of bytes incorrectly cast buffer to (uint32_t *) and then added number of bytes resulting in possible write to unintended stack memory.
=> stm32: Fix flash write

fs/fcb/src/fcb.c, fs/fcb/src/fcb_append.c, fs/fcb/src/fcb_getnext.c, fs/fcb/src/fcb_rotate.c, fs/fcb2/src/fcb_getnext.c, sys/log/full/src/log_fcb.c, sys/log/full/src/log_fcb2.c
Changes to accommodate flash with bigger alignment restrictions (STM32H7, STM32U5)
- Now log_fcb and log_fcb will work with flashes with write alignment restriction up to 32 bytes (it was 8)
- fcb now takes into account write alignment restriction that was previously ignored in few places
- fcb2 one additional place respect write alignment restrictions
=> Fix fcb and log_fcb for flashes with bigger write alignment

hw/usb/tinyusb/msc_fat_view/include/msc_fat_view/msc_fat_view.h
qualifier const was incorrectly added to what pointed value instead of pointer itself.
Pointer should go to section that is put in flash. For PIC32 this non-constant pointers were put in
wrong state as if they in RAM (although addresses were in flash) and init code tried to initialize them resulting in access violation.
=> tinyusb/msc_fat_view: Fix constnes of link table entries

kernel/os/include/os/os_cputime.h, kernel/os/src/os_cputime.c
Amends the documentation for functions and structures.
Removes the doxygen comments from the source file
=> kernel/os_cputime: Update doxygen comments in the header file

kernel/os/include/os/os_callout.h, kernel/os/src/os_callout.c
Adds missing parameter names to function declarations
Amends the documentation for functions and structures.
Moves documentation entries to the header file.
=> kernel/os_callout: Update doxygen comments in the header file

kernel/os/include/os/os_dev.h, kernel/os/src/os_dev.c
Adds missing documentation for functions and callbacks.
Adds missing parameter names to function declarations
=> kernel/os_dev: Update doxygen comments in the header file

hw/mcu/stm/stm32f3xx/include/mcu/stm32_hal.h, hw/mcu/stm/stm32f3xx/src/hal_flash.c
STM32_HAL_FLASH_INIT macro was empty unlike all other implementations leaving embedded flash locked.
stm32_mcu_flash_erase_sector() unlocked flash before erase and locked it afterwards.
Erase flash worked but write did not since write is done in common stm32 code that assumed that flash is unlocked.
Now flash is unlocked at the start and not locked during erase.
=> hw/mcu/stm32f3: Fix flash write

hw/drivers/flash/spiflash/include/spiflash/spiflash.h
spiflash uses bool type without including correct
header relaying on it being included before.
Now there is direct inclusion of stdbool.h
=> spiflash: Add missing include

util/crc/src/crc16.c, util/crc/syscfg.yml
This adds crc16_ccitt() version without table.
It makes it slower but can reduce flash usage
about 512 bytes.
Default still uses table but can be disabled
with UTIL_CRC_CRC16_CCITT_USE_TABLE: 0
=> util/crc: Add option for crc16_ccitt without table

hw/bsp/nucleo-l073rz/bsp.yml
STM32L0 has 128 byte page, this would allow for 16kB of slot0/1 size to be supported by mcuboot.
For this reason flash page is artificially reported to mcuboot to be 2kB.
Scratch area was put in flash with size 1kB making in unusable for mcuboot.
This could be fixed by:
- removing this limit from mcuboot (most reasonable solution)
- setting page size to be 1kB instead of 2
- changing flash area layout to have at least 2kB scratch sector
Third option is chosen because flash area layout
was already left with some holes.
Now scratch has 4kB
Reboot log is reduced to 2kB since current implementation of reboot_log uses only one sector so 75% was unusable anyway
=> hw/bsp/nucleo-l073: Fix flash map scratch area

util/stream/include/stream/stream.h
OSTREAM_DEF macro is utility macro for creating function table for output stream with function names derived from stream type name.
i.e. OSTREAM_DEF(mem) would create function table like this: const struct out_stream_vft mem_vft = {
.write = mem_write,
.flush = mem_flush,
.pump_from = mem_pump_from,
}
along with prototypes:
static int mem_write(struct out_stream *, const uint8_t *, uint32_t); static int mem_flush(struct out_stream *);
static int mem_pump_from(struct out_stream *, struct in_stream *, uint32_t);
last function was late addition and is optional
This change removes requirement to define pump_from function from OSTREAM_DEF User still can create function table with pump_from funtion without using macro if pumping is required.
=> util/stream: Update OSTREAM_DEF and ISTREAM_DEF

util/stream/include/stream/stream.h, util/stream/src/stream.c
This is simple utility function to write null terminated string to stream.
Function is already referenced in msc_fat_view.
=> util/stream: Add ostream_write_str function

kernel/os/include/os/os_task.h
Adds missing parameter names to function declarations
Amends/adds the documentation for macros, functions and structures.
=> kernel/os_task: Update doxygen comments in the header file

hw/hal/include/hal/hal_flash.h, hw/hal/src/hal_flash.c, test/flash_test/pkg.yml, test/flash_test/src/flash_test.c
command flash used to work on flash id
```
flash 0 read 0 100
```
Now it can be used with flash area id instead, while rest of the syntax remain unchanged
```
flash area 10 read 0 100
```
=> Update flash_test with access to flash area directly

kernel/os/include/os/os_mempool.h
Adds missing parameter names to function declarations.
Amends the documentation for functions and structures.
=> kernel/os_mempool: Update doxygen comments in the header file

kernel/os/include/os/os_sanity.h, kernel/os/src/os_sanity.c
Amends the documentation for functions and structures.
Adds missing parameter names to function declarations
Moves documentation entries to the header file.
=> kernel/os_sanity: Update doxygen comments in the header file

hw/mcu/stm/stm32_common/src/hal_os_tick.c
When tick was provided by RTC instead of SysTick (default) and MCUboot used SysTick during boot, SysTick was never turned off and was running in application code.
This resulted in two interrupts advancing mynewt OS tick so clock was running too fast.
Now os_tick_init() from RTC code disables SysTick that could be started in bootloader.
Same code was already applied to STM32F1 that has different RTC block.
=> hw/mcu/stm32: Disable SysTick when RTC is selected as tick source

hw/mcu/nordic/nrf_common/src/hal_gpio.c
hal_gpio_read was always returning state of IN register even if GPIO pin was configured as output pin
=> hw/mcu/nordic: Fix GPIO read bug

.github/labeler_cfg.yml, .github/workflows/labeler.yml
Adds a new workflow for adding labels to Pull Requests. 
The labels are based on the paths of changed files and the number of altered lines.
=> ci: Add PR labeler

hw/usb/tinyusb/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32f3/include/tusb_hw.h, hw/usb/tinyusb/stm32_fsdev/stm32f3/pkg.yml, hw/usb/tinyusb/stm32_fsdev/stm32f3/src/stm32_fsdev.c, hw/usb/tinyusb/stm32_fsdev/stm32f3/syscfg.yml
STM32F3 while similar to STM32F1 has different interrupt settings.
This also allows signal disconnect on D+ line during restart.
=> tinyusb: Add hardware initialization for stm32f3

hw/mcu/stm/stm32_common/src/hal_os_tick.c
Even though function stm32_wfi_from_ram() has attribute to be placed in ram in -03 it can be inlined that can effectively run WFI from flash.
Now additional attribute is added to make sure that it is not inlined.
bx lr is also removed allowing compiler to make normal exit from function (which in most cases will be bx lr)
=>  hw/mcu/stm32: Fix WFI in RAM for -O3

sys/config/pkg.yml, sys/config/src/config_file.c, sys/config/src/config_init.c, sys/config/syscfg.yml
Until now CONFIG_LITTLEFS was only defined,
but wasn't doing anything. Now littlefs
is configured and used as backend storage.
Tested with slinky app config.
=> sys/config: Add littlefs configuration

hw/bsp/nordic_pca10059/readme.md
This adds readme.md files that explains how to use board without hardware debugger when factory programmed Open DFU Bootloader is present.
=> hw/bsp: pca10059 add readme.md

.github/check_style.py
Resets temporary file pointer to the beginning of a file after writing the data.
In some cases it caused `uncrustify` to return empty list instead of corrected output, because it had not any input to process.
=> ci: Fix style check

hw/drivers/i2s/pkg.yml
Package i2s has now i2s_stream that requires
util/stream that is missing in pkg.yml
=> drivers/i2s: Fix missing dependency

sys/log/full/pkg.yml, sys/log/full/src/log_shell.c, sys/log/full/syscfg.yml
Shell command log now has additional parameter `-t` that allows to measure time for log traversal
```
compat> log -t
826231 Log reboot_log 30366 entries walked in 2664 ms
826232 Log log 0 entries walked in 0 ms
```
Option `-n` allows to limit number of displayed logs
```
log -n 10
```
`log-fill` command allows to add some logs to test logging
```
log-fill 1000 reboot_log
```
=> log_shell: Add log related shell functionality

apps/blues-wireless/pkg.yml, apps/blues-wireless/src/main.c, apps/blues-wireless/src/note_c_hooks.c, apps/blues-wireless/src/note_c_hooks.h, net/cellular/blues/pkg.yml
Hi,
I have added support for Blues Wireless [note-c ](https://github.com/blues/note-c/tree/2b31718ec01a9000f8f62cea848449eacfe50807)library. in` /net/cellular`. Also, I have added an example application inside apps/blues-wireless to get location data based on GPS. 
I took the inspiration from [note-zephyr](https://github.com/blues/note-zephyr/tree/main) repository.
=> Added Blues Wireless note-c library support and example application.

boot/startup/mynewt_cortex_m0.ld, boot/startup/mynewt_cortex_m3.ld, boot/startup/mynewt_cortex_m33.ld, boot/startup/mynewt_cortex_m4.ld, boot/startup/mynewt_cortex_m7.ld, boot/startup/scripts/generate_linker_script.sh, hw/mcu/stm/stm32h7xx/link/include/user_sections.ld.h
Some MCU/applications may require special sections
in linker script
So far memory_regions.ld.h could add non standard
memory regions, newt link_tables could add filters
to read only data for easy link time table generations.
This adds way to add whole sections and or symbol
definitions if required
=> boot/startup: Add user_section.ld.h

hw/drivers/sensors/bme280/include/bme280/bme280.h, hw/drivers/sensors/bme280/src/bme280.c
I2C writes when driver was enabled clear MSB of register address.
This prevented any write to control registers.
Now registers MSB is cleared on write only for SPI.
=> hw/drivers/bme280: Fix writes to I2C

fs/fcb/include/fcb/fcb.h, fs/fcb/src/fcb.c, fs/fcb/src/fcb_append.c, fs/fcb/src/fcb_getnext.c, fs/fcb/src/fcb_priv.h, fs/fcb/src/fcb_walk.c, fs/fcb/syscfg.yml, sys/log/full/include/log/log.h, sys/log/full/src/log_fcb.c, sys/log/full/src/log_shell.c
This adds functionality to walk back in fcb and in log_fcb
Additional options to `log` cmd
`-s <n>` skips n logs before prints are started
`-r` start printing from the latest logs (work only for FCB based logs)
```
log -n 10 -r reboot_log
```
will print 10 latest logs from reboot log
```
log -s 1000 reboot_log
```
will print logs skipping first 1000 from reboot_log
=> log_fcb walk back

fs/fcb/src/fcb_getnext.c
There was no real problem with the code
356                         loc1.fe_area = fcb_get_prev_area(fcb, loc->fe_area);
>>>     CID 418283:  Code maintainability issues  (UNUSED_VALUE)
>>>     Assigning value "0UL" to "loc1.fe_elem_off" here, but that stored value is overwritten before it can be used.
357                         loc1.fe_elem_off = 0;
This should satisfy coverity
Additionally call `fcb_start_offset(fcb);` in function `fcb_step()`
is replaced with precomputed value that was used in some place
but not in others
=> fs/fcb: Coverity fix

hw/drivers/i2s/i2s_stm32f1/src/i2s_stm32f1.c
case HAL_I2S_STATE_BUSY_TX_RX is not valid for this chip It should be only present for F4, F3 and H7.
Definition was present in mynewt copy of stm32f1xx_hal_i2s.h and probably was part of Stm32Cube package, but it is not present in stm32f1xx_hal_driver
=> hw/drivers/i2s: Fix I2S driver for STM32F1 family

hw/mcu/stm/stm32f4xx/src/clock_stm32f4xx.c
Only STM32F411 devices have PLLI2S PLLM parameter.
Also TIPPresSelection is not always present but since it was initialized with 0 initializing line is omitted.
=> mcu/stm32: Fix clock configuration for non STM32F4xx

hw/drivers/display/lvgl/indev/ft6x36/pkg.yml, hw/drivers/display/lvgl/indev/ft6x36/src/ft6x36.c, hw/drivers/display/lvgl/indev/ft6x36/syscfg.yml, hw/drivers/display/lvgl/pkg.yml, hw/drivers/display/lvgl/syscfg.yml
This adds basic driver for touch screen controller FT6x36
=> lvgl: Add driver for ft6x36 touch screen

sys/log/full/src/log_shell.c
During some log_shell improvements printed storage info was extended to show actual number of entries in the log. Durin review function that counts number of entries was dropped but call remained in log_shell resulting in build error when LOG_STORAGE_INFO is 1
This restores original print for of storage info.
=> sys/log: Fix build with LOG_STORAGE_INFO enabled

hw/drivers/audio/cirruslogic-mcu-drivers/pkg.yml, hw/drivers/audio/cirruslogic-mcu-drivers/syscfg.yml, hw/drivers/audio/cs47l63/include/cs47l63/cs47l63_driver.h, hw/drivers/audio/cs47l63/include/cs47l63_syscfg_regs.h, hw/drivers/audio/cs47l63/pkg.yml, hw/drivers/audio/cs47l63/shell/pkg.yml, hw/drivers/audio/cs47l63/shell/src/cs47l64_shell.c, hw/drivers/audio/cs47l63/shell/syscfg.yml, hw/drivers/audio/cs47l63/src/cs47l63_driver.c, hw/drivers/audio/cs47l63/syscfg.yml
This adds:
- package with repository from CirrusLogic github for audio chip drivers
- driver that can configure CS47L63 for I2S usage
=> Add CS47L63 driver

kernel/os/include/os/arch/mips/os/os_arch.h, kernel/os/include/os/arch/pic32/os/os_arch.h, kernel/os/include/os/os_callout.h, kernel/os/include/os/os_cputime.h, kernel/os/include/os/os_trace_api.h, sys/console/full/include/console/history.h, sys/coredump/include/coredump/coredump.h, sys/fault/include/fault/fault.h, sys/flash_map/include/flash_map/flash_map.h, sys/log/modlog/include/modlog/modlog.h, sys/mfg/include/mfg/mfg.h
Few headers did not have usual extern "C" blocks to be safely included by C++ code.
In few cases extern "C" was place before includes that is not correct way.
=> kernel: Fix builds for C++

crypto/mbedtls/pkg.yml
https://github.com/Mbed-TLS/mbedtls/releases/tag/mbedtls-2.28.9
=> crypto/mbedtls: Upgrade to v2.28.9

kernel/os/include/os/os_sanity.h
=> kernel/os_sanity: Remove double function typedef

hw/mcu/nordic/pkg.yml
https://github.com/NordicSemiconductor/nrfx/releases/tag/v3.8.0
=> mcu/nordic: Update NRFX to version 3.8.0

hw/mcu/dialog/da1469x/include/mcu/da1469x_clock.h, hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h, hw/mcu/dialog/da1469x/include/mcu/da1469x_lpclk.h, hw/mcu/dialog/da1469x/src/da1469x_clock.c, hw/mcu/dialog/da1469x/src/da1469x_lpclk.c, hw/mcu/dialog/da1469x/src/hal_os_tick.c, hw/mcu/dialog/da1469x/src/hal_system.c, hw/mcu/dialog/da1469x/syscfg.yml
If the LP clock's frequency is not an integer multiple of the specified OS tick frequency, the period of OS ticks will be incorrect due to integer division truncation errors (to the tune of almost 1% for RCX), resulting in OS Time
gradually creeping away from the actual time. This PR fixes the issue, by maintaining the fractional OS tick value and advance OS Time accordingly.
This PR also improves on the implementation of the DA1469x clock driver and updates the RTC divider registers after the selected LP clock is calibrated.
=> DA1469x: Clock time shifts on reboots

sys/sys/include/sys/queue.h
This adds various new macros (_SAFE variants in particular) for queue operations.
Consequence is removal of CIRCLEQs which were removed in FreeBSD (and later in other BSDs) in 2000 (sic!), original commit citation: "CIRCLEQs are a disgrace to everything Knuth taught us in Volume 1 Chapter 2. Retire them before anybody starts to use them again. Use TAILQ instead, it provides the same functionality."
=> sys/queue: Update to version from FreeBSD 14.1

libc/baselibc/pkg.yml
This is not needed for native but was causing link issues on MacOS (clang).
=> baselibc: Don't use -umain for native build

.github/workflows/newt_test_all.yml, encoding/json/include/json/json.h, util/cbmem/selftest/src/testcases/cbmem_test_case_3.c
We properly support 64bit in native target now so those can be re-enabled.
=> ci: Enable newt test on Mac

sys/shell/src/shell_os.c
This commit removes the "flg" label from the Tasks table header, after the column itself was removed in commit 6c918ac ("Remove not used oti_flags from struct os_task_info").
=> sys/shell: Fix the Tasks table header row

sys/sys/include/sys/queue.h
In FreeBSD this is provided in <sys/cdefs.h> but we don't need to pull whole system header.
=> sys/queue: Add definition of __containerof

hw/mcu/nordic/nrf5340/nrf5340.ld, hw/mcu/nordic/nrf5340/src/hal_system_start.c, hw/mcu/nordic/nrf5340/tfm/README.md, hw/mcu/nordic/nrf5340/tfm/pkg.yml, hw/mcu/nordic/nrf5340/tfm/scripts/create_tfmlib.sh, hw/mcu/nordic/nrf5340/tfm/scripts/import_tfmlib.sh, hw/mcu/nordic/nrf5340/tfm/src/tfm.c, hw/mcu/nordic/nrf5340/tfm/syscfg.yml
This modifies tfm package so it produces library that can be used to build non-secure code that will call tfm functions provided by secure code (mcuboot)
=> mcu/nrf5340: Add scripts to export/import NSC code

sys/log/full/src/log.c, sys/log/full/src/log_console.c, sys/log/full/src/log_shell.c, sys/log/full/syscfg.yml
When LOG_CONSOLE_PRETTY is set dumping logs from log_shell
uses same function for printing log header
Module names are not printed in colors.
log level now is printed always even when colors are enabled.
=> sys/log: Use colors for module name when dumping log

kernel/os/selftest/src/testcases/os_mutex_test_basic.c, kernel/os/selftest/src/testcases/os_mutex_test_case_1.c, kernel/os/selftest/src/testcases/os_mutex_test_case_2.c
On slower VMs (for example GHA's mac-os) tests were failing, as previous timeout was not enough.
=> kernel/os: Increase mutex test timeout

sys/config/src/config_store.c, sys/config/syscfg.yml
By default value is written to config storage only if it changed since last stored value. This however requires that all stored values are read to determine last value and in case of conf_save this is done for each saved value which can take a lot of time.
This adds option to skip that dup check and simply stores new value. This results in much faster writes at the expense of load times as there are more copies of the same value stored. Also conf_save will always write all exported values so this increase number of writes to flash. However, e.g. in case of large FCB used as config storage dup check on write can take much longer than simple read or store without dup checks.
=> sys/config: Add option to skip dup check when saving values

hw/mcu/dialog/da1469x/include/mcu/da1469x_hal.h, hw/mcu/dialog/da1469x/src/hal_gpio.c
Add API to support GPIO configuration using a combined mode / I/O properties value.
=> hw/mcu/dialog: GPIO configuration with single value

hw/mcu/nordic/nrf_common/src/hal_gpio.c
Code was using NRF_GPIOTE0 instead of NRF_GPIOTE which maps to NRF_GPIOTE1 for non secure code
=> hw/mcu/nordic: FIX GPIO HAL for non secure code

sys/log/full/src/log.c, sys/log/full/src/log_fcb.c, sys/log/full/src/log_fcb2.c
1063e8201 added new field to log_offset struct so functions that define that struct on stack may have random results if struct is not initialized properly.
=> sys/log: Zero-initialize log_offset struct

crypto/tinycrypt/pkg.yml
This disables maybe-uninitialized compile option in tinycrypt library to fix spurious compilation errors.
Error: In function 'uECC_vli_modMult_fast',
inlined from 'uECC_vli_modSquare_fast' at repos/apache-mynewt-core/crypto/tinycrypt/src/ecc.c:386:2,
inlined from 'XYcZ_addC' at repos/apache-mynewt-core/crypto/tinycrypt/src/ecc.c:702:2:
repos/apache-mynewt-core/crypto/tinycrypt/src/ecc.c:377:9: error: 't5' may be used uninitialized [-Werror=maybe-uninitialized]
377 |         uECC_vli_mult(product, left, right, curve->num_words);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> crypto: tinycrypt: Fix spurious uninitialized array error

fs/fatfs/src/mynewt_glue.c, fs/fatfs/syscfg.yml
=> fs/fatfs: Add modlog to fatfs

hw/hal/include/hal/hal_flash.h, hw/hal/src/hal_flash.c, sys/flash_map/include/flash_map/flash_map.h, sys/flash_map/src/flash_map.c
This changes alignment type from uint8_t to uint32_t in several places.
For flash_area_align() function 32 bits are already used by other platform supported by mcuboot.
struct hal_flash also was using 32 bits before.
This is needed for lpc55sxx chips that have flash alignment 512 bytes.
=> hw/hal: Use 32 bit for flash alignment

hw/mcu/nordic/nrf5340/src/hal_spi.c
hal_spi.c used hardcoded NRF_SPIMx_S NRF_SPISx_S instead of secure/non-secure aware macros NRF_SPIMx NRF_SPISx
=> hw/mcu/nordic: Fix SPI for non-secure code

hw/mcu/stm/stm32f4xx/mcu_cli/pkg.yml, hw/mcu/stm/stm32f4xx/mcu_cli/src/mcu_cli.c, hw/mcu/stm/stm32f4xx/mcu_cli/syscfg.yml
This adds package that can display all enabled clocks. Similar to what was already done for stm32f1
=> hw/mcu/stm32f4: Add shell command to show clocks

hw/mcu/nordic/nrf_common/src/hal_flash.c
Commit 11d13cc1a4621160e045d612ebba3031b50d9d95 of #3270 that removed duplicated hal_flash.c did not set correct value for network core flash sector size of NRF5340 which should be 2048 not 4096
=> hw/bsp/nordic: Fix flash sector size for NRF5340 network core

hw/usb/tinyusb/msc_fat_view/src/update_handler.c
When new file that showed up in root directory was not referring to image file that was written to flash update handler was unregistered and further writes to root directory containing correct information
about new image was not handled.
Now writes to root that were not recognized don't
remove image handler.
This fixes case when user drops two files at once
and only one is actual image.
This was detected on Mac OS that probably
wanted to created additional file when image file was dropped for upgrade.
=> tinyusb/msc_fat_view: Handle multi file write

boot/startup/mynewt_cortex_m0.ld, boot/startup/mynewt_cortex_m3.ld, boot/startup/mynewt_cortex_m33.ld, boot/startup/mynewt_cortex_m4.ld, boot/startup/mynewt_cortex_m7.ld
__text symbol is needed when OS_CRASH_STACKTRACE
is enabled. It was lost accidentally where common
autogenerated linker script were added.
=> boot/startup: Add missing __text symbol

hw/mcu/nordic/nrf_common/src/hal_qspi.c
When common code for QSPI was introduced to
use nrfx API instead of direct register access,
erase functions that waited for QSPI controller
to become ready started usin nrfx API but did
not take into account that waiting for previous
task to complete is required.
Now after each nrfx_qspi_erase() call, code
waits for controller to be ready as was the
case before switching to nrfx
=> hw/mcu/nordic: Fix common QSPI HAL

hw/usb/tinyusb/msc_fat_view/pkg.yml
Change order of package inits, so that the coredump file(s) are added to MSC-FAT-View successfully.
=> tinyusb/msc_fat_view: 

fs/fcb/selftest/src/testcases/fcb_test_append.c, fs/fcb/selftest/src/testcases/fcb_test_append_fill.c, fs/fcb/selftest/src/testcases/fcb_test_append_too_big.c, fs/fcb/selftest/src/testcases/fcb_test_area_info.c, fs/fcb/selftest/src/testcases/fcb_test_last_of_n.c, fs/fcb/selftest/src/testcases/fcb_test_multiple_scratch.c, fs/fcb/selftest/src/testcases/fcb_test_reset.c, fs/fcb/selftest/src/testcases/fcb_test_rotate.c, fs/fcb/src/fcb_area_info.c, hw/drivers/flash/enc_flash/selftest/src/testcases/enc_flash_fcb.c, sys/config/src/config_fcb.c, sys/log/full/src/log_fcb.c
In several cases struct fcb_entry was not initialized before usage.
In some cases it could lead to unpredictable behaviour.
=> log_fcb: Init all usage of fcb_entry on stack

uncrustify.cfg
This puts it in line with coding standards.
=> uncrustify: Update configuration for 4 spaces indent on macros

fs/fcb/include/fcb/fcb.h, fs/fcb/src/fcb.c
We are seeing some logging issues related to rotates, on analyzing the FCB code, it seems not protecting FCB access using the mutex might be one of the reasons and causes.
=> fs/fcb: FCB has some async issues, fixing some obvious ones

hw/usb/tinyusb/msc_fat_view/syscfg.yml
Update functionality was not enabled by default.
This enables this since it's easier to disable it
once functionality works then guessing why it's
not working.
'Drop image here' file now requires update handler to be enabled to avoid confusion when file shows
up in the volume but update is not enabled.
=> tinyusb/msc_fat_view: Enable update handler by default

hw/drivers/sensors/lis2dh12/src/lis2dh12.c, hw/drivers/sensors/lis2dh12/src/lis2dh12_shell.c
Replace commented out `lis2dh12_shell_init()` with `LIS2DH12_CLI` syscfg conditional. 
In `lis2dh12_shell.c`, remove `SENSOR_CLI` conditional so only `LIS2DH12_CLI` is required to enable the shell. `SENSOR_CLI` is now optional to enable output in float format for `lis2dh12 r <num_readings>`, since a helper function in the sensor package is used for float conversion. When `SENSOR_CLI` is 0 the output will be integers with 3 implied decimal places.
=> Fix for lis2dh12 shell initialization

sys/log/full/include/log/log.h, sys/log/full/src/log.c
- Log should only be added to the list after global index and local indexes are set
The reason is log entries can start appending once the log gets added to the list.
We want to restrict adding a log unless the global index/log index gets updated
appropriately.
- Also adding registration error stat to detect any registration failures since error
condition goes undetected, especially the index update case.
Note: The case where `log_registered()` callback fails, log gets removed from the list,
so a stat increment is of no use
=> sys/log: Log registration fix

sys/log/full/src/log_fcb.c, sys/log/full/src/log_fcb_bmark.c
- When no logs are present, sector bookmarks were not getting assigned if a log entry was generated, fixing this specific case.
- On log flush/clear, next_sec was not getting pointed to earlier inited sect_cap - 1 value.
=> sys/log: Fix Sector bookmark no log init and log flush

kernel/os/include/os/arch/common.h, kernel/os/src/arch/arc/os_fault.c, kernel/os/src/arch/cortex_m0/os_fault.c, kernel/os/src/arch/cortex_m3/os_fault.c, kernel/os/src/arch/cortex_m33/os_fault.c, kernel/os/src/arch/cortex_m4/os_fault.c, kernel/os/src/arch/cortex_m7/os_fault.c, kernel/os/src/arch/mips/os_fault.c, kernel/os/src/arch/pic32/os_fault.c, kernel/os/src/arch/rv32imac/os_fault.c, kernel/os/src/arch/sim-armv7/os_arch.c, kernel/os/src/arch/sim-mips/os_arch.c, kernel/os/src/arch/sim/os_arch.c
This updates os_assert_cb prototype to match assert_func. This allows to get proper assert information in callback e.g. for logging.
Note that this breaks API, but since updates in other projects are trivial I'd like to get this merged. A good example why this is useful is a blehci app which can use os_assert_cb to log asserts system-wide via HCI vs event: https://github.com/apache/mynewt-nimble/pull/1930
=> kernel/os: Update os_assert_cb to match assert_func

boot/startup/syscfg.yml
Default 768 bytes for stack is not enough for mcuboot with mbedtls.
This change was already present in NRF53 but it applies to more devices
=> boot/startup: Increase interrupt stack in bootloader

hw/usb/tinyusb/msc_fat_view/pkg.yml, hw/usb/tinyusb/msc_fat_view/src/entry_boot_bin.c, hw/usb/tinyusb/msc_fat_view/syscfg.yml
This allows to show booloader in fat view.
When enabled by MSC_FAT_VIEW_BOOT_BIN fat
view is populated with BOOT.BIN that can
be easily extracted if needed.
=> tinyusb/msc_fat_view: Add entry for BOOT.BIN

hw/bsp/nucleo-l073rz/syscfg.yml
BSP_FLASH_SPI_NAME and BSP_FLASH_SPI_BUS are for some time defined in stm32_common package.
This change removes leftover definitions from bsp.
=> hw/bsp/nucleo-l073rz: Remove duplicate syscfg.defs

hw/usb/tinyusb/msc_fat_view/src/entry_slot0_hex.c, util/stream/include/stream/stream.h, util/stream/src/stream.c
Previous content of SLOT0.HEX contained data in a format that was
easy to create in 512 byte chunks of text.
Now format is changed so generated output can be
later used as any other hex file
=> msc_fat_view: Add support for Intel hex format for slot0

sys/log/full/pkg.yml, sys/log/full/src/log_console.c, sys/log/full/syscfg.yml
When LOG_CONSOLE_PRETTY_WITH_TIMESTAMP is set to 1 timestamp of the logs is print in human readable format instead of really big numbers.
=> log_console: Add option to print time stamp as clock time

boot/startup/include/mynewt_config.ld.h
Autogenerated linker script have BOOT and SLOT0 regions specified to avoid potential inconsistency between bootloader and application code.
Fragment of generated linker script for application:
```ld
MEMORY
{
BOOT (rx!w) : ORIGIN = 0x08000000, LENGTH = 131072
SLOT0 (rx!w) : ORIGIN = 0x08020000, LENGTH = 786432
RAM (rwx) : ORIGIN = (0x24000000), LENGTH = ((0x80000) - (768))
STACK_RAM (rw) : ORIGIN = (0x24000000) + (0x80000) - (768), LENGTH = (768)
}
SECTIONS
{
...
.interrupts :
{
...
__isr_vector_end = .;
} > SLOT0
.text :
{
...
} > SLOT0
```
**SLOT0** is used as destination instead of customary **FLASH**
For bootloader build regions would be the same but destination would be `> BOOT`
This however confuses newt size that expect **FLASH** as destination when used with `newt size -F`
This …
=> boot/startup: Update generated linker script for newt size

boot/startup/src/arch/cortex_m0/cortex_m0_startup.s, boot/startup/src/arch/cortex_m3/cortex_m3_startup.s, boot/startup/src/arch/cortex_m33/cortex_m33_startup.s, boot/startup/src/arch/cortex_m4/cortex_m4_startup.s, boot/startup/src/arch/cortex_m7/cortex_m7_startup.s, boot/startup/syscfg.yml
Code was already present in default startup code for NRF5340. Now is available for all devices with common startup.
It allows to verify real main stack requirements (interrupt stack) and stack used in bootloader.
=> boot/startup: Add optional stack fill in startup

sys/log/full/src/log_fcb.c
Local function log_fcb_copy() did not use information about start location that was already available.
Function log_fcb_rtr_erase() found first element to copy and then used only part of what wa returned.
In turn log_fcb_copy() walk log again skipping entries.
It would not work correctly if more then on sector was used for source fcb and requested number of
preserved entries span more then one sector.
Code is shorter, faster and uses less stack
=> log_fcb: optimize log_fcb_copy

hw/drivers/hash/hash_stm32/src/hash_stm32.c
Comment explicitly mentioned STM32F415 and STM32F417 devices that don't have support for SHA256.
Now condition is reversed so those two are marked as not supported. This will enable STM32H7 devices as well as STM32H5.
When device does not have supprt for hash HASH symbol will not be defined and build will fail, while right now build for STM32H7 works but hash functionality does not work.
=> hw/drivers/hash_stm32: Enable for STM32H devices

sys/log/full/src/log_console.c
If non-cbor log does not end with end of line
append it when log is printed.
This allows to have shorted logs stored in flash.
=> log_console: Append new line if not present

hw/bus/drivers/spi_stm32/src/spi_stm32.c
SPI was enabled too soon. It could result in
clock line glitch for STM32H7/5 where GPIO
lines can be left in wrong state before CR registers are correctly filled.
STM HAL will enable it at correct time during transmission.
=> bus/spi_stm32: Fix spi initialization sequence

hw/mcu/stm/stm32_common/src/hal_uart.c
More recent STM32 devices have FIFO that
can help to use higher baudrate speeds without
DMA (which is not used in hal_uart).
This enables FIFO if proper bit in CR1 register
exists.
=> stm32/hal_uart: Enable FIFO if present

hw/bus/drivers/i2c_common/include/bus/drivers/i2c_common.h, hw/bus/drivers/i2c_da1469x/src/i2c_da1469x.c, hw/bus/drivers/i2c_hal/src/i2c_hal.c, hw/bus/drivers/i2c_nrf52_twim/src/i2c_nrf52_twim.c, hw/bus/drivers/i2c_nrf5340/src/i2c_nrf5340.c, hw/bus/drivers/i2c_nrf91_twim/src/i2c_nrf91_twim.c, hw/bus/drivers/spi_apollo3/src/spi_apollo3.c, hw/bus/drivers/spi_common/include/bus/drivers/spi_common.h, hw/bus/drivers/spi_da1469x/src/spi_da1469x.c, hw/bus/drivers/spi_hal/src/spi_hal.c, hw/bus/drivers/spi_stm32/src/spi_stm32.c, hw/bus/src/bus.c
It was impossible to change basic configuration for SPI/I2C device once it was used.
If only one devices is connected to SPI lines and device requires for example different frequency during work (like for SD card) it was impossible to change it.
Now node can have change settings and drivers will check actual parameters and not only whether same device is being used.
=> bus: Allow configuration change for a node

hw/battery/pkg.yml
battery_adc.c included adc/adc.h but package
for hw/drivers/adc was missing from dependency list.
=> hw/battery: Add missing dependency to adc

sys/log/full/selftest/util/src/testcases/log_test_case_level.c
Unit test was broken in several ways and pass verdict was not reliable.
First of log_offset used for starting walk was never initialized and received random data.
By accident this data had non zero ts_stamp that resulted in expected start from the beginning (it stack was different it could look for timestamp instead).
log_last_walk function that is called on each enumerated entry used uninitialized lo_index value to report last entry index. The assumption that lo_index has means something in this context was also incorrect as this value never changes in walk functions. It looks like original code expected this value to have index of log entry which it never does.
Code also did not expected that very first entry added to the log will have index 0 (which was never modified correctly). To …
=> log/full: Fix log level unit test

sys/config/include/config/config_file.h, sys/config/src/config_file.c, sys/config/src/config_init.c, sys/config/syscfg.yml
There was duplicated code for config base on file system for littlefs and nffs.
Now there is common initialization function for both file systems. Additionally other file system can be used for config storage without need to modify initialization code since it used mynewt fs api and nothing specific to littlefs of nffs. It is needed if FATFS (sdcard) is to be used for config storage
=> config: Cleanup config file initialization

fs/fatfs/src/mynewt_glue.c
When fatfs_open() was called to open file
for writing it set FA_WRITE flag to fat driver.
It is enough if file already exists but if
it first call to open file to write it always
failed.
Now additional flag FA_OPEN_ALWAYS is added
to make sure file will be created if it's not
present yet.
For FS_ACCESS_READ only flag file still must
exists before.
=> fs/fatfs: Fix open for write

kernel/os/selftest/src/msys_test.c
Depending on optimization and compiler used unit test could produce following error:
repos/apache-mynewt-core/kernel/os/selftest/src/msys_test.c: In function ‘os_msys_test_setup’: repos/apache-mynewt-core/kernel/os/selftest/src/msys_test.c:61:30: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
61 |     context->mempool_list = *(struct os_mempool_list *)&g_os_mempool_list;
|                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This is because declaration of extern g_os_mempool_list was taken directly from os_mempool.c where this variable is create without specifying type with macro STAILQ_HEAD(, os_mempool) that produces:
struct {
struct os_mempool *stqh_first;
struct os_mempool **stqh_last;
} g_os_mempool_list;
while …
=> kernel/os: Fix msys unit tests

hw/bsp/nordic_pca10121/include/bsp/bsp.h
Add definition for SPI pins that are connected
to SD card slot and cs47l63 codec.
This will allow easy configuration without need
to check product schematic.
=> bsp/pca10121: Init on board pins

.clang-format
This PR includes two formatting-related changes to `.clang-format` and supporting tooling:
1. **Fix formatting for STATS macros**  
Updated `MacroBlockBegin`, `MacroBlockEnd`, and `StatementMacros` settings to properly handle macro blocks like `STATS_NAME_START` / `STATS_NAME_END`.  
2. **Disable line breaking after enums**  
Changed `BraceWrapping.AfterEnum` to `false` to align with the existing code style and prevent unnecessary newlines after enum declarations.
=> Improve clang-format handling for macros and enums

hw/usb/tinyusb/msc_fat_view/src/msc_fat_view.c, hw/usb/tinyusb/msc_fat_view/syscfg.yml
Short name generation incorrectly build file extension.
For config.txt it would create
'CONFIG  .TX' instead of 'CONFIG  TXT'
(Extra dot that should not be there)
Now short name is displayed correctly
Additionally typo in variable name is corrected.
Root directory sector count is not increased to 3
and configurable in syscfg.
This can prevent case when due to number of entries
in root directory host system can't write file with
updated firmware.
=> tinyusb/msc_fat_view: Small fixes

hw/mcu/native/src/hal_flash.c, sys/log/full/include/log/log.h, sys/log/full/selftest/util/src/testcases/log_test_case_2logs.c, sys/log/full/selftest/util/src/testcases/log_test_case_append_cb.c, sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_body.c, sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_mbuf.c, sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_append_mbuf_body.c, sys/log/full/selftest/util/src/testcases/log_test_case_cbmem_printf.c, sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append.c, sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_body.c, sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_mbuf.c, sys/log/full/selftest/util/src/testcases/log_test_case_fcb_append_mbuf_body.c, sys/log/full/selftest/util/src/testcases/log_test_case_fcb_printf.c, sys/log/full/src/log.c, sys/log/full/src/log_fcb.c, sys/log/full/syscfg.yml
- Trailer callbacks can be enabled using
LOG_FLAGS_TRAILER_SUPPORT.
- This is needed since we cannot update the log header
without breaking backwards compatibility
- Adding a trailer keeps the log header in place and the entry
intact. On an upgrade or downgrade, log entries are still
readable.
- Trailer callbacks can be registered using log_trailer_cbs_register().
- Trailer data is managed by the callbacks
- Add trailer buffer append/free callback
- Add reset_data callback for trailer data
- Allocate trailer buffer in log_append_prepare() and
free the trailer buffer with log_trailer_free() in
log.c. Both of them being callbacks to be implemented
by the user.
- Add 2 byte trailer length field after trailer at
the end of the log entry.
Note: This is a replacement for the number of entries …
=> sys/log, fs/fcb: Add support for trailers per entry in logs for fcb

hw/usb/tinyusb/msc_fat_view/src/entry_config.c
entry_config.c uses **size_t** that requires one of the standard headers. **stddef.h** is included to provide
definition as specified by standard
=> tinyusb/msc_fat_view: Fix missing include file

hw/drivers/i2s/i2s_nrfx/src/i2s_nrfx.c
With this change when bypass is enabled ratio
between MSCK and BCLK is computed when needed.
Previously user could prepare mck_setup and ratio
values but now it's done automatically
=> hw/drivers/i2s: Fix setting for bypass mode

kernel/os/include/os/link_tables.h, sys/shell/include/shell/shell.h, sys/shell/pkg.yml, sys/shell/src/shell.c, sys/shell/src/shell_os.c, sys/shell/src/shell_priv.h, sys/shell/src/shell_prompt.c
So far shell commands could be added with `shell_cmd_register()` and modules (set of commands) could be added with `shell_register()`
This approach requires function call usually added in package initialization function.
Registering commands requires some RAM two tables:
```c
static struct shell_module shell_modules[MYNEWT_VAL(SHELL_MAX_MODULES)];
static struct shell_cmd compat_commands[MYNEWT_VAL(SHELL_MAX_COMPAT_COMMANDS) + 1];
```
Number of modules that can be registered is defined by two mynewt values `SHELL_MAX_MODULES` and `SHELL_MAX_COMPAT_COMMANDS`.
When code tries to add more commands or modules system will crash with assert(0).
Now when link time table can be used shell commands and modules can be added to be available in shell.
Commands can be added with macro …
=> Shell commands and modules added during link time

sys/config/include/config/config.h, util/scfg/include/scfg/scfg.h, util/scfg/src/scfg.c
This:
- adds standard __cplusplus block
- changes filed name private to priv so file struct can be used in C++ where private is keyword
- adds const to scfg_register name parameter that would block usage in C++ where string literal const-ness is enforced
=> util/scfg: Update for c++

fs/fatfs/include/fatfs/ffconf.h, fs/fatfs/src/mynewt_glue.c, fs/fatfs/syscfg.yml, hw/drivers/mmc/src/mmc.c
This:
- Add option to enable long line support in FAT driver
- Add option to enable ExFAT driver
- Add option to enable thread safe code
- enables ExFAT in mmc driver during disk detection
=> Enable FATFS features in syscfg

fs/littlefs/src/mynewt_glue.c
RDRW was chosen if either read or write was requested.
Now LFS_O_RDRW is selected correctly
=> fs/littlefs: Fix open functions

hw/drivers/chg_ctrl/da1469x_charger/src/da1469x_charger.c
Function da1469x_charger_set_state_change_irq_mask had different signature in header and implementation.
New compiler detects this while older ones probably ignored this.
Implementation now matches header signature.
=> hw/drivers/da1469x_charger: Fix prototype mismatch

hw/bsp/apollo3_evb/syscfg.yml, hw/mcu/ambiq/apollo3/src/hal_watchdog.c
This adds watchdog timer support for apollo3 based boards. Apollo3 microcontrollers allow selecting different WDT clock frequencies. To enable this feature, a new configuration variable is introduced: `AM_WATCHDOG_CLOCK`.
You can set `AM_WATCHDOG_CLOCK` to one of the supported values:
- 1 (default)
- 16
- 128
The clock affects how long the watchdog timeout can be, since the hardware register for reset timeout is 8 bit.
This means:
- for 128Hz, max timeout ~ 2 seconds
- for 16Hz, max timeout ~ 16 seconds
- for 1Hz, max timeout 255 seconds
If you choose a higher clock, you must decrease the interval values accordingly. Two other config variables should be adjusted based on the selected clock:
- SANITY_INTERVAL
- WATCHDOG_INTERVAL
Example for syscfg.vals in an app or target:
```
syscfg.vals: …
```
=> hw/mcu: Add watchdog support for apollo3 with configurable clock

hw/mcu/ambiq/apollo2/src/hal_system.c
Added support for reading the reset cause using the `RSTGEN->STAT` register. Function checks what kind of reset occurred and returns matching `hal_reset_reason` enum value.
After that the register is cleared.
=> hw/mcu: add reset cause handling for apollo2 board

boot/startup/mynewt_cortex_m3.ld, boot/startup/mynewt_cortex_m33.ld, boot/startup/mynewt_cortex_m4.ld, boot/startup/mynewt_cortex_m7.ld
Relocated vectors had 4 byte alignment while VTOR
is 128 byte aligned.
Code only worked because relocation vector was
at the beginning of RAM.
If something was put there interrupt vectors would not match and strange things would happen.
=> boot/startup: Fix alignment for relocate vectors

sys/shell/src/shell.c
When static linking of shell commands was introduced, standard 'help' and 'select' commands were no longer marked as extended (using streamer).
This resulted in both of them crashing system with NULL pointer dereference.
Now it's corrected by calling correct macros for
creation of those commands.
=> sys/shell: Fix help and select commands

hw/drivers/flash/spiflash/pkg.yml
When SPIFLASH_STAT was set to 1 code tries to
include stats/stats.h but direct dependency was
not there.
It worked if other packages included stats.
Now code compiles when SPIFLASH_STAT is 1 and
nothing else wanted stats.
=> spiflash: Add dependency to stats when needed

sys/log/full/include/log/log.h, sys/log/full/src/log_shell.c
- For string logs, the trailer would get printed on the shell. This PR fixes it such that we subtract the trailer length and size of trailer length from the log entry being printed
=> sys/log/shell: Fix string log shell printf for log entries with a trailer

hw/mcu/atmel/samd21xx/include/mcu/mcu.h
This fixes build issues with `__BKPT()` and standard types.
=> hw/mcu: add missing includes for __BKPT() and integer types

hw/bsp/arduino_zero/pkg.yml, hw/bsp/arduino_zero/src/hal_bsp.c, hw/bsp/arduino_zero/syscfg.yml
The default UART used for logging (console_printf) is now routed through the debugger interface instead of external TX/RX pins, making serial output easier to access via USB cable.
Additionally, UART1 has been configured and exposed on external pins for user applications.
=> hw/bsp/arduino-zero: route default UART to debugger, add UART1

hw/scripts/jlink.sh, hw/scripts/nrfjprog.sh, hw/scripts/nrfutil.sh, hw/scripts/openocd.sh, hw/scripts/pyocd.sh, hw/scripts/stlink.sh, hw/scripts/stm32_programmer.sh, hw/scripts/syscfg.yml
Added option for selecting USB serial of a debug probe via syscfg.vals in targets syscfg.yml file.
This was achieved by addition of following definitions to hw/scripts/syscfg.yml file:
- STLINK_SN
- JLINK_SN
- CMSIS_DAP_SN and their usage in scripts.
This removes the need of manual choosing target device everytime load is called, by having serial number value in targets syscfg.yml file.
This value will be used, when environment variable is missing.
=> hw/scripts: Add adapter selection via syscfg.yml

apps/crypto_test/pkg.yml, apps/hash_test/pkg.yml, crypto/mbedtls/pkg.yml
Now -DMBEDTLS_USER_CONFIG_FILE=<mbedtls/config_mynewt.h> flag is used globally for each build that depends on mbedtls package. This way we won't have to add this flag in each package that uses mbedtls.
=> crypto/mbedtls: Use config defining flag globally

hw/mcu/stm/stm32g0xx/syscfg.yml, hw/mcu/stm/stm32g4xx/syscfg.yml, hw/mcu/stm/stm32l0xx/syscfg.yml, hw/mcu/stm/stm32l1xx/syscfg.yml, hw/mcu/stm/stm32l4xx/syscfg.yml, hw/mcu/stm/stm32u5xx/syscfg.yml
LSI was not enable by default is several MCUs.
LSI is required for Watchdog which is enable by default in mynewt.
Now LSI is enabled. It can be disabled if user
really knows why this could be needed.
=> mcu/stmxxx: Enable LSI by default

.asf.yaml
This disables merge commits and allows only rebase or squash commits. This is to keep repo history linear.
=> Force linear history

hw/drivers/sensors/bmp5/src/bmp5.c
- Put sensor into standby before configuring.
- This fixes an issue where after waking up the MCU on reconfiguration of the sensor, it was going into continuous mode.
- This PR also fixes `set_pwr_ctrl_settings()`
=> hw/sensors/bmp5: Put sensor into standby before configuring
